# -*- coding: utf-8 -*-
"""Large trilingual Bible story books (44 stories each -> 45 pages with cover).
Each story dict: title_en/ti/am, verse, story_en/ti/am, moral_en/ti/am, illustration.
"""


def S(te, tt, ta, v, se, st, sa, me, mt, ma, ill):
    """Compact helper to build a story dict."""
    return {
        "title_en": te, "title_ti": tt, "title_am": ta, "verse": v,
        "story_en": se, "story_ti": st, "story_am": sa,
        "moral_en": me, "moral_ti": mt, "moral_am": ma, "illustration": ill,
    }


# ============================================================
# BOOK 1: The Big Story of the Bible (44 stories)
# ============================================================
BIG_STORY = []


BIG_STORY += [
 S("God Makes Everything","ኣምላኽ ንዅሉ ይፈጥር","እግዚአብሔር ሁሉን ይፈጥራል","Genesis 1",
   "In the beginning there was nothing but God. He spoke, and light appeared. He made the sky, the seas, the land, the sun, moon, and stars. He filled the world with plants, fish, birds, and animals. Everything God made was good, and He was very pleased.",
   "ኣብ መጀመርታ ኣምላኽ ጥራይ ነበረ። ተዛረበ እሞ ብርሃን ተራእየ። ሰማይ፡ ባሕርታት፡ ምድሪ፡ ጸሓይ፡ ወርሒን ከዋኽብትን ገበረ። ንዓለም ብተኽሊ፡ ዓሳ፡ ኣዕዋፍን እንስሳታትን መልኣ። ኣምላኽ ዝገበሮ ኵሉ ጽቡቕ ነበረ፡ ኣዝዩ ድማ ባህ በሎ።",
   "በመጀመሪያ ከእግዚአብሔር በቀር ምንም አልነበረም። ተናገረ ብርሃንም ታየ። ሰማይን፡ ባሕሮችን፡ ምድርን፡ ፀሐይን፡ ጨረቃንና ከዋክብትን ሠራ። ዓለምን በተክል፡ በዓሣ፡ በወፎችና በእንስሳት ሞላ። እግዚአብሔር የሠራው ሁሉ መልካም ነበር፡ እጅግም ደስ አለው።",
   "God made a beautiful world out of love.","ኣምላኽ ብፍቕሪ ጽብቕቲ ዓለም ገበረ።","እግዚአብሔር በፍቅር ውብ ዓለም ሠራ.","star"),
 S("The First People","እቶም ቀዳሞት ሰባት","የመጀመሪያዎቹ ሰዎች","Genesis 2",
   "God made the first man, Adam, and the first woman, Eve. He placed them in a beautiful garden called Eden. He walked with them and gave them work to do and everything they needed. God loved them like a father loves his children.",
   "ኣምላኽ ንቀዳማይ ሰብኣይ ኣዳም ንቀዳመይቲ ሰበይቲ ሄዋን ገበረ። ኣብ ኤደን እትብሃል ጽብቕቲ ገነት ኣንበሮም። ምሳታቶም ተመላለሰ ዕዮን ዘድልዮም ኵሉን ሃቦም። ኣቦ ንደቁ ኸም ዜፍቅር ኣምላኽ የፍቅሮም ነበረ።",
   "እግዚአብሔር የመጀመሪያውን ሰው አዳምንና የመጀመሪያዋን ሴት ሔዋንን ሠራ። ኤደን በምትባል ውብ ገነት አኖራቸው። ከእነርሱ ጋር ተመላለሰ ሥራንና የሚያስፈልጋቸውን ሁሉ ሰጣቸው። አባት ልጆቹን እንደሚወድ እግዚአብሔር ይወዳቸው ነበር።",
   "God made us to know Him and be loved by Him.","ኣምላኽ ንኺፈልጦን ኪፍቀርን ገበረና።","እግዚአብሔር እንድናውቀውና እንድንወደድ ፈጠረን.","garden" if False else "hills"),
 S("The Sad Choice","እቲ ዜሕዝን ምርጫ","ያሳዘነው ምርጫ","Genesis 3",
   "God gave Adam and Eve one rule, but a crafty serpent tricked them into breaking it. For the first time they felt afraid and ashamed. Sin came into the world. Yet even then God promised that one day a Rescuer would come to make things right.",
   "ኣምላኽ ንኣዳምን ሄዋንን ሓደ ሕጊ ሃቦም፡ ተንኰለኛ ተመን ግና ኪጥሕስዎ ኣታለሎም። ንፈለማ ግዜ ፈርሁን ሓፈሩን። ሓጢኣት ናብ ዓለም ኣተወ። ሽዑ እኳ ኣምላኽ ሓደ መዓልቲ መድሓኒ መጺኡ ኵሉ ኼቕንዖ ኸም ዝኾነ ተመባጽዐ።",
   "እግዚአብሔር ለአዳምና ሔዋን አንድ ሕግ ሰጣቸው፡ ተንኮለኛ እባብ ግን እንዲጥሱት አታለላቸው። ለመጀመሪያ ጊዜ ፈሩና አፈሩ። ኃጢአት ወደ ዓለም ገባ። ያኔም እንኳ እግዚአብሔር አንድ ቀን አዳኝ መጥቶ ሁሉን እንደሚያስተካክል ቃል ገባ።",
   "Even when we do wrong, God has a plan to save us.","ጌጋ ኽንገብር ከለና እኳ፡ ኣምላኽ መደብ ምድሓን ኣለዎ።","ስሕተት ስንሠራም እንኳ፡ እግዚአብሔር የማዳን ዕቅድ አለው.","hills"),
 S("Noah Trusts God","ኖህ ብኣምላኽ ይውከል","ኖኅ በእግዚአብሔር ይታመናል","Genesis 6-9",
   "The world became full of wrong, but Noah loved God. God told him to build a great ark. Noah obeyed, even when others laughed. A flood came, but Noah, his family, and the animals were safe. Afterward God set a rainbow in the sky as a promise.",
   "ዓለም ብኽፍኣት መልአ፡ ኖህ ግና ንኣምላኽ የፍቅሮ ነበረ። ኣምላኽ ዓባይ መርከብ ኪሰርሕ ነገሮ። ካልኦት ኪስሕቁ ኸለዉ እኳ ኖህ ተኣዘዘ። ውሒዝ መጸ፡ ኖህ፡ ስድራ ቤቱን እንስሳታትን ግና ድሑናት ነበሩ። ድሕሪኡ ኣምላኽ ከም መብጽዓ ቀስተ ደመና ኣብ ሰማይ ኣቐመጠ።",
   "ዓለም በክፋት ተሞላች፡ ኖኅ ግን እግዚአብሔርን ይወድ ነበር። እግዚአብሔር ታላቅ መርከብ እንዲሠራ ነገረው። ሌሎች ሲስቁም እንኳ ኖኅ ታዘዘ። ጎርፍ መጣ፡ ኖኅ፡ ቤተሰቡና እንስሳት ግን ደኅና ነበሩ። ከዚያ በኋላ እግዚአብሔር እንደ ቃል ኪዳን ቀስተ ደመናን በሰማይ አኖረ።",
   "Obey God even when others do not understand.","ካልኦት ዘይርድኡ ኽነሶም እኳ ንኣምላኽ ተኣዘዞ።","ሌሎች ባይረዱም እንኳ እግዚአብሔርን ታዘዝ.","boat"),
 S("God Calls Abraham","ኣምላኽ ንኣብርሃም ይጽውዕ","እግዚአብሔር አብርሃምን ይጠራል","Genesis 12",
   "God asked Abraham to leave his home and travel to a new land. God promised to bless him and, through his family, to bless the whole world. Abraham trusted God and went, even though he did not know the way. His faith began a great story.",
   "ኣምላኽ ንኣብርሃም ገዝኡ ገዲፉ ናብ ሓዳስ ምድሪ ኪጓዓዝ ሓተቶ። ኪባርኾ ብስድራ ቤቱ ኸኣ ንብምሉኡ ዓለም ኪባርኽ ተመባጽዐ። ኣብርሃም መገዲ ኸይፈለጠ እኳ ንኣምላኽ ኣሚኑ ኸደ። እምነቱ ዓባይ ዛንታ ጀመረት።",
   "እግዚአብሔር አብርሃምን ቤቱን ትቶ ወደ አዲስ ምድር እንዲሄድ ጠየቀው። ሊባርከውና በቤተሰቡም ዓለምን ሁሉ ሊባርክ ቃል ገባ። አብርሃም መንገዱን ባያውቅም እንኳ በእግዚአብሔር አምኖ ሄደ። እምነቱ ታላቅ ታሪክ ጀመረ።",
   "Faith means trusting God's direction.","እምነት ማለት ንመምርሒ ኣምላኽ ምውካል እዩ።","እምነት ማለት የእግዚአብሔርን መመሪያ መታመን ነው.","prophet"),
 S("The Promised Son","እቲ ተስፋ እተዋህበ ወዲ","ተስፋ የተሰጠው ልጅ","Genesis 21",
   "God promised Abraham and Sarah a son, though they were very old. Sarah laughed, for it seemed impossible. But at just the right time, baby Isaac was born! Their laughter turned to joy. Nothing is too hard for God.",
   "ኣምላኽ ንኣብርሃምን ሳራን ኣዝዮም ኣረግቲ እኳ ኽነሶም ወዲ ተመባጽዖም። ዘይከኣል ስለ ዝመሰላ ሳራ ሰሓቐት። ኣብ ግቡእ ግዜ ግና ህጻን ይስሓቅ ተወልደ! ሰሓቖም ናብ ሓጐስ ተለወጠ። ንኣምላኽ ዚኸብዶ የልቦን።",
   "እግዚአብሔር ለአብርሃምና ለሣራ በጣም ሽማግሌ ቢሆኑም ልጅ ቃል ገባላቸው። የማይቻል ስለመሰላት ሣራ ሳቀች። በትክክለኛው ጊዜ ግን ሕፃኑ ይስሐቅ ተወለደ! ሳቃቸው ወደ ደስታ ተለወጠ። ለእግዚአብሔር የሚከብደው የለም።",
   "Nothing is too hard for God.","ንኣምላኽ ዚኸብዶ የልቦን።","ለእግዚአብሔር የሚከብደው የለም.","star"),
 S("Jacob's Dream","ሕልሚ ያእቆብ","የያዕቆብ ሕልም","Genesis 28",
   "Jacob was traveling alone and slept with a stone for a pillow. He dreamed of a stairway to heaven with angels on it, and God promised to be with him wherever he went. Jacob woke up knowing God was near, even in a lonely place.",
   "ያእቆብ በይኑ ይጓዓዝ ነበረ እምኒ ተተርኢሱ ድማ ደቀሰ። ናብ ሰማይ ዚበጽሕ መሰላል ምስ መላእኽቲ ሓለመ፡ ኣምላኽ ድማ ናብ ዝኸዶ ዅሉ ምስኡ ኪኸውን ተመባጽዐ። ያእቆብ ኣብ ጽምዋ ቦታ እኳ ኣምላኽ ቀረባ ምዃኑ ፈሊጡ ተንስአ።",
   "ያዕቆብ ብቻውን ይጓዝ ነበር ድንጋይ ተንተርሶም ተኛ። ወደ ሰማይ የሚደርስ መሰላል ከመላእክት ጋር አለመ፡ እግዚአብሔርም ወደሚሄድበት ሁሉ ከእርሱ ጋር ሊሆን ቃል ገባ። ያዕቆብ በብቸኝነት ቦታም እንኳ እግዚአብሔር ቅርብ መሆኑን አውቆ ነቃ።",
   "God is near, even when we feel alone.","በይንና ኽንስምዕ ከለና እኳ ኣምላኽ ቀረባ እዩ።","ብቻችንን ስንሰማም እንኳ እግዚአብሔር ቅርብ ነው.","angel"),
 S("Joseph the Dreamer","ዮሴፍ እቲ ሓላሚ","ሕልመኛው ዮሴፍ","Genesis 37",
   "Joseph's father loved him and gave him a beautiful coat. God gave Joseph special dreams about the future. His brothers grew jealous and sold him away to Egypt. Even in trouble, God had a good plan for Joseph's life.",
   "ኣቦ ዮሴፍ የፍቅሮ ነበረ ጽብቕቲ ቀሚሽ ድማ ሃቦ። ኣምላኽ ብዛዕባ መጻኢ ፍሉይ ሕልምታት ሃቦ። ኣሕዋቱ ቀኒኦም ናብ ግብጺ ሸጥዎ። ኣብ ጸበባ እኳ ኣምላኽ ንህይወት ዮሴፍ ጽቡቕ መደብ ነበሮ።",
   "የዮሴፍ አባት ይወደው ነበር ውብ ቀሚስም ሰጠው። እግዚአብሔር ስለ ወደፊቱ ልዩ ሕልሞች ሰጠው። ወንድሞቹ ቀንተው ወደ ግብጽ ሸጡት። በመከራም እንኳ እግዚአብሔር ለዮሴፍ ሕይወት መልካም ዕቅድ ነበረው።",
   "God can bring good even out of hard times.","ኣምላኽ ካብ ከቢድ እዋን እኳ ጽቡቕ ኬምጽእ ይኽእል።","እግዚአብሔር ከከባድ ጊዜም መልካም ሊያወጣ ይችላል.","hills"),
 S("Joseph Forgives","ዮሴፍ ይቕረ ይብል","ዮሴፍ ይቅር ይላል","Genesis 45",
   "Years later Joseph became a ruler in Egypt. When famine came, his brothers came for food, not knowing it was him. Joseph forgave them with tears of joy and saved their whole family. He said, 'You meant harm, but God meant it for good.'",
   "ድሕሪ ዓመታት ዮሴፍ ኣብ ግብጺ ገዛኢ ኮነ። ጥሜት ምስ መጸ ኣሕዋቱ ንሱ ምዃኑ ኸይፈለጡ ንምግቢ መጹ። ዮሴፍ ብንብዓት ሓጐስ ይቕረ በለሎም ንብምሉኡ ስድራ ቤቶም ድማ ኣድሓነ። 'ንስኻትኩም ክፉእ ሓሰብኩም፡ ኣምላኽ ግና ንጽቡቕ ሓሰቦ' በለ።",
   "ከዓመታት በኋላ ዮሴፍ በግብጽ ገዥ ሆነ። ራብ ሲመጣ ወንድሞቹ እርሱ መሆኑን ሳያውቁ ለምግብ መጡ። ዮሴፍ በደስታ እንባ ይቅር አላቸው ቤተሰባቸውንም ሁሉ አዳነ። 'እናንተ ክፉ አሰባችሁ፡ እግዚአብሔር ግን ለበጎ አሰበው' አለ።",
   "Forgiveness heals; God turns evil into good.","ይቕረ ምባል ይፍውስ፡ ኣምላኽ ክፉእ ናብ ጽቡቕ ይልውጥ።","ይቅርታ ይፈውሳል፡ እግዚአብሔር ክፉውን ወደ በጎ ይለውጣል.","crown"),
 S("Baby Moses is Saved","ህጻን ሙሴ ይድሕን","ሕፃኑ ሙሴ ይድናል","Exodus 2",
   "A cruel king wanted to harm the baby boys of God's people. To save baby Moses, his mother placed him in a basket by the river. The king's own daughter found him and raised him as her son. God was watching over Moses from the very start.",
   "ጨካን ንጉስ ንኣወዳት ህዝቢ ኣምላኽ ኪጐድኦም ደለየ። ንህጻን ሙሴ ንኺድሕን ኣዲኡ ኣብ መንኮርኮር ኣብ ጥቓ ሩባ ኣንበረቶ። ጓል ንጉስ ባዕላ ረኺባ ኸም ወዳ ኣዕበየቶ። ኣምላኽ ካብ ጥንቲ ንሙሴ ይሕልዎ ነበረ።",
   "ጨካኝ ንጉሥ የእግዚአብሔርን ሕዝብ ወንድ ሕፃናት ሊጎዳ ፈለገ። ሕፃኑ ሙሴን ለማዳን እናቱ በቅርጫት በወንዙ አጠገብ አኖረችው። የንጉሡ ልጅ ራሷ አግኝታ እንደ ልጇ አሳደገችው። እግዚአብሔር ከመጀመሪያ ሙሴን ይጠብቀው ነበር።",
   "God watches over us from the very beginning.","ኣምላኽ ካብ መጀመርታ ይሕልወና።","እግዚአብሔር ከመጀመሪያ ጀምሮ ይጠብቀናል.","boat"),
 S("The Burning Bush","እቲ ዚነድድ ቆጥቋጥ","የሚነደው ቁጥቋጦ","Exodus 3",
   "While Moses watched sheep, he saw a bush on fire that did not burn up. From it God called him to rescue His people from slavery. Moses felt afraid, but God promised, 'I will be with you.' God gives courage for the work He calls us to do.",
   "ሙሴ ኣባጊዕ ኪሕሉ ኸሎ ዚነድድ ግናኸ ዘይነድድ ቆጥቋጥ ረኣየ። ካብኡ ኣምላኽ ንህዝቡ ኻብ ባርነት ኬናግፎም ጸውዖ። ሙሴ ፈርሀ፡ ኣምላኽ ግና 'ኣነ ምሳኻ ኽኸውን እየ' ኢሉ ተመባጽዐ። ኣምላኽ ንዚጽውዓና ዕዮ ትብዓት ይህበና።",
   "ሙሴ በጎችን ሲጠብቅ የሚነድ ግን የማይቃጠል ቁጥቋጦ አየ። ከዚያ እግዚአብሔር ሕዝቡን ከባርነት እንዲያድን ጠራው። ሙሴ ፈራ፡ እግዚአብሔር ግን 'እኔ ካንተ ጋር እሆናለሁ' ብሎ ቃል ገባ። እግዚአብሔር ለሚጠራን ሥራ ድፍረት ይሰጠናል።",
   "God gives us courage for what He calls us to do.","ኣምላኽ ንዚጽውዓና ትብዓት ይህበና።","እግዚአብሔር ለሚጠራን ድፍረት ይሰጠናል.","prophet"),
]


BIG_STORY += [
 S("Crossing the Sea","ባሕሪ ምስጋር","ባሕርን መሻገር","Exodus 14",
   "God set His people free, but the king chased them to the sea. They were trapped! Moses raised his staff, and God split the water so the people crossed on dry ground. When there seems to be no way, God can make a way.",
   "ኣምላኽ ንህዝቡ ናጻ ኣውጽኦም፡ ንጉስ ግና ኽሳብ ባሕሪ ሰጐጎም። ተዓጽዮም! ሙሴ በትሩ ኣልዓለ፡ ኣምላኽ ድማ ነቲ ማይ ከፈሎ እሞ ህዝቢ ኣብ ንቑጽ ምድሪ ሰገሩ። መገዲ ዘየለ ኪመስል ከሎ ኣምላኽ መገዲ ኪገብር ይኽእል።",
   "እግዚአብሔር ሕዝቡን ነፃ አወጣ፡ ንጉሡ ግን እስከ ባሕር አሳደዳቸው። ተከበቡ! ሙሴ በትሩን አነሳ፡ እግዚአብሔርም ውኃውን ከፈለው ሕዝቡም በደረቅ መሬት ተሻገሩ። መንገድ የሌለ ሲመስል እግዚአብሔር መንገድ ሊያደርግ ይችላል።",
   "When there seems no way, God makes a way.","መገዲ ዘየለ ኪመስል ከሎ ኣምላኽ መገዲ ይገብር።","መንገድ የሌለ ሲመስል እግዚአብሔር መንገድ ያደርጋል.","sea"),
 S("God's Good Rules","ጽቡቕ ሕግታት ኣምላኽ","የእግዚአብሔር መልካም ሕጎች","Exodus 20",
   "On a mountain God gave Moses ten important rules. They taught the people to love God most of all and to love and respect one another. God gave these rules out of love, like a good parent, to help His children live happy and safe.",
   "ኣብ ከረን ኣምላኽ ንሙሴ ዓሰርተ ኣገዳሲ ሕግታት ሃቦ። ንህዝቢ ንኣምላኽ ልዕሊ ዅሉ ኺፍቅሩ ንሓድሕዶም ድማ ኪፋቐሩን ኪከባበሩን መሃርዎም። ኣምላኽ ንደቁ ሕጉሳትን ድሑናትን ኪኾኑ ኸም ሰናይ ወላዲ ብፍቕሪ ሃቦም።",
   "በተራራ ላይ እግዚአብሔር ለሙሴ አሥር አስፈላጊ ሕጎችን ሰጠ። ሕዝቡ እግዚአብሔርን ከሁሉ በላይ እንዲወዱና እርስ በርስ እንዲዋደዱና እንዲከባበሩ አስተማሩ። እግዚአብሔር ልጆቹ ደስተኛና ደኅና እንዲሆኑ እንደ መልካም ወላጅ በፍቅር ሰጣቸው።",
   "God's rules are gifts of love to help us live well.","ሕግታት ኣምላኽ ጽቡቕ ኪንነብር ዚሕግዙ ህያባት ፍቕሪ እዮም።","የእግዚአብሔር ሕጎች በመልካም እንድንኖር የፍቅር ስጦታዎች ናቸው.","scroll"),
 S("Into the Promised Land","ናብ ምድሪ ተስፋ","ወደ ተስፋይቱ ምድር","Joshua 3-6",
   "After Moses, Joshua led the people into the land God promised. At the city of Jericho, God told them to march and trust Him. When they obeyed, the great walls fell down. God keeps His promises when His people trust and obey.",
   "ድሕሪ ሙሴ፡ እያሱ ንህዝቢ ናብታ ኣምላኽ ተስፋ ዝኣተወላ ምድሪ መርሖም። ኣብ ከተማ ያሪኮ ኣምላኽ ኪዞሩን ኪውከልዎን ነገሮም። ምስ ተኣዘዙ እቶም ዓበይቲ መናድቕ ወደቑ። ህዝቡ ኺውከልዎን ኪእዘዝዎን ከለዉ ኣምላኽ ተስፋታቱ ይሕልው።",
   "ከሙሴ በኋላ ኢያሱ ሕዝቡን ወደ እግዚአብሔር ተስፋ ወደ ገባላት ምድር መራ። በኢያሪኮ ከተማ እግዚአብሔር እንዲዞሩና እንዲታመኑት ነገራቸው። ሲታዘዙ ታላላቆቹ ቅጥሮች ወደቁ። ሕዝቡ ሲታመኑና ሲታዘዙ እግዚአብሔር ተስፋውን ይጠብቃል።",
   "God keeps His promises when we trust and obey.","ክንውከልን ክንእዘዝን ከለና ኣምላኽ ተስፋታቱ ይሕልው።","ስንታመንና ስንታዘዝ እግዚአብሔር ተስፋውን ይጠብቃል.","temple"),
 S("Deborah Leads Bravely","ዲቦራ ብትብዓት ትመርሕ","ደቦራ በድፍረት ትመራለች","Judges 4",
   "Deborah was a wise judge who led God's people. When enemies came, she trusted God and encouraged the army to be brave. God gave them victory. God uses anyone who trusts Him, men and women alike, to do great things.",
   "ዲቦራ ንህዝቢ ኣምላኽ እትመርሕ ጥበበኛ ፈራዲት ነበረት። ጸላእቲ ምስ መጹ ብኣምላኽ ተወከለት ንሰራዊት ድማ ተባዓት ኪኾኑ ኣተባብዓቶም። ኣምላኽ ዓወት ሃቦም። ኣምላኽ ንዚውከልዎ ሰብኡትን ኣንስትን ዓበይቲ ነገራት ኪገብሩ ይጥቀመሎም።",
   "ደቦራ የእግዚአብሔርን ሕዝብ የመራች ጥበበኛ ፈራጅ ነበረች። ጠላቶች ሲመጡ በእግዚአብሔር ታመነች ሠራዊቱም ደፋሮች እንዲሆኑ አበረታታች። እግዚአብሔር ድል ሰጣቸው። እግዚአብሔር በእርሱ የሚታመኑ ወንዶችንም ሴቶችንም ታላቅ ነገር እንዲያደርጉ ይጠቀማል።",
   "God uses anyone who trusts Him to do great things.","ኣምላኽ ንዚውከልዎ ዅሉ ዓበይቲ ነገራት ኪገብር ይጥቀመሉ።","እግዚአብሔር በእርሱ የሚታመንን ሁሉ ለታላቅ ነገር ይጠቀማል.","woman"),
 S("Gideon's Small Army","ንእሽቶ ሰራዊት ጌዴዎን","የጌዴዎን ትንሽ ሠራዊት","Judges 7",
   "God chose Gideon to save His people, but told him to use only 300 men against a huge army. With trumpets and torches, and God's help, they won! God showed that victory comes from Him, not from big numbers.",
   "ኣምላኽ ንህዝቡ ኬድሕን ንጌዴዎን መረጾ፡ ኣንጻር ዓቢ ሰራዊት ግና 300 ሰብኡት ጥራይ ኪጥቀም ነገሮ። ብመለኸትን ብጥዋፍን ብሓገዝ ኣምላኽን ሰዓሩ! ዓወት ካብ ኣምላኽ እምበር ካብ ብዝሒ ኸም ዘይኮነ ኣምላኽ ኣርኣየ።",
   "እግዚአብሔር ሕዝቡን ለማዳን ጌዴዎንን መረጠ፡ በታላቅ ሠራዊት ላይ ግን 300 ሰዎች ብቻ እንዲጠቀም ነገረው። በመለከትና በችቦ በእግዚአብሔር እርዳታ አሸነፉ! ድል ከእግዚአብሔር እንጂ ከብዛት እንዳልሆነ አሳየ።",
   "Victory comes from God, not from our own strength.","ዓወት ካብ ኣምላኽ እምበር ካብ ሓይልና ኣይኮነን።","ድል ከእግዚአብሔር እንጂ ከራሳችን ኃይል አይደለም.","hills"),
 S("Ruth's Faithful Love","ተኣማንነት ፍቕሪ ሩት","የሩት ታማኝ ፍቅር","Ruth 1-4",
   "After hard times, Ruth stayed loyal to her mother-in-law Naomi and to God. She worked hard and was kind. God blessed her with a new family, and she became the great-grandmother of King David. Loyalty and kindness are rewarded by God.",
   "ድሕሪ ኸቢድ እዋን ሩት ንሓማታ ናኦሚን ንኣምላኽን እምንቲ ኮነት። ብትግሃት ሰርሐት ለዋህ ድማ ነበረት። ኣምላኽ ብሓዳስ ስድራ ቤት ባረኻ፡ ዓባይ ዓባይ ንጉስ ዳዊት ድማ ኮነት። ተኣማንነትን ለውሃትን ብኣምላኽ ይምንዘዓ።",
   "ከከባድ ጊዜ በኋላ ሩት ለአማቷ ናኦሚና ለእግዚአብሔር ታማኝ ሆነች። በትጋት ሠራች ደግም ነበረች። እግዚአብሔር በአዲስ ቤተሰብ ባረካት፡ የንጉሥ ዳዊት ቅድመ አያትም ሆነች። ታማኝነትና ደግነት በእግዚአብሔር ይመነዳሉ።",
   "Loyalty and kindness are rewarded by God.","ተኣማንነትን ለውሃትን ብኣምላኽ ይምንዘዓ።","ታማኝነትና ደግነት በእግዚአብሔር ይመነዳሉ.","woman"),
 S("God Calls Samuel","ኣምላኽ ንሳሙኤል ይጽውዕ","እግዚአብሔር ሳሙኤልን ይጠራል","1 Samuel 3",
   "Young Samuel slept in the temple when he heard a voice calling his name. It was God! The priest taught him to answer, 'Speak, Lord, your servant is listening.' Samuel listened, and God made him a great prophet. God speaks; we should be ready to listen.",
   "ንእሽቶ ሳሙኤል ኣብ ቤተ መቕደስ ደቂሱ ኸሎ ስሙ ዚጽውዕ ድምጺ ሰምዐ። ኣምላኽ እዩ ነይሩ! እቲ ኻህን፡ 'ተዛረብ ጐይታ፡ ባርያኻ ይሰምዕ ኣሎ' ኢሉ ኪምልስ መሃሮ። ሳሙኤል ሰምዐ፡ ኣምላኽ ድማ ዓቢ ነብዪ ገበሮ። ኣምላኽ ይዛረብ፡ ንሕና ኽንሰምዕ ክንዳሎ ኣሎና።",
   "ወጣቱ ሳሙኤል በቤተ መቅደስ ተኝቶ ሳለ ስሙን የሚጠራ ድምፅ ሰማ። እግዚአብሔር ነበር! ካህኑ፡ 'ተናገር ጌታ ሆይ ባሪያህ ይሰማል' ብሎ እንዲመልስ አስተማረው። ሳሙኤል ሰማ፡ እግዚአብሔርም ታላቅ ነቢይ አደረገው። እግዚአብሔር ይናገራል፡ እኛ ለመስማት መዘጋጀት አለብን።",
   "God speaks; be ready to listen and obey.","ኣምላኽ ይዛረብ፡ ንኺሰምዕን ንኺእዘዝን ተዳሎ።","እግዚአብሔር ይናገራል፡ ለመስማትና ለመታዘዝ ተዘጋጅ.","temple"),
 S("David the Shepherd King","ዳዊት ጓሳ ንጉስ","ዳዊት እረኛ ንጉሥ","1 Samuel 16",
   "God sent Samuel to choose a new king. The tall, strong brothers passed by, but God chose David, the young shepherd. God said, 'People look at the outside, but I look at the heart.' God sees who we really are inside.",
   "ኣምላኽ ንሳሙኤል ሓድሽ ንጉስ ኪመርጽ ለኣኾ። ነዋሕትን ሓያላትን ኣሕዋት ሓለፉ፡ ኣምላኽ ግና ንዳዊት እቲ ንኡስ ጓሳ መረጾ። ኣምላኽ 'ሰብ ንደገ ይርኢ፡ ኣነ ግና ንልቢ እርኢ' በለ። ኣምላኽ ኣብ ውሽጥና መን ምዃንና ይርኢ።",
   "እግዚአብሔር ሳሙኤልን አዲስ ንጉሥ እንዲመርጥ ላከው። ረጃጅሙና ጠንካሮች ወንድሞች አለፉ፡ እግዚአብሔር ግን ወጣቱን እረኛ ዳዊትን መረጠ። እግዚአብሔር 'ሰው ውጪውን ያያል፡ እኔ ግን ልብን አያለሁ' አለ። እግዚአብሔር በውስጣችን ማን እንደሆንን ያያል።",
   "God looks at the heart, not the outside.","ኣምላኽ ንልቢ ይርኢ፡ ንደገ ኣይኮነን።","እግዚአብሔር ልብን ያያል፡ ውጪውን አይደለም.","crown"),
 S("David and the Giant","ዳዊትን እቲ ገዚፍን","ዳዊትና ግዙፉ","1 Samuel 17",
   "A giant soldier named Goliath frightened everyone. But young David trusted God. With a sling and a stone, and God's help, David defeated the giant. David showed that with God even the small can be brave and strong.",
   "ጎልያድ ዝበሃል ገዚፍ ወተሃደር ንዅሉ የፍርሖ ነበረ። ንእሽቶ ዳዊት ግና ብኣምላኽ ተወከለ። ብወንጭፍን ብእምንን ብሓገዝ ኣምላኽን ዳዊት ነቲ ገዚፍ ሰዓሮ። ብኣምላኽ ንኡስ እኳ ተባዕን ሓያልን ኪኸውን ከም ዚኽእል ዳዊት ኣርኣየ።",
   "ጎልያድ የተባለ ግዙፍ ወታደር ሁሉንም ያስፈራ ነበር። ወጣቱ ዳዊት ግን በእግዚአብሔር ታመነ። በወንጭፍና በድንጋይ በእግዚአብሔር እርዳታ ዳዊት ግዙፉን አሸነፈ። በእግዚአብሔር ትንሹም እንኳ ደፋርና ጠንካራ ሊሆን እንደሚችል ዳዊት አሳየ።",
   "With God, even the small can be brave.","ብኣምላኽ ንኡስ እኳ ተባዕ ኪኸውን ይኽእል።","በእግዚአብሔር ትንሹም እንኳ ደፋር ሊሆን ይችላል.","hills"),
 S("Solomon Asks for Wisdom","ሰሎሞን ጥበብ ይሓትት","ሰሎሞን ጥበብን ይጠይቃል","1 Kings 3",
   "When Solomon became king, God offered him anything. Solomon did not ask for money, but for wisdom to lead God's people well. God was so pleased that He gave him wisdom AND riches. Wanting to do good pleases God.",
   "ሰሎሞን ንጉስ ምስ ኮነ ኣምላኽ ዝደለዮ ዅሉ ኺህቦ ኣቕረበሉ። ሰሎሞን ገንዘብ ዘይኮነስ ንህዝቢ ኣምላኽ ጽቡቕ ኪመርሕ ጥበብ ለመነ። ኣምላኽ ኣዝዩ ተሓጐሰ እሞ ጥበብን ሃብትን ሃቦ። ጽቡቕ ምግባር ምድላይ ንኣምላኽ ባህ የብሎ።",
   "ሰሎሞን ንጉሥ ሲሆን እግዚአብሔር የፈለገውን ሁሉ አቀረበለት። ሰሎሞን ገንዘብ ሳይሆን የእግዚአብሔርን ሕዝብ በሚገባ ለመምራት ጥበብ ለመነ። እግዚአብሔር እጅግ ደስ አለው ጥበብንና ሀብትንም ሰጠው። መልካም ማድረግ መፈለግ እግዚአብሔርን ደስ ያሰኘዋል።",
   "Ask God for wisdom to do what is good.","ጽቡቕ ንኽትገብር ካብ ኣምላኽ ጥበብ ለምን።","መልካም ለማድረግ ከእግዚአብሔር ጥበብ ለምን.","crown"),
 S("Elijah and the Fire","ኤልያስን ሓውን","ኤልያስና እሳቱ","1 Kings 18",
   "The prophet Elijah showed that the Lord alone is the true God. He prayed, and God sent fire from heaven while the false gods did nothing. Everyone saw that God is real and powerful. There is only one true God, and He answers prayer.",
   "ነብዪ ኤልያስ እግዚኣብሄር ጥራይ ሓቀኛ ኣምላኽ ምዃኑ ኣርኣየ። ጸለየ፡ ኣምላኽ ካብ ሰማይ ሓዊ ለኣኸ፡ እቶም ናይ ሓሶት ኣማልኽቲ ግና ገለ እኳ ኣይገበሩን። ኵሉ ኣምላኽ ናይ ሓቂ ሓያልን ምዃኑ ረኣየ። ሓደ ሓቀኛ ኣምላኽ ጥራይ ኣሎ፡ ንሱ ድማ ጸሎት ይምልስ።",
   "ነቢዩ ኤልያስ እግዚአብሔር ብቻ እውነተኛ አምላክ መሆኑን አሳየ። ጸለየ፡ እግዚአብሔር ከሰማይ እሳት ላከ፡ የሐሰት አማልክት ግን ምንም አላደረጉም። ሁሉም እግዚአብሔር እውነተኛና ኃያል መሆኑን አየ። አንድ እውነተኛ አምላክ ብቻ አለ፡ እርሱም ጸሎትን ይመልሳል።",
   "There is only one true God, and He answers prayer.","ሓደ ሓቀኛ ኣምላኽ ጥራይ ኣሎ፡ ንሱ ጸሎት ይምልስ።","አንድ እውነተኛ አምላክ ብቻ አለ፡ እርሱም ጸሎትን ይመልሳል.","prophet"),
]


BIG_STORY += [
 S("Jonah and the Big Fish","ዮናስን እቲ ዓቢ ዓሳን","ዮናስና ታላቁ ዓሣ","Jonah 1-3",
   "God told Jonah to go warn the city of Nineveh, but Jonah ran away on a ship. A storm came, and a great fish swallowed Jonah. Inside, he prayed and said sorry. God gave him another chance, and Nineveh turned back to God. God is patient and forgiving.",
   "ኣምላኽ ንዮናስ ንኸተማ ነነዌ ኺጠንቅቕ ነገሮ፡ ዮናስ ግና ብመርከብ ሃደመ። ህቦብላ መጸ፡ ዓቢ ዓሳ ድማ ንዮናስ ወሓጦ። ኣብ ውሽጡ ጸለየ ተጣዕሰ ድማ። ኣምላኽ ካልእ ዕድል ሃቦ፡ ነነዌ ድማ ናብ ኣምላኽ ተመልሰት። ኣምላኽ ዓቃልን ይቕረ በሃልን እዩ።",
   "እግዚአብሔር ዮናስን የነነዌን ከተማ እንዲያስጠነቅቅ ነገረው፡ ዮናስ ግን በመርከብ ሸሸ። ማዕበል መጣ፡ ታላቅ ዓሣም ዮናስን ዋጠው። ውስጡ ጸለየ ተጸጸተም። እግዚአብሔር ሌላ ዕድል ሰጠው፡ ነነዌም ወደ እግዚአብሔር ተመለሰች። እግዚአብሔር ታጋሽና ይቅር ባይ ነው።",
   "God is patient and always ready to forgive.","ኣምላኽ ዓቃልን ኵሉ ግዜ ይቕረ ንኺብል ድሉውን እዩ።","እግዚአብሔር ታጋሽና ሁልጊዜ ይቅር ለማለት ዝግጁ ነው.","boat"),
 S("God's Comforting Promise","ዜጸናንዕ መብጽዓ ኣምላኽ","የእግዚአብሔር የሚያጽናና ተስፋ","Isaiah 40",
   "The prophet Isaiah spoke comforting words from God: 'Those who trust the Lord will find new strength. They will soar like eagles.' When people feel tired and afraid, God gives them hope and renewed strength. God cares for His weary people.",
   "ነብዪ ኢሳይያስ ካብ ኣምላኽ ዜጸናንዕ ቃላት ተዛረበ፡ 'እቶም ንእግዚኣብሄር ዚውከሉ ሓድሽ ሓይሊ ኪረኽቡ እዮም። ከም ንስሪ ኪበሩ እዮም።' ሰባት ደኺሞምን ፈሪሆምን ከለዉ ኣምላኽ ተስፋን ሓድሽ ሓይልን ይህቦም። ኣምላኽ ንደኸየ ህዝቡ ይግደሰሉ።",
   "ነቢዩ ኢሳይያስ ከእግዚአብሔር የሚያጽናኑ ቃላት ተናገረ፡ 'እግዚአብሔርን የሚታመኑ አዲስ ኃይል ያገኛሉ። እንደ ንስር ይበራሉ።' ሰዎች ደክሟቸውና ፈርተው ሲሆኑ እግዚአብሔር ተስፋና አዲስ ኃይል ይሰጣቸዋል። እግዚአብሔር ስለ ደከመው ሕዝቡ ያስባል።",
   "God gives new strength to those who trust Him.","ኣምላኽ ንዚውከልዎ ሓድሽ ሓይሊ ይህብ።","እግዚአብሔር በእርሱ ለሚታመኑ አዲስ ኃይል ይሰጣል.","prophet"),
 S("Daniel and the Lions","ዳንኤልን ኣናብስን","ዳንኤልና አንበሶች","Daniel 6",
   "Daniel loved God and prayed every day. Jealous men tricked the king into a law against prayer, and Daniel was thrown to hungry lions. But God sent an angel to shut the lions' mouths, and Daniel was safe. Stay faithful, and trust God to protect you.",
   "ዳንኤል ንኣምላኽ የፍቅሮ ነበረ ኵሉ መዓልቲ ድማ ይጽሊ ነበረ። ቀናኣት ሰባት ንንጉስ ኣታልዮም ኣንጻር ጸሎት ሕጊ ኣውጽኡ፡ ዳንኤል ድማ ናብ ጥሙያት ኣናብስ ተደርበየ። ኣምላኽ ግና ኣፍ ኣናብስ ኪዓጹ መልኣኽ ለኣኸ፡ ዳንኤል ድማ ድሑን ኮነ። እሙን ኩን፡ ኣምላኽ ኪሕልወካ ድማ ተወከሎ።",
   "ዳንኤል እግዚአብሔርን ይወድ ነበር በየቀኑም ይጸልይ ነበር። ቀናተኞች ሰዎች ንጉሡን አታልለው በጸሎት ላይ ሕግ አወጡ፡ ዳንኤልም ወደ ተራቡ አንበሶች ተጣለ። እግዚአብሔር ግን የአንበሶችን አፍ ለመዝጋት መልአክ ላከ፡ ዳንኤልም ደኅና ሆነ። ታማኝ ሁን፡ እግዚአብሔር እንዲጠብቅህም ታመን።",
   "Stay faithful; God protects those who trust Him.","እሙን ኩን፡ ኣምላኽ ንዚውከልዎ ይሕልዎም።","ታማኝ ሁን፡ እግዚአብሔር በእርሱ የሚታመኑትን ይጠብቃል.","angel"),
 S("The Fiery Furnace","እቲ ዚነድድ እቶን","የሚነደው እቶን","Daniel 3",
   "Three brave friends refused to bow to a golden statue, so they were thrown into a blazing furnace. But God kept them safe, and a fourth figure walked with them in the fire. God is with us even in our hardest trials.",
   "ሰለስተ ተባዓት ኣዕሩኽ ንናይ ወርቂ ምስሊ ኪሰግዱ ኣበዩ፡ ስለዚ ናብ ዚነድድ እቶን ተደርበዩ። ኣምላኽ ግና ድሑናት ገበሮም፡ ራብዓይ ኣካል ድማ ኣብቲ ሓዊ ምሳታቶም ይኸይድ ነበረ። ኣምላኽ ኣብ ኣዝዩ ኸበድቲ ፈተናታትና እኳ ምሳና እዩ።",
   "ሦስት ደፋር ጓደኞች ለወርቅ ምስል መስገድን እምቢ አሉ፡ ስለዚህ ወደሚነድ እቶን ተጣሉ። እግዚአብሔር ግን ደኅና አደረጋቸው፡ አራተኛ አካልም በእሳቱ ውስጥ ከእነርሱ ጋር ይሄድ ነበር። እግዚአብሔር በእጅግ ከባድ ፈተናዎቻችንም ከእኛ ጋር ነው።",
   "God is with us even in our hardest trials.","ኣምላኽ ኣብ ኣዝዩ ኸበድቲ ፈተናታትና እኳ ምሳና እዩ።","እግዚአብሔር በእጅግ ከባድ ፈተናዎቻችንም ከእኛ ጋር ነው.","angel"),
 S("Nehemiah Rebuilds the Wall","ነህምያ ንመንደቕ ይሃንጽ","ነህምያ ቅጥሩን ያንፃል","Nehemiah 2-6",
   "The wall of Jerusalem was broken down. Nehemiah prayed, then led the people to rebuild it together. Enemies tried to stop them, but they kept working and trusting God. In just 52 days the wall was finished. With prayer and teamwork, great things get done.",
   "መንደቕ የሩሳሌም ፈሪሱ ነበረ። ነህምያ ጸለየ፡ ሽዑ ንህዝቢ ብሓደ ኪሃንጽዎ መርሖም። ጸላእቲ ኬቋርጽዎም ፈተኑ፡ ንሳቶም ግና ብኣምላኽ እናተወከሉ ሰርሑ። ብ52 መዓልቲ ጥራይ እቲ መንደቕ ተወድአ። ብጸሎትን ብምትሕብባርን ዓበይቲ ነገራት ይፍጸሙ።",
   "የኢየሩሳሌም ቅጥር ፈርሶ ነበር። ነህምያ ጸለየ፡ ከዚያ ሕዝቡን አብረው እንዲያንፁት መራ። ጠላቶች ሊያስቆሙአቸው ሞከሩ፡ እነርሱ ግን በእግዚአብሔር እየታመኑ ሠሩ። በ52 ቀን ብቻ ቅጥሩ ተጠናቀቀ። በጸሎትና በመተባበር ታላቅ ነገር ይሠራል።",
   "With prayer and teamwork, great things get done.","ብጸሎትን ብምትሕብባርን ዓበይቲ ነገራት ይፍጸሙ።","በጸሎትና በመተባበር ታላቅ ነገር ይሠራል.","temple"),
 S("Esther Saves Her People","ኣስቴር ንህዝባ ተድሕን","አስቴር ሕዝቧን ታድናለች","Esther 4-7",
   "Esther was a young queen. When an evil man planned to harm her people, she bravely went to the king to plead for them, even though it was dangerous. God used her courage to save the whole nation. God can use your courage to help many.",
   "ኣስቴር ንእስቲ ንግስቲ ነበረት። ሓደ እኩይ ሰብ ንህዝባ ኪጐድእ ምስ መደበ፡ ሓደገኛ እኳ እንተ ነበረ ንንጉስ ክትልምኖም ተባዕ ኮነት። ኣምላኽ ብትብዓታ ንብምሉኡ ህዝቢ ኣድሓኖ። ኣምላኽ ብትብዓትካ ንብዙሓት ኪሕግዝ ይኽእል።",
   "አስቴር ወጣት ንግሥት ነበረች። ክፉ ሰው ሕዝቧን ሊጎዳ ሲያቅድ፡ አደገኛ ቢሆንም ወደ ንጉሡ ሄዳ ለመነችላቸው። እግዚአብሔር በድፍረቷ ሕዝቡን ሁሉ አዳነ። እግዚአብሔር በድፍረትህ ብዙዎችን ሊረዳ ይችላል።",
   "God can use your courage to help many people.","ኣምላኽ ብትብዓትካ ንብዙሓት ኪሕግዝ ይኽእል።","እግዚአብሔር በድፍረትህ ብዙዎችን ሊረዳ ይችላል.","crown"),
 S("Job Trusts in Sorrow","ኢዮብ ኣብ ሓዘን ይውከል","ኢዮብ በሐዘን ይታመናል","Job 1-2",
   "Job was a good man who lost his family, his wealth, and his health. His friends did not understand, but Job still trusted God through his tears. In the end, God comforted Job and gave him more than before. We can trust God even when life is hard.",
   "ኢዮብ ስድራ ቤቱን ሃብቱን ጥዕናኡን ዘጥፍአ ጽቡቕ ሰብ ነበረ። ኣዕሩኹ ኣይተረድእዎን፡ ኢዮብ ግና ብንብዓቱ እኳ ኣብ ኣምላኽ ተወከለ። ኣብ መወዳእታ ኣምላኽ ንኢዮብ ኣጸናንዖ ኻብ ቀደሙ ንላዕሊ ድማ ሃቦ። ህይወት ኪኸብድ ከሎ እኳ ብኣምላኽ ክንውከል ንኽእል።",
   "ኢዮብ ቤተሰቡን፡ ሀብቱንና ጤናውን ያጣ መልካም ሰው ነበር። ጓደኞቹ አልተረዱም፡ ኢዮብ ግን በእንባውም እንኳ በእግዚአብሔር ታመነ። በመጨረሻ እግዚአብሔር ኢዮብን አጽናናው ከበፊቱም በላይ ሰጠው። ሕይወት ሲከብድም እንኳ በእግዚአብሔር መታመን እንችላለን።",
   "We can trust God even when life is hard.","ህይወት ኪኸብድ ከሎ እኳ ብኣምላኽ ክንውከል ንኽእል።","ሕይወት ሲከብድም እንኳ በእግዚአብሔር መታመን እንችላለን.","hills"),
 S("The Shepherd's Song","መዝሙር እቲ ጓሳ","የእረኛው መዝሙር","Psalm 23",
   "King David wrote, 'The Lord is my shepherd; I have all I need.' Like a shepherd who leads sheep to green grass and quiet water, God guides and cares for us. Even in dark valleys we need not fear, for God is always with us.",
   "ንጉስ ዳዊት፡ 'እግዚኣብሄር ጓሳየይ እዩ፡ ዘድልየኒ ዅሉ ኣለኒ' ኢሉ ጸሓፈ። ንኣባጊዑ ናብ ልሙዕ ሳዕርን ህዱእ ማይን ከም ዚመርሕ ጓሳ ኣምላኽ ይመርሓናን ይኣልየናን። ኣብ ጸልማት ስንጭሮ እኳ ኣምላኽ ኵሉ ግዜ ምሳና ስለ ዘሎ ክንፈርህ ኣየድልየናን።",
   "ንጉሥ ዳዊት፡ 'እግዚአብሔር እረኛዬ ነው፡ የሚያስፈልገኝ ሁሉ አለኝ' ብሎ ጻፈ። በጎቹን ወደ ለምለም ሣርና ጸጥ ወዳለ ውኃ እንደሚመራ እረኛ እግዚአብሔር ይመራናል ይንከባከበናልም። በጨለማ ሸለቆም እንኳ እግዚአብሔር ሁልጊዜ ከእኛ ጋር ስለሆነ መፍራት አያስፈልገንም።",
   "God guides and cares for us like a shepherd.","ኣምላኽ ከም ጓሳ ይመርሓናን ይኣልየናን።","እግዚአብሔር እንደ እረኛ ይመራናል ይንከባከበናልም.","hills"),
 S("Wisdom for Living","ጥበብ ንህይወት","ለሕይወት ጥበብ","Proverbs 3",
   "King Solomon wrote wise sayings. One of the best is, 'Trust in the Lord with all your heart, and He will guide your paths.' When we honor God in everything and ask for His help, He shows us the right way to go.",
   "ንጉስ ሰሎሞን ጥበባዊ ምስላታት ጸሓፈ። ካብቲ ዝበለጸ ሓደ፡ 'ብምሉእ ልብኻ ብእግዚኣብሄር ተወከል፡ ንመገድኻ ኸኣ ኬቕንዖ እዩ' ዚብል እዩ። ኣብ ኵሉ ንኣምላኽ ምስ ነኽብሮን ሓገዙ ምስ እንልምንን ቅኑዕ መገዲ የርእየና።",
   "ንጉሥ ሰሎሞን ጥበብ ያላቸው ምሳሌዎችን ጻፈ። ከምርጦቹ አንዱ፡ 'በፍጹም ልብህ በእግዚአብሔር ታመን፡ መንገድህንም ያቀናል' የሚለው ነው። በሁሉ እግዚአብሔርን ስናከብርና እርዳታውን ስንለምን ትክክለኛውን መንገድ ያሳየናል።",
   "Trust God with all your heart, and He will guide you.","ብምሉእ ልብኻ ብኣምላኽ ተወከል፡ ኪመርሓካ ድማ እዩ።","በፍጹም ልብህ በእግዚአብሔር ታመን፡ ይመራሃልም.","scroll"),
 S("A Rescuer is Promised","መድሓኒ ተመባጽዐ","አዳኝ ተስፋ ተሰጠ","Micah 5:2",
   "The prophets told of a special King who would come to save the world. He would be born in a small town called Bethlehem, be gentle and humble, and bring peace. For hundreds of years, God's people waited for this promise to come true.",
   "ነብያት ንዓለም ኬድሕን ዚመጽእ ፍሉይ ንጉስ ተነበዩ። ኣብ ቤትልሄም እትብሃል ንእሽቶ ኸተማ ኪውለድ፡ ልዙብን ትሑትን ኪኸውን፡ ሰላም ድማ ኬምጽእ እዩ። ንኣማእታት ዓመታት ህዝቢ ኣምላኽ እዚ መብጽዓ ኪፍጸም ተጸበዩ።",
   "ነቢያት ዓለምን የሚያድን ልዩ ንጉሥ እንደሚመጣ ተነበዩ። ቤተልሔም በምትባል ትንሽ ከተማ ይወለዳል፡ ገርና ትሑት ይሆናል፡ ሰላምም ያመጣል። ለብዙ መቶ ዓመታት የእግዚአብሔር ሕዝብ ይህ ተስፋ እንዲፈጸም ጠበቁ።",
   "God always keeps His promises, in His own time.","ኣምላኽ ብግዜኡ ተስፋታቱ ኵሉ ግዜ ይሕልው።","እግዚአብሔር በራሱ ጊዜ ተስፋውን ሁልጊዜ ይጠብቃል.","star"),
 S("The Angel Visits Mary","መልኣኽ ንማርያም ይበጽሓ","መልአኩ ማርያምን ይጎበኛል","Luke 1",
   "God sent the angel Gabriel to a young woman named Mary. He told her she would give birth to Jesus, the Son of God. Mary was surprised but trusted God, saying, 'Let it be as you have said.' The waiting was almost over; the Rescuer was coming.",
   "ኣምላኽ ንመልኣኽ ገብርኤል ናብ ማርያም እትብሃል ንእስቲ ጓል ለኣኾ። ንየሱስ፡ ወዲ ኣምላኽ ከም እትወልድ ነገራ። ማርያም ተገረመት ብኣምላኽ ግና ተወከለት፡ 'ከምቲ ዝበልካኒ ይኹን' በለት። እቲ ምጽባይ ኪውዳእ ቀሪቡ ነበረ፡ እቲ መድሓኒ ይመጽእ ነበረ።",
   "እግዚአብሔር መልአኩ ገብርኤልን ማርያም ወደተባለች ወጣት ሴት ላከ። የእግዚአብሔርን ልጅ ኢየሱስን እንደምትወልድ ነገራት። ማርያም ተገረመች በእግዚአብሔር ግን ታመነች፡ 'እንዳልከው ይሁን' አለች። መጠበቁ ሊያበቃ ተቃርቦ ነበር፡ አዳኙ እየመጣ ነበር።",
   "Trust God and say yes to His plan.","ብኣምላኽ ተወከል ንመደቡ ድማ እወ በል።","በእግዚአብሔር ታመን ለዕቅዱም አዎ በል.","angel"),
]


BIG_STORY += [
 S("Jesus is Born","የሱስ ይውለድ","ኢየሱስ ይወለዳል","Luke 2",
   "In Bethlehem, baby Jesus was born and laid in a manger, because there was no room in the inn. Angels told shepherds the wonderful news, and they hurried to see Him. The long-promised Rescuer had finally come into the world.",
   "ኣብ ቤትልሄም ህጻን የሱስ ተወልደ ኣብ መብልዕ ከብቲ ድማ ተቐመጠ፡ ኣብ ማሕደር ስፍራ ስለ ዘይነበረ። መላእኽቲ ንጓሶት እቲ ዜደንቕ ብስራት ነገርዎም፡ ንሱ ኺርእዩ ድማ ተሓጓሱ። እቲ ኻብ ጥንቲ እተመባጽዐ መድሓኒ ኣብ መወዳእታ ናብ ዓለም መጸ።",
   "በቤተልሔም ሕፃኑ ኢየሱስ ተወለደ በግርግምም ተኛ፡ በማደሪያው ስፍራ ስላልነበረ። መላእክት ለእረኞች ድንቁን የምስራች ነገሩአቸው፡ ሊያዩትም ቸኮሉ። ከጥንት ተስፋ የተሰጠው አዳኝ በመጨረሻ ወደ ዓለም መጣ።",
   "God kept His promise: the Savior was born!","ኣምላኽ ተስፋኡ ሓለወ፡ እቲ መድሓኒ ተወልደ!","እግዚአብሔር ተስፋውን ጠበቀ፡ አዳኙ ተወለደ!","star"),
 S("Wise Men Follow the Star","ጠቢባን ንኮኸብ ይስዕቡ","ጠቢባን ኮከቡን ይከተላሉ","Matthew 2",
   "Wise men from far away saw a special star and followed it to find the newborn King. They knelt before Jesus and gave Him precious gifts of gold, frankincense, and myrrh. People from every land are welcome to come and worship Jesus.",
   "ጠቢባን ካብ ርሑቕ ፍሉይ ኮኸብ ረኸቡ ነቲ ሕጻን ንጉስ ኪረኽብዎ ድማ ሰዓብዎ። ኣብ ቅድሚ የሱስ ተምበርኪኾም ክቡር ህያባት ወርቅን ዕጣንን ከርበእን ሃብዎ። ካብ ኵሉ ሃገር ዝመጹ ሰባት ናብ የሱስ መጺኦም ኪሰግዱ ቅቡላት እዮም።",
   "ጠቢባን ከሩቅ ልዩ ኮከብ አዩ አዲስ የተወለደውን ንጉሥ ለማግኘትም ተከተሉት። በኢየሱስ ፊት ተንበርክከው ውድ ስጦታ ወርቅ፡ ዕጣንና ከርቤ ሰጡት። ከየትኛውም አገር የመጡ ሰዎች ወደ ኢየሱስ መጥተው ሊሰግዱ ተቀባይነት አላቸው።",
   "Everyone everywhere is welcome to come to Jesus.","ካብ ኵሉ ቦታ ዝመጸ ኵሉ ናብ የሱስ ኪመጽእ ቅቡል እዩ።","ከየትኛውም ቦታ የመጣ ሁሉ ወደ ኢየሱስ ሊመጣ ተቀባይነት አለው.","star"),
 S("Jesus is Baptized","የሱስ ይጥመቕ","ኢየሱስ ይጠመቃል","Matthew 3",
   "When Jesus grew up, John baptized Him in the Jordan River. As Jesus came out of the water, heaven opened, the Spirit came like a dove, and God's voice said, 'This is my beloved Son.' Jesus was ready to begin His special work.",
   "የሱስ ምስ ዓበየ ዮሃንስ ኣብ ርባ ዮርዳኖስ ኣጠመቖ። የሱስ ካብ ማይ ክወጽእ ከሎ ሰማይ ተኸፍተ፡ መንፈስ ከም ርግቢ ወረደ፡ ድምጺ ኣምላኽ ድማ 'እዚ ፍቁር ወደይ እዩ' በለ። የሱስ ነቲ ፍሉይ ዕዮኡ ኪጅምር ተዳለወ።",
   "ኢየሱስ ሲያድግ ዮሐንስ በዮርዳኖስ ወንዝ አጠመቀው። ኢየሱስ ከውኃው ሲወጣ ሰማይ ተከፈተ፡ መንፈስ እንደ ርግብ ወረደ፡ የእግዚአብሔር ድምፅም 'ይህ የተወደደ ልጄ ነው' አለ። ኢየሱስ ልዩ ሥራውን ለመጀመር ተዘጋጀ።",
   "God is pleased when we obey and follow Him.","ክንእዘዝን ክንስዕቦን ከለና ኣምላኽ ባህ ይብሎ።","ስንታዘዝና ስንከተለው እግዚአብሔር ደስ ይለዋል.","dove"),
 S("Jesus Chooses Helpers","የሱስ ሓገዝቲ ይመርጽ","ኢየሱስ ረዳቶችን ይመርጣል","Mark 1:16-20",
   "Jesus called ordinary fishermen to follow Him: 'Come, and I will make you fishers of people.' They left their nets at once and followed Jesus. He wanted friends to help share God's love. Jesus still calls ordinary people to do wonderful things.",
   "የሱስ ተራ ገፈፍቲ ዓሳ ኪስዕብዎ ጸውዖም፡ 'ንዑ፡ ገፈፍቲ ሰብ ክገብረኩም እየ።' ብኡንብኡ መርበቦም ገዲፎም ንየሱስ ሰዓብዎ። ፍቕሪ ኣምላኽ ንኺካፈሉ ዚሕግዝዎ ኣዕሩኽ ደለየ። የሱስ ሎሚ እውን ንተራ ሰባት ዜደንቕ ነገራት ኪገብሩ ይጽውዕ።",
   "ኢየሱስ ተራ ዓሣ አጥማጆችን ሊከተሉት ጠራቸው፡ 'ኑ፡ ሰው አጥማጆች አደርጋችኋለሁ።' ወዲያውኑ መረባቸውን ትተው ኢየሱስን ተከተሉ። የእግዚአብሔርን ፍቅር ለማካፈል የሚረዱት ጓደኞች ፈለገ። ኢየሱስ ዛሬም ተራ ሰዎችን ድንቅ ነገር እንዲያደርጉ ይጠራል።",
   "Jesus calls ordinary people to follow and help Him.","የሱስ ንተራ ሰባት ኪስዕብዎን ኪሕግዝዎን ይጽውዕ።","ኢየሱስ ተራ ሰዎችን ሊከተሉትና ሊረዱት ይጠራል.","boat"),
 S("Jesus Calms the Storm","የሱስ ንህቦብላ የህድኦ","ኢየሱስ ማዕበሉን ያረጋጋል","Mark 4:35-41",
   "Jesus and His friends were in a boat when a fierce storm arose. The friends were terrified, but Jesus stood up and said, 'Peace, be still!' At once the wind and waves became calm. Jesus has power over every storm, and He is always with us.",
   "የሱስን ኣዕሩኹን ኣብ ጃልባ ኸለዉ ብርቱዕ ህቦብላ ተላዕለ። እቶም ኣዕሩኽ ፈርሁ፡ የሱስ ግና ተንሲኡ 'ስቕ በል፡ ህዱእ ኹን!' በለ። ብኡንብኡ ንፋስን ማዕበልን ህዱኣት ኮኑ። የሱስ ኣብ ልዕሊ ዅሉ ህቦብላ ሓይሊ ኣለዎ፡ ኵሉ ግዜ ድማ ምሳና ኣሎ።",
   "ኢየሱስና ጓደኞቹ በጀልባ ውስጥ ሳሉ ኃይለኛ ማዕበል ተነሳ። ጓደኞቹ ፈሩ፡ ኢየሱስ ግን ተነስቶ 'ጸጥ በል፡ ዝም በል!' አለ። ወዲያውኑ ነፋሱና ማዕበሉ ጸጥ አሉ። ኢየሱስ በማዕበል ሁሉ ላይ ኃይል አለው፡ ሁልጊዜም ከእኛ ጋር ነው።",
   "Jesus has power over every storm; do not be afraid.","የሱስ ኣብ ልዕሊ ዅሉ ህቦብላ ሓይሊ ኣለዎ፡ ኣይትፍራህ።","ኢየሱስ በማዕበል ሁሉ ላይ ኃይል አለው፡ አትፍራ.","boat"),
 S("Jesus Feeds the Crowd","የሱስ ንህዝቢ ይምግብ","ኢየሱስ ሕዝቡን ይመግባል","John 6:1-14",
   "A huge crowd was hungry, but there was only a boy's five loaves and two fish. Jesus gave thanks, and the food multiplied until everyone was full, with baskets left over! When we give Jesus even a little, He can do great things with it.",
   "ብዙሕ ህዝቢ ጠምዩ ነበረ፡ ናይ ሓደ ቆልዓ ሓሙሽተ እንጌራን ክልተ ዓሳን ጥራይ ግና ነበረ። የሱስ ኣመስጊኑ፡ እቲ ምግቢ ኵሉ ኽሳብ ዚጸግብ በዝሐ፡ መሶባት ድማ ተረፈ! ንየሱስ ንእሽቶ እኳ ምስ እንህቦ ዓበይቲ ነገራት ኪገብረሉ ይኽእል።",
   "ብዙ ሕዝብ ተርቦ ነበር፡ የአንድ ልጅ አምስት እንጀራና ሁለት ዓሣ ብቻ ግን ነበረ። ኢየሱስ አመሰገነ፡ ምግቡም ሁሉም እስኪጠግብ በዛ፡ ቅርጫቶችም ተረፉ! ለኢየሱስ ትንሽም እንኳ ስንሰጠው ታላቅ ነገር ሊያደርግበት ይችላል።",
   "Give Jesus your little, and He does great things.","ንየሱስ ንእሽቶኻ ሃብ፡ ዓበይቲ ነገራት ድማ ይገብር።","ለኢየሱስ ትንሽህን ስጥ፡ ታላቅ ነገርም ያደርጋል.","loaves"),
 S("Jesus Loves the Children","የሱስ ንቖልዑ የፍቅር","ኢየሱስ ልጆችን ይወዳል","Mark 10:13-16",
   "Parents brought their children to Jesus, but the disciples tried to send them away. Jesus said, 'Let the little children come to Me!' He held them, blessed them, and said God's kingdom belongs to those with childlike hearts. You are precious to Jesus.",
   "ወለዲ ደቆም ናብ የሱስ ኣምጽኡ፡ ደቀ መዛሙርቲ ግና ኪሰድዎም ፈተኑ። የሱስ 'ንኣሽቱ ቘልዑ ናባይ ይምጽኡ ሕደግዎም!' በለ። ሓቚፉ ባረኾም፡ መንግስቲ ኣምላኽ ናይቶም ከም ቆልዓ ልቢ ዘለዎም ምዃና ድማ በለ። ንስኻ ንየሱስ ክቡር ኢኻ።",
   "ወላጆች ልጆቻቸውን ወደ ኢየሱስ አመጡ፡ ደቀ መዛሙርቱ ግን ሊሰዷቸው ሞከሩ። ኢየሱስ 'ትንንሽ ልጆች ወደ እኔ ይምጡ ተዉአቸው!' አለ። አቅፎ ባረካቸው፡ የእግዚአብሔር መንግሥት እንደ ልጅ ልብ ላላቸው እንደሆነም አለ። አንተ ለኢየሱስ ውድ ነህ።",
   "You are precious to Jesus, just as you are.","ከምዘለኻ ንየሱስ ክቡር ኢኻ።","እንዳለህ ለኢየሱስ ውድ ነህ.","heal"),
 S("The Good Samaritan","እቲ ሕያዋይ ሳምራዊ","ደጉ ሳምራዊ","Luke 10:25-37",
   "Jesus told of a hurt man ignored by others, until a kind Samaritan stopped to help him, bandaged his wounds, and cared for him. Jesus said, 'Go and do the same.' We should show love and kindness to anyone in need, even strangers.",
   "የሱስ ብዛዕባ ዝተጐድአ ሰብ ካልኦት ዝሸለልዎ ነገረ፡ ክሳብ ሓደ ሕያዋይ ሳምራዊ ደው ኢሉ ዝሓገዞ፡ ቁስሉ ዝዘነጎን ዝኣለዮን። የሱስ 'ኪድ ከምኡ ግበር' በለ። ንዝኾነ ኣብ ጸገም ዘሎ፡ ንጋሻ እኳ፡ ፍቕርን ለውሃትን ከነርኢ ኣሎና።",
   "ኢየሱስ ስለ ተጎዳ ሰው ሌሎች ስለ ተዉት ነገረ፡ አንድ ደግ ሳምራዊ ቆም ብሎ እስኪረዳው ድረስ፡ ቁስሉን ጠቅልሎ ተንከባከበው። ኢየሱስ 'ሂድና እንደዚሁ አድርግ' አለ። በችግር ላለ ማንም፡ ለእንግዳም እንኳ፡ ፍቅርና ደግነት ማሳየት አለብን።",
   "Show love and kindness to anyone in need.","ንዝኾነ ኣብ ጸገም ዘሎ ፍቕርን ለውሃትን ኣርኢ።","በችግር ላለ ሁሉ ፍቅርና ደግነት አሳይ.","heal"),
 S("The Loving Father","እቲ ፈቃር ኣቦ","አፍቃሪው አባት","Luke 15:11-32",
   "Jesus told of a son who wasted everything and came home ashamed. But his father ran to him, hugged him, and threw a joyful party. Jesus said God is like that loving father. No matter how far we wander, God welcomes us home with open arms.",
   "የሱስ ብዛዕባ ኵሉ ዘባኸነን ሓፊሩ ናብ ገዛ ዝተመልሰን ወዲ ነገረ። ኣቦኡ ግና ናብኡ ጐየየ፡ ሓቖፎ፡ ናይ ሓጐስ ድግስ ድማ ገበረ። የሱስ ኣምላኽ ከምቲ ፈቃር ኣቦ ምዃኑ በለ። ክንደይ ርሒቕና ኸሎ እኳ፡ ኣምላኽ ብኽፉት ኢዱ ናብ ገዛ ይቕበለና።",
   "ኢየሱስ ስለ አንድ ሁሉን ስላባከነና አፍሮ ወደ ቤት ስለ ተመለሰ ልጅ ተናገረ። አባቱ ግን ወደ እርሱ ሮጠ፡ አቀፈው፡ የደስታ ግብዣም አደረገ። ኢየሱስ እግዚአብሔር እንደዚያ አፍቃሪ አባት ነው አለ። ምንም ያህል ብንርቅ፡ እግዚአብሔር በክፍት እጅ ወደ ቤት ይቀበለናል።",
   "God always welcomes us back with open arms.","ኣምላኽ ኵሉ ግዜ ብኽፉት ኢዱ ይቕበለና።","እግዚአብሔር ሁልጊዜ በክፍት እጅ ይቀበለናል.","hills"),
 S("Jesus Gives His Life","የሱስ ህይወቱ ይህብ","ኢየሱስ ሕይወቱን ይሰጣል","Luke 23",
   "Out of great love, Jesus was willing to die on a cross to take the punishment for our wrongs. Even while suffering, He forgave those who hurt Him. Jesus did this so that everyone who trusts Him can be forgiven and become God's friend forever.",
   "ብዓቢ ፍቕሪ የሱስ ንኣበሳና መቕጻዕቲ ኺወስድ ኣብ መስቀል ኪመውት ፍቓደኛ ኮነ። ኪሳቐ ኸሎ እኳ ነቶም ዝጐድእዎ ይቕረ በለሎም። የሱስ እዚ ዝገበረ ዚውከሎ ዅሉ ይቕረ ተባሂሉ ንዘለኣለም ፈታዊ ኣምላኽ ኪኸውን ምእንቲ እዩ።",
   "በታላቅ ፍቅር ኢየሱስ ለበደላችን ቅጣት ለመውሰድ በመስቀል ላይ ለመሞት ፈቃደኛ ሆነ። ሲሠቃይም እንኳ የጎዱትን ይቅር አላቸው። ኢየሱስ ይህን ያደረገው በእርሱ የሚታመን ሁሉ ይቅርታ አግኝቶ ለዘላለም የእግዚአብሔር ወዳጅ እንዲሆን ነው።",
   "Jesus loves us so much He gave His life for us.","የሱስ ኣዝዩ ስለ ዜፍቅረና ህይወቱ ሃበልና።","ኢየሱስ እጅግ ስለ ወደደን ሕይወቱን ሰጠልን.","temple"),
 S("Jesus is Alive!","የሱስ ህያው እዩ!","ኢየሱስ ሕያው ነው!","Luke 24",
   "On the third day, women came to Jesus' tomb and found it empty. An angel said, 'He is not here—He is risen!' Jesus was alive again, just as He promised. Because Jesus rose, we have hope that lasts forever. This is the happiest news of all!",
   "ኣብ ሳልሳይ መዓልቲ ኣንስቲ ናብ መቓብር የሱስ መጻ ጥራሕ ድማ ረኸብኦ። መልኣኽ 'ኣብዚ የልቦን፡ ተንሲኡ እዩ!' በለ። የሱስ ከምቲ ተመባጽዖ መሊሱ ህያው ኮነ። የሱስ ስለ ዝተንስአ ንዘለኣለም ዚጸንዕ ተስፋ ኣሎና። እዚ ኻብ ኵሉ ዝሓጐሰ ብስራት እዩ!",
   "በሦስተኛው ቀን ሴቶች ወደ ኢየሱስ መቃብር መጡ ባዶም አገኙት። መልአክ 'እዚህ የለም፡ ተነስቷል!' አለ። ኢየሱስ ቃል እንደገባው እንደገና ሕያው ሆነ። ኢየሱስ ስለ ተነሳ ለዘላለም የሚኖር ተስፋ አለን። ይህ ከሁሉ የላቀ ደስ የሚል የምስራች ነው!",
   "Jesus is alive, giving us hope forever!","የሱስ ህያው እዩ፡ ንዘለኣለም ተስፋ ይህበና!","ኢየሱስ ሕያው ነው፡ ለዘላለም ተስፋ ይሰጠናል!","star"),
 S("A New Home with God","ሓድሽ ገዛ ምስ ኣምላኽ","ከእግዚአብሔር ጋር አዲስ ቤት","Revelation 21",
   "The Bible ends with a wonderful promise: one day God will make a new heaven and a new earth. There will be no more crying, pain, or sadness. God will live with His people forever, and He will wipe away every tear. This is our great hope!",
   "መጽሓፍ ቅዱስ ብዜደንቕ መብጽዓ ይውዳእ፡ ሓደ መዓልቲ ኣምላኽ ሓድሽ ሰማይን ሓዳስ ምድርን ኪገብር እዩ። ደጊም ብኽያት፡ ቃንዛ፡ ሓዘን ኣይኪህሉን። ኣምላኽ ምስ ህዝቡ ንዘለኣለም ኪነብር፡ ንነፍሲ ወከፍ ንብዓት ድማ ኪደርዝ እዩ። እዚ ዓቢ ተስፋና እዩ!",
   "መጽሐፍ ቅዱስ በድንቅ ተስፋ ይጠናቀቃል፡ አንድ ቀን እግዚአብሔር አዲስ ሰማይና አዲስ ምድር ያደርጋል። ከእንግዲህ ልቅሶ፡ ሕመም፡ ሐዘን አይኖርም። እግዚአብሔር ከሕዝቡ ጋር ለዘላለም ይኖራል፡ እንባንም ሁሉ ያብሳል። ይህ ታላቅ ተስፋችን ነው!",
   "One day God will make everything new and perfect.","ሓደ መዓልቲ ኣምላኽ ንዅሉ ሓድሽን ፍጹምን ኪገብር እዩ።","አንድ ቀን እግዚአብሔር ሁሉን አዲስና ፍጹም ያደርጋል.","star"),
]



BOOK_BIG_STORY = {
    "slug": "the_big_story_of_the_bible",
    "title_en": "The Big Story of the Bible",
    "title_ti": "እታ ዓባይ ዛንታ መጽሓፍ ቅዱስ",
    "title_am": "የመጽሐፍ ቅዱስ ታላቁ ታሪክ",
    "stories": BIG_STORY,
}

# ============================================================
# BOOK 2: Jesus, Friend of All (44 stories)
# ============================================================
FRIEND = []


FRIEND += [
 S("Jesus and Nicodemus","የሱስን ኒቆዲሞስን","ኢየሱስና ኒቆዲሞስ","John 3:1-16",
   "A teacher named Nicodemus came to Jesus at night with questions. Jesus told him that God loves the world so much that He gave His Son, so that everyone who believes can have new life. Jesus welcomes our questions and offers a fresh start to all.",
   "ኒቆዲሞስ ዝበሃል መምህር ብለይቲ ሕቶታት ሒዙ ናብ የሱስ መጸ። የሱስ ኣምላኽ ንዓለም ኣዝዩ ስለ ዜፍቅራ ወዱ ኸም ዝሃበ፡ ዚኣምን ኵሉ ኸኣ ሓድሽ ህይወት ኪረክብ ከም ዚኽእል ነገሮ። የሱስ ሕቶታትና ይቕበል ንዅሉ ድማ ሓድሽ ጅማሮ ይህብ።",
   "ኒቆዲሞስ የተባለ አስተማሪ በሌሊት ጥያቄ ይዞ ወደ ኢየሱስ መጣ። ኢየሱስ እግዚአብሔር ዓለምን እጅግ ስለወደዳት ልጁን እንደሰጠ፡ የሚያምንም ሁሉ አዲስ ሕይወት ሊያገኝ እንደሚችል ነገረው። ኢየሱስ ጥያቄያችንን ይቀበላል ለሁሉም አዲስ ጅምርም ይሰጣል።",
   "God loves us so much He gives us new life.","ኣምላኽ ኣዝዩ ስለ ዜፍቅረና ሓድሽ ህይወት ይህበና።","እግዚአብሔር እጅግ ስለ ወደደን አዲስ ሕይወት ይሰጠናል.","prophet"),
 S("The Woman at the Well","እታ ኣብ ዔላ ዝነበረት ሰበይቲ","በጉድጓድ ዳር የነበረች ሴት","John 4:1-26",
   "Jesus met a lonely woman drawing water at a well. He kindly spoke with her, though others avoided her. He offered her 'living water' that satisfies the heart forever. The woman was so happy she told her whole town. Jesus welcomes everyone with love.",
   "የሱስ ኣብ ዔላ ማይ እትቐድ ጽምዋ ሰበይቲ ረኸበ። ካልኦት እኳ ይርሕቕዋ እንተ ነበሩ፡ ብለውሃት ተዛረባ። ንልቢ ንዘለኣለም ዜርዊ 'ህያው ማይ' ሃባ። እታ ሰበይቲ ኣዝያ ተሓጒሳ ንብምሉኡ ኸተማኣ ነገረት። የሱስ ንዅሉ ብፍቕሪ ይቕበል።",
   "ኢየሱስ በጉድጓድ ዳር ውኃ የምትቀዳ ብቸኛ ሴት አገኘ። ሌሎች ቢርቁአትም፡ በደግነት አነጋገራት። ልብን ለዘላለም የሚያረካ 'ሕያው ውኃ' ሰጣት። ሴቲቱ እጅግ ተደስታ ከተማዋን ሁሉ ነገረች። ኢየሱስ ሁሉንም በፍቅር ይቀበላል።",
   "Jesus welcomes everyone with love and kindness.","የሱስ ንዅሉ ብፍቕርን ለውሃትን ይቕበል።","ኢየሱስ ሁሉንም በፍቅርና በደግነት ይቀበላል.","woman"),
 S("The Official's Son","ወዲ እቲ ሓለቓ","የሹሙ ልጅ","John 4:46-54",
   "A royal official's son was very sick. He begged Jesus to come and heal him. Jesus simply said, 'Go home; your son will live.' The man believed and went, and found his son well at that very hour. Faith trusts Jesus even when we cannot see how.",
   "ወዲ ሓደ ንጉሳዊ ሓለቓ ኣዝዩ ሓሚሙ ነበረ። መጺኡ ኪፍውሶ ንየሱስ ለመኖ። የሱስ ብቐሊሉ 'ናብ ገዛኻ ኪድ፡ ወድኻ ኺድሕን እዩ' በለ። እቲ ሰብ ኣሚኑ ኸደ፡ ኣብታ ሰዓት እቲኣ ድማ ወዱ ተሓዊዩ ረኸቦ። እምነት ብኸመይ ከም ዚኸውን ከይረኣና እኳ ብየሱስ ትውከል።",
   "የአንድ ንጉሣዊ ሹም ልጅ በጣም ታሞ ነበር። መጥቶ እንዲፈውሰው ኢየሱስን ለመነው። ኢየሱስ በቀላሉ 'ወደ ቤትህ ሂድ፡ ልጅህ ይድናል' አለ። ሰውዬው አምኖ ሄደ፡ በዚያች ሰዓትም ልጁ ተፈውሶ አገኘው። እምነት እንዴት እንደሚሆን ሳናይም እንኳ በኢየሱስ ይታመናል።",
   "Faith trusts Jesus even before we see the answer.","እምነት መልሲ ኸይረኣና እኳ ብየሱስ ትውከል።","እምነት መልሱን ሳናይም እንኳ በኢየሱስ ይታመናል.","heal"),
 S("Jesus Heals a Leper","የሱስ ለምጻም ይፍውስ","ኢየሱስ ለምጻምን ይፈውሳል","Mark 1:40-45",
   "A man with a terrible skin disease came to Jesus. Others were afraid to touch him, but Jesus reached out His hand, touched him, and healed him. Jesus is never afraid to come close to those who are hurting. He touches our lives with love.",
   "ብኸቢድ ናይ ቆርበት ሕማም ዝሓመመ ሰብ ናብ የሱስ መጸ። ካልኦት ኪትንክይዎ ይፈርሁ ነበሩ፡ የሱስ ግና ኢዱ ዘርጊሑ ተንከዮ ፈወሶ ድማ። የሱስ ናብቶም ዚሳቐዩ ኺቐርብ ከቶ ኣይፈርህን። ንህይወትና ብፍቕሪ ይትንክፎ።",
   "በከባድ የቆዳ በሽታ የተያዘ ሰው ወደ ኢየሱስ መጣ። ሌሎች ሊነኩት ፈሩ፡ ኢየሱስ ግን እጁን ዘርግቶ ነካው ፈወሰውም። ኢየሱስ ወደሚሠቃዩ ለመቅረብ ፈጽሞ አይፈራም። ሕይወታችንን በፍቅር ይነካል።",
   "Jesus comes close to those who are hurting.","የሱስ ናብቶም ዚሳቐዩ ይቐርብ።","ኢየሱስ ወደሚሠቃዩ ይቀርባል.","heal"),
 S("The Centurion's Faith","እምነት እቲ ሓለቓ ሚእቲ","የመቶ አለቃው እምነት","Matthew 8:5-13",
   "A Roman soldier asked Jesus to heal his servant. He said, 'Just say the word, and he will be healed.' Jesus was amazed at his faith and healed the servant from far away. Great faith trusts Jesus' power even without seeing it up close.",
   "ሓደ ሮማዊ ወተሃደር ንየሱስ ንባርያኡ ኪፍውሰሉ ሓተቶ። 'ቃል ጥራይ በል፡ ኪሓዊ እዩ' በለ። የሱስ በምነቱ ተገረመ ነቲ ባርያ ድማ ካብ ርሑቕ ፈወሶ። ዓባይ እምነት ብቐረባ ኸይረኣየቶ እኳ ብሓይሊ የሱስ ትውከል።",
   "አንድ ሮማዊ ወታደር ኢየሱስ ባሪያውን እንዲፈውስ ጠየቀ። 'ቃል ብቻ በል፡ ይድናል' አለ። ኢየሱስ በእምነቱ ተገረመ ባሪያውንም ከሩቅ ፈወሰ። ታላቅ እምነት በቅርበት ሳያይም እንኳ በኢየሱስ ኃይል ይታመናል።",
   "Great faith trusts Jesus' power completely.","ዓባይ እምነት ብሓይሊ የሱስ ምሉእ ብምሉእ ትውከል።","ታላቅ እምነት በኢየሱስ ኃይል ሙሉ በሙሉ ይታመናል.","heal"),
 S("Jesus and Matthew","የሱስን ማቴዎስን","ኢየሱስና ማቴዎስ","Matthew 9:9-13",
   "Matthew was a tax collector, and most people disliked him. But Jesus walked up and said, 'Follow Me.' Matthew left everything and became one of Jesus' close friends. Jesus said He came for those who need Him. Nobody is beyond His love.",
   "ማቴዎስ ተቐባል ቀረጽ ነበረ፡ መብዛሕትኦም ሰባት ድማ ኣይፈትዉዎን። የሱስ ግና ቀሪቡ 'ስዓበኒ' በሎ። ማቴዎስ ኵሉ ገዲፉ ኻብ ቀረባ ኣዕሩኽ የሱስ ሓደ ኮነ። የሱስ ንዜድልይዎ ኸም ዝመጸ በለ። ካብ ፍቕሩ ወጻኢ ዝኾነ ሰብ የልቦን።",
   "ማቴዎስ ቀረጥ ሰብሳቢ ነበር፡ አብዛኞቹ ሰዎችም አይወዱትም ነበር። ኢየሱስ ግን ቀርቦ 'ተከተለኝ' አለው። ማቴዎስ ሁሉን ትቶ ከኢየሱስ የቅርብ ጓደኞች አንዱ ሆነ። ኢየሱስ ለሚያስፈልጉት እንደመጣ አለ። ከፍቅሩ ውጪ የሆነ ሰው የለም።",
   "Nobody is beyond the love of Jesus.","ካብ ፍቕሪ የሱስ ወጻኢ ዝኾነ ሰብ የልቦን።","ከኢየሱስ ፍቅር ውጪ የሆነ ሰው የለም.","hills"),
 S("The Woman Who Touched His Robe","እታ ንኽዳኑ ዝተንከየት ሰበይቲ","ልብሱን የነካች ሴት","Mark 5:25-34",
   "A woman had been sick for many years. She believed that if she just touched Jesus' robe she would be well. She reached out through the crowd, touched it, and was healed instantly! Jesus said, 'Your faith has made you well.' Even a small touch of faith reaches Jesus.",
   "ሓንቲ ሰበይቲ ንብዙሕ ዓመታት ሓሚማ ነበረት። ንኽዳን የሱስ ጥራይ እንተ ተንከየት ከም እትሓዊ ኣመነት። ብማእከል ህዝቢ ኢዳ ዘርጊሓ ተንከየቶ፡ ብኡንብኡ ድማ ሓወየት! የሱስ 'እምነትኪ ኣሕወየትኪ' በለ። ንእሽቶ ንኽኪ እምነት እኳ ናብ የሱስ ይበጽሕ።",
   "አንዲት ሴት ለብዙ ዓመታት ታማ ነበር። የኢየሱስን ልብስ ብቻ ብትነካ እንደምትድን አመነች። በሕዝቡ መካከል እጇን ዘርግታ ነካችው፡ ወዲያውኑም ተፈወሰች! ኢየሱስ 'እምነትሽ አዳነሽ' አለ። ትንሽ የእምነት ንክኪም እንኳ ኢየሱስ ዘንድ ይደርሳል።",
   "Even a small touch of faith reaches Jesus.","ንእሽቶ ንኽኪ እምነት እኳ ናብ የሱስ ይበጽሕ።","ትንሽ የእምነት ንክኪም እንኳ ኢየሱስ ዘንድ ይደርሳል.","heal"),
 S("Jairus's Daughter","ጓል ኢያኢሮስ","የኢያኢሮስ ልጅ","Mark 5:21-43",
   "A father named Jairus begged Jesus to heal his dying daughter. On the way, news came that she had died. But Jesus said, 'Do not fear; only believe.' He took her hand and said, 'Little girl, get up!' and she lived. Jesus brings hope where there seems to be none.",
   "ኢያኢሮስ ዝበሃል ኣቦ ንየሱስ ንዝሓመመት ጓሉ ኪፍውሳ ለመኖ። ኣብ መገዲ ኸለዉ ኸም ዝሞተት ወረ መጸ። የሱስ ግና 'ኣይትፍራህ፡ ኣምን ጥራይ' በለ። ኢዳ ሒዙ 'ንእሽቶ ጓል፡ ተንሲ!' በለ እሞ ህያው ኮነት። የሱስ ተስፋ ዘይብሉ ኺመስል ኣብ ዘለዎ ተስፋ የምጽእ።",
   "ኢያኢሮስ የተባለ አባት ኢየሱስን የታመመች ልጁን እንዲፈውስ ለመነ። በመንገድ ላይ እንደሞተች ወሬ መጣ። ኢየሱስ ግን 'አትፍራ፡ እመን ብቻ' አለ። እጇን ይዞ 'ትንሽ ልጅ ሆይ ተነሺ!' አለ ሕያውም ሆነች። ኢየሱስ ተስፋ በሌለ በሚመስልበት ተስፋን ያመጣል።",
   "Jesus brings hope where there seems to be none.","የሱስ ተስፋ ዘይብሉ ኣብ ዚመስል ተስፋ የምጽእ።","ኢየሱስ ተስፋ በሌለ በሚመስል ተስፋን ያመጣል.","heal"),
 S("Two Blind Men See","ክልተ ዕዉራት ይርእዩ","ሁለት ዕውሮች ያያሉ","Matthew 9:27-31",
   "Two blind men followed Jesus, calling out for mercy. Jesus asked, 'Do you believe I can help you?' They said yes. He touched their eyes and said, 'According to your faith it will be done,' and they could see! Jesus loves to answer those who trust Him.",
   "ክልተ ዕዉራት ንየሱስ ስዒቦም ምሕረት ጨርሑ። የሱስ 'ክሕግዘኩም ከም ዝኽእል ትኣምኑዶ?' በለ። እወ በሉ። ኣዒንቶም ተንኪዩ 'ከም እምነትኩም ይኹነልኩም' በለ እሞ ኪርእዩ ኸኣሉ! የሱስ ንዚውከልዎ ኺምልሰሎም ይፈቱ።",
   "ሁለት ዕውሮች ኢየሱስን ተከትለው ምሕረት ጮኹ። ኢየሱስ 'ልረዳችሁ እንደምችል ታምናላችሁ?' አለ። አዎ አሉ። ዓይኖቻቸውን ነክቶ 'እንደ እምነታችሁ ይሁንላችሁ' አለ ማየትም ቻሉ! ኢየሱስ በእርሱ ለሚታመኑ መልስ መስጠት ይወዳል።",
   "Jesus loves to help those who trust in Him.","የሱስ ንዚውከልዎ ኺሕግዞም ይፈቱ።","ኢየሱስ በእርሱ የሚታመኑትን መርዳት ይወዳል.","heal"),
 S("Jesus and Zacchaeus","የሱስን ዘኬዎስን","ኢየሱስና ዘኬዎስ","Luke 19:1-10",
   "Zacchaeus was a short tax collector whom nobody liked. He climbed a tree just to see Jesus. Jesus looked up and said, 'Zacchaeus, come down. I want to visit your house today!' Zacchaeus changed his ways and gave to the poor. Jesus sees and loves each of us.",
   "ዘኬዎስ ሓጺር ተቐባል ቀረጽ ነበረ ዝኾነ ሰብ ድማ ኣይፈትዎን። ንየሱስ ኪርኢ ጥራይ ኢሉ ኦም ደየበ። የሱስ ንላዕሊ ጠሚቱ 'ዘኬዎስ፡ ውረድ። ሎሚ ናብ ገዛኻ ኽበጽሕ እደሊ!' በለ። ዘኬዎስ ኣካይዳኡ ለወጠ ንድኻታት ድማ ሃበ። የሱስ ንነፍሲ ወከፍና ይርእየናን የፍቅረናን።",
   "ዘኬዎስ ማንም የማይወደው አጭር ቀረጥ ሰብሳቢ ነበር። ኢየሱስን ለማየት ብቻ ዛፍ ወጣ። ኢየሱስ ወደ ላይ ተመልክቶ 'ዘኬዎስ ውረድ። ዛሬ ወደ ቤትህ ልመጣ እፈልጋለሁ!' አለ። ዘኬዎስ መንገዱን ለወጠ ለድሆችም ሰጠ። ኢየሱስ እያንዳንዳችንን ያየናል ይወደናልም።",
   "Jesus sees and loves each one of us.","የሱስ ንነፍሲ ወከፍና ይርእየናን የፍቅረናን።","ኢየሱስ እያንዳንዳችንን ያየናል ይወደናልም.","hills"),
 S("Blind Bartimaeus","ዕዉር በርጤሜዎስ","ዕውር በርጢሜዎስ","Mark 10:46-52",
   "Bartimaeus was a blind beggar who called out loudly, 'Jesus, have mercy on me!' Others told him to be quiet, but he called even louder. Jesus stopped, healed him, and Bartimaeus could see. Do not be afraid to call out to Jesus; He always hears.",
   "በርጤሜዎስ ዕዉር ለማናይ ነበረ 'የሱስ ምሓረኒ!' ኢሉ ብዓውታ ጨርሐ። ካልኦት ስቕ ኪብል ነገርዎ፡ ንሱ ግና ኣዝዩ ብዝያዳ ጨርሐ። የሱስ ደው ኢሉ ፈወሶ፡ በርጤሜዎስ ድማ ኪርኢ ኸኣለ። ናብ የሱስ ኪትጽውዕ ኣይትፍራህ፡ ንሱ ኵሉ ግዜ ይሰምዕ።",
   "በርጢሜዎስ ዕውር ለማኝ ነበር 'ኢየሱስ ማረኝ!' ብሎ ጮኸ። ሌሎች ዝም እንዲል ነገሩት፡ እርሱ ግን ይበልጥ ጮኸ። ኢየሱስ ቆም ብሎ ፈወሰው፡ በርጢሜዎስም ማየት ቻለ። ወደ ኢየሱስ ለመጥራት አትፍራ፡ እርሱ ሁልጊዜ ይሰማል።",
   "Do not be afraid to call out to Jesus; He hears.","ናብ የሱስ ኪትጽውዕ ኣይትፍራህ፡ ንሱ ይሰምዕ።","ወደ ኢየሱስ ለመጥራት አትፍራ፡ እርሱ ይሰማል.","heal"),
]


FRIEND += [
 S("Mary and Martha","ማርያምን ማርታን","ማርያምና ማርታ","Luke 10:38-42",
   "Jesus visited two sisters. Martha was busy cooking and cleaning, while Mary sat and listened to Jesus. When Martha complained, Jesus gently said Mary had chosen the better thing. Spending quiet time with Jesus is more important than being too busy.",
   "የሱስ ንኽልተ ኣሓት በጽሐን። ማርታ ብምግቢ ምድላውን ምጽራይን ትሽቀል ነበረት፡ ማርያም ግና ኮፍ ኢላ ንየሱስ ትሰምዕ ነበረት። ማርታ ምስ ኣጕረመረመት፡ የሱስ ብልዙብ ማርያም ዝሓሸ ነገር ከም ዝመረጸት በለ። ምስ የሱስ ህዱእ ግዜ ምሕላፍ ካብ ብዙሕ ምስራሕ ይበልጽ።",
   "ኢየሱስ ሁለት እህትማማቾችን ጎበኘ። ማርታ በማብሰልና በማጽዳት ተጠምዳ ነበር፡ ማርያም ግን ተቀምጣ ኢየሱስን ታዳምጥ ነበር። ማርታ ስታጉረመርም ኢየሱስ በገርነት ማርያም የተሻለውን እንደመረጠች አለ። ከኢየሱስ ጋር ጸጥ ያለ ጊዜ ማሳለፍ በጣም ከመጠመድ ይሻላል።",
   "Quiet time with Jesus is the most important thing.","ምስ የሱስ ህዱእ ግዜ ምሕላፍ እቲ ኣዝዩ ኣገዳሲ እዩ።","ከኢየሱስ ጋር ጸጥ ያለ ጊዜ ማሳለፍ እጅግ አስፈላጊ ነው.","woman"),
 S("Jesus Raises Lazarus","የሱስ ንኣልኣዛር የተሲኦ","ኢየሱስ አልዓዛርን ያስነሳል","John 11",
   "Jesus' friend Lazarus died, and everyone was crying. Jesus cried too, because He loved them. Then He called out, 'Lazarus, come out!' and Lazarus, who was dead, walked out alive! Jesus shares our sadness and has power even over death.",
   "ዓርኪ የሱስ ኣልኣዛር ሞተ፡ ኵሉ ድማ ይበኪ ነበረ። የሱስ የፍቅሮም ስለ ዝነበረ ንሱ እውን በኸየ። ሽዑ 'ኣልኣዛር፡ ውጻእ!' ኢሉ ጨርሐ እሞ እቲ ዝሞተ ኣልኣዛር ህያው ኮይኑ ወጸ! የሱስ ሓዘንና ይካፈል ኣብ ልዕሊ ሞት እኳ ሓይሊ ኣለዎ።",
   "የኢየሱስ ጓደኛ አልዓዛር ሞተ፡ ሁሉም ያለቅስ ነበር። ኢየሱስም አለቀሰ፡ ስለሚወዳቸው። ከዚያ 'አልዓዛር ውጣ!' ብሎ ጮኸ የሞተውም አልዓዛር ሕያው ሆኖ ወጣ! ኢየሱስ ሐዘናችንን ይካፈላል በሞት ላይም እንኳ ኃይል አለው።",
   "Jesus shares our sadness and has power over death.","የሱስ ሓዘንና ይካፈል ኣብ ልዕሊ ሞት ሓይሊ ኣለዎ።","ኢየሱስ ሐዘናችንን ይካፈላል በሞት ላይ ኃይል አለው.","heal"),
 S("The Grateful Leper","እቲ አመስጋኒ ለምጻም","አመስጋኙ ለምጻም","Luke 17:11-19",
   "Ten men with skin disease cried out to Jesus, and He healed them all. But only one came back to say thank you. Jesus asked, 'Where are the other nine?' Jesus wants us to remember to thank Him for all the good things He does.",
   "ዓሰርተ ብናይ ቆርበት ሕማም ዝሓመሙ ሰባት ናብ የሱስ ጨርሑ፡ ንሱ ድማ ንዅሎም ፈወሶም። ሓደ ጥራይ ግና ኬመስግን ተመልሰ። የሱስ 'እቶም ትሽዓተ ኣበይ ኣለዉ?' በለ። የሱስ ብዛዕባ ዅሉ ዝገብሮ ጽቡቕ ከነመስግኖ ኺንዝክር ይደሊ።",
   "አሥር በቆዳ በሽታ የተያዙ ሰዎች ወደ ኢየሱስ ጮኹ፡ እርሱም ሁሉንም ፈወሳቸው። አንድ ብቻ ግን ሊያመሰግን ተመለሰ። ኢየሱስ 'ዘጠኙ የት ናቸው?' አለ። ኢየሱስ ስለሚያደርገው መልካም ነገር ሁሉ ማመስገንን እንድናስታውስ ይፈልጋል።",
   "Always remember to thank Jesus.","ንየሱስ ኬተመስግኖ ኵሉ ግዜ ዘክር።","ኢየሱስን ማመስገን ሁልጊዜ አስታውስ.","heal"),
 S("The Children Sing","ቆልዑ ይዝምሩ","ልጆች ይዘምራሉ","Matthew 21:14-16",
   "When Jesus entered the temple, children sang and praised Him with joy. Some leaders were annoyed, but Jesus was pleased. He said even little children can offer perfect praise to God. Your praise and worship are precious to Jesus.",
   "የሱስ ናብ ቤተ መቕደስ ምስ ኣተወ፡ ቆልዑ ብሓጐስ ዘመሩሉን ወደስዎን። ገሊኦም መራሕቲ ተቖጥዑ፡ የሱስ ግና ተሓጐሰ። ንኣሽቱ ቆልዑ እኳ ንኣምላኽ ፍጹም ውዳሴ ኬቕርቡ ኸም ዚኽእሉ በለ። ውዳሴኻን ኣምልኾኻን ንየሱስ ክቡር እዩ።",
   "ኢየሱስ ወደ ቤተ መቅደስ ሲገባ ልጆች በደስታ ዘመሩለት አመሰገኑትም። አንዳንድ መሪዎች ተቆጡ፡ ኢየሱስ ግን ደስ አለው። ትንንሽ ልጆችም እንኳ ለእግዚአብሔር ፍጹም ውዳሴ ማቅረብ እንደሚችሉ አለ። ውዳሴህና አምልኮህ ለኢየሱስ ውድ ነው።",
   "Your praise is precious to Jesus.","ውዳሴኻ ንየሱስ ክቡር እዩ።","ውዳሴህ ለኢየሱስ ውድ ነው.","temple"),
 S("The Little Children Blessed","ንኣሽቱ ቆልዑ ይባረኹ","ትንንሽ ልጆች ይባረካሉ","Matthew 19:13-15",
   "People brought little children to Jesus so He could bless them. The disciples tried to stop them, but Jesus said, 'Let the children come to Me, for the kingdom of heaven belongs to such as these.' Jesus always has time for children.",
   "ሰባት ንኣሽቱ ቆልዑ ኪባርኾም ናብ የሱስ ኣምጽኡ። ደቀ መዛሙርቲ ኪኽልክልዎም ፈተኑ፡ የሱስ ግና 'ቆልዑ ናባይ ይምጽኡ ሕደግዎም፡ መንግስቲ ሰማይ ናይ ከምዚኦም እያ' በለ። የሱስ ኵሉ ግዜ ንቖልዑ ግዜ ኣለዎ።",
   "ሰዎች ትንንሽ ልጆችን ሊባርካቸው ወደ ኢየሱስ አመጡ። ደቀ መዛሙርቱ ሊከለክሉአቸው ሞከሩ፡ ኢየሱስ ግን 'ልጆች ወደ እኔ ይምጡ ተዉአቸው፡ የሰማይ መንግሥት እንደ እነዚህ ላሉ ናትና' አለ። ኢየሱስ ሁልጊዜ ለልጆች ጊዜ አለው።",
   "Jesus always has time for children.","የሱስ ኵሉ ግዜ ንቖልዑ ግዜ ኣለዎ።","ኢየሱስ ሁልጊዜ ለልጆች ጊዜ አለው.","heal"),
 S("The Widow's Two Coins","ክልተ ሳንቲም እታ መበለት","የመበለቲቱ ሁለት ሳንቲም","Mark 12:41-44",
   "Jesus watched people give money at the temple. Rich people gave large amounts, but a poor widow gave two tiny coins—all she had. Jesus said she gave the most, because she gave from her heart. God sees the love behind our giving.",
   "የሱስ ኣብ ቤተ መቕደስ ገንዘብ ዚህቡ ሰባት ይዕዘብ ነበረ። ሃብታማት ብዙሕ ሃቡ፡ ሓንቲ ድኻ መበለት ግና ክልተ ንኣሽቱ ሳንቲም—ዝነበራ ዅሉ—ሃበት። የሱስ ካብ ልባ ስለ ዝሃበት ካብ ኵሉ ንላዕሊ ኸም ዝሃበት በለ። ኣምላኽ ብድሕሪ ህያብና ዘሎ ፍቕሪ ይርኢ።",
   "ኢየሱስ በቤተ መቅደስ ገንዘብ የሚሰጡ ሰዎችን ይመለከት ነበር። ሀብታሞች ብዙ ሰጡ፡ አንዲት ድሀ መበለት ግን ሁለት ትንንሽ ሳንቲም—ያላትን ሁሉ—ሰጠች። ኢየሱስ ከልቧ ስለ ሰጠች ከሁሉ በላይ እንደሰጠች አለ። እግዚአብሔር ከስጦታችን ጀርባ ያለውን ፍቅር ያያል።",
   "God sees the love behind what we give.","ኣምላኽ ብድሕሪ እንህቦ ዘሎ ፍቕሪ ይርኢ።","እግዚአብሔር ከምንሰጠው ጀርባ ያለውን ፍቅር ያያል.","temple"),
 S("The Forgiven Woman","እታ ይቕረ እተባህለ ሰበይቲ","ይቅርታ የተደረገላት ሴት","Luke 7:36-50",
   "A woman who had done many wrong things came to Jesus, crying, and washed His feet with her tears. Others judged her, but Jesus forgave her and said, 'Your faith has saved you; go in peace.' No sin is too big for Jesus to forgive.",
   "ብዙሕ ጌጋ ዝገበረት ሰበይቲ እናበኸየት ናብ የሱስ መጸት፡ ኣእጋሩ ድማ ብንብዓታ ሓጸበት። ካልኦት ፈረድዋ፡ የሱስ ግና ይቕረ በለላ 'እምነትኪ ኣድሒኑኪ፡ ብሰላም ኪዲ' በለ። ንየሱስ ይቕረ ኺብለሉ ዚኸብዶ ሓጢኣት የልቦን።",
   "ብዙ ስህተት የሠራች ሴት እያለቀሰች ወደ ኢየሱስ መጣች፡ እግሮቹንም በእንባዋ አጠበች። ሌሎች ፈረዱባት፡ ኢየሱስ ግን ይቅር አላት 'እምነትሽ አዳነሽ፡ በሰላም ሂጂ' አለ። ኢየሱስ ይቅር ለማለት የሚከብደው ኃጢአት የለም።",
   "No sin is too big for Jesus to forgive.","ንየሱስ ይቕረ ኪብለሉ ዚኸብዶ ሓጢኣት የልቦን።","ኢየሱስ ይቅር ለማለት የሚከብደው ኃጢአት የለም.","woman"),
 S("Jesus Heals a Bent Woman","የሱስ ንዝጐበጠት ሰበይቲ ይፍውስ","ኢየሱስ የጎበጠችን ሴት ይፈውሳል","Luke 13:10-17",
   "A woman had been bent over for eighteen years and could not stand up straight. Jesus saw her, called her over, and healed her right away. She praised God with joy. Jesus notices those who are hurting and lifts them up with love.",
   "ሓንቲ ሰበይቲ ን18 ዓመት ጐቢጣ ነበረት ትቕንዕ ድማ ኣይትኽእልን ነበረት። የሱስ ረኣያ፡ ጸውዓ፡ ብኡንብኡ ድማ ፈወሳ። ብሓጐስ ንኣምላኽ ወደሰት። የሱስ ነቶም ዚሳቐዩ የስተብህሎም ብፍቕሪ ድማ የተስኦም።",
   "አንዲት ሴት ለአሥራ ስምንት ዓመት ጎብጣ ነበር ቀጥ ብላ መቆምም አትችልም ነበር። ኢየሱስ አያት፡ ጠራት፡ ወዲያውኑም ፈወሳት። በደስታ እግዚአብሔርን አመሰገነች። ኢየሱስ የሚሠቃዩትን ያስተውላል በፍቅርም ያነሳቸዋል።",
   "Jesus notices those who hurt and lifts them up.","የሱስ ነቶም ዚሳቐዩ የስተብህሎምን የተስኦምን።","ኢየሱስ የሚሠቃዩትን ያስተውላል ያነሳቸዋልም.","heal"),
 S("The Ten Bridesmaids","እተን ዓሰርተ መርዑ ኣሰነይቲ","አሥሩ ሚዜዎች","Matthew 25:1-13",
   "Jesus told of ten girls waiting for a wedding. Five wisely brought extra oil for their lamps; five did not. When the groom came at night, only the ready ones went in to the feast. Jesus teaches us to be ready and to keep our hearts prepared for Him.",
   "የሱስ ብዛዕባ ዓሰርተ ንመርዓ ዚጽበያ ኣዋልድ ነገረ። ሓሙሽተ ብጥበብ ንመብራህተን ተወሳኺ ዘይቲ ኣምጽኣ፡ ሓሙሽተ ኣየምጽኣን። እቲ መርዓዊ ብለይቲ ምስ መጸ፡ እተን ድሉዋት ጥራይ ናብ ድግስ ኣተዋ። የሱስ ድሉዋት ክንከውንን ልብና ንእኡ ኸነዳሉን ይምህረና።",
   "ኢየሱስ ስለ አሥር ለሰርግ የሚጠብቁ ልጃገረዶች ተናገረ። አምስቱ በጥበብ ለመብራታቸው ተጨማሪ ዘይት አመጡ፡ አምስቱ አላመጡም። ሙሽራው በሌሊት ሲመጣ የተዘጋጁት ብቻ ወደ ግብዣ ገቡ። ኢየሱስ ዝግጁ እንድንሆንና ልባችንን ለእርሱ እንድናዘጋጅ ያስተምረናል።",
   "Keep your heart ready and prepared for Jesus.","ልብኻ ንየሱስ ድሉውን ተዳልዩን ሓሉ።","ልብህን ለኢየሱስ ዝግጁና የተዘጋጀ አድርገው.","star"),
 S("Jesus and the Tax Collector's Prayer","ጸሎት እቲ ተቐባል ቀረጽ","የቀረጥ ሰብሳቢው ጸሎት","Luke 18:9-14",
   "Jesus told of two men praying. One proudly listed his good deeds. The other humbly bowed and said, 'God, be merciful to me.' Jesus said God was pleased with the humble one. God loves a humble heart that knows it needs Him.",
   "የሱስ ብዛዕባ ኽልተ ዚጽልዩ ሰባት ነገረ። ሓደ ብትዕቢት ጽቡቕ ግብሩ ቆጸረ። እቲ ኻልኣይ ብትሕትና ኣድኒኑ 'ኦ ኣምላኽ ምሓረኒ' በለ። የሱስ ኣምላኽ በቲ ትሑት ከም ዝተሓጐሰ በለ። ኣምላኽ ንኣኡ ኸም ዜድልዮ ዚፈልጥ ትሑት ልቢ የፍቅር።",
   "ኢየሱስ ስለ ሁለት የሚጸልዩ ሰዎች ተናገረ። አንዱ በኩራት መልካም ሥራውን ዘረዘረ። ሌላው በትሕትና አጎንብሶ 'እግዚአብሔር ሆይ ማረኝ' አለ። ኢየሱስ እግዚአብሔር በትሑቱ እንደተደሰተ አለ። እግዚአብሔር እርሱን እንደሚያስፈልገው የሚያውቅ ትሑት ልብን ይወዳል።",
   "God loves a humble heart that trusts Him.","ኣምላኽ ዚውከሎ ትሑት ልቢ የፍቅር።","እግዚአብሔር በእርሱ የሚታመን ትሑት ልብን ይወዳል.","temple"),
 S("Jesus Washes Feet","የሱስ ኣእጋር ይሓጽብ","ኢየሱስ እግር ያጥባል","John 13:1-17",
   "At His last supper, Jesus wrapped a towel around Himself and washed His friends' dusty feet—a servant's job. He said, 'I have given you an example: serve one another in love.' Jesus shows us that true greatness is found in humbly helping others.",
   "ኣብ መወዳእታ ድራሩ የሱስ ፎጣ ተዓጢቑ ናይ ኣዕሩኹ ዕፉር ኣእጋር ሓጸበ—ስራሕ ባርያ። 'ኣብነት ሂበኩም እየ፡ ብፍቕሪ ንሓድሕድኩም ተገልገሉ' በለ። የሱስ ሓቀኛ ዕቤት ብትሕትና ንኻልኦት ኣብ ምሕጋዝ ከም ዚርከብ የርኢ።",
   "በመጨረሻ እራቱ ኢየሱስ ፎጣ ታጥቆ የጓደኞቹን አቧራማ እግር አጠበ—የአገልጋይ ሥራ። 'ምሳሌ ሰጥቻችኋለሁ፡ በፍቅር እርስ በርሳችሁ ተገልገሉ' አለ። ኢየሱስ እውነተኛ ታላቅነት በትሕትና ሌሎችን በማገልገል እንደሚገኝ ያሳያል።",
   "True greatness is humbly serving others.","ሓቀኛ ዕቤት ብትሕትና ንኻልኦት ምግልጋል እዩ።","እውነተኛ ታላቅነት በትሕትና ሌሎችን ማገልገል ነው.","heal"),
]


FRIEND += [
 S("Peter Walks on Water","ጴጥሮስ ኣብ ማይ ይኸይድ","ጴጥሮስ በውኃ ላይ ይሄዳል","Matthew 14:22-33",
   "The disciples saw Jesus walking on the water at night. Peter stepped out and walked too, but when he looked at the waves he began to sink. Jesus caught him and said, 'Why did you doubt?' Keep your eyes on Jesus, not on your fears.",
   "ደቀ መዛሙርቲ ብለይቲ ንየሱስ ኣብ ማይ ኪኸይድ ረኣይዎ። ጴጥሮስ ወጺኡ ንሱ እውን ከደ፡ ናብ ማዕበል ምስ ጠመተ ግና ኪጥሕል ጀመረ። የሱስ ሒዙ 'ስለምንታይ ተጠራጠርካ?' በለ። ኣዒንትኻ ኣብ የሱስ ኣንብር፡ ኣብ ፍርሕኻ ኣይኮነን።",
   "ደቀ መዛሙርቱ በሌሊት ኢየሱስ በውኃ ላይ ሲሄድ አዩ። ጴጥሮስ ወጥቶ እርሱም ሄደ፡ ማዕበሉን ሲመለከት ግን መስጠም ጀመረ። ኢየሱስ ያዘውና 'ለምን ተጠራጠርክ?' አለ። ዓይንህን በኢየሱስ ላይ አድርግ፡ በፍርሃትህ ላይ አይደለም።",
   "Keep your eyes on Jesus, not on your fears.","ኣዒንትኻ ኣብ የሱስ ኣንብር፡ ኣብ ፍርሕኻ ኣይኮነን።","ዓይንህን በኢየሱስ ላይ አድርግ፡ በፍርሃትህ ላይ አይደለም.","boat"),
 S("The Great Catch of Fish","እቲ ዓቢ ምጽያድ ዓሳ","ታላቁ የዓሣ አሳ","Luke 5:1-11",
   "Peter had fished all night and caught nothing. Jesus told him to try again in the deep water. Peter obeyed, and the nets filled with so many fish they nearly broke! Obeying Jesus, even when it seems pointless, brings surprising blessings.",
   "ጴጥሮስ ምሉእ ለይቲ ዓሲዱ ገለ እኳ ኣይሓዘን። የሱስ ኣብ ዓሚቝ ማይ ከም ብሓድሽ ኪፍትን ነገሮ። ጴጥሮስ ተኣዘዘ፡ እቲ መርበብ ድማ ክሳብ ዚስበር ብብዙሕ ዓሳ መልአ! ንየሱስ ምእዛዝ ትርጉም ዘይብሉ ኪመስል ከሎ እኳ ዜደንቕ በረኸት የምጽእ።",
   "ጴጥሮስ ሌሊቱን ሙሉ ዓሣ አጥምዶ ምንም አላገኘም። ኢየሱስ በጥልቁ ውኃ እንደገና እንዲሞክር ነገረው። ጴጥሮስ ታዘዘ፡ መረቡም እስኪበጠስ ድረስ በብዙ ዓሣ ተሞላ! ኢየሱስን መታዘዝ ትርጉም የለሽ ቢመስልም ድንቅ በረከትን ያመጣል።",
   "Obeying Jesus brings surprising blessings.","ንየሱስ ምእዛዝ ዜደንቕ በረኸት የምጽእ።","ኢየሱስን መታዘዝ ድንቅ በረከትን ያመጣል.","boat"),
 S("Jesus and Thomas","የሱስን ቶማስን","ኢየሱስና ቶማስ","John 20:24-29",
   "After Jesus rose, Thomas said he would not believe unless he saw Jesus himself. A week later Jesus appeared and gently let Thomas see. Thomas cried, 'My Lord and my God!' Jesus said, 'Blessed are those who believe without seeing.'",
   "የሱስ ድሕሪ ምትንሳኡ፡ ቶማስ ንየሱስ ባዕሉ እንተ ዘይረኣየ ኸም ዘይኣምን በለ። ድሕሪ ሰሙን የሱስ ተገልጸ ብልዙብ ድማ ንቶማስ ኪርኢ ሓደጎ። ቶማስ 'ጐይታይን ኣምላኸይን!' ኢሉ ጨርሐ። የሱስ 'እቶም ከይረኣዩ ዚኣምኑ ብጹኣን እዮም' በለ።",
   "ኢየሱስ ከተነሳ በኋላ ቶማስ ኢየሱስን ራሱ ካላየ እንደማያምን አለ። ከሳምንት በኋላ ኢየሱስ ተገለጠ በገርነትም ቶማስ እንዲያይ ተወው። ቶማስ 'ጌታዬና አምላኬ!' ብሎ ጮኸ። ኢየሱስ 'ሳያዩ የሚያምኑ ብፁዓን ናቸው' አለ።",
   "Blessed are those who believe without seeing.","እቶም ከይረኣዩ ዚኣምኑ ብጹኣን እዮም።","ሳያዩ የሚያምኑ ብፁዓን ናቸው.","dove"),
 S("Breakfast by the Sea","ቁርሲ ኣብ ገምገም ባሕሪ","በባሕር ዳር ቁርስ","John 21:1-14",
   "After a long night of fishing with no catch, the disciples saw Jesus on the shore. He told them where to cast, and their net filled with fish. Then Jesus made them breakfast on the beach. Jesus cares about our ordinary days and everyday needs.",
   "ነዊሕ ለይቲ ዓሲዶም ገለ እኳ ኸይሓዙ ድሕሪ ምጽናሕ፡ ደቀ መዛሙርቲ ንየሱስ ኣብ ገምገም ረኣይዎ። ኣበይ ከም ዚድርብዩ ነገሮም፡ መርበቦም ድማ ብዓሳ መልአ። ሽዑ የሱስ ኣብቲ ገምገም ቁርሲ ኣዳለወሎም። የሱስ ብዛዕባ ተራ መዓልትታትናን ዕለታዊ ድሌታትናን ይግደስ።",
   "ረጅም ሌሊት ዓሣ አጥምደው ምንም ሳይዙ ከቆዩ በኋላ፡ ደቀ መዛሙርቱ ኢየሱስን በባሕር ዳር አዩት። የት እንደሚጥሉ ነገራቸው፡ መረባቸውም በዓሣ ተሞላ። ከዚያ ኢየሱስ በባሕሩ ዳር ቁርስ አዘጋጀላቸው። ኢየሱስ ስለ ተራ ቀኖቻችንና ዕለታዊ ፍላጎቶቻችን ያስባል።",
   "Jesus cares about our ordinary, everyday needs.","የሱስ ብዛዕባ ተራ ዕለታዊ ድሌታትና ይግደስ።","ኢየሱስ ስለ ተራ ዕለታዊ ፍላጎቶቻችን ያስባል.","boat"),
 S("Jesus Restores Peter","የሱስ ንጴጥሮስ የሐድስ","ኢየሱስ ጴጥሮስን ያድሳል","John 21:15-19",
   "Peter had failed Jesus by denying he knew Him. But Jesus did not give up on Peter. Three times He asked, 'Do you love Me?' and gave Peter important work to do. Jesus forgives our failures and gives us a fresh start.",
   "ጴጥሮስ ንየሱስ ኸም ዘይፈልጦ ብምኽሓድ ኣጉዲልዎ ነበረ። የሱስ ግና ንጴጥሮስ ኣይሓደጎን። ሰለስተ ሳዕ 'ተፍቅረኒዶ?' ኢሉ ሓተቶ ኣገዳሲ ዕዮ ድማ ሃቦ። የሱስ ንውድቀትና ይቕረ ይብለልና ሓድሽ ጅማሮ ድማ ይህበና።",
   "ጴጥሮስ ኢየሱስን እንደማያውቀው በመካድ አሳዝኖት ነበር። ኢየሱስ ግን ጴጥሮስን አልተወውም። ሦስት ጊዜ 'ትወደኛለህ?' ብሎ ጠየቀው አስፈላጊ ሥራም ሰጠው። ኢየሱስ ውድቀታችንን ይቅር ይለናል አዲስ ጅምርም ይሰጠናል።",
   "Jesus forgives our failures and gives a fresh start.","የሱስ ንውድቀትና ይቕረ ይብልን ሓድሽ ጅማሮ ይህብን።","ኢየሱስ ውድቀታችንን ይቅር ይላል አዲስ ጅምርም ይሰጣል.","boat"),
 S("The Good Shepherd","እቲ ሕያዋይ ጓሳ","ደጉ እረኛ","John 10:11-15",
   "Jesus said, 'I am the good shepherd. I lay down my life for the sheep.' A good shepherd knows each sheep and keeps them safe. Jesus knows each of us by name and loves us dearly. We can trust Him to lead and protect us.",
   "የሱስ 'ኣነ ሕያዋይ ጓሳ እየ። ህይወተይ ኣብ ክንዲ ኣባጊዕ የንብር' በለ። ሕያዋይ ጓሳ ንነፍሲ ወከፍ በጊዕ ይፈልጦ ድሑን ድማ ይሕልዎ። የሱስ ንነፍሲ ወከፍና ብስምና ይፈልጠናን ኣዝዩ የፍቅረናን። ኪመርሓናን ኪሕልወናን ክንውከሎ ንኽእል።",
   "ኢየሱስ 'እኔ ደጉ እረኛ ነኝ። ሕይወቴን ስለ በጎቹ አኖራለሁ' አለ። ደግ እረኛ እያንዳንዱን በግ ያውቃል ደኅናም ይጠብቃል። ኢየሱስ እያንዳንዳችንን በስም ያውቀናል በጣምም ይወደናል። ሊመራንና ሊጠብቀን ልንታመነው እንችላለን።",
   "Jesus knows and loves each of us by name.","የሱስ ንነፍሲ ወከፍና ብስምና ይፈልጠናን የፍቅረናን።","ኢየሱስ እያንዳንዳችንን በስም ያውቀናል ይወደናልም.","hills"),
 S("Jesus the True Vine","የሱስ እታ ናይ ሓቂ ወይኒ","ኢየሱስ እውነተኛው ወይን","John 15:1-8",
   "Jesus said, 'I am the vine; you are the branches.' A branch only grows fruit when it stays joined to the vine. When we stay close to Jesus—praying, listening, and obeying—our lives grow good and beautiful. Stay connected to Jesus every day.",
   "የሱስ 'ኣነ ወይኒ እየ፡ ንስኻትኩም ጨናፍር ኢኹም' በለ። ጨንፈር ምስ ወይኒ ተጸጊዑ ኺጸንሕ ከሎ ጥራይ እዩ ፍረ ዚፈሪ። ምስ የሱስ ቀረባ ኽንከውን ከለና—እናጸለና፡ እናሰማዕናን እናተኣዘዝናን—ህይወትና ጽብቕትን ጽብቕትን ትዓቢ። ኵሉ መዓልቲ ምስ የሱስ ተጸጋዕ።",
   "ኢየሱስ 'እኔ ወይን ነኝ፡ እናንተ ቅርንጫፎች ናችሁ' አለ። ቅርንጫፍ ከወይኑ ጋር ተጣብቆ ሲቆይ ብቻ ነው ፍሬ የሚያፈራው። ከኢየሱስ ጋር ቅርብ ስንሆን—እየጸለይን፡ እያዳመጥንና እየታዘዝን—ሕይወታችን መልካምና ውብ ያድጋል። በየቀኑ ከኢየሱስ ጋር ተጣበቅ።",
   "Stay close to Jesus, and your life will grow good.","ምስ የሱስ ቀረባ ኹን፡ ህይወትካ ጽብቕቲ ትዓቢ።","ከኢየሱስ ጋር ቅርብ ሁን፡ ሕይወትህ መልካም ያድጋል.","hills"),
 S("Jesus and Little Faith","የሱስን ንእሽቶ እምነትን","ኢየሱስና ትንሽ እምነት","Matthew 17:20",
   "Jesus told His friends that even faith as small as a tiny mustard seed can do great things with God's help. We do not need to be strong or perfect—we just need to trust God. A little faith placed in a big God can move mountains.",
   "የሱስ ንኣዕሩኹ ብሓገዝ ኣምላኽ ከም ንእሽቶ ፍረ ኣድሪ ዝኣክል እምነት እኳ ዓበይቲ ነገራት ኪገብር ከም ዚኽእል ነገሮም። ሓያላት ወይ ፍጹማት ክንከውን ኣየድልየናን—ንኣምላኽ ክንውከል ጥራይ ኣሎና። ኣብ ዓቢ ኣምላኽ እተነብረት ንእሽቶ እምነት ንኣኽራን ከተግዕዝ ትኽእል።",
   "ኢየሱስ ለጓደኞቹ በእግዚአብሔር እርዳታ እንደ ትንሽ የሰናፍጭ ዘር ያለ እምነት እንኳ ታላቅ ነገር ማድረግ እንደሚችል ነገራቸው። ጠንካሮች ወይም ፍጹማን መሆን አያስፈልገንም—በእግዚአብሔር መታመን ብቻ ያስፈልገናል። በታላቅ አምላክ ላይ የተቀመጠ ትንሽ እምነት ተራሮችን ሊያንቀሳቅስ ይችላል።",
   "A little faith in a big God can do great things.","ኣብ ዓቢ ኣምላኽ እተነብረት ንእሽቶ እምነት ዓበይቲ ነገራት ትገብር።","በታላቅ አምላክ ላይ ያለ ትንሽ እምነት ታላቅ ነገር ያደርጋል.","hills"),
 S("Jesus Blesses a Meal","የሱስ ንመግቢ ይባርኽ","ኢየሱስ ምግብን ይባርካል","Matthew 26:26-28",
   "At His last meal with His friends, Jesus shared bread and a cup, and gave thanks to God. He asked them to remember Him and His love whenever they eat together. Jesus wants us to remember His love and to be thankful in everything.",
   "ኣብ መወዳእታ ድራሩ ምስ ኣዕሩኹ የሱስ እንጌራን ጽውኡን ተመቓሪሑ ንኣምላኽ ኣመስገነ። ሓቢሮም ኪበልዑ ኸለዉ ንእኡን ንፍቕሩን ኪዝክሩ ሓተቶም። የሱስ ፍቕሩ ኽንዝክርን ኣብ ኵሉ ኸነመስግንን ይደሊ።",
   "በመጨረሻ እራቱ ከጓደኞቹ ጋር ኢየሱስ እንጀራንና ጽዋን አካፍሎ እግዚአብሔርን አመሰገነ። አብረው ሲበሉ እርሱንና ፍቅሩን እንዲያስታውሱ ጠየቃቸው። ኢየሱስ ፍቅሩን እንድናስታውስና በሁሉ እንድናመሰግን ይፈልጋል።",
   "Remember Jesus' love and be thankful always.","ፍቕሪ የሱስ ዘክር ኵሉ ግዜ ድማ ኣመስግን።","የኢየሱስን ፍቅር አስታውስ ሁልጊዜም አመስግን.","loaves"),
 S("Jesus Prays for Us","የሱስ ምእንታና ይጽሊ","ኢየሱስ ስለ እኛ ይጸልያል","John 17",
   "On the night before He died, Jesus prayed—not just for His friends there, but for everyone who would ever believe in Him, including us today. He asked God to keep us close and full of joy. Jesus loves us so much that He prays for us.",
   "ቅድሚ ሞቱ ብዝነበረት ለይቲ የሱስ ጸለየ—ንኣዕሩኹ ጥራይ ዘይኮነስ፡ ንኹሎም ዚኣምንዎ፡ ንዓና ሎሚ ሓዊሱ። ኣምላኽ ቀረባን ብሓጐስ ምሉኣትን ኪገብረና ለመነ። የሱስ ኣዝዩ ስለ ዜፍቅረና ምእንታና ይጽሊ።",
   "ከመሞቱ በፊት በነበረች ሌሊት ኢየሱስ ጸለየ—ለጓደኞቹ ብቻ ሳይሆን፡ በእርሱ ለሚያምኑ ሁሉ፡ ዛሬ እኛንም ጨምሮ። እግዚአብሔር ቅርብና በደስታ የተሞላን እንዲያደርገን ለመነ። ኢየሱስ እጅግ ስለ ወደደን ስለ እኛ ይጸልያል።",
   "Jesus loves us so much that He prays for us.","የሱስ ኣዝዩ ስለ ዜፍቅረና ምእንታና ይጽሊ።","ኢየሱስ እጅግ ስለ ወደደን ስለ እኛ ይጸልያል.","prophet"),
 S("The Cross of Love","መስቀል ፍቕሪ","የፍቅር መስቀል","John 19",
   "Because He loves us, Jesus was willing to die on a cross to take away our wrongs. Even in pain, He cared for others and forgave. Jesus did the hardest thing so that we could be forgiven and become God's children forever.",
   "ስለ ዜፍቅረና፡ የሱስ ንኣበሳና ኬርሕቕ ኣብ መስቀል ኪመውት ፍቓደኛ ኮነ። ኣብ ቃንዛ እኳ ንኻልኦት ተገዲሱ ይቕረ በለ። ንዘለኣለም ደቂ ኣምላኽ ኴንና ይቕረ ኪበሃለልና ምእንቲ የሱስ እቲ ኣዝዩ ኸቢድ ነገር ገበረ።",
   "ስለ ወደደን፡ ኢየሱስ በደላችንን ለማስወገድ በመስቀል ላይ ለመሞት ፈቃደኛ ሆነ። በሕመሙም እንኳ ለሌሎች ተጨንቆ ይቅር አለ። ለዘላለም የእግዚአብሔር ልጆች ሆነን ይቅር እንድንባል ኢየሱስ እጅግ ከባዱን ነገር አደረገ።",
   "Jesus gave His life out of great love for us.","የሱስ ብዓቢ ፍቕሪ ምእንታና ህይወቱ ሃበ።","ኢየሱስ በታላቅ ፍቅር ስለ እኛ ሕይወቱን ሰጠ.","temple"),
 S("The Empty Tomb","እቲ ጥራሕ መቓብር","ባዶው መቃብር","John 20:1-18",
   "On Sunday morning Mary came to Jesus' tomb and found it empty. Then Jesus Himself appeared and said her name, 'Mary.' She was filled with joy—Jesus was alive! He calls each of us by name too. Jesus lives, and He knows us personally.",
   "ሰንበት ንግሆ ማርያም ናብ መቓብር የሱስ መጸት ጥራሕ ድማ ረኸበቶ። ሽዑ የሱስ ባዕሉ ተገልጸ ስማ ድማ 'ማርያም' ኢሉ ጸውዓ። ብሓጐስ መልአት—የሱስ ህያው ነበረ! ንነፍሲ ወከፍና እውን ብስምና ይጽውዓና። የሱስ ህያው እዩ ብብሕታዊ ድማ ይፈልጠና።",
   "እሁድ ጠዋት ማርያም ወደ ኢየሱስ መቃብር መጣች ባዶም አገኘችው። ከዚያ ኢየሱስ ራሱ ተገለጠ ስሟንም 'ማርያም' ብሎ ጠራት። በደስታ ተሞላች—ኢየሱስ ሕያው ነበር! እያንዳንዳችንንም በስም ይጠራናል። ኢየሱስ ሕያው ነው በግልም ያውቀናል።",
   "Jesus lives, and He knows each of us by name.","የሱስ ህያው እዩ፡ ንነፍሲ ወከፍና ብስምና ይፈልጠና።","ኢየሱስ ሕያው ነው፡ እያንዳንዳችንንም በስም ያውቀናል.","star"),
 S("Jesus Sends His Friends","የሱስ ንኣዕሩኹ ይሰድድ","ኢየሱስ ጓደኞቹን ይልካል","Matthew 28:18-20",
   "Before returning to heaven, Jesus told His friends, 'Go and tell everyone the good news, and I am with you always.' He wants His love to reach the whole world. And He is with us as we share His love. We can tell others about Jesus, our Friend.",
   "ናብ ሰማይ ቅድሚ ምምላሱ የሱስ ንኣዕሩኹ 'ኪዱ ነቲ ብስራት ንዅሉ ንገሩ፡ ኣነ ኸኣ ኵሉ ግዜ ምሳኻትኩም እየ' በለ። ፍቕሩ ናብ ብምሉኡ ዓለም ኪበጽሕ ይደሊ። ፍቕሩ ኽንካፈል ከለና ድማ ምሳና ኣሎ። ብዛዕባ የሱስ ፈታዊና ንኻልኦት ክንነግር ንኽእል።",
   "ወደ ሰማይ ከመመለሱ በፊት ኢየሱስ ጓደኞቹን 'ሂዱ የምስራቹን ለሁሉም ንገሩ፡ እኔም ሁልጊዜ ከእናንተ ጋር ነኝ' አለ። ፍቅሩ ወደ ዓለም ሁሉ እንዲደርስ ይፈልጋል። ፍቅሩን ስናካፍልም ከእኛ ጋር ነው። ስለ ኢየሱስ ወዳጃችን ለሌሎች መንገር እንችላለን።",
   "We can share Jesus, our Friend, with everyone.","ብዛዕባ የሱስ ፈታዊና ንዅሉ ክንካፈል ንኽእል።","ስለ ኢየሱስ ወዳጃችን ለሁሉም ማካፈል እንችላለን.","star"),
]

FRIEND += [
 S("Jesus Calms the Storm","የሱስ ንህቦብላ የህድእ","ኢየሱስ ማዕበሉን ያረጋጋል","Mark 4:35-41",
   "One night a great storm shook the boat while Jesus slept. His friends were afraid and woke Him. Jesus stood and said, 'Peace, be still!' At once the wind and waves grew calm. His friends were amazed that even the storm obeys Him. When we are afraid, Jesus is near to give us peace.",
   "ሓደ ለይቲ የሱስ ደቂሱ ኸሎ ዓቢ ህቦብላ ነታ ጃልባ ኣናወጻ። ኣዕሩኹ ፈሪሆም ኣበራበርዎ። የሱስ ተንሲኡ 'ህድእ በል፡ ጸጥ በል!' በለ። ሽዑ ንፋስን ማዕበልን ጸጥ በሉ። ኣዕሩኹ እቲ ህቦብላ እኳ ኸም ዚእዘዞ ተገረሙ። ኣብ ግዜ ፍርሂ የሱስ ሰላም ኪህበና ቀረባና እዩ።",
   "አንድ ሌሊት ኢየሱስ ተኝቶ ሳለ ታላቅ ማዕበል ጀልባዋን አናወጣት። ጓደኞቹ ፈርተው ቀሰቀሱት። ኢየሱስ ተነስቶ 'ጸጥ በል፡ ዝም በል!' አለ። ወዲያውም ነፋሱና ማዕበሉ ጸጥ አሉ። ጓደኞቹም ማዕበሉ እንኳ እንደሚታዘዘው ተደነቁ። በምንፈራበት ጊዜ ኢየሱስ ሰላም ሊሰጠን ቅርባችን ነው።",
   "Jesus gives us peace in every storm.","የሱስ ኣብ ኵሉ ህቦብላ ሰላም ይህበና።","ኢየሱስ በማዕበሉ ሁሉ ሰላም ይሰጠናል.","boat"),
 S("Jesus Feeds Four Thousand","የሱስ ንኣርባዕተ ሽሕ ይምግብ","ኢየሱስ አራት ሺህ ይመግባል","Mark 8:1-9",
   "A great crowd stayed with Jesus for three days and had nothing to eat. Jesus felt compassion for them. With seven loaves and a few fish He gave thanks and fed four thousand people. Everyone ate and was full. Jesus cares about our needs, both big and small.",
   "ብዙሕ ህዝቢ ሰለስተ መዓልቲ ምስ የሱስ ጸንሐ ዚበልዕ ከኣ ኣይነበሮምን። የሱስ ራህርሀሎም። ብሸውዓተ እንጌራን ቍሩብ ዓሳን ኣመስጊኑ ንኣርባዕተ ሽሕ ሰብ መገበ። ኵሎም በሊዖም ጸገቡ። የሱስ ብዛዕባ ድሌትና ዓብዪ ኾነ ንእሽቶ ይግደስ እዩ።",
   "ብዙ ሕዝብ ሦስት ቀን ከኢየሱስ ጋር ቆየ የሚበሉትም አልነበራቸውም። ኢየሱስም አዘነላቸው። በሰባት እንጀራና ጥቂት ዓሣ አመስግኖ አራት ሺህ ሰው መገበ። ሁሉም በልተው ጠገቡ። ኢየሱስ ስለ ፍላጎታችን ትልቅም ትንሽም ይጨነቃል።",
   "Jesus cares for all our needs.","የሱስ ንዅሉ ድሌትና ይግደስ።","ኢየሱስ ስለ ፍላጎታችን ሁሉ ይጨነቃል.","loaves"),
 S("Jesus and the Little Lamb","የሱስን እታ ንእሽቶ ገንሸል","ኢየሱስና ትንሿ በግ","Luke 15:3-7",
   "Jesus told of a shepherd with a hundred sheep. When one was lost, he left the ninety-nine and searched until he found it. He carried it home on his shoulders with joy. Jesus is like that shepherd, and He seeks each one of us with great love.",
   "የሱስ ብዛዕባ ሓደ ሚእቲ በጊዕ ዘለዎ ጓሳ ነገረ። ሓንቲ ምስ ጠፍአት ነተን ተስዓን ትሽዓተን ሓዲጉ ክሳዕ ዚረኽባ ደለያ። ብሓጐስ ከኣ ኣብ መንኩቡ ጾይሩ ናብ ገዛ ኣምጽኣ። የሱስ ከምዚ ጓሳ እዩ፡ ንነፍሲ ወከፍና ብዓብዪ ፍቕሪ ይደልየና።",
   "ኢየሱስ አንድ መቶ በግ ስለ ነበረው እረኛ ተናገረ። አንዷ ስትጠፋ ዘጠና ዘጠኙን ትቶ እስኪያገኛት ፈለጋት። በደስታም በጫንቃው ተሸክሞ ወደ ቤት አመጣት። ኢየሱስ እንደዚያ እረኛ ነው፡ እያንዳንዳችንንም በታላቅ ፍቅር ይፈልገናል።",
   "Jesus seeks each one of us with love.","የሱስ ንነፍሲ ወከፍና ብፍቕሪ ይደልየና።","ኢየሱስ እያንዳንዳችንን በፍቅር ይፈልገናል.","hills"),
 S("The Boy with Loaves and Fish","እቲ እንጌራን ዓሳን ዝሓዘ ወዲ","እንጀራና ዓሣ የያዘው ልጅ","John 6:1-14",
   "A little boy gave his five loaves and two fish to Jesus. It seemed too small for such a crowd. But Jesus blessed the gift and fed five thousand people with plenty left over. When we give what we have, Jesus can do wonderful things.",
   "ሓደ ንእሽቶ ወዲ ሓሙሽተ እንጌራኡን ክልተ ዓሳኡን ንየሱስ ሃቦ። ነዚ ኽንድዚ ህዝቢ ኣዝዩ ንእሽቶ መሰለ። የሱስ ግና ነታ ህያብ ባሪኹ ንሓሙሽተ ሽሕ ሰብ መገበ ትርፉ ኸኣ ተረፈ። ዘሎና ኽንህብ ከለና የሱስ ዜደንቕ ነገራት ኪገብር ይኽእል።",
   "አንድ ትንሽ ልጅ አምስት እንጀራውንና ሁለት ዓሣውን ለኢየሱስ ሰጠ። ለዚህ ብዙ ሕዝብ በጣም ትንሽ መሰለ። ኢየሱስ ግን ስጦታውን ባርኮ አምስት ሺህ ሰው መገበ ትርፉም ተረፈ። ያለንን ስንሰጥ ኢየሱስ ድንቅ ነገር ሊያደርግ ይችላል።",
   "When we give, Jesus does great things.","ክንህብ ከለና የሱስ ዓበይቲ ነገራት ይገብር።","ስንሰጥ ኢየሱስ ታላላቅ ነገር ያደርጋል.","loaves"),
 S("Jesus and the Deaf Man","የሱስን እቲ ጸማም ሰብኣይ","ኢየሱስና ደንቆሮው ሰው","Mark 7:31-37",
   "People brought a man who could not hear or speak. Jesus took him aside, touched his ears, and said, 'Be opened!' At once the man could hear and speak clearly. Everyone was amazed. Jesus does all things well and cares for each person.",
   "ሰባት ዘይሰምዕን ዘይዛረብን ሰብኣይ ኣምጽኡሉ። የሱስ ንበይኑ ወሲዱ ኣእዛኑ ተንኪፉ 'ተኸፈት!' በለ። ሽዑ እቲ ሰብኣይ ብንጹር ኪሰምዕን ኪዛረብን ከኣለ። ኵሎም ተገረሙ። የሱስ ንዅሉ ጽቡቕ ይገብር ንነፍሲ ወከፍ ሰብ ከኣ ይግደስ።",
   "ሰዎች የማይሰማና የማይናገር ሰው አመጡለት። ኢየሱስ ለብቻው ወስዶ ጆሮዎቹን ነክቶ 'ተከፈት!' አለ። ወዲያውም ሰውየው በግልጽ መስማትና መናገር ቻለ። ሁሉም ተደነቁ። ኢየሱስ ሁሉን በጎ ያደርጋል ስለ እያንዳንዱ ሰውም ይጨነቃል።",
   "Jesus does all things well.","የሱስ ንዅሉ ጽቡቕ ይገብር።","ኢየሱስ ሁሉን በጎ ያደርጋል.","heal"),
 S("Jesus Blesses the Bread","የሱስ ንህብስቲ ይባርኽ","ኢየሱስ ኅብስቱን ይባርካል","Luke 24:28-35",
   "Two friends walked to Emmaus, sad because Jesus had died. A stranger joined them and explained the Scriptures. When He broke bread at the table, their eyes opened and they knew it was Jesus, risen and alive! They ran to tell the others with great joy.",
   "ክልተ ኣዕሩኽ የሱስ ስለ ዝሞተ ኣዝዮም ጐሂዮም ናብ ኤማሁስ ይኸዱ ነበሩ። ሓደ ጓና ተጸንበሮም ንቅዱሳት ጽሑፋት ከኣ ገለጸሎም። ኣብ ጣውላ ህብስቲ ምስ ቈረሰ ኣዒንቶም ተኸፍታ የሱስ ተንሲኡ ህያው ምዃኑ ኸኣ ፈለጡ! ብዓብዪ ሓጐስ ንኻልኦት ኪነግሩ ጐየዩ።",
   "ሁለት ወዳጆች ኢየሱስ ስለ ሞተ በጣም አዝነው ወደ ኤማሁስ ይሄዱ ነበር። አንድ እንግዳ ተቀላቀላቸው መጻሕፍቱንም ገለጸላቸው። በማዕድ ኅብስቱን ሲቆርስ ዓይኖቻቸው ተከፈቱ ኢየሱስም ተነስቶ ሕያው መሆኑን አወቁ! በታላቅ ደስታም ለሌሎች ሊነግሩ ሮጡ።",
   "Jesus is alive and walks with us.","የሱስ ህያው እዩ ምሳናውን ይኸይድ።","ኢየሱስ ሕያው ነው ከእኛም ጋር ይሄዳል.","loaves"),
 S("Jesus and the Trusting Child","የሱስን እቲ ዝኣምን ቆልዓ","ኢየሱስና ታማኙ ልጅ","Matthew 18:1-5",
   "The disciples asked who is greatest in God's kingdom. Jesus called a little child to stand among them. He said, 'Whoever becomes humble like this child is greatest.' Jesus loves a trusting, humble heart. We can come to Him just as we are.",
   "እቶም ደቀ መዛሙርቲ ኣብ መንግስቲ ኣምላኽ መን ከም ዚዓቢ ሓተቱ። የሱስ ንሓደ ንእሽቶ ቆልዓ ኣብ ማእከሎም ደው ኪብል ጸውዖ። 'ከምዚ ቆልዓ ትሑት ዚኸውን ንሱ ዓቢ እዩ' በለ። የሱስ ዚኣምንን ትሑትን ልቢ የፍቅር። ከምዘሎና ኾይንና ናብኡ ክንመጽእ ንኽእል።",
   "ደቀ መዛሙርቱ በእግዚአብሔር መንግሥት ማን ታላቅ እንደ ሆነ ጠየቁ። ኢየሱስ አንድ ትንሽ ልጅ በመካከላቸው እንዲቆም ጠራው። 'እንደዚህ ልጅ ትሑት የሚሆን እርሱ ታላቅ ነው' አለ። ኢየሱስ የሚያምንና ትሑት ልብን ይወዳል። እንዳለን ሆነን ወደ እርሱ መምጣት እንችላለን።",
   "Jesus loves a humble, trusting heart.","የሱስ ትሑትን ዚኣምንን ልቢ የፍቅር።","ኢየሱስ ትሑትና የሚያምን ልብን ይወዳል.","hills"),
 S("The Friend Who Never Leaves","እቲ ዘይፍለ ፈታዊ","የማይለየው ወዳጅ","Hebrews 13:5",
   "Jesus promised, 'I will never leave you or forsake you.' Even when we feel alone, Jesus is with us. He is a Friend who stays closer than a brother. In happy days and hard days, His love never ends. We are never alone with Jesus.",
   "የሱስ 'ከቶ ኣይሓድገካን እየ ኣይግድፈካን ከኣ እየ' ኢሉ ተመባጽዐ። በይንና ዀይኑ እኳ እንተ ተሰምዓና የሱስ ምሳና እዩ። ካብ ሓው ዚቐርብ ዚነብር ፈታዊ እዩ። ብሕጉስ መዓልትን ብኸቢድ መዓልትን ፍቕሩ ኣይውዳእን። ምስ የሱስ ከቶ በይንና ኣይኰንናን።",
   "ኢየሱስ 'ከቶ አልተውህም አልጥልህምም' ብሎ ተስፋ ሰጠ። ብቻችንን የሆነ ቢሰማንም ኢየሱስ ከእኛ ጋር ነው። ከወንድም አብልጦ የሚቀርብ ወዳጅ ነው። በደስታ ቀንም በክፉ ቀንም ፍቅሩ አያልቅም። ከኢየሱስ ጋር ከቶ ብቻችንን አይደለንም።",
   "Jesus is a Friend who never leaves us.","የሱስ ከቶ ዘይሓድገና ፈታዊ እዩ።","ኢየሱስ ከቶ የማይተወን ወዳጅ ነው.","dove"),
 S("Jesus, Our Forever Friend","የሱስ፡ ናይ ዘለኣለም ፈታዊና","ኢየሱስ፡ የዘላለም ወዳጃችን","John 15:13-15",
   "Jesus said, 'You are my friends.' He showed the greatest love by giving His life for us. He listens when we pray and walks with us every day. There is no friend like Jesus. He loves us now and forever, and nothing can take that love away.",
   "የሱስ 'ንስኻትኩም ኣዕሩኸይ ኢኹም' በለ። ህይወቱ ኣብ ክንዳና ብምሃብ እቲ ዝዓበየ ፍቕሪ ኣርኣየ። ክንጽሊ ኸለና ይሰምዓና ኵሉ መዓልቲ ኸኣ ምሳና ይኸይድ። ከም የሱስ ፈታዊ የልቦን። ሕጅን ንዘለኣለምን የፍቅረና ነታ ፍቕሪ እቲኣ ኸኣ ዚወስዳ የልቦን።",
   "ኢየሱስ 'እናንተ ወዳጆቼ ናችሁ' አለ። ሕይወቱን ስለ እኛ በመስጠት ታላቁን ፍቅር አሳየ። ስንጸልይ ይሰማናል በየቀኑም ከእኛ ጋር ይሄዳል። እንደ ኢየሱስ ወዳጅ የለም። አሁንም ለዘላለምም ይወደናል ያንን ፍቅርም የሚወስድ የለም።",
   "There is no friend like Jesus, now and forever.","ከም የሱስ ፈታዊ የልቦን፡ ሕጅን ንዘለኣለምን።","እንደ ኢየሱስ ወዳጅ የለም፡ አሁንም ለዘላለምም.","star"),
]

BOOK_FRIEND = {
    "slug": "jesus_friend_of_all",
    "title_en": "Jesus, Friend of All",
    "title_ti": "የሱስ፡ ፈታዊ ዅሉ",
    "title_am": "ኢየሱስ፡ የሁሉ ወዳጅ",
    "stories": FRIEND,
}

BOOKS = [BOOK_BIG_STORY, BOOK_FRIEND]
