# -*- coding: utf-8 -*-
"""Scene data for the trilingual picture books — one scene per page.
Each of the 10 Bible stories is expanded into 44 scene pages
(so every book = 1 cover + 44 scenes = 45 pages, well over 42).

Languages per scene: English (en), Tigrinya (ti), Amharic (am).
'ill' is the illustration key used by generate_picture_books.svg_scene().
"""


def SC(en, ti, am, ill="hills"):
    return {"en": en, "ti": ti, "am": am, "ill": ill}


# ============================================================
# BOOK 1 — NOAH BUILDS THE ARK
# ============================================================
NOAH = [
 SC("Long, long ago, the world was full of people.",
    "ኣብ ጥንቲ ዘመን ዓለም ብሰብ መሊኣ ነበረት።",
    "በጥንት ዘመን ዓለም በሰው ተሞልታ ነበር።", "hills"),
 SC("But the people had forgotten to love God.",
    "እቶም ሰባት ግና ንኣምላኽ ከፍቅሩ ረሲዖም ነበሩ።",
    "ሰዎቹ ግን እግዚአብሔርን መውደድ ረስተው ነበር።", "hills"),
 SC("They were unkind and did many wrong things.",
    "ሕያዎት ኣይነበሩን ብዙሕ ክፉእ ነገር ይገብሩ ነበሩ።",
    "ደጎች አልነበሩም ብዙ ክፉ ነገር ያደርጉ ነበር።", "hills"),
 SC("This made God very sad.",
    "እዚ ንኣምላኽ ኣዝዩ ኣጕሃዮ።",
    "ይህ እግዚአብሔርን እጅግ አሳዘነው።", "hills"),
 SC("But there was one good man named Noah.",
    "ኖህ ዝስሙ ሓደ ሕያዋይ ሰብ ግና ነበረ።",
    "ኖኅ የሚባል አንድ ደግ ሰው ግን ነበረ።", "prophet"),
 SC("Noah loved God and obeyed Him.",
    "ኖህ ንኣምላኽ የፍቅሮን ይእዘዞን ነበረ።",
    "ኖኅ እግዚአብሔርን ይወድና ይታዘዘው ነበር።", "prophet"),
 SC("One day God spoke to Noah.",
    "ሓደ መዓልቲ ኣምላኽ ንኖህ ተዛረቦ።",
    "አንድ ቀን እግዚአብሔር ለኖኅ ተናገረው።", "prophet"),
 SC("'Build a great big boat,' said God.",
    "'ዓባይ መርከብ ስራሕ' በሎ ኣምላኽ።",
    "'ታላቅ መርከብ ሥራ' አለው እግዚአብሔር።", "prophet"),
 SC("'A flood is coming to cover the earth.'",
    "'ንምድሪ ዚኸድን ውሒዝ ኪመጽእ እዩ።'",
    "'ምድርን የሚሸፍን ጎርፍ ይመጣል።'", "prophet"),
 SC("'But you and your family will be safe.'",
    "'ንስኻን ስድራኻን ግና ክትድሕኑ ኢኹም።'",
    "'አንተና ቤተሰብህ ግን ትድናላችሁ።'", "prophet"),
 SC("So Noah began to build the ark.",
    "ስለዚ ኖህ ነታ መርከብ ኪሰርሕ ጀመረ።",
    "ስለዚህ ኖኅ መርከቧን መሥራት ጀመረ።", "ark"),
 SC("He cut strong wood, piece by piece.",
    "ጽኑዕ ዕንጨይቲ በብቝራጽ ቈረጸ።",
    "ጠንካራ እንጨት ቁራጭ በቁራጭ ቆረጠ።", "ark"),
 SC("He worked in the hot sun every day.",
    "ኵሉ መዓልቲ ኣብ ትሪ ጸሓይ ይሰርሕ ነበረ።",
    "በየቀኑ በሚያቃጥል ፀሐይ ይሠራ ነበር።", "ark"),
 SC("People laughed at Noah and his boat.",
    "ሰባት ንኖህን ንመርከቡን ሰሓቑሉ።",
    "ሰዎች ኖኅንና መርከቡን ሳቁበት።", "ark"),
 SC("But Noah kept obeying God.",
    "ኖህ ግና ንኣምላኽ ይእዘዞ ነበረ።",
    "ኖኅ ግን እግዚአብሔርን መታዘዙን ቀጠለ።", "ark"),
 SC("The ark grew bigger and bigger.",
    "እታ መርከብ እናዓበየት ከደት።",
    "መርከቧ እየገዘፈች ሄደች።", "ark"),
 SC("It had three floors and one big door.",
    "ሰለስተ ደርቢን ሓደ ዓቢ ማዕጾን ነበራ።",
    "ሦስት ፎቆችና አንድ ትልቅ በር ነበራት።", "ark"),
 SC("At last the great ark was finished.",
    "ኣብ መወዳእታ እታ ዓባይ መርከብ ተወድአት።",
    "በመጨረሻ ታላቂቱ መርከብ ተጠናቀቀች።", "ark"),
 SC("Then God sent the animals to Noah.",
    "ሽዑ ኣምላኽ ነተን እንስሳታት ናብ ኖህ ሰደደን።",
    "ከዚያም እግዚአብሔር እንስሳቱን ወደ ኖኅ ላከ።", "ark"),
 SC("Two by two the animals came.",
    "እንስሳታት ክልተ ክልተ ኰይነን መጻ።",
    "እንስሳቱ ሁለት ሁለት ሆነው መጡ።", "ark"),
 SC("Lions and lambs, big and small.",
    "ኣናብስን ገናሽልን ዓበይትን ንኣሽቱን።",
    "አንበሶችና በጎች ትልቅና ትንሽ።", "lion"),
 SC("Birds flew in and sang their songs.",
    "ኣዕዋፍ በሪረን ኣተዋ ደርፈን ከኣ ዘመራ።",
    "ወፎች በረው ገቡ ዘፈናቸውንም ዘመሩ።", "dove"),
 SC("Noah led them all safely inside.",
    "ኖህ ንዅለን ብደሓን ናብ ውሽጢ ኣእተወን።",
    "ኖኅ ሁሉንም በደኅና ወደ ውስጥ አስገባ።", "ark"),
 SC("Then Noah's family went in too.",
    "ሽዑ ስድራ ኖህ እውን ኣተዉ።",
    "ከዚያም የኖኅ ቤተሰብ ደግሞ ገቡ።", "ark"),
 SC("God gently shut the big door.",
    "ኣምላኽ ነቲ ዓቢ ማዕጾ ብህዱእ ዓጸዎ።",
    "እግዚአብሔር ትልቁን በር በቀስታ ዘጋው።", "ark"),
 SC("Then the rain began to fall.",
    "ሽዑ ዝናብ ኪዘንብ ጀመረ።",
    "ከዚያም ዝናብ መዝነብ ጀመረ።", "ark"),
 SC("It rained and rained for forty days.",
    "ኣርባዓ መዓልቲ ዘነመን ዘነመን።",
    "አርባ ቀን ዘነበ ዘነበ።", "ark"),
 SC("Water covered the whole earth.",
    "ማይ ንብምሉኣ ምድሪ ኸደና።",
    "ውኃ ምድርን ሁሉ ሸፈነ።", "sea"),
 SC("But the ark floated safely on top.",
    "እታ መርከብ ግና ኣብ ልዕሊ ማይ ብደሓን ተንሳፈፈት።",
    "መርከቧ ግን በውኃ ላይ በደኅና ተንሳፈፈች።", "ark"),
 SC("Inside, everyone was warm and safe.",
    "ኣብ ውሽጢ ኵሉ ውዑይን ደሓንን ነበረ።",
    "በውስጡ ሁሉም ሞቅ ብሎና በደኅና ነበር።", "ark"),
 SC("Noah trusted God through the storm.",
    "ኖህ ኣብ ግዜ ህቦብላ ኣብ ኣምላኽ ተወከለ።",
    "ኖኅ በማዕበሉ ጊዜ በእግዚአብሔር ታመነ።", "ark"),
 SC("At last the rain stopped.",
    "ኣብ መወዳእታ እቲ ዝናብ ደው በለ።",
    "በመጨረሻ ዝናቡ ቆመ።", "hills"),
 SC("Slowly the water went down.",
    "ማይ ቀስ ኢሉ ጐደለ።",
    "ውኃው ቀስ ብሎ ወረደ።", "hills"),
 SC("Noah sent out a dove to look.",
    "ኖህ ንኽትርኢ ርግቢት ሰደደ።",
    "ኖኅ ለማየት ርግብ ላከ።", "dove"),
 SC("The dove came back with a green leaf!",
    "እታ ርግቢት ቈጽሊ ሒዛ ተመልሰት!",
    "ርግቧ አረንጓዴ ቅጠል ይዛ ተመለሰች!", "dove"),
 SC("Dry land was near at last.",
    "ኣብ መወዳእታ ንቑጽ ምድሪ ቀረበ።",
    "በመጨረሻ ደረቅ መሬት ቀረበ።", "hills"),
 SC("The ark rested on a mountain top.",
    "እታ መርከብ ኣብ ርእሲ ኸረን ዓለበት።",
    "መርከቧ በተራራ ጫፍ ላይ አረፈች።", "hills"),
 SC("Noah opened the big door wide.",
    "ኖህ ነቲ ዓቢ ማዕጾ ኸፈቶ።",
    "ኖኅ ትልቁን በር ከፈተው።", "ark"),
 SC("All the animals ran out with joy.",
    "ኵለን እንስሳታት ብሓጐስ ወጻ።",
    "እንስሳቱ ሁሉ በደስታ ወጡ።", "hills"),
 SC("Noah thanked God for keeping them safe.",
    "ኖህ ስለ ዝሓለዎም ንኣምላኽ ኣመስገነ።",
    "ኖኅ ስለ ጠበቃቸው እግዚአብሔርን አመሰገነ።", "pray"),
 SC("Then God put a rainbow in the sky.",
    "ሽዑ ኣምላኽ ኣብ ሰማይ ቀስተ ደመና ገበረ።",
    "ከዚያም እግዚአብሔር በሰማይ ቀስተ ደመና አደረገ።", "rainbow"),
 SC("It shone with beautiful colors.",
    "ብጽቡቕ ሕብርታት ኣንጸባረቐት።",
    "በውብ ቀለማት አበራች።", "rainbow"),
 SC("'This is my promise,' said God.",
    "'እዚ መብጽዓይ እዩ' በለ ኣምላኽ።",
    "'ይህ ተስፋዬ ነው' አለ እግዚአብሔር።", "rainbow"),
 SC("When we obey God, He keeps us safe.",
    "ንኣምላኽ ክንእዘዞ ኸለና የድሕነና።",
    "እግዚአብሔርን ስንታዘዝ ይጠብቀናል።", "rainbow"),
]

BOOK_NOAH = {
    "slug": "noah_builds_the_ark",
    "title_en": "Noah Builds the Ark",
    "title_ti": "ኖህ መርከብ ይሰርሕ",
    "title_am": "ኖኅ መርከብ ይሠራል",
    "verse": "Genesis 6-9",
    "cover_ill": "ark",
    "scenes": NOAH,
}



# ============================================================
# BOOK 2 — JOSEPH AND HIS COLORFUL COAT
# ============================================================
JOSEPH = [
 SC("Long ago there lived a boy named Joseph.",
    "ኣብ ጥንቲ ዮሴፍ ዝስሙ ወዲ ነበረ።",
    "በጥንት ጊዜ ዮሴፍ የሚባል ልጅ ነበረ።", "prophet"),
 SC("Joseph had eleven brothers.",
    "ዮሴፍ ዓሰርተው ሓደ ኣሕዋት ነበርዎ።",
    "ዮሴፍ አሥራ አንድ ወንድሞች ነበሩት።", "hills"),
 SC("His father loved him very much.",
    "ኣቦኡ ኣዝዩ የፍቅሮ ነበረ።",
    "አባቱ እጅግ ይወደው ነበር።", "prophet"),
 SC("One day his father gave him a gift.",
    "ሓደ መዓልቲ ኣቦኡ ህያብ ሃቦ።",
    "አንድ ቀን አባቱ ስጦታ ሰጠው።", "coat"),
 SC("It was a beautiful colorful coat.",
    "ጽብቕቲ ሕብራዊት ቀሚሽ ነበረት።",
    "ውብ ባለ ቀለም ካባ ነበረች።", "coat"),
 SC("Joseph loved his special coat.",
    "ዮሴፍ ነታ ፍልይቲ ቀሚሹ ኣፍቀራ።",
    "ዮሴፍ ልዩዋን ካባ ወደዳት።", "coat"),
 SC("But his brothers became jealous.",
    "ኣሕዋቱ ግና ቀንኡ።",
    "ወንድሞቹ ግን ቀኑ።", "coat"),
 SC("Joseph also had special dreams.",
    "ዮሴፍ ፍሉይ ሕልምታት እውን ነበርዎ።",
    "ዮሴፍ ልዩ ሕልሞችም ነበሩት።", "star"),
 SC("In his dream, sheaves bowed to him.",
    "ኣብ ሕልሙ እኽሊ ሰገደሉ።",
    "በሕልሙ ነዶዎች ሰገዱለት።", "star"),
 SC("The stars also bowed down to him.",
    "ከዋኽብቲ እውን ሰገዱሉ።",
    "ከዋክብትም ሰገዱለት።", "star"),
 SC("His brothers grew angry at the dreams.",
    "ኣሕዋቱ በቲ ሕልምታት ተቘጥዑ።",
    "ወንድሞቹ በሕልሞቹ ተቆጡ።", "hills"),
 SC("One day the brothers were far away.",
    "ሓደ መዓልቲ ኣሕዋቱ ኣብ ርሑቕ ነበሩ።",
    "አንድ ቀን ወንድሞቹ ሩቅ ነበሩ።", "hills"),
 SC("Their father sent Joseph to find them.",
    "ኣቦኦም ንዮሴፍ ኪደልዮም ሰደዶ።",
    "አባታቸው ዮሴፍን እንዲፈልጋቸው ላከው።", "hills"),
 SC("When they saw him, they made a plan.",
    "ምስ ረኣይዎ መደብ ገበሩ።",
    "ባዩት ጊዜ ዕቅድ አወጡ።", "hills"),
 SC("They took away his colorful coat.",
    "ነታ ሕብራዊት ቀሚሹ ኣውጽእዎ።",
    "ባለ ቀለም ካባውን ወሰዱበት።", "coat"),
 SC("They sold Joseph to traders.",
    "ንዮሴፍ ንነጋዶ ሸጥዎ።",
    "ዮሴፍን ለነጋዴዎች ሸጡት።", "hills"),
 SC("The traders took him to Egypt.",
    "እቶም ነጋዶ ናብ ግብጺ ወሰድዎ።",
    "ነጋዴዎቹ ወደ ግብጽ ወሰዱት።", "temple"),
 SC("Joseph was far from home and sad.",
    "ዮሴፍ ካብ ገዛ ርሒቑ ጐሃየ።",
    "ዮሴፍ ከቤት ርቆ አዘነ።", "temple"),
 SC("But God was with Joseph.",
    "ኣምላኽ ግና ምስ ዮሴፍ ነበረ።",
    "እግዚአብሔር ግን ከዮሴፍ ጋር ነበረ።", "temple"),
 SC("Joseph worked hard and was honest.",
    "ዮሴፍ ጽዒቱ ሰርሐ እሙን ከኣ ነበረ።",
    "ዮሴፍ ጠንክሮ ሠራ ታማኝም ነበረ።", "temple"),
 SC("But one day he was put in prison.",
    "ሓደ መዓልቲ ግና ኣብ ቤት ማእሰርቲ ተኣስረ።",
    "አንድ ቀን ግን ወደ እስር ቤት ገባ።", "temple"),
 SC("Even there, God helped Joseph.",
    "ኣብኡ እኳ ኣምላኽ ንዮሴፍ ሓገዞ።",
    "እዚያም እግዚአብሔር ዮሴፍን ረዳው።", "temple"),
 SC("Joseph could understand dreams.",
    "ዮሴፍ ሕልምታት ኪርድእ ይኽእል ነበረ።",
    "ዮሴፍ ሕልሞችን መተርጎም ይችል ነበር።", "star"),
 SC("The king of Egypt had a dream.",
    "ንጉስ ግብጺ ሕልሚ ሓለመ።",
    "የግብጽ ንጉሥ ሕልም አለመ።", "crown"),
 SC("No one could tell what it meant.",
    "ትርጉሙ ኺነግር ዝኽእል ኣይነበረን።",
    "ትርጉሙን መንገር የሚችል አልነበረም።", "crown"),
 SC("So they called for Joseph.",
    "ስለዚ ንዮሴፍ ጸውዕዎ።",
    "ስለዚህ ዮሴፍን ጠሩት።", "crown"),
 SC("God helped Joseph explain the dream.",
    "ኣምላኽ ንዮሴፍ ነቲ ሕልሚ ኪገልጽ ሓገዞ።",
    "እግዚአብሔር ዮሴፍ ሕልሙን እንዲገልጽ ረዳው።", "crown"),
 SC("'Seven years of good food will come.'",
    "'ሸውዓተ ዓመት ጽቡቕ መግቢ ኪመጽእ እዩ።'",
    "'ሰባት ዓመት ጥሩ ምግብ ይመጣል።'", "loaves"),
 SC("'Then seven years of hunger will follow.'",
    "'ደሓር ሸውዓተ ዓመት ጥሜት ኪስዕብ እዩ።'",
    "'ከዚያም ሰባት ዓመት ረሃብ ይከተላል።'", "hills"),
 SC("'Save food now for the hungry days.'",
    "'ንመዓልትታት ጥሜት ሕጂ መግቢ ኣኻዕብቱ።'",
    "'ለረሃብ ቀናት አሁን ምግብ አጠራቅሙ።'", "loaves"),
 SC("The king was amazed by Joseph.",
    "ንጉስ በዮሴፍ ተገረመ።",
    "ንጉሡ በዮሴፍ ተደነቀ።", "crown"),
 SC("He made Joseph a great ruler.",
    "ንዮሴፍ ዓቢ ገዛኢ ገበሮ።",
    "ዮሴፍን ታላቅ ገዥ አደረገው።", "crown"),
 SC("Joseph stored food all over the land.",
    "ዮሴፍ ኣብ ኵላ እታ ምድሪ መግቢ ኣኻዕበተ።",
    "ዮሴፍ በምድሪቱ ሁሉ ምግብ አጠራቀመ።", "loaves"),
 SC("Then the hungry years came.",
    "ሽዑ ዓመታት ጥሜት መጹ።",
    "ከዚያም የረሃብ ዓመታት መጡ።", "hills"),
 SC("People came from far to buy food.",
    "ሰባት ካብ ርሑቕ መጺኦም መግቢ ገዝኡ።",
    "ሰዎች ከሩቅ መጥተው ምግብ ገዙ።", "loaves"),
 SC("One day Joseph's brothers came too.",
    "ሓደ መዓልቲ ኣሕዋት ዮሴፍ እውን መጹ።",
    "አንድ ቀን የዮሴፍ ወንድሞችም መጡ።", "hills"),
 SC("They did not know it was Joseph.",
    "ዮሴፍ ምዃኑ ኣይፈለጡን።",
    "ዮሴፍ መሆኑን አላወቁም።", "crown"),
 SC("Joseph's heart was full of love.",
    "ልቢ ዮሴፍ ብፍቕሪ መሊኡ ነበረ።",
    "የዮሴፍ ልብ በፍቅር ተሞልቶ ነበር።", "crown"),
 SC("'I am Joseph, your brother,' he said.",
    "'ኣነ ዮሴፍ ሓውኹም እየ' በለ።",
    "'እኔ ወንድማችሁ ዮሴፍ ነኝ' አለ።", "crown"),
 SC("His brothers were afraid and sorry.",
    "ኣሕዋቱ ፈሪሆምን ተጣዒሶምን።",
    "ወንድሞቹ ፈሩና አዘኑ።", "hills"),
 SC("But Joseph forgave them with love.",
    "ዮሴፍ ግና ብፍቕሪ ይቕረ በለሎም።",
    "ዮሴፍ ግን በፍቅር ይቅር አላቸው።", "crown"),
 SC("'God turned it into good,' he said.",
    "'ኣምላኽ ናብ ጽቡቕ ለወጦ' በለ።",
    "'እግዚአብሔር ወደ በጎ ለወጠው' አለ።", "crown"),
 SC("The whole family lived together in joy.",
    "ብምሉኣ እታ ስድራ ብሓጐስ ሓቢሮም ነበሩ።",
    "ቤተሰቡ ሁሉ በደስታ አብረው ኖሩ።", "hills"),
 SC("God can turn hard times into blessings.",
    "ኣምላኽ ንኸቢድ ግዜ ናብ በረኸት ኪልውጦ ይኽእል።",
    "እግዚአብሔር ክፉ ጊዜን ወደ በረከት ሊለውጠው ይችላል።", "crown"),
]

BOOK_JOSEPH = {
    "slug": "joseph_and_his_colorful_coat",
    "title_en": "Joseph and His Colorful Coat",
    "title_ti": "ዮሴፍን ሕብራዊ ቀሚሹን",
    "title_am": "ዮሴፍና ባለ ቀለም ካባው",
    "verse": "Genesis 37-45",
    "cover_ill": "coat",
    "scenes": JOSEPH,
}



# ============================================================
# BOOK 3 — BABY MOSES IN THE BASKET
# ============================================================
MOSES = [
 SC("Long ago, God's people lived in Egypt.",
    "ኣብ ጥንቲ ህዝቢ ኣምላኽ ኣብ ግብጺ ይነብር ነበረ።",
    "በጥንት ጊዜ የእግዚአብሔር ሕዝብ በግብጽ ይኖር ነበር።", "temple"),
 SC("A hard king ruled the land.",
    "ጨካን ንጉስ ነታ ምድሪ ይገዝኣ ነበረ።",
    "ጨካኝ ንጉሥ ምድሪቱን ይገዛ ነበር።", "crown"),
 SC("He was unkind to God's people.",
    "ንህዝቢ ኣምላኽ ኣይሓንን ነበረ።",
    "ለእግዚአብሔር ሕዝብ ጨካኝ ነበረ።", "crown"),
 SC("In one home a baby boy was born.",
    "ኣብ ሓደ ገዛ ወዲ ህጻን ተወልደ።",
    "በአንድ ቤት ወንድ ሕፃን ተወለደ።", "woman"),
 SC("His mother loved him very much.",
    "ኣዲኡ ኣዝያ ተፍቅሮ ነበረት።",
    "እናቱ እጅግ ትወደው ነበር።", "woman"),
 SC("She wanted to keep her baby safe.",
    "ንህጻና ኽትሕሉ ደለየት።",
    "ሕፃኗን መጠበቅ ፈለገች።", "woman"),
 SC("So she made a little basket.",
    "ስለዚ ንእሽቶ መሶብ ሰርሐት።",
    "ስለዚህ ትንሽ ቅርጫት ሠራች።", "basket"),
 SC("She covered it so no water could enter.",
    "ማይ ከይኣቱ ገይራ ለኸየቶ።",
    "ውኃ እንዳይገባ አድርጋ ለሰነችው።", "basket"),
 SC("She laid her baby gently inside.",
    "ንህጻና ብህዱእ ኣብ ውሽጢ ኣቐመጠቶ።",
    "ሕፃኗን በቀስታ ውስጥ አኖረችው።", "basket"),
 SC("Then she placed it among the reeds.",
    "ሽዑ ኣብ መንጎ ኣቃውዖ ኣቐመጠቶ።",
    "ከዚያም በደንገሉ መካከል አኖረችው።", "basket"),
 SC("The river flowed gently by.",
    "እቲ ወሓዚ ብህዱእ ይውሕዝ ነበረ።",
    "ወንዙ በቀስታ ይፈስ ነበር።", "basket"),
 SC("His big sister watched from nearby.",
    "ዓባይ ሓብቱ ኻብ ቀረባ ትዕዘብ ነበረት።",
    "ታላቅ እኅቱ ከአቅራቢያ ትጠብቅ ነበር።", "woman"),
 SC("She wanted to keep him safe.",
    "ብደሓን ክትሕልዎ ደለየት።",
    "በደኅና ልትጠብቀው ፈለገች።", "woman"),
 SC("Soon the king's daughter came to the river.",
    "ድሕሪ ቕሩብ ጓል ንጉስ ናብ ወሓዚ መጸት።",
    "ወዲያውም የንጉሡ ልጅ ወደ ወንዙ መጣች።", "crown"),
 SC("She came to wash by the water.",
    "ኣብ ጥቓ ማይ ክትሕጸብ መጸት።",
    "በውኃው ዳር ልትታጠብ መጣች።", "crown"),
 SC("She saw the little basket floating.",
    "ነታ ንእሽቶ መሶብ ክትንሳፈፍ ከላ ረኣየት።",
    "ትንሿ ቅርጫት ስትንሳፈፍ አየች።", "basket"),
 SC("She opened it and saw the baby.",
    "ከፊታ ነቲ ህጻን ረኣየቶ።",
    "ከፍታ ሕፃኑን አየች።", "basket"),
 SC("The baby was crying softly.",
    "እቲ ህጻን ብህዱእ ይበኪ ነበረ።",
    "ሕፃኑ በቀስታ ያለቅስ ነበር።", "woman"),
 SC("Her heart was filled with love.",
    "ልባ ብፍቕሪ መልአ።",
    "ልቧ በፍቅር ተሞላ።", "crown"),
 SC("'I will care for this child,' she said.",
    "'ነዚ ቘልዓ ኸናብዮ እየ' በለት።",
    "'ይህን ልጅ እንከባከበዋለሁ' አለች።", "crown"),
 SC("The sister ran up to help.",
    "እታ ሓብቲ ንኽትሕግዝ ጐየየት።",
    "እኅቱ ልትረዳ ሮጠች።", "woman"),
 SC("'Shall I find someone to feed him?'",
    "'ዜጥብዎ ሰብ ክደልየልኪዶ?'",
    "'የሚያጠባው ሰው ልፈልግልሽን?'", "woman"),
 SC("'Yes, please do,' said the princess.",
    "'እወ በጃኺ' በለት እታ ጓል ንጉስ።",
    "'አዎ እባክሽ' አለች ልዕልቲቱ።", "crown"),
 SC("So the sister brought the baby's own mother!",
    "ስለዚ እታ ሓብቲ ንገዛእ ኣደ እቲ ህጻን ኣምጽአት!",
    "ስለዚህ እኅቱ የሕፃኑን እናት አመጣች!", "woman"),
 SC("The mother cared for her own baby.",
    "እታ ኣደ ንገዛእ ህጻና ኣላየት።",
    "እናቲቱ የገዛ ሕፃኗን ተንከባከበች።", "woman"),
 SC("God had kept the baby safe.",
    "ኣምላኽ ነቲ ህጻን ሓልይዎ ነበረ።",
    "እግዚአብሔር ሕፃኑን ጠብቆት ነበር።", "woman"),
 SC("They named the boy Moses.",
    "ነቲ ወዲ ሙሴ ኢሎም ሰመይዎ።",
    "ልጁን ሙሴ ብለው ሰየሙት።", "prophet"),
 SC("Moses grew bigger every day.",
    "ሙሴ ኵሉ መዓልቲ እናዓበየ ኸደ።",
    "ሙሴ በየቀኑ እያደገ ሄደ።", "prophet"),
 SC("He lived in the king's palace.",
    "ኣብ ቤተ መንግስቲ ንጉስ ይነብር ነበረ።",
    "በንጉሡ ቤተ መንግሥት ይኖር ነበር።", "temple"),
 SC("But God had a special plan for him.",
    "ኣምላኽ ግና ፍሉይ መደብ ነበሮ።",
    "እግዚአብሔር ግን ልዩ ዕቅድ ነበረው።", "prophet"),
 SC("God was always watching over Moses.",
    "ኣምላኽ ኵሉ ግዜ ንሙሴ ይሕልዎ ነበረ።",
    "እግዚአብሔር ሁልጊዜ ሙሴን ይጠብቀው ነበር።", "prophet"),
 SC("Moses would help God's people one day.",
    "ሓደ መዓልቲ ሙሴ ንህዝቢ ኣምላኽ ኪሕግዝ እዩ።",
    "አንድ ቀን ሙሴ የእግዚአብሔርን ሕዝብ ይረዳል።", "prophet"),
 SC("God protects us even when we are small.",
    "ኣምላኽ ንኣሽቱ ኸለና እኳ ይሕልወና።",
    "እግዚአብሔር ትንሽ ስንሆንም ይጠብቀናል።", "prophet"),
 SC("He knows each of us by name.",
    "ንነፍሲ ወከፍና ብስምና ይፈልጠና።",
    "እያንዳንዳችንን በስም ያውቀናል።", "prophet"),
 SC("Baby Moses was never alone.",
    "ህጻን ሙሴ ከቶ በይኑ ኣይነበረን።",
    "ሕፃን ሙሴ ከቶ ብቻውን አልነበረም።", "basket"),
 SC("God's care is bigger than any danger.",
    "ክንክን ኣምላኽ ካብ ዝዀነ ሓደጋ ይዓቢ።",
    "የእግዚአብሔር እንክብካቤ ከማንኛውም አደጋ ይበልጣል።", "basket"),
 SC("The little basket kept him safe.",
    "እታ ንእሽቶ መሶብ ብደሓን ሓለወቶ።",
    "ትንሿ ቅርጫት በደኅና ጠበቀችው።", "basket"),
 SC("A watching sister helped save him.",
    "እታ እትዕዘብ ሓብቲ ንኽትድሕኖ ሓገዘት።",
    "የምትጠብቀው እኅት እንዲድን ረዳች።", "woman"),
 SC("A kind princess opened her heart.",
    "ሓንቲ ሕያወይቲ ጓል ንጉስ ልባ ኸፈተት።",
    "ደግ ልዕልት ልቧን ከፈተች።", "crown"),
 SC("A loving mother stayed close.",
    "ሓንቲ ኣፍቃሪት ኣደ ኣብ ቀረባ ጸንሐት።",
    "አፍቃሪ እናት በአቅራቢያ ቆየች።", "woman"),
 SC("God used them all together.",
    "ኣምላኽ ንዅሎም ብሓባር ተጠቕመሎም።",
    "እግዚአብሔር ሁሉንም አብሮ ተጠቀመባቸው።", "prophet"),
 SC("Nothing is too hard for God.",
    "ንኣምላኽ ዚኸብዶ ነገር የልቦን።",
    "ለእግዚአብሔር የሚከብደው ነገር የለም።", "prophet"),
 SC("He watches over you too.",
    "ንዓኻ እውን ይሕልወካ።",
    "አንተንም ይጠብቅሃል።", "prophet"),
 SC("You are precious in God's eyes.",
    "ኣብ ኣዒንቲ ኣምላኽ ክቡር ኢኻ።",
    "በእግዚአብሔር ዓይን ውድ ነህ።", "star"),
]

BOOK_MOSES = {
    "slug": "baby_moses_in_the_basket",
    "title_en": "Baby Moses in the Basket",
    "title_ti": "ህጻን ሙሴ ኣብ መሶብ",
    "title_am": "ሕፃን ሙሴ በቅርጫት",
    "verse": "Exodus 2:1-10",
    "cover_ill": "basket",
    "scenes": MOSES,
}



# ============================================================
# BOOK 4 — DAVID AND THE GIANT
# ============================================================
DAVID = [
 SC("David was a young shepherd boy.",
    "ዳዊት መንእሰይ ጓሳ ወዲ ነበረ።",
    "ዳዊት ወጣት እረኛ ልጅ ነበረ።", "sheep"),
 SC("He cared for his father's sheep.",
    "ንኣባጊዕ ኣቦኡ ይናብ ነበረ።",
    "የአባቱን በጎች ይጠብቅ ነበር።", "sheep"),
 SC("David loved to sing to God.",
    "ዳዊት ንኣምላኽ ኪዝምር የፍቅር ነበረ።",
    "ዳዊት ለእግዚአብሔር መዘመር ይወድ ነበር።", "sheep"),
 SC("He trusted God with all his heart.",
    "ብምሉእ ልቡ ኣብ ኣምላኽ ተወከለ።",
    "በፍጹም ልቡ በእግዚአብሔር ታመነ።", "sheep"),
 SC("One day a war came to the land.",
    "ሓደ መዓልቲ ውግእ ናብ ምድሪ መጸ።",
    "አንድ ቀን ጦርነት ወደ ምድሪቱ መጣ።", "hills"),
 SC("David's brothers were soldiers.",
    "ኣሕዋት ዳዊት ወተሃደራት ነበሩ።",
    "የዳዊት ወንድሞች ወታደሮች ነበሩ።", "hills"),
 SC("A huge giant stood on the hill.",
    "ግዙፍ ዓብዪ ኣብ ኩድ ኰይኑ ደው በለ።",
    "ግዙፍ ትልቅ ሰው በኮረብታው ላይ ቆመ።", "hills"),
 SC("His name was Goliath.",
    "ስሙ ጎልያድ ነበረ።",
    "ስሙ ጎልያድ ነበረ።", "hills"),
 SC("Goliath was very tall and strong.",
    "ጎልያድ ኣዝዩ ነዊሕን ብርቱዕን ነበረ።",
    "ጎልያድ እጅግ ረጅምና ጠንካራ ነበረ።", "hills"),
 SC("He shouted at God's soldiers.",
    "ንወተሃደራት ኣምላኽ ኣእወየሎም።",
    "በእግዚአብሔር ወታደሮች ጮኸ።", "hills"),
 SC("'Who is brave enough to fight me?'",
    "'ምስይ ኪዋጋእ ዚኽእል መን እዩ?'",
    "'ከእኔ ጋር ሊዋጋ የሚደፍር ማን ነው?'", "hills"),
 SC("All the soldiers were afraid.",
    "ኵሎም ወተሃደራት ፈርሁ።",
    "ወታደሮቹ ሁሉ ፈሩ።", "hills"),
 SC("They trembled and ran away.",
    "ራዕዲ ሒዝዎም ሃደሙ።",
    "ተንቀጠቀጡና ሸሹ።", "hills"),
 SC("David came to bring food to his brothers.",
    "ዳዊት ንኣሕዋቱ መግቢ ኼምጽእ መጸ።",
    "ዳዊት ለወንድሞቹ ምግብ ሊያመጣ መጣ።", "sheep"),
 SC("He heard the giant shouting.",
    "ነቲ ግዙፍ ኪእውይ ሰምዖ።",
    "ግዙፉ ሲጮኽ ሰማ።", "hills"),
 SC("David was not afraid.",
    "ዳዊት ኣይፈርሀን።",
    "ዳዊት አልፈራም።", "sheep"),
 SC("'I will fight the giant,' said David.",
    "'ኣነ ምስቲ ግዙፍ ክዋጋእ እየ' በለ ዳዊት።",
    "'እኔ ከግዙፉ ጋር እዋጋለሁ' አለ ዳዊት።", "sheep"),
 SC("People said, 'You are too small!'",
    "ሰባት 'ኣዝኻ ንእሽቶ ኢኻ!' በሉ።",
    "ሰዎች 'በጣም ትንሽ ነህ!' አሉ።", "hills"),
 SC("But David trusted in God.",
    "ዳዊት ግና ኣብ ኣምላኽ ተወከለ።",
    "ዳዊት ግን በእግዚአብሔር ታመነ።", "sheep"),
 SC("'God helped me protect my sheep.'",
    "'ኣምላኽ ኣባጊዐይ ኽከላኸል ሓጊዙኒ።'",
    "'እግዚአብሔር በጎቼን ልጠብቅ ረድቶኛል።'", "sheep"),
 SC("'God will help me now too.'",
    "'ኣምላኽ ሕጂ እውን ኪሕግዘኒ እዩ።'",
    "'እግዚአብሔር አሁንም ይረዳኛል።'", "sheep"),
 SC("David did not wear heavy armor.",
    "ዳዊት ከቢድ ኣጽዋር ኣይተኸድነን።",
    "ዳዊት ከባድ ጋሻ አልለበሰም።", "hills"),
 SC("He took his simple sling.",
    "ንቐሊል ወንጭፉ ወሰደ።",
    "ቀላል ወንጭፉን ወሰደ።", "hills"),
 SC("He picked five smooth stones.",
    "ሓሙሽተ ልሙጻት ኣእማን ኣልዓለ።",
    "አምስት ለስላሳ ድንጋዮች አነሳ።", "hills"),
 SC("He walked toward the giant bravely.",
    "ብትብዓት ናብቲ ግዙፍ ከደ።",
    "በድፍረት ወደ ግዙፉ ሄደ።", "hills"),
 SC("Goliath laughed at little David.",
    "ጎልያድ ንንእሽቶ ዳዊት ሰሓቐሉ።",
    "ጎልያድ ትንሹን ዳዊት ሳቀበት።", "hills"),
 SC("But David was not afraid at all.",
    "ዳዊት ግና ፈጺሙ ኣይፈርሀን።",
    "ዳዊት ግን ፈጽሞ አልፈራም።", "sheep"),
 SC("'I come in the name of the Lord!'",
    "'ብስም እግዚኣብሄር እመጽእ ኣለኹ!'",
    "'በእግዚአብሔር ስም እመጣለሁ!'", "sheep"),
 SC("David put a stone in his sling.",
    "ዳዊት ኣብ ወንጭፉ እምኒ ኣንበረ።",
    "ዳዊት በወንጭፉ ድንጋይ አደረገ።", "hills"),
 SC("He swung it round and round.",
    "ኣዞረ ኣዞረ።",
    "አዞረ አዞረ።", "hills"),
 SC("The stone flew fast and straight.",
    "እታ እምኒ ቀልጢፋ ብቐጥታ በረረት።",
    "ድንጋዩ ፈጥኖ በቀጥታ በረረ።", "hills"),
 SC("It struck the giant on the head.",
    "ነቲ ግዙፍ ኣብ ርእሱ ወቕዖ።",
    "ግዙፉን በራሱ መታው።", "hills"),
 SC("The great giant fell down!",
    "እቲ ዓብዪ ግዙፍ ወደቐ!",
    "ታላቁ ግዙፍ ወደቀ!", "hills"),
 SC("God had given David the victory.",
    "ኣምላኽ ንዳዊት ዓወት ሂብዎ ነበረ።",
    "እግዚአብሔር ለዳዊት ድል ሰጥቶት ነበር።", "sheep"),
 SC("The soldiers cheered with joy.",
    "እቶም ወተሃደራት ብሓጐስ ኣእወዩ።",
    "ወታደሮቹ በደስታ ጮኹ።", "hills"),
 SC("David gave all the thanks to God.",
    "ዳዊት ንዅሉ ምስጋና ንኣምላኽ ሃበ።",
    "ዳዊት ምስጋናውን ሁሉ ለእግዚአብሔር ሰጠ።", "pray"),
 SC("God helped a small boy do a big thing.",
    "ኣምላኽ ንንእሽቶ ወዲ ዓቢ ነገር ኪገብር ሓገዞ።",
    "እግዚአብሔር ትንሽ ልጅ ትልቅ ነገር እንዲያደርግ ረዳው።", "sheep"),
 SC("Being small is never too small for God.",
    "ንኣምላኽ ንእሽቶ ምዃን ከቶ ኣይንእስን።",
    "ለእግዚአብሔር ትንሽ መሆን ከቶ ትንሽ አይደለም።", "sheep"),
 SC("What matters is trusting Him.",
    "ኣገዳሲ ዘበለ ኣብኡ ምውካል እዩ።",
    "አስፈላጊው በእርሱ መታመን ነው።", "pray"),
 SC("God gives courage to those who trust Him.",
    "ኣምላኽ ነቶም ዚውከልዎ ትብዓት ይህብ።",
    "እግዚአብሔር በእርሱ ለሚታመኑ ድፍረት ይሰጣል።", "pray"),
 SC("You can be brave with God's help.",
    "ብሓገዝ ኣምላኽ ትብዕ ክትከውን ትኽእል።",
    "በእግዚአብሔር እርዳታ ደፋር መሆን ትችላለህ።", "sheep"),
 SC("God is bigger than any giant.",
    "ኣምላኽ ካብ ዝዀነ ግዙፍ ይዓቢ።",
    "እግዚአብሔር ከማንኛውም ግዙፍ ይበልጣል።", "sheep"),
 SC("With God, even the small can be brave.",
    "ምስ ኣምላኽ ንኣሽቱ እኳ ኪተባብዑ ይኽእሉ።",
    "ከእግዚአብሔር ጋር ትንሾችም ደፋር መሆን ይችላሉ።", "sheep"),
 SC("Trust God, and He will help you too.",
    "ኣብ ኣምላኽ ተወከል፡ ንዓኻ እውን ኪሕግዘካ እዩ።",
    "በእግዚአብሔር ታመን አንተንም ይረዳሃል።", "pray"),
]

BOOK_DAVID = {
    "slug": "david_and_the_giant",
    "title_en": "David and the Giant",
    "title_ti": "ዳዊትን እቲ ግዙፍን",
    "title_am": "ዳዊትና ግዙፉ",
    "verse": "1 Samuel 17",
    "cover_ill": "sheep",
    "scenes": DAVID,
}



# ============================================================
# BOOK 5 — DANIEL IN THE LIONS' DEN
# ============================================================
DANIEL = [
 SC("Daniel was a man who loved God.",
    "ዳንኤል ንኣምላኽ ዜፍቅር ሰብ ነበረ።",
    "ዳንኤል እግዚአብሔርን የሚወድ ሰው ነበረ።", "prophet"),
 SC("He lived far away in a big city.",
    "ኣብ ርሑቕ ኣብ ዓባይ ከተማ ይነብር ነበረ።",
    "ራቅ ብሎ በአንድ ትልቅ ከተማ ይኖር ነበር።", "temple"),
 SC("Daniel prayed to God three times a day.",
    "ዳንኤል ኣብ መዓልቲ ሰለስተ ግዜ ናብ ኣምላኽ ይጽሊ ነበረ።",
    "ዳንኤል በቀን ሦስት ጊዜ ወደ እግዚአብሔር ይጸልይ ነበር።", "pray"),
 SC("He thanked God every morning.",
    "ኵሉ ንግሆ ንኣምላኽ የመስግን ነበረ።",
    "በየጠዋቱ እግዚአብሔርን ያመሰግን ነበር።", "pray"),
 SC("The king liked Daniel very much.",
    "ንጉስ ንዳንኤል ኣዝዩ ኣፍቀሮ።",
    "ንጉሡ ዳንኤልን እጅግ ወደደው።", "crown"),
 SC("He made Daniel a great leader.",
    "ንዳንኤል ዓቢ መራሒ ገበሮ።",
    "ዳንኤልን ታላቅ መሪ አደረገው።", "crown"),
 SC("But other men were jealous of Daniel.",
    "ካልኦት ሰባት ግና ንዳንኤል ቀንኡ።",
    "ሌሎች ሰዎች ግን ዳንኤልን ቀኑ።", "hills"),
 SC("They wanted to get him in trouble.",
    "ኣብ ጸገም ኬእትውዎ ደለዩ።",
    "ወደ ችግር ሊከቱት ፈለጉ።", "hills"),
 SC("They made a tricky new law.",
    "ተንኰለኛ ሓድሽ ሕጊ ኣውጽኡ።",
    "ተንኮለኛ አዲስ ሕግ አወጡ።", "scroll"),
 SC("'Pray only to the king,' said the law.",
    "'ንንጉስ ጥራይ ጸሊ' ይብል ነበረ እቲ ሕጊ።",
    "'ለንጉሡ ብቻ ጸልይ' ይል ነበር ሕጉ።", "scroll"),
 SC("Anyone who disobeyed would face the lions.",
    "ዘይእዘዝ ንኣናብስ ኪግጠም እዩ።",
    "የማይታዘዝ ወደ አንበሶች ይጣላል።", "lion"),
 SC("Daniel heard about the new law.",
    "ዳንኤል ብዛዕባ እቲ ሓድሽ ሕጊ ሰምዐ።",
    "ዳንኤል ስለ አዲሱ ሕግ ሰማ።", "scroll"),
 SC("But Daniel still loved God.",
    "ዳንኤል ግና ገና ንኣምላኽ የፍቅሮ ነበረ።",
    "ዳንኤል ግን አሁንም እግዚአብሔርን ይወድ ነበር።", "prophet"),
 SC("He went home and opened his window.",
    "ናብ ገዛ ኸይዱ መስኮቱ ኸፈተ።",
    "ወደ ቤቱ ሄዶ መስኮቱን ከፈተ።", "temple"),
 SC("He knelt down and prayed to God.",
    "ተምበርኪኹ ናብ ኣምላኽ ጸለየ።",
    "ተንበርክኮ ወደ እግዚአብሔር ጸለየ።", "pray"),
 SC("Daniel was not afraid to pray.",
    "ዳንኤል ኪጽሊ ኣይፈርሀን።",
    "ዳንኤል መጸለይ አልፈራም።", "pray"),
 SC("The jealous men saw him praying.",
    "እቶም ቀናኣት ሰባት ኪጽሊ ኸሎ ረኣይዎ።",
    "ቀናተኞቹ ሰዎች ሲጸልይ አዩት።", "hills"),
 SC("They ran to tell the king.",
    "ንንጉስ ኪነግሩ ጐየዩ።",
    "ለንጉሡ ሊነግሩ ሮጡ።", "crown"),
 SC("The king was very sad.",
    "ንጉስ ኣዝዩ ጐሃየ።",
    "ንጉሡ እጅግ አዘነ።", "crown"),
 SC("He did not want to hurt Daniel.",
    "ንዳንኤል ኪጐድኦ ኣይደለየን።",
    "ዳንኤልን ሊጎዳ አልፈለገም።", "crown"),
 SC("But the law could not be changed.",
    "እቲ ሕጊ ግና ኪልወጥ ኣይክኣለን።",
    "ሕጉ ግን ሊለወጥ አልቻለም።", "scroll"),
 SC("So Daniel was put in the lions' den.",
    "ስለዚ ዳንኤል ኣብ ጕድጓድ ኣናብስ ተኣትወ።",
    "ስለዚህ ዳንኤል ወደ አንበሶች ጉድጓድ ተጣለ።", "lion"),
 SC("The lions were big and hungry.",
    "እቶም ኣናብስ ዓበይትን ጥሙያትን ነበሩ።",
    "አንበሶቹ ትልልቅና የተራቡ ነበሩ።", "lion"),
 SC("The king said, 'May your God save you.'",
    "ንጉስ 'ኣምላኽካ ይናበኻ' በለ።",
    "ንጉሡ 'አምላክህ ያድንህ' አለ።", "crown"),
 SC("A big stone was rolled over the den.",
    "ዓባይ እምኒ ኣብ ልዕሊ እቲ ጕድጓድ ተንከባለለት።",
    "ትልቅ ድንጋይ በጉድጓዱ ላይ ተንከባለለ።", "lion"),
 SC("Daniel was not afraid.",
    "ዳንኤል ኣይፈርሀን።",
    "ዳንኤል አልፈራም።", "prophet"),
 SC("He trusted God to help him.",
    "ኣምላኽ ኪሕግዞ ተወከሎ።",
    "እግዚአብሔር ይረዳው ዘንድ ታመነው።", "prophet"),
 SC("God sent an angel that night.",
    "ኣምላኽ በታ ለይቲ መልኣኽ ሰደደ።",
    "እግዚአብሔር በዚያ ሌሊት መልአክ ላከ።", "angel"),
 SC("The angel shut the lions' mouths.",
    "እቲ መልኣኽ ኣፍ ኣናብስ ዓጸወ።",
    "መልአኩ የአንበሶቹን አፍ ዘጋ።", "angel"),
 SC("The lions lay down quietly.",
    "እቶም ኣናብስ ጸጥ ኢሎም ደቀሱ።",
    "አንበሶቹ ጸጥ ብለው ተኙ።", "lion"),
 SC("Daniel was safe all night long.",
    "ዳንኤል ምሉእ ለይቲ ደሓን ነበረ።",
    "ዳንኤል ሌሊቱን ሙሉ በደኅና ነበረ።", "lion"),
 SC("He was not hurt at all.",
    "ፈጺሙ ኣይተጐድአን።",
    "ፈጽሞ አልተጎዳም።", "prophet"),
 SC("In the morning the king ran to the den.",
    "ንግሆ ንጉስ ናብቲ ጕድጓድ ጐየየ።",
    "በጠዋት ንጉሡ ወደ ጉድጓዱ ሮጠ።", "crown"),
 SC("'Daniel, did your God save you?'",
    "'ዳንኤል፡ ኣምላኽካ ኣድሓነካዶ?'",
    "'ዳንኤል አምላክህ አዳነህን?'", "crown"),
 SC("'Yes! God kept me safe,' said Daniel.",
    "'እወ! ኣምላኽ ሓልዩኒ' በለ ዳንኤል።",
    "'አዎ! እግዚአብሔር ጠበቀኝ' አለ ዳንኤል።", "prophet"),
 SC("The king was full of joy.",
    "ንጉስ ብሓጐስ መልአ።",
    "ንጉሡ በደስታ ተሞላ።", "crown"),
 SC("He lifted Daniel out of the den.",
    "ንዳንኤል ካብቲ ጕድጓድ ኣውጽኦ።",
    "ዳንኤልን ከጉድጓዱ አወጣው።", "crown"),
 SC("The king praised Daniel's God.",
    "ንጉስ ንኣምላኽ ዳንኤል ኣመስገነ።",
    "ንጉሡ የዳንኤልን አምላክ አመሰገነ።", "crown"),
 SC("'Everyone should honor this great God!'",
    "'ኵሉ ነዚ ዓቢ ኣምላኽ የኽብር!'",
    "'ሁሉም ይህን ታላቅ አምላክ ያክብር!'", "crown"),
 SC("Daniel kept on trusting God.",
    "ዳንኤል ኣብ ኣምላኽ ምውካሉ ቐጸለ።",
    "ዳንኤል በእግዚአብሔር መታመኑን ቀጠለ።", "pray"),
 SC("God is with us in scary times.",
    "ኣብ ግዜ ፍርሒ ኣምላኽ ምሳና እዩ።",
    "በሚያስፈራ ጊዜ እግዚአብሔር ከእኛ ጋር ነው።", "angel"),
 SC("We can pray to Him any time.",
    "ኣብ ዝዀነ ግዜ ናብኡ ክንጽሊ ንኽእል።",
    "በማንኛውም ጊዜ ወደ እርሱ መጸለይ እንችላለን።", "pray"),
 SC("God protects those who stay faithful.",
    "ኣምላኽ ነቶም እሙናት ዝዀኑ ይሕልዎም።",
    "እግዚአብሔር የታመኑትን ይጠብቃል።", "prophet"),
 SC("Be brave and keep loving God.",
    "ትብዕ በል ንኣምላኽ ከኣ የፍቅሮ።",
    "ደፋር ሁን እግዚአብሔርንም መውደድህን ቀጥል።", "pray"),
]

BOOK_DANIEL = {
    "slug": "daniel_in_the_lions_den",
    "title_en": "Daniel in the Lions' Den",
    "title_ti": "ዳንኤል ኣብ ጕድጓድ ኣናብስ",
    "title_am": "ዳንኤል በአንበሶች ጉድጓድ",
    "verse": "Daniel 6",
    "cover_ill": "lion",
    "scenes": DANIEL,
}



# ============================================================
# BOOK 6 — JONAH AND THE BIG FISH
# ============================================================
JONAH = [
 SC("Jonah was a man who served God.",
    "ዮናስ ንኣምላኽ ዘገልግል ሰብ ነበረ።",
    "ዮናስ እግዚአብሔርን የሚያገለግል ሰው ነበረ።", "prophet"),
 SC("One day God spoke to Jonah.",
    "ሓደ መዓልቲ ኣምላኽ ንዮናስ ተዛረቦ።",
    "አንድ ቀን እግዚአብሔር ለዮናስ ተናገረው።", "prophet"),
 SC("'Go to the city of Nineveh.'",
    "'ናብ ከተማ ነነዌ ኪድ።'",
    "'ወደ ነነዌ ከተማ ሂድ።'", "temple"),
 SC("'Tell them to turn from their bad ways.'",
    "'ካብ ክፉእ መገዶም ኪምለሱ ንገሮም።'",
    "'ከክፉ መንገዳቸው እንዲመለሱ ንገራቸው።'", "temple"),
 SC("But Jonah did not want to go.",
    "ዮናስ ግና ኪኸይድ ኣይደለየን።",
    "ዮናስ ግን መሄድ አልፈለገም።", "hills"),
 SC("He ran the other way.",
    "ናብ ካልእ መገዲ ሃደመ።",
    "ወደ ሌላ መንገድ ሸሸ።", "hills"),
 SC("Jonah got on a big ship.",
    "ዮናስ ኣብ ዓባይ መርከብ ደየበ።",
    "ዮናስ በአንድ ትልቅ መርከብ ተሳፈረ።", "boat"),
 SC("The ship sailed across the sea.",
    "እታ መርከብ ንባሕሪ ሰገረት።",
    "መርከቧ ባሕሩን አቋረጠች።", "boat"),
 SC("Jonah tried to hide from God.",
    "ዮናስ ካብ ኣምላኽ ኪሕባእ ፈተነ።",
    "ዮናስ ከእግዚአብሔር ሊደበቅ ሞከረ።", "boat"),
 SC("But no one can hide from God.",
    "ካብ ኣምላኽ ኪሕባእ ዚኽእል ግና የልቦን።",
    "ከእግዚአብሔር ሊደበቅ የሚችል ግን የለም።", "boat"),
 SC("God sent a great storm.",
    "ኣምላኽ ዓቢ ህቦብላ ሰደደ።",
    "እግዚአብሔር ታላቅ ማዕበል ላከ።", "boat"),
 SC("The wind blew hard.",
    "ንፋስ ብሓይሊ ነፈሰ።",
    "ነፋሱ በኃይል ነፈሰ።", "boat"),
 SC("The waves tossed the ship.",
    "ማዕበል ነታ መርከብ ኣናወጻ።",
    "ማዕበሉ መርከቧን አናወጣት።", "boat"),
 SC("The sailors were very afraid.",
    "እቶም ማሎሓት ኣዝዮም ፈርሁ።",
    "መርከበኞቹ እጅግ ፈሩ።", "boat"),
 SC("Jonah knew it was because of him.",
    "ዮናስ ብሰሪኡ ምዃኑ ፈለጠ።",
    "ዮናስ በእርሱ ምክንያት መሆኑን አወቀ።", "boat"),
 SC("'Throw me into the sea,' said Jonah.",
    "'ናብ ባሕሪ ደርብዩኒ' በለ ዮናስ።",
    "'ወደ ባሕር ጣሉኝ' አለ ዮናስ።", "boat"),
 SC("The sailors gently let him down.",
    "እቶም ማሎሓት ብህዱእ ኣውረድዎ።",
    "መርከበኞቹ በቀስታ አወረዱት።", "sea"),
 SC("At once the storm stopped.",
    "ሽዑ ንሽዑ እቲ ህቦብላ ደው በለ።",
    "ወዲያውኑ ማዕበሉ ቆመ።", "sea"),
 SC("Jonah sank into the deep water.",
    "ዮናስ ናብ ዓሚቝ ማይ ጠሓለ።",
    "ዮናስ ወደ ጥልቅ ውኃ ሰጠመ።", "sea"),
 SC("Then God sent a very big fish.",
    "ሽዑ ኣምላኽ ኣዝዩ ዓቢ ዓሳ ሰደደ።",
    "ከዚያም እግዚአብሔር እጅግ ትልቅ ዓሣ ላከ።", "fish"),
 SC("The big fish swallowed Jonah!",
    "እቲ ዓቢ ዓሳ ንዮናስ ወሓጦ!",
    "ትልቁ ዓሣ ዮናስን ዋጠው!", "fish"),
 SC("Jonah was safe inside the fish.",
    "ዮናስ ኣብ ውሽጢ እቲ ዓሳ ደሓን ነበረ።",
    "ዮናስ በዓሣው ውስጥ በደኅና ነበረ።", "fish"),
 SC("It was dark and quiet in there.",
    "ኣብኡ ጸልማትን ጸጥታን ነበረ።",
    "እዚያ ውስጥ ጨለማና ጸጥታ ነበረ።", "fish"),
 SC("Jonah began to pray.",
    "ዮናስ ኪጽሊ ጀመረ።",
    "ዮናስ መጸለይ ጀመረ።", "pray"),
 SC("'I am sorry, God,' he said.",
    "'ይቕረ በለለይ ኣምላኸይ' በለ።",
    "'ይቅር በለኝ አምላኬ' አለ።", "pray"),
 SC("'Thank you for saving me.'",
    "'ስለ ዘድሓንካኒ የመስግነካ።'",
    "'ስላዳንከኝ አመሰግንሃለሁ።'", "pray"),
 SC("Jonah stayed there three days.",
    "ዮናስ ሰለስተ መዓልቲ ኣብኡ ጸንሐ።",
    "ዮናስ ሦስት ቀን እዚያ ቆየ።", "fish"),
 SC("God heard Jonah's prayer.",
    "ኣምላኽ ጸሎት ዮናስ ሰምዐ።",
    "እግዚአብሔር የዮናስን ጸሎት ሰማ።", "pray"),
 SC("The fish swam to the shore.",
    "እቲ ዓሳ ናብ ገምገም ሓንበሰ።",
    "ዓሣው ወደ ባሕር ዳር ዋኘ።", "sea"),
 SC("It set Jonah safely on dry land.",
    "ንዮናስ ኣብ ንቑጽ ምድሪ ብደሓን ኣቐመጦ።",
    "ዮናስን በደረቅ መሬት በደኅና አኖረው።", "sea"),
 SC("Jonah thanked God for his mercy.",
    "ዮናስ ስለ ምሕረቱ ንኣምላኽ ኣመስገነ።",
    "ዮናስ ስለ ምሕረቱ እግዚአብሔርን አመሰገነ።", "pray"),
 SC("God spoke to Jonah again.",
    "ኣምላኽ ንዮናስ ከም ብሓድሽ ተዛረቦ።",
    "እግዚአብሔር ለዮናስ እንደገና ተናገረው።", "prophet"),
 SC("'Go to Nineveh now.'",
    "'ሕጂ ናብ ነነዌ ኪድ።'",
    "'አሁን ወደ ነነዌ ሂድ።'", "temple"),
 SC("This time Jonah obeyed God.",
    "ሕጂ ዮናስ ንኣምላኽ ተኣዘዞ።",
    "በዚህ ጊዜ ዮናስ እግዚአብሔርን ታዘዘ።", "prophet"),
 SC("He walked to the big city.",
    "ናብታ ዓባይ ከተማ ኸደ።",
    "ወደ ትልቁ ከተማ ሄደ።", "temple"),
 SC("Jonah told the people God's message.",
    "ዮናስ ንህዝቢ መልእኽቲ ኣምላኽ ነገሮም።",
    "ዮናስ ለሕዝቡ የእግዚአብሔርን መልእክት ነገራቸው።", "temple"),
 SC("'Turn from your bad ways!'",
    "'ካብ ክፉእ መገድኹም ተመለሱ!'",
    "'ከክፉ መንገዳችሁ ተመለሱ!'", "temple"),
 SC("The people listened to Jonah.",
    "እቲ ህዝቢ ንዮናስ ሰምዕዎ።",
    "ሕዝቡ ዮናስን አዳመጡት።", "temple"),
 SC("They were sorry for their wrongs.",
    "ብጌጋታቶም ተጣዕሱ።",
    "በስሕተታቸው አዘኑ።", "temple"),
 SC("The whole city turned to God.",
    "ብምሉኣ እታ ኸተማ ናብ ኣምላኽ ተመልሰት።",
    "ከተማዋ ሁሉ ወደ እግዚአብሔር ተመለሰች።", "temple"),
 SC("God forgave them all.",
    "ኣምላኽ ንዅሎም ይቕረ በለሎም።",
    "እግዚአብሔር ሁሉንም ይቅር አላቸው።", "temple"),
 SC("Jonah learned to obey God.",
    "ዮናስ ንኣምላኽ ኪእዘዝ ተማህረ።",
    "ዮናስ እግዚአብሔርን መታዘዝ ተማረ።", "prophet"),
 SC("God is patient and full of mercy.",
    "ኣምላኽ ዓቃልን ምሕረት ዝመልኦን እዩ።",
    "እግዚአብሔር ታጋሽና ምሕረት የተሞላ ነው።", "dove"),
 SC("It is always better to obey God.",
    "ንኣምላኽ ምእዛዝ ኵሉ ግዜ ይሓይሽ።",
    "እግዚአብሔርን መታዘዝ ሁልጊዜ ይሻላል።", "prophet"),
]

BOOK_JONAH = {
    "slug": "jonah_and_the_big_fish",
    "title_en": "Jonah and the Big Fish",
    "title_ti": "ዮናስን እቲ ዓቢ ዓሳን",
    "title_am": "ዮናስና ታላቁ ዓሣ",
    "verse": "Jonah 1-3",
    "cover_ill": "fish",
    "scenes": JONAH,
}



# ============================================================
# BOOK 7 — THE GOOD SAMARITAN
# ============================================================
SAMARITAN = [
 SC("One day Jesus told a special story.",
    "ሓደ መዓልቲ የሱስ ፍልይቲ ዛንታ ነገረ።",
    "አንድ ቀን ኢየሱስ ልዩ ታሪክ ተናገረ።", "prophet"),
 SC("It was about being a good neighbor.",
    "ብዛዕባ ሕያዋይ ጐረቤት ምዃን ነበረ።",
    "ስለ ደግ ጎረቤት መሆን ነበረ።", "prophet"),
 SC("A man was walking on a lonely road.",
    "ሓደ ሰብ ኣብ ጽምዋ መገዲ ይኸይድ ነበረ።",
    "አንድ ሰው በምድረ በዳ መንገድ ይሄድ ነበር።", "hills"),
 SC("The road went over rocky hills.",
    "እታ መገዲ ብኣኻውሕ ኣሽንዳ ትሓልፍ ነበረት።",
    "መንገዱ በዓለታማ ኮረብቶች ያልፍ ነበር።", "hills"),
 SC("Suddenly robbers jumped out.",
    "ብድንገት ከተርቲ ወጹ።",
    "ድንገት ዘራፊዎች ወጡ።", "hills"),
 SC("They hurt the poor man.",
    "ነቲ ድኻ ሰብ ጐድእዎ።",
    "ደሃዩን ሰው ጎዱት።", "hills"),
 SC("They took all he had.",
    "ዘለዎ ዅሉ ወሰዱ።",
    "ያለውን ሁሉ ወሰዱ።", "hills"),
 SC("They left him lying on the road.",
    "ኣብ መገዲ ደቂሱ ገደፍዎ።",
    "በመንገዱ ላይ ተኝቶ ተዉት።", "hills"),
 SC("The man was hurt and could not move.",
    "እቲ ሰብ ተጐዲኡ ኪንቀሳቐስ ኣይከኣለን።",
    "ሰውየው ተጎድቶ መንቀሳቀስ አልቻለም።", "hills"),
 SC("He needed someone to help him.",
    "ዚሕግዞ ሰብ የድልዮ ነበረ።",
    "የሚረዳው ሰው ያስፈልገው ነበር።", "hills"),
 SC("Soon a priest came down the road.",
    "ድሕሪ ቕሩብ ሓደ ኻህን በታ መገዲ መጸ።",
    "ወዲያውም አንድ ካህን በመንገዱ መጣ።", "temple"),
 SC("He saw the hurt man.",
    "ነቲ ዝተጐድአ ሰብ ረኣዮ።",
    "የተጎዳውን ሰው አየ።", "temple"),
 SC("But he walked by on the other side.",
    "ግናኸ በቲ ሓደ ሸነኽ ሓሊፉ ኸደ።",
    "ነገር ግን በሌላው ጎን አልፎ ሄደ።", "temple"),
 SC("He did not stop to help.",
    "ኪሕግዝ ደው ኣይበለን።",
    "ሊረዳ አልቆመም።", "temple"),
 SC("Then another man came along.",
    "ሽዑ ኻልእ ሰብ መጸ።",
    "ከዚያም ሌላ ሰው መጣ።", "hills"),
 SC("He also saw the hurt man.",
    "ንሱ እውን ነቲ ዝተጐድአ ሰብ ረኣዮ።",
    "እርሱም የተጎዳውን ሰው አየ።", "hills"),
 SC("But he hurried past too.",
    "ንሱ እውን ተቐላጢፉ ሓለፈ።",
    "እርሱም ፈጥኖ አለፈ።", "hills"),
 SC("The poor man was still alone.",
    "እቲ ድኻ ሰብ ገና በይኑ ነበረ።",
    "ደሃዩ ሰው አሁንም ብቻውን ነበረ።", "hills"),
 SC("Then a Samaritan came near.",
    "ሽዑ ሓደ ሳምራዊ ቀረበ።",
    "ከዚያም አንድ ሳምራዊ ቀረበ።", "hills"),
 SC("Many people did not like Samaritans.",
    "ብዙሓት ሰባት ንሳምራውያን ኣይፈትውዎምን።",
    "ብዙ ሰዎች ሳምራውያንን አይወዱም ነበር።", "hills"),
 SC("But this man had a kind heart.",
    "እዚ ሰብ ግና ሕያዋይ ልቢ ነበሮ።",
    "ይህ ሰው ግን ደግ ልብ ነበረው።", "hills"),
 SC("He stopped when he saw the man.",
    "ነቲ ሰብ ምስ ረኣዮ ደው በለ።",
    "ሰውየውን ባየ ጊዜ ቆመ።", "hills"),
 SC("His heart was full of pity.",
    "ልቡ ብድንጋጸ መልአ።",
    "ልቡ በርኅራኄ ተሞላ።", "hills"),
 SC("He knelt down beside the man.",
    "ኣብ ጥቓ እቲ ሰብ ተምበርከኸ።",
    "በሰውየው አጠገብ ተንበረከከ።", "heal"),
 SC("He cleaned the man's wounds.",
    "ንቝስሉ ኣጽረዮ።",
    "ቁስሉን አጸዳ።", "heal"),
 SC("He gently wrapped them up.",
    "ብህዱእ ጠቕለሎ።",
    "በቀስታ ጠቀለለው።", "heal"),
 SC("He gave the man water to drink.",
    "ንሰብኣይ ማይ ኪሰቲ ሃቦ።",
    "ሰውየውን የሚጠጣ ውኃ ሰጠው።", "heal"),
 SC("Then he lifted him onto his donkey.",
    "ሽዑ ኣብ ኣድጉ ኣደየቦ።",
    "ከዚያም በአህያው ላይ አወጣው።", "hills"),
 SC("He walked beside him all the way.",
    "ኵሉ መገዲ ኣብ ጐድኑ ኸደ።",
    "መንገዱን ሁሉ በጎኑ ሄደ።", "hills"),
 SC("He took him to an inn to rest.",
    "ኪዓርፍ ናብ ሆቴል ወሰዶ።",
    "ያርፍ ዘንድ ወደ ማደሪያ ወሰደው።", "temple"),
 SC("The Samaritan cared for him all night.",
    "እቲ ሳምራዊ ምሉእ ለይቲ ኣላዮ።",
    "ሳምራዊው ሌሊቱን ሙሉ ተንከባከበው።", "heal"),
 SC("In the morning he had to leave.",
    "ንግሆ ኪኸይድ ነበሮ።",
    "በጠዋት መሄድ ነበረበት።", "temple"),
 SC("He gave money to the innkeeper.",
    "ንበዓል ሆቴል ገንዘብ ሃቦ።",
    "ለማደሪያው ባለቤት ገንዘብ ሰጠ።", "temple"),
 SC("'Please care for this man,' he said.",
    "'በጃኻ ነዚ ሰብ ኣላዮ' በለ።",
    "'እባክህ ይህን ሰው ተንከባከበው' አለ።", "temple"),
 SC("'I will pay for anything more.'",
    "'ዝበዝሐ ኵሉ ኽኸፍል እየ።'",
    "'ተጨማሪውን ሁሉ እከፍላለሁ።'", "temple"),
 SC("The Samaritan showed true love.",
    "እቲ ሳምራዊ ናይ ሓቂ ፍቕሪ ኣርኣየ።",
    "ሳምራዊው እውነተኛ ፍቅር አሳየ።", "heal"),
 SC("Then Jesus asked a question.",
    "ሽዑ የሱስ ሕቶ ሓተተ።",
    "ከዚያም ኢየሱስ ጥያቄ ጠየቀ።", "prophet"),
 SC("'Who was a good neighbor?'",
    "'ሕያዋይ ጐረቤት መን ነበረ?'",
    "'ደግ ጎረቤት ማን ነበረ?'", "prophet"),
 SC("'The one who showed mercy,' they said.",
    "'እቲ ምሕረት ዘርኣየ' በሉ።",
    "'ምሕረት ያሳየው' አሉ።", "prophet"),
 SC("Jesus said, 'Go and do the same.'",
    "የሱስ 'ኪድ ንስኻ እውን ከምኡ ግበር' በለ።",
    "ኢየሱስ 'ሂድ አንተም እንዲሁ አድርግ' አለ።", "prophet"),
 SC("We can help anyone in need.",
    "ንዝዀነ ዘድልዮ ሰብ ክንሕግዝ ንኽእል።",
    "የተቸገረውን ሁሉ መርዳት እንችላለን።", "heal"),
 SC("Even a stranger can be our neighbor.",
    "ጓና እኳ ጐረቤትና ኪኸውን ይኽእል።",
    "እንግዳም ጎረቤታችን ሊሆን ይችላል።", "heal"),
 SC("Kindness makes God happy.",
    "ሕያውነት ንኣምላኽ የሕጕሶ።",
    "ደግነት እግዚአብሔርን ያስደስተዋል።", "heal"),
 SC("Love and help everyone, even a stranger.",
    "ንዅሉ ኣፍቅርን ሓግዝን፡ ንጓና እኳ።",
    "ሁሉንም ውደድና እርዳ፡ እንግዳንም እንኳ።", "heal"),
]

BOOK_SAMARITAN = {
    "slug": "the_good_samaritan",
    "title_en": "The Good Samaritan",
    "title_ti": "እቲ ሕያዋይ ሳምራዊ",
    "title_am": "ደጉ ሳምራዊ",
    "verse": "Luke 10:25-37",
    "cover_ill": "heal",
    "scenes": SAMARITAN,
}



# ============================================================
# BOOK 8 — THE LOST SHEEP
# ============================================================
LOSTSHEEP = [
 SC("Jesus told a story about a shepherd.",
    "የሱስ ብዛዕባ ሓደ ጓሳ ዛንታ ነገረ።",
    "ኢየሱስ ስለ አንድ እረኛ ታሪክ ተናገረ።", "sheep"),
 SC("The shepherd had one hundred sheep.",
    "እቲ ጓሳ ሚእቲ በጊዕ ነበሮ።",
    "እረኛው መቶ በጎች ነበሩት።", "sheep"),
 SC("He loved every single one.",
    "ንነፍሲ ወከፍ የፍቅር ነበረ።",
    "እያንዳንዷን ይወድ ነበር።", "sheep"),
 SC("He knew all of them by name.",
    "ንዅለን ብስመን ይፈልጠን ነበረ።",
    "ሁሉንም በስም ያውቃቸው ነበር።", "sheep"),
 SC("Each morning he led them to grass.",
    "ኵሉ ንግሆ ናብ ሳዕሪ ይመርሐን ነበረ።",
    "በየጠዋቱ ወደ ሣር ይመራቸው ነበር።", "sheep"),
 SC("He led them to cool water.",
    "ናብ ዝሑል ማይ ይመርሐን ነበረ።",
    "ወደ ቀዝቃዛ ውኃ ይመራቸው ነበር።", "sheep"),
 SC("The sheep felt safe with him.",
    "እተን ኣባጊዕ ምስኡ ውሑሳት ኰይኑ ተሰምዐን።",
    "በጎቹ ከእርሱ ጋር ደኅንነት ተሰማቸው።", "sheep"),
 SC("Each evening he counted them.",
    "ኵሉ ምሸት ይቘጽረን ነበረ።",
    "በየምሽቱ ይቆጥራቸው ነበር።", "sheep"),
 SC("One, two, three, he counted.",
    "ሓደ፡ ክልተ፡ ሰለስተ፡ ይቘጽር ነበረ።",
    "አንድ፡ ሁለት፡ ሦስት፡ ይቆጥር ነበር።", "sheep"),
 SC("One night a sheep was missing!",
    "ሓደ ለይቲ ሓንቲ በጊዕ ጠፍአት!",
    "አንድ ሌሊት አንዷ በግ ጠፋች!", "sheep"),
 SC("He counted only ninety-nine.",
    "ተስዓን ትሽዓተን ጥራይ ቈጸረ።",
    "ዘጠና ዘጠኝ ብቻ ቆጠረ።", "sheep"),
 SC("One little sheep was lost.",
    "ሓንቲ ንእሽቶ በጊዕ ጠፊኣ ነበረት።",
    "አንዲት ትንሽ በግ ጠፍታ ነበር።", "sheep"),
 SC("The shepherd was worried.",
    "እቲ ጓሳ ተጨነቐ።",
    "እረኛው ተጨነቀ።", "sheep"),
 SC("He loved that little sheep.",
    "ነታ ንእሽቶ በጊዕ የፍቅራ ነበረ።",
    "ያችን ትንሽ በግ ይወዳት ነበር።", "sheep"),
 SC("He left the ninety-nine safe.",
    "ነተን ተስዓን ትሽዓተን ብደሓን ገደፈን።",
    "ዘጠና ዘጠኙን በደኅና ተዋቸው።", "sheep"),
 SC("He went out into the dark night.",
    "ናብ ጸልማት ለይቲ ወጸ።",
    "ወደ ጨለማ ሌሊት ወጣ።", "hills"),
 SC("He searched over the hills.",
    "ኣብ ኣኽራናት ደለያ።",
    "በኮረብቶቹ ላይ ፈለጋት።", "hills"),
 SC("He looked behind the rocks.",
    "ኣብ ድሕሪ ኣኻውሕ ጠመተ።",
    "ከዓለቶቹ ጀርባ ተመለከተ።", "hills"),
 SC("He called the sheep by name.",
    "ነታ በጊዕ ብስማ ጸውዓ።",
    "በጓን በስሟ ጠራት።", "hills"),
 SC("He searched high and low.",
    "ኣብ ላዕልን ታሕትን ደለያ።",
    "ከፍ ዝቅ ብሎ ፈለጋት።", "hills"),
 SC("He did not give up.",
    "ተስፋ ኣይቈረጸን።",
    "ተስፋ አልቆረጠም።", "hills"),
 SC("The night was cold and windy.",
    "እታ ለይቲ ቁርን ንፋስን ነበራ።",
    "ሌሊቱ ብርድና ነፋሻማ ነበር።", "hills"),
 SC("But the shepherd kept looking.",
    "እቲ ጓሳ ግና ኪደሊ ቀጸለ።",
    "እረኛው ግን መፈለጉን ቀጠለ።", "hills"),
 SC("Then he heard a soft cry.",
    "ሽዑ ህዱእ ብኽያት ሰምዐ።",
    "ከዚያም ለስላሳ ጩኸት ሰማ።", "hills"),
 SC("It was the little lost sheep!",
    "እታ ጠፋኢት ንእሽቶ በጊዕ እያ ነበረት!",
    "የጠፋችው ትንሿ በግ ነበረች!", "sheep"),
 SC("She was stuck and afraid.",
    "ተታሒዛን ፈሪሓን ነበረት።",
    "ተይዛና ፈርታ ነበር።", "sheep"),
 SC("The shepherd ran to her.",
    "እቲ ጓሳ ናብኣ ጐየየ።",
    "እረኛው ወደ እርሷ ሮጠ።", "sheep"),
 SC("He was so glad to find her.",
    "ስለ ዝረኸባ ኣዝዩ ተሓጐሰ።",
    "ስላገኛት እጅግ ተደሰተ።", "sheep"),
 SC("He gently picked her up.",
    "ብህዱእ ኣልዓላ።",
    "በቀስታ አነሳት።", "sheep"),
 SC("He held her close and warm.",
    "ብቐረባን ብምዉቕን ሓቚፉ ሓዛ።",
    "ቀርባ አድርጎ በሙቀት ያዛት።", "sheep"),
 SC("He put her on his shoulders.",
    "ኣብ መንኩቡ ኣቐመጣ።",
    "በጫንቃው ላይ አኖራት።", "sheep"),
 SC("He carried her all the way home.",
    "ኵሉ መገዲ ጾይሩ ናብ ገዛ ኣምጽኣ።",
    "መንገዱን ሁሉ ተሸክሞ ወደ ቤት አመጣት።", "sheep"),
 SC("His heart was full of joy.",
    "ልቡ ብሓጐስ መልአ።",
    "ልቡ በደስታ ተሞላ።", "sheep"),
 SC("He called his friends together.",
    "ንኣዕሩኹ ብሓባር ጸውዖም።",
    "ጓደኞቹን አብረው ጠራ።", "sheep"),
 SC("'Rejoice with me!' he said.",
    "'ምሳይ ተሓጐሱ!' በለ።",
    "'ከእኔ ጋር ደስ ይበላችሁ!' አለ።", "sheep"),
 SC("'I found my lost sheep!'",
    "'ጠፋኢት በጊዐይ ረኺበያ!'",
    "'የጠፋችውን በጌን አገኘኋት!'", "sheep"),
 SC("Everyone was happy together.",
    "ኵሎም ብሓባር ተሓጐሱ።",
    "ሁሉም አብረው ተደሰቱ።", "children"),
 SC("Jesus said God is like that shepherd.",
    "የሱስ 'ኣምላኽ ከምዚ ጓሳ እዩ' በለ።",
    "ኢየሱስ 'እግዚአብሔር እንደዚያ እረኛ ነው' አለ።", "prophet"),
 SC("God looks for each one of us.",
    "ኣምላኽ ንነፍሲ ወከፍና ይደልየና።",
    "እግዚአብሔር እያንዳንዳችንን ይፈልገናል።", "prophet"),
 SC("You are precious to God.",
    "ንኣምላኽ ክቡር ኢኻ።",
    "ለእግዚአብሔር ውድ ነህ።", "star"),
 SC("He will never stop loving you.",
    "ከቶ ምፍቃርካ ኣየቋርጽን።",
    "ከቶ መውደድህን አያቆምም።", "star"),
 SC("God rejoices when we come to Him.",
    "ናብኡ ክንመጽእ ከለና ኣምላኽ ይሕጐስ።",
    "ወደ እርሱ ስንመጣ እግዚአብሔር ደስ ይሰኛል።", "prophet"),
 SC("You are always welcome in His arms.",
    "ኵሉ ግዜ ኣብ ሕቝፉ ተቐባልነት ኣለካ።",
    "ሁልጊዜ በእቅፉ ተቀባይነት አለህ።", "sheep"),
]

BOOK_LOSTSHEEP = {
    "slug": "the_lost_sheep",
    "title_en": "The Lost Sheep",
    "title_ti": "እታ ጠፋኢት በጊዕ",
    "title_am": "የጠፋችው በግ",
    "verse": "Luke 15:3-7",
    "cover_ill": "sheep",
    "scenes": LOSTSHEEP,
}



# ============================================================
# BOOK 9 — ZACCHAEUS IN THE TREE
# ============================================================
ZACCHAEUS = [
 SC("In a town called Jericho lived a man.",
    "ኣብ ኢያሪኮ እትብሃል ከተማ ሓደ ሰብ ይነብር ነበረ።",
    "ኢያሪኮ በምትባል ከተማ አንድ ሰው ይኖር ነበር።", "temple"),
 SC("His name was Zacchaeus.",
    "ስሙ ዘኬዎስ ነበረ።",
    "ስሙ ዘኬዎስ ነበረ።", "temple"),
 SC("Zacchaeus was a tax collector.",
    "ዘኬዎስ ተቐባል ቀረጽ ነበረ።",
    "ዘኬዎስ የቀረጥ ሰብሳቢ ነበረ።", "temple"),
 SC("He collected money from the people.",
    "ካብ ህዝቢ ገንዘብ ይእክብ ነበረ።",
    "ከሕዝቡ ገንዘብ ይሰበስብ ነበር።", "temple"),
 SC("Sometimes he took too much.",
    "ሓድሓደ ግዜ ካብ ግቡእ ንላዕሊ ይወስድ ነበረ።",
    "አንዳንዴ ከሚገባው በላይ ይወስድ ነበር።", "temple"),
 SC("The people did not like him.",
    "ህዝቢ ኣይፈትውዎን ነበሩ።",
    "ሕዝቡ አይወዱትም ነበር።", "hills"),
 SC("Zacchaeus was a very short man.",
    "ዘኬዎስ ኣዝዩ ሓጺር ሰብ ነበረ።",
    "ዘኬዎስ እጅግ አጭር ሰው ነበረ።", "temple"),
 SC("One day Jesus came to town.",
    "ሓደ መዓልቲ የሱስ ናብ ከተማ መጸ።",
    "አንድ ቀን ኢየሱስ ወደ ከተማ መጣ።", "prophet"),
 SC("Everyone wanted to see Jesus.",
    "ኵሉ ንየሱስ ኪርኢ ደለየ።",
    "ሁሉም ኢየሱስን ማየት ፈለገ።", "prophet"),
 SC("A big crowd filled the streets.",
    "ብዙሕ ህዝቢ ንኣደባባያት መልኦ።",
    "ብዙ ሕዝብ አደባባዮቹን ሞላ።", "children"),
 SC("Zacchaeus wanted to see Jesus too.",
    "ዘኬዎስ እውን ንየሱስ ኪርኢ ደለየ።",
    "ዘኬዎስም ኢየሱስን ማየት ፈለገ።", "temple"),
 SC("But he was too short to see.",
    "ሓጺር ስለ ዝነበረ ግና ኪርኢ ኣይከኣለን።",
    "አጭር ስለ ነበር ግን ማየት አልቻለም።", "temple"),
 SC("The crowd was too tall for him.",
    "እቲ ህዝቢ ንዕኡ ኣዝዩ ነዊሕ ነበረ።",
    "ሕዝቡ ለእርሱ በጣም ረጅም ነበር።", "children"),
 SC("He could not see over their heads.",
    "ካብ ልዕሊ ኣርእስቶም ኪርኢ ኣይከኣለን።",
    "ከራሳቸው በላይ ማየት አልቻለም።", "hills"),
 SC("Then he had a good idea.",
    "ሽዑ ጽቡቕ ሓሳብ ረኸበ።",
    "ከዚያም ጥሩ ሐሳብ አገኘ።", "tree"),
 SC("He ran ahead of the crowd.",
    "ቅድሚ እቲ ህዝቢ ጐየየ።",
    "ከሕዝቡ ቀድሞ ሮጠ።", "tree"),
 SC("He found a big sycamore tree.",
    "ዓባይ ኦም ሳግላ ረኸበ።",
    "ትልቅ የሾላ ዛፍ አገኘ።", "tree"),
 SC("Zacchaeus climbed up the tree.",
    "ዘኬዎስ ናብቲ ኦም ደየበ።",
    "ዘኬዎስ ዛፉ ላይ ወጣ።", "tree"),
 SC("He climbed higher and higher.",
    "ንላዕሊ ንላዕሊ ደየበ።",
    "ከፍ ከፍ ብሎ ወጣ።", "tree"),
 SC("Now he could see very well.",
    "ሕጂ ጽቡቕ ጌሩ ኪርኢ ኸኣለ።",
    "አሁን በደንብ ማየት ቻለ።", "tree"),
 SC("He waited on the branch.",
    "ኣብቲ ጨንፈር ተጸበየ።",
    "በቅርንጫፉ ላይ ጠበቀ።", "tree"),
 SC("Soon Jesus came walking by.",
    "ድሕሪ ቕሩብ የሱስ እናኸደ መጸ።",
    "ወዲያውም ኢየሱስ እየሄደ መጣ።", "prophet"),
 SC("Jesus stopped under the tree.",
    "የሱስ ኣብ ትሕቲ እቲ ኦም ደው በለ።",
    "ኢየሱስ ከዛፉ ሥር ቆመ።", "tree"),
 SC("He looked up at Zacchaeus.",
    "ናብ ዘኬዎስ ቋሕ በለ።",
    "ወደ ዘኬዎስ ቀና አለ።", "tree"),
 SC("'Zacchaeus, come down!' said Jesus.",
    "'ዘኬዎስ ውረድ!' በለ የሱስ።",
    "'ዘኬዎስ ውረድ!' አለ ኢየሱስ።", "prophet"),
 SC("Jesus knew his name!",
    "የሱስ ስሙ ይፈልጦ ነበረ!",
    "ኢየሱስ ስሙን ያውቅ ነበር!", "prophet"),
 SC("'Today I will visit your house.'",
    "'ሎሚ ናብ ቤትካ ኽበጽሕ እየ።'",
    "'ዛሬ ወደ ቤትህ እጎበኛለሁ።'", "prophet"),
 SC("Zacchaeus was so surprised!",
    "ዘኬዎስ ኣዝዩ ተገረመ!",
    "ዘኬዎስ እጅግ ተገረመ!", "temple"),
 SC("He climbed down quickly.",
    "ቀልጢፉ ወረደ።",
    "ፈጥኖ ወረደ።", "tree"),
 SC("He was full of joy.",
    "ብሓጐስ መልአ።",
    "በደስታ ተሞላ።", "temple"),
 SC("He welcomed Jesus to his home.",
    "ንየሱስ ናብ ቤቱ ተቐበሎ።",
    "ኢየሱስን ወደ ቤቱ ተቀበለ።", "temple"),
 SC("Being with Jesus changed his heart.",
    "ምስ የሱስ ምዃን ልቡ ለወጦ።",
    "ከኢየሱስ ጋር መሆን ልቡን ለወጠው።", "prophet"),
 SC("Zacchaeus wanted to do right.",
    "ዘኬዎስ ቅኑዕ ኪገብር ደለየ።",
    "ዘኬዎስ ትክክለኛ ማድረግ ፈለገ።", "temple"),
 SC("'I will give to the poor,' he said.",
    "'ንድኻታት ክህብ እየ' በለ።",
    "'ለድሆች እሰጣለሁ' አለ።", "temple"),
 SC("'I will give back what I took.'",
    "'ዝወሰድክዎ ኽመልስ እየ።'",
    "'የወሰድኩትን እመልሳለሁ።'", "temple"),
 SC("He gave back even more than before.",
    "ካብ ቀደም ንላዕሊ መለሰ።",
    "ከበፊቱ በላይ መለሰ።", "temple"),
 SC("Jesus was happy with Zacchaeus.",
    "የሱስ በዘኬዎስ ተሓጐሰ።",
    "ኢየሱስ በዘኬዎስ ተደሰተ።", "prophet"),
 SC("'Today salvation came to this house.'",
    "'ሎሚ ናብዚ ቤት ምድሓን መጸ።'",
    "'ዛሬ ወደዚህ ቤት ደኅንነት መጣ።'", "prophet"),
 SC("Zacchaeus was a new man.",
    "ዘኬዎስ ሓድሽ ሰብ ኰነ።",
    "ዘኬዎስ አዲስ ሰው ሆነ።", "temple"),
 SC("Jesus loves everyone, big or small.",
    "የሱስ ንዅሉ የፍቅር፡ ዓብዪ ኾነ ንእሽቶ።",
    "ኢየሱስ ሁሉንም ይወዳል፡ ትልቅም ትንሽም።", "prophet"),
 SC("Jesus can change any heart.",
    "የሱስ ንዝዀነ ልቢ ኪልውጦ ይኽእል።",
    "ኢየሱስ ማንኛውንም ልብ ሊለውጠው ይችላል።", "prophet"),
 SC("No one is too lost for His love.",
    "ንፍቕሩ ኣዝዩ ዝጠፍአ ሰብ የልቦን።",
    "ለፍቅሩ በጣም የጠፋ ሰው የለም።", "star"),
 SC("Jesus can change your heart too.",
    "የሱስ ንልብኻ እውን ኪልውጦ ይኽእል።",
    "ኢየሱስ ልብህንም ሊለውጠው ይችላል።", "prophet"),
 SC("Let Jesus be your friend today.",
    "ሎሚ የሱስ ፈታዊኻ ይኹን።",
    "ዛሬ ኢየሱስ ወዳጅህ ይሁን።", "prophet"),
]

BOOK_ZACCHAEUS = {
    "slug": "zacchaeus_in_the_tree",
    "title_en": "Zacchaeus in the Tree",
    "title_ti": "ዘኬዎስ ኣብ ኦም",
    "title_am": "ዘኬዎስ በዛፉ ላይ",
    "verse": "Luke 19:1-10",
    "cover_ill": "tree",
    "scenes": ZACCHAEUS,
}



# ============================================================
# BOOK 10 — JESUS BLESSES THE CHILDREN
# ============================================================
BLESSCHILDREN = [
 SC("Jesus loved to help many people.",
    "የሱስ ንብዙሓት ሰባት ኪሕግዝ የፍቅር ነበረ።",
    "ኢየሱስ ብዙ ሰዎችን መርዳት ይወድ ነበር።", "prophet"),
 SC("He walked from town to town.",
    "ካብ ከተማ ናብ ከተማ ይኸይድ ነበረ።",
    "ከከተማ ወደ ከተማ ይሄድ ነበር።", "hills"),
 SC("He taught about God's love.",
    "ብዛዕባ ፍቕሪ ኣምላኽ ይምህር ነበረ።",
    "ስለ እግዚአብሔር ፍቅር ያስተምር ነበር።", "prophet"),
 SC("Everywhere Jesus went, crowds came.",
    "የሱስ ናብ ዝኸዶ ኵሉ ህዝቢ ይመጽእ ነበረ።",
    "ኢየሱስ በሄደበት ሁሉ ሕዝብ ይመጣ ነበር።", "children"),
 SC("One day some parents came to Him.",
    "ሓደ መዓልቲ ገለ ወለዲ ናብኡ መጹ።",
    "አንድ ቀን አንዳንድ ወላጆች ወደ እርሱ መጡ።", "children"),
 SC("They brought their little children.",
    "ንንኣሽቱ ደቆም ኣምጽእዎም።",
    "ትንንሽ ልጆቻቸውን አመጡ።", "children"),
 SC("The children were happy and excited.",
    "እቶም ቆልዑ ሕጉሳትን ሕቡናትን ነበሩ።",
    "ልጆቹ ደስተኞችና ጓጉ ነበሩ።", "children"),
 SC("The parents wanted a blessing.",
    "እቶም ወለዲ በረኸት ደለዩ።",
    "ወላጆቹ በረከት ፈለጉ።", "children"),
 SC("They wanted Jesus to bless them.",
    "የሱስ ኪባርኾም ደለዩ።",
    "ኢየሱስ ሊባርካቸው ፈለጉ።", "prophet"),
 SC("But the disciples said, 'Stop!'",
    "እቶም ደቀ መዛሙርቲ ግና 'ጠጠው በሉ!' በሉ።",
    "ደቀ መዛሙርቱ ግን 'ቁሙ!' አሉ።", "hills"),
 SC("'Jesus is too busy for children.'",
    "'የሱስ ንቘልዑ ግዜ የብሉን።'",
    "'ኢየሱስ ለልጆች ጊዜ የለውም።'", "hills"),
 SC("They tried to send them away.",
    "ኪሰጕዎም ፈተኑ።",
    "ሊያባርሯቸው ሞከሩ።", "hills"),
 SC("The children felt sad.",
    "እቶም ቆልዑ ጐሃዩ።",
    "ልጆቹ አዘኑ።", "children"),
 SC("But Jesus saw what was happening.",
    "የሱስ ግና እቲ ዚኸውን ዘሎ ረኣዮ።",
    "ኢየሱስ ግን የሚሆነውን አየ።", "prophet"),
 SC("Jesus was not too busy.",
    "የሱስ ግዜ ዝሰኣነ ኣይነበረን።",
    "ኢየሱስ ጊዜ ያጣ አልነበረም።", "prophet"),
 SC("'Let the children come to me!'",
    "'ቆልዑ ናባይ ይምጽኡ!'",
    "'ልጆች ወደ እኔ ይምጡ!'", "prophet"),
 SC("'Do not stop them,' Jesus said.",
    "'ኣይትኸልክልዎም' በለ የሱስ።",
    "'አትከልክሏቸው' አለ ኢየሱስ።", "prophet"),
 SC("The children ran to Jesus.",
    "እቶም ቆልዑ ናብ የሱስ ጐየዩ።",
    "ልጆቹ ወደ ኢየሱስ ሮጡ።", "children"),
 SC("They gathered all around Him.",
    "ኣብ ዙርያኡ ተኣከቡ።",
    "በዙሪያው ተሰበሰቡ።", "children"),
 SC("Jesus smiled with great love.",
    "የሱስ ብዓቢ ፍቕሪ ፍሽኽ በለ።",
    "ኢየሱስ በታላቅ ፍቅር ፈገግ አለ።", "prophet"),
 SC("He was happy to see them.",
    "ብምርኣዮም ተሓጐሰ።",
    "ባያቸው ደስ አለው።", "prophet"),
 SC("He took the little ones in His arms.",
    "ንንኣሽቱ ኣብ ኢዱ ሓቘፎም።",
    "ትንንሾቹን በእቅፉ ያዛቸው።", "children"),
 SC("He held them gently and close.",
    "ብህዱእን ብቐረባን ሓቘፎም።",
    "በቀስታና ቀርባ አድርጎ ያዛቸው።", "children"),
 SC("He listened to what they said.",
    "ዝበልዎ ሰምዖም።",
    "የሚሉትን አዳመጣቸው።", "prophet"),
 SC("The children laughed with joy.",
    "እቶም ቆልዑ ብሓጐስ ሰሓቑ።",
    "ልጆቹ በደስታ ሳቁ።", "children"),
 SC("Jesus put His hands on them.",
    "የሱስ ኣእዳዉ ኣንበረሎም።",
    "ኢየሱስ እጆቹን ጫነባቸው።", "prophet"),
 SC("He blessed each and every child.",
    "ንነፍሲ ወከፍ ቆልዓ ባረኾ።",
    "እያንዳንዱን ልጅ ባረከ።", "children"),
 SC("'God loves you very much,' He said.",
    "'ኣምላኽ ኣዝዩ የፍቅረኩም' በለ።",
    "'እግዚአብሔር እጅግ ይወዳችኋል' አለ።", "prophet"),
 SC("Then Jesus taught the grown-ups.",
    "ሽዑ የሱስ ንዓበይቲ መሃሮም።",
    "ከዚያም ኢየሱስ ትልልቆቹን አስተማራቸው።", "prophet"),
 SC("'You must be like little children.'",
    "'ከም ንኣሽቱ ቆልዑ ክትኰኑ ኣለኩም።'",
    "'እንደ ትንንሽ ልጆች መሆን አለባችሁ።'", "prophet"),
 SC("'Trust God with a simple heart.'",
    "'ብቐሊል ልቢ ኣብ ኣምላኽ ተወከሉ።'",
    "'በቀላል ልብ በእግዚአብሔር ታመኑ።'", "prophet"),
 SC("Children believe with open hearts.",
    "ቆልዑ ብ ክፉት ልቢ ይኣምኑ።",
    "ልጆች በክፍት ልብ ያምናሉ።", "children"),
 SC("They trust and love so freely.",
    "ብናጻ ይኣምኑን የፍቅሩን።",
    "በነጻነት ያምናሉ ይወዳሉም።", "children"),
 SC("Jesus wants us to trust like that.",
    "የሱስ ከምኡ ኽንኣምን ይደሊ።",
    "ኢየሱስ እንደዚያ እንድናምን ይፈልጋል።", "prophet"),
 SC("The kingdom of God is for children.",
    "መንግስቲ ኣምላኽ ናይ ቈልዑ እያ።",
    "የእግዚአብሔር መንግሥት የልጆች ናት።", "prophet"),
 SC("Every child is special to Jesus.",
    "ነፍሲ ወከፍ ቆልዓ ንየሱስ ፍሉይ እዩ።",
    "እያንዳንዱ ልጅ ለኢየሱስ ልዩ ነው።", "children"),
 SC("He knows you and loves you.",
    "ይፈልጠካን የፍቅረካን።",
    "ያውቅሃል ይወድሃልም።", "prophet"),
 SC("You can come to Jesus any time.",
    "ኣብ ዝዀነ ግዜ ናብ የሱስ ክትመጽእ ትኽእል።",
    "በማንኛውም ጊዜ ወደ ኢየሱስ መምጣት ትችላለህ።", "prophet"),
 SC("You can talk to Him in prayer.",
    "ብጸሎት ክትዛረቦ ትኽእል።",
    "በጸሎት ልታናግረው ትችላለህ።", "pray"),
 SC("Jesus is always near to you.",
    "የሱስ ኵሉ ግዜ ቀረባኻ እዩ።",
    "ኢየሱስ ሁልጊዜ ቅርብህ ነው።", "prophet"),
 SC("His love for you never ends.",
    "ፍቕሩ ንዓኻ ኸቶ ኣይውዳእን።",
    "ላንተ ያለው ፍቅር ከቶ አያልቅም።", "star"),
 SC("Jesus loves children and welcomes them.",
    "የሱስ ንቘልዑ የፍቅሮምን ይቕበሎምን።",
    "ኢየሱስ ልጆችን ይወዳል ይቀበላቸውማል።", "children"),
 SC("You are loved by Jesus today.",
    "ሎሚ ብየሱስ ፍቁር ኢኻ።",
    "ዛሬ በኢየሱስ የተወደድክ ነህ።", "children"),
]

BOOK_BLESSCHILDREN = {
    "slug": "jesus_blesses_the_children",
    "title_en": "Jesus Blesses the Children",
    "title_ti": "የሱስ ንቈልዑ ይባርኽ",
    "title_am": "ኢየሱስ ልጆችን ይባርካል",
    "verse": "Mark 10:13-16",
    "cover_ill": "children",
    "scenes": BLESSCHILDREN,
}


# ============================================================
# ALL 10 BOOKS
# ============================================================
BOOKS = [
    BOOK_NOAH,
    BOOK_JOSEPH,
    BOOK_MOSES,
    BOOK_DAVID,
    BOOK_DANIEL,
    BOOK_JONAH,
    BOOK_SAMARITAN,
    BOOK_LOSTSHEEP,
    BOOK_ZACCHAEUS,
    BOOK_BLESSCHILDREN,
]
