# -*- coding: utf-8 -*-
"""
Story + activity data for the English–Tigrigna Bible Activity Books.
Series author: Daniel Tesfamariam.

Each entry in BOOKS is consumed by generate_books.build_book().
The Tigrigna is prepared carefully but MUST be proofread by a native speaker
before commercial publication.
"""

# Shared secret-code alphabet used by every book's page 33.
# A compact A=1..Z=26 cipher so any English word can be encoded.
_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
CODE_KEY = [(str(i + 1), ch) for i, ch in enumerate(_ALPHABET)]
LETTER2NUM = {ch: str(i + 1) for i, ch in enumerate(_ALPHABET)}


def code(line1, line2, hint_ti):
    # Show a key only for the letters actually used (keeps it a real puzzle),
    # sorted by their code number.
    used = sorted({ch for ch in (line1 + line2) if ch.isalpha()},
                  key=lambda c: int(LETTER2NUM[c]))
    key = [(LETTER2NUM[c], c) for c in used]
    return {"key": key, "letter2num": LETTER2NUM,
            "line1": line1, "line2": line2, "hint_ti": hint_ti}


BOOKS = []


# ===========================================================================
# BOOK 2 — Daniel and the Lions' Den
# ===========================================================================
BOOKS.append({
  "slug": "02-daniel",
  "icon": "lion", "icon2": "scroll",
  "title_en": "Daniel and the Lions' Den",
  "title_ti": "ዳንኤልን ጉድጓድ ኣናብስን",
  "cover_line_en": "A colour-and-learn activity book about prayer, faith and God's protection.",
  "cover_line_ti": "ብዛዕባ ጸሎት፡ እምነትን ዕቝባ ኣምላኽን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("Daniel", "a man who loved and prayed to God.", "ዳንኤል — ንኣምላኽ ዘፍቅርን ዝጽልን ሰብኣይ።"),
    ("King Darius", "the king who liked Daniel.", "ንጉስ ዳርዮስ — ንዳንኤል ዝፈትዎ ንጉስ።"),
    ("The Officials", "jealous men who made a trap.", "እቶም ሹማምንቲ — ቀናእቲ ሰባት፡ መፈንጠራ ዝገበሩ።"),
    ("The Lions", "hungry lions in the den.", "እቶም ኣናብስ — ኣብ ጉድጓድ ዝነበሩ ጥሙያት ኣናብስ።"),
  ],
  "story": [
    {"sub_en":"Daniel Loves God","sub_ti":"ዳንኤል ንኣምላኽ የፍቅር",
     "paras":[
       ("Long ago, Daniel lived far from his home in the land of Babylon. He served King Darius, and he was wise, honest and kind.",
        "ቀደም ዳንኤል ካብ ዓዱ ርሒቑ ኣብ ባቢሎን ይነብር ነበረ። ንንጉስ ዳርዮስ የገልግል ነበረ፡ ጥበበኛ፡ ቅኑዕን ሕያዋይን ከኣ ነበረ።"),
       ("Every day, three times a day, Daniel knelt down by his window and prayed to God. He was never ashamed to pray.",
        "ዳንኤል መዓልታዊ ሰለስተ ሳዕ ኣብ መስኮቱ ተምበርኪኹ ናብ ኣምላኽ ይጽሊ ነበረ። ንኺጽሊ ኸኣ ኣይሓፈረን።"),
       ("The king trusted Daniel so much that he wanted to put him in charge of the whole kingdom.",
        "እቲ ንጉስ ንዳንኤል ኣዝዩ ስለ ዝኣመኖ፡ ኣብ ልዕሊ ብዘሎ መንግስቲ ኪሸሞ ደለየ።"),
     ]},
    {"sub_en":"A Jealous Trap","sub_ti":"ቀናእ መፈንጠራ",
     "paras":[
       ("Some other officials were jealous of Daniel. They could find nothing wrong with him, so they made a sneaky plan.",
        "ገሊኦም ሹማምንቲ ንዳንኤል ቀንኡሉ። ገበን ኪረኽቡሉ ስለ ዘይከኣሉ፡ ተንኮል ዝመልኦ መደብ ገበሩ።"),
       ("They tricked the king into making a new law: for thirty days, no one could pray to anyone except the king. Anyone who disobeyed would be thrown to the lions!",
        "ንንጉስ ኣታሊሎም ሓድሽ ሕጊ ኬውጽእ ገበርዎ፦ ንሰላሳ መዓልቲ ብጀካ ንንጉስ ንዝኾነ ኪጽሊ ኣይፍቀድን። ዝጠሓሰ ናብ ኣናብስ ኪድርበ እዩ!"),
     ]},
    {"sub_en":"Daniel Keeps Praying","sub_ti":"ዳንኤል ምጽላይ ቀጸለ",
     "paras":[
       ("When Daniel heard about the law, he still went home, opened his window, and prayed to God just as he always did. He would not stop praying.",
        "ዳንኤል ብዛዕባ እቲ ሕጊ ምስ ሰምዐ፡ ከምቲ ልማዱ ናብ ቤቱ ኸይዱ መስኮቱ ከፊቱ ናብ ኣምላኽ ጸለየ። ምጽላይ ኣየቋረጸን።"),
       ("The jealous men were watching. They ran to the king and said, 'Daniel is still praying to his God!'",
        "እቶም ቀናእቲ ይዕዘቡ ነበሩ። ናብ ንጉስ ጐይዮም፡ 'ዳንኤል ገና ናብ ኣምላኹ ይጽሊ ኣሎ!' በሉ።"),
     ]},
    {"sub_en":"Into the Den","sub_ti":"ናብ ጉድጓድ",
     "paras":[
       ("The king was very sad, because he liked Daniel. But the law could not be changed. So Daniel was thrown into the den of hungry lions.",
        "እቲ ንጉስ ንዳንኤል ስለ ዝፈትዎ ኣዝዩ ጐሃየ። እቲ ሕጊ ግና ኪልወጥ ኣይከኣለን። ስለዚ ዳንኤል ናብ ጉድጓድ ጥሙያት ኣናብስ ተደርበየ።"),
       ("The king said to Daniel, 'May your God, whom you serve, rescue you!' All night the king could not sleep or eat.",
        "እቲ ንጉስ ንዳንኤል፡ 'እቲ እተገልግሎ ኣምላኽካ የናግፈካ!' በሎ። ንጉስ ምሉእ ለይቲ ኪድቅስ ወይ ኪበልዕ ኣይከኣለን።"),
     ]},
    {"sub_en":"God Shuts the Lions' Mouths","sub_ti":"ኣምላኽ ኣፍ ኣናብስ ዓጸወ",
     "paras":[
       ("Early in the morning the king ran to the den and called out. Daniel answered, 'My God sent his angel and shut the lions' mouths. They have not hurt me!'",
        "ንጉስ ኣንጊሁ ናብቲ ጉድጓድ ጐዪዩ ጸውዐ። ዳንኤል፡ 'ኣምላኸይ መልኣኹ ልኢኹ ኣፍ ኣናብስ ዓጸወ። ኣይጐድኡንን!' ኢሉ መለሰ።"),
       ("The king was overjoyed! He lifted Daniel out, safe and unharmed, because Daniel had trusted in God.",
        "እቲ ንጉስ ኣዝዩ ተሓጐሰ! ዳንኤል ኣብ ኣምላኽ ስለ ዝተኣመነ፡ ጥዑይ ኮይኑ ኣውጽኦ።"),
       ("Then the king told everyone in the kingdom to honour the living God of Daniel, who saves and rescues his people.",
        "ሽዑ እቲ ንጉስ ንብዘለዉ ኣብ መንግስቲ፡ ነቲ ዘናግፍ ህያው ኣምላኽ ዳንኤል ኬኽብሩ ኣዘዘ።"),
     ]},
  ],
  "verse": {"en":"My God sent his angel to shut the lions' mouths.",
            "ti":"ኣምላኸይ ኣፍ ኣናብስ ኪዓጹ መልኣኹ ለኣኸ።",
            "ref_en":"Daniel 6:22","ref_ti":"ዳንኤል 6፡22"},
  "easy_q": [
    {"q_en":"How many times a day did Daniel pray?","q_ti":"ዳንኤል መዓልታዊ ክንደይ ሳዕ ይጽሊ ነበረ?","opts":"a) One &nbsp;&nbsp; b) <strong>Three</strong> &nbsp;&nbsp; c) Ten"},
    {"q_en":"Where was Daniel thrown?","q_ti":"ዳንኤል ናበይ ተደርበየ?","opts":"a) A river &nbsp;&nbsp; b) <strong>The lions' den</strong> &nbsp;&nbsp; c) A tower"},
    {"q_en":"Who shut the lions' mouths?","q_ti":"ኣፍ ኣናብስ መን ዓጸዎ?","opts":"a) Daniel &nbsp;&nbsp; b) The king &nbsp;&nbsp; c) <strong>God's angel</strong>"},
    {"q_en":"Daniel was ___ by the lions.","q_ti":"ዳንኤል በቶም ኣናብስ ___ ።","opts":"a) hurt &nbsp;&nbsp; b) <strong>not hurt</strong> &nbsp;&nbsp; c) eaten"},
  ],
  "hard_q": [
    ("Why did Daniel keep praying even when it was against the law?","ዳንኤል ኣንጻር ሕጊ እኳ እንተኾነ ስለምንታይ ምጽላይ ቀጸለ?"),
    ("How do you think the king felt during the night?","እቲ ንጉስ ብለይቲ ከመይ ተሰሚዕዎ ይኸውን?"),
    ("What does this story teach us about trusting God when we are afraid?","ክንፈርህ ከለና ኣብ ኣምላኽ ብዛዕባ ምእማን እንታይ ይምህረና?"),
    ("Write about a time you prayed when something was hard.","ከቢድ ነገር ኣብ ዘጋጠመሉ እዋን ዝጸለኻሉ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("Daniel prays to God three times a day.","ዳንኤል መዓልታዊ ሰለስተ ሳዕ ይጽሊ።"),
    ("Jealous men make a trap with a new law.","ቀናእቲ ሰባት ብሓድሽ ሕጊ መፈንጠራ ገበሩ።"),
    ("Daniel keeps praying by his window.","ዳንኤል ኣብ መስኮቱ ምጽላይ ቀጸለ።"),
    ("Daniel is thrown into the lions' den.","ዳንኤል ናብ ጉድጓድ ኣናብስ ተደርበየ።"),
    ("God's angel shuts the lions' mouths.","መልኣኽ ኣምላኽ ኣፍ ኣናብስ ዓጸወ።"),
    ("Daniel is safe, and God is honoured!","ዳንኤል ደሓነ፡ ኣምላኽ ከኣ ተኸብረ!"),
  ],
  "ws_words": ["DANIEL","LIONS","PRAY","KING","ANGEL","FAITH","DEN","TRUST"],
  "crossword": {
    "spine": "DANIEL",
    "crossers": ["LIONS","KING","ANGEL","PRAY"],
    "grid": 13,
    "down_clues": [(1,"He prayed three times a day.","DANIEL — ዳንኤል")],
    "across_clues": [(2,"Big cats in the den.","LIONS — ኣናብስ"),
                     (3,"Darius was one.","KING — ንጉስ"),
                     (4,"God sent one to shut the mouths.","ANGEL — መልኣኽ"),
                     (5,"Daniel did this to God.","PRAY — ጸሎት")],
    "answer_line": "1 DANIEL · 2 LIONS · 3 KING · 4 ANGEL · 5 PRAY",
  },
  "match": [("Lion","ኣንበሳ"),("King","ንጉስ"),("Pray","ጸሊ"),("Angel","መልኣኽ"),("Faith","እምነት"),("Den","ጉድጓድ")],
  "colouring": [
    {"title_en":"Colour the Brave Lion","sub_en":"In the den","sub_ti":"ኣብ ጉድጓድ","note_en":"Give the lion a big furry mane!","note_ti":"ነቲ ኣንበሳ ዓቢ ጨጓር ሃቦ!"},
    {"title_en":"Colour the Royal Scroll","sub_en":"The king's law","sub_ti":"ሕጊ ንጉስ","note_en":"What colour is the king's seal?","note_ti":"ማሕተም ንጉስ እንታይ ሕብሪ እዩ?"},
    {"title_en":"Colour Daniel Praying","sub_en":"By the window","sub_ti":"ኣብ መስኮት","note_en":"Draw a sunny sky behind him.","note_ti":"ብድሕሪኡ ጸሓያዊ ሰማይ ስኣል።"},
    {"title_en":"Colour the Lions' Den","sub_en":"God kept Daniel safe","sub_ti":"ኣምላኽ ዳንኤል ሓለዎ","note_en":"How many lions can you count?","note_ti":"ክንደይ ኣናብስ ትቖጽር?"},
  ],
  "count_word_en":"lions","count_word_ti":"ኣናብስ","count_sets":[2,3,1,4],
  "count_fact_en":"Daniel prayed 3 times a day.","count_fact_ti":"ዳንኤል መዓልታዊ ሰለስተ ሳዕ ጸለየ።",
  "lesson_en":"Being faithful like Daniel","lesson_ti":"ከም ዳንኤል እሙን ምዃን",
  "scenarios": [
    {"q_en":"Your friends want you to skip praying or church to play.","q_ti":"ኣዕሩኽትኻ ጸሎት ወይ ቤተ ክርስትያን ክትሓድግ ይደልዩ።","opts":"a) <strong>Kindly keep your good habit.</strong> &nbsp;&nbsp; b) Give up right away."},
    {"q_en":"Someone dares you to do something you know is wrong.","q_ti":"ሓደ ሰብ ጌጋ ዝኾነ ነገር ክትገብር ይደፋፍኣካ።","opts":"a) Do it to look cool. &nbsp;&nbsp; b) <strong>Say no and do what is right.</strong>"},
    {"q_en":"You feel scared about something big tomorrow.","q_ti":"ብዛዕባ ጽባሕ ዘሎ ዓቢ ነገር ትፈርህ ኣለኻ።","opts":"a) <strong>Pray and ask God for help.</strong> &nbsp;&nbsp; b) Worry all alone."},
  ],
  "reflect_write": [
    ("Daniel prayed even when it was hard. When can you talk to God?","ዳንኤል ከቢድ እኳ እንተኾነ ጸለየ። መዓስ ምስ ኣምላኽ ክትዛረብ ትኽእል?"),
    ("How does it help to know God protects those who trust him?","ኣምላኽ ነቶም ዝኣምንዎ ከም ዝሕልዎም ምፍላጥ ብኸመይ ይሕግዝ?"),
    ("Write a short prayer thanking God for keeping you safe.","ኣምላኽ ስለ ዝሓለወካ እተመስግን ሓጺር ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help Daniel Get Safely Out","maze_instr_en":"Guide Daniel through the den to the king who lifts him out.",
  "maze_instr_ti":"ንዳንኤል ናብቲ ዘውጽኦ ንጉስ ምርሓዮ።",
  "draw_title_en":"Draw a Friendly Lion","draw_sub_en":"Design your own lion","draw_sub_ti":"ናትካ ኣንበሳ ስኣል",
  "draw_instr_en":"God kept the lions calm. Draw a big, gentle lion and give it a name.",
  "draw_instr_ti":"ኣምላኽ ነቶም ኣናብስ ኣህዳኦም። ዓቢ ህዱእ ኣንበሳ ስኣል።",
  "craft_title_en":"Craft: Paper-Plate Lion","craft_sub_en":"Make a lion mane!","craft_sub_ti":"ጨጓር ኣንበሳ ስራሕ!",
  "craft_need_en":"You will need: a paper plate or circle, yellow/orange paper, scissors, glue, crayons.",
  "craft_need_ti":"እትደሊ፦ ወረቐት ሸሓኒ፡ ብጫን ብርቱኳናውን ወረቐት፡ መቐስ፡ ልቖ፡ ሕብሪ።",
  "craft_steps": [
    ("Colour a face in the middle of the plate or circle.","ኣብ ማእከል እቲ ሸሓኒ ገጽ ሕብሮ።"),
    ("Cut strips of paper for the mane and glue them around the edge.","ንጨጓር ወረቐት ቆሪጽካ ኣብ ዙርያ ኣጣብቖ።"),
    ("Add ears, eyes, a nose and whiskers.","እዝኒ፡ ኣዒንቲ፡ ኣፍንጫን ኣስናንን ወስኽ።"),
    ("Remember: God can protect you, just as he protected Daniel!","ዘክር፦ ኣምላኽ ከምቲ ንዳንኤል ዝሓለዎ ንዓኻ'ውን ኪሕልወካ ይኽእል!"),
  ],
  "template_title_en":"Lion Mask Template",
  "bookmarks": [("Pray Every Day","መዓልታዊ ጸሊ"),("God Protects Me","ኣምላኽ ይሕልወኒ")],
  "secret_code": code("BRAVE","GOD IS GOOD","መልሲ፦ BRAVE (ትብዕ) · GOD IS GOOD (ኣምላኽ ሰናይ እዩ)"),
  "true_false": [
    ("Daniel prayed to God.","ዳንኤል ናብ ኣምላኽ ጸለየ።",True),
    ("The lions ate Daniel.","እቶም ኣናብስ ንዳንኤል በልዕዎ።",False),
    ("A jealous group made a trap.","ቀናእቲ ጉጅለ መፈንጠራ ገበሩ።",True),
    ("God sent an angel to help.","ኣምላኽ መልኣኽ ልኢኹ ሓገዘ።",True),
    ("The king was happy about the trap.","እቲ ንጉስ በቲ መፈንጠራ ተሓጐሰ።",False),
  ],
  "fill_blanks": {
    "bank": ["prayed","lions","angel","king","safe"],
    "sentences": ["Daniel __________ to God three times a day.",
                  "Daniel was thrown into the den of __________.",
                  "God sent an __________ to shut their mouths.",
                  "In the morning Daniel was __________.",
                  "The __________ was overjoyed to see Daniel alive."],
    "answers": "prayed · lions · angel · safe · king",
  },
  "acrostic": "DANIEL",
  "prayer": {"en":"Dear God, thank you for hearing me when I pray. Help me to trust you and be brave, even when things are scary. Keep me safe in your loving care. Amen.",
             "ti":"ኦ ኣምላኽ፡ ክጽሊ ኸለኹ ስለ እትሰምዓኒ የቐንየለይ። ክኣምነካን ትብዕ ክኸውንን ሓግዘኒ። ብፍቕራዊ ሓልዮትካ ሓልወኒ። ኣሜን።"},
  "reflect1_en":"What helps you feel brave when you are afraid?","reflect1_ti":"ክትፈርህ ከለኻ ትብዕ ንኽትከውን እንታይ ይሕግዘካ?",
  "reflect2_en":"How does it feel to know God is watching over you?","reflect2_ti":"ኣምላኽ ይሕልወካ ከም ዘሎ ምፍላጥ ከመይ ይስመዓካ?",
  "three_lessons": [("Pray Always","ኩሉ ግዜ ጸሊ"),("Stay Faithful","እሙን ኩን"),("Trust God","ኣብ ኣምላኽ ተኣመን")],
  "review_en":"You have learned about Daniel's faith. Remember these three things:",
  "review_ti":"ብዛዕባ እምነት ዳንኤል ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for praying faithfully and trusting God, just like Daniel!",
  "cert_line_ti":"ከም ዳንኤል ብእምነት ስለ ዝጸለየን ኣብ ኣምላኽ ስለ ዝተኣመነን!",
})


# ===========================================================================
# BOOK 3 — David and Goliath
# ===========================================================================
BOOKS.append({
  "slug": "03-david",
  "icon": "sling", "icon2": "crown",
  "title_en": "David and Goliath",
  "title_ti": "ዳዊትን ጎልያድን",
  "cover_line_en": "A colour-and-learn activity book about courage, faith and God's strength.",
  "cover_line_ti": "ብዛዕባ ትብዓት፡ እምነትን ሓይሊ ኣምላኽን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("David", "a young shepherd boy who trusted God.", "ዳዊት — ኣብ ኣምላኽ ዝተኣመነ መንእሰይ ጓሳ።"),
    ("Goliath", "a giant soldier from the Philistines.", "ጎልያድ — ካብ ፍልስጥኤማውያን ግዙፍ ተዋጋኢ።"),
    ("King Saul", "the king of Israel.", "ንጉስ ሳኦል — ንጉስ እስራኤል።"),
    ("The Army", "the frightened soldiers of Israel.", "እቲ ሰራዊት — ዝፈርሁ ወተሃደራት እስራኤል።"),
  ],
  "story": [
    {"sub_en":"The Shepherd Boy","sub_ti":"እቲ ጓሳ ቆልዓ",
     "paras":[
       ("David was the youngest of eight brothers. He looked after his father's sheep and played music on his harp.",
        "ዳዊት ካብ ሸሞንተ ኣሕዋት እቲ ዝነኣሰ ነበረ። ኣባጊዕ ኣቦኡ ይሕሉን በገና ይጻወትን ነበረ።"),
       ("When lions or bears tried to take a lamb, David protected the flock. God gave him courage and strength.",
        "ኣናብስ ወይ ድቢ ገንሸል ኪወስዱ ኪፍትኑ ኸለዉ፡ ዳዊት ነቲ መጓሰ ይከላኸል ነበረ። ኣምላኽ ትብዓትን ሓይልን ሃቦ።"),
     ]},
    {"sub_en":"The Giant's Challenge","sub_ti":"ብድሆ እቲ ግዙፍ",
     "paras":[
       ("The Philistine army had a giant named Goliath. He was over nine feet tall! Every day he shouted and dared Israel to send someone to fight him.",
        "ሰራዊት ፍልስጥኤም ጎልያድ ዝበሃል ግዙፍ ነበሮም። ካብ ትሽዓተ ጫማ ንላዕሊ ነዊሕ ነበረ! መዓልታዊ እናጨደረ ንእስራኤል ኪዋግኦ ሰብ ኪልእኩ ይብድህ ነበረ።"),
       ("All the soldiers of Israel, and even the king, were terrified. No one was brave enough to face the giant.",
        "ኩሎም ወተሃደራት እስራኤል፡ ንጉስ እውን ከይተረፈ፡ ፈርሁ። ነቲ ግዙፍ ኪገጥም ዝኣክል ትብዕ ሰብ ኣይነበረን።"),
     ]},
    {"sub_en":"David Is Not Afraid","sub_ti":"ዳዊት ኣይፈርሀን",
     "paras":[
       ("David came to bring food to his brothers. When he heard Goliath, he said, 'Who is this giant to defy the army of the living God?'",
        "ዳዊት ንኣሕዋቱ ምግቢ ኬምጽእ መጸ። ንጎልያድ ምስ ሰምዖ፡ 'እዚ ግዙፍ መን እዩ ንሰራዊት ህያው ኣምላኽ ዝብድህ?' በለ።"),
       ("David told King Saul, 'I will fight him. The Lord who saved me from the lion and the bear will save me from this giant.'",
        "ዳዊት ንንጉስ ሳኦል፡ 'ኣነ ክዋግኦ እየ። እቲ ኻብ ኣንበሳን ድብን ዘናገፈኒ እግዚኣብሄር ካብዚ ግዙፍ እውን ኬናግፈኒ እዩ' በሎ።"),
     ]},
    {"sub_en":"Five Smooth Stones","sub_ti":"ሓሙሽተ ልሙጻት ኣእማን",
     "paras":[
       ("David would not wear heavy armour. Instead he took his sling and five smooth stones from the stream. He trusted God, not swords.",
        "ዳዊት ከቢድ ኣጽዋር ኣይተኸድነን። ኣብ ክንዳኡ ወንጭፉን ሓሙሽተ ልሙጻት ኣእማንን ካብ ወሓዚ ወሰደ። ኣብ ኣምላኽ እምበር ኣብ ኣስያፍ ኣይተኣመነን።"),
       ("Goliath laughed at the small boy. But David said, 'You come with a sword, but I come in the name of the Lord!'",
        "ጎልያድ ነቲ ንእሽቶ ቆልዓ ሰሓቐሉ። ዳዊት ግና፡ 'ንስኻ ብሰይፊ ትመጽእ፡ ኣነ ግና ብስም እግዚኣብሄር እመጽእ!' በለ።"),
     ]},
    {"sub_en":"God Gives the Victory","sub_ti":"ኣምላኽ ዓወት ሃበ",
     "paras":[
       ("David ran toward Goliath, swung his sling, and let a stone fly. It struck the giant on the forehead, and Goliath fell down!",
        "ዳዊት ናብ ጎልያድ ጐዪዩ፡ ወንጭፉ ኣዞረ፡ ሓደ እምኒ ኸኣ ወርወረ። ኣብ ግምባር እቲ ግዙፍ ወቕዖ፡ ጎልያድ ከኣ ወደቐ!"),
       ("The huge giant was defeated by a boy who trusted God. Israel cheered and gave thanks to the Lord.",
        "እቲ ግዙፍ ብሓደ ኣብ ኣምላኽ ዝተኣመነ ቆልዓ ተሳዕረ። እስራኤል ተሓጐሱ ንእግዚኣብሄር ከኣ ኣመስገኑ።"),
       ("David teaches us that with God, no problem is too big. We can be brave because God is strong.",
        "ዳዊት ምስ ኣምላኽ ዝኾነ ጸገም ኣዝዩ ዓቢ ኸም ዘይኮነ ይምህረና። ኣምላኽ ሓያል ስለ ዝኾነ ትብዓት ክንገብር ንኽእል።"),
     ]},
  ],
  "verse": {"en":"I come to you in the name of the Lord of heaven's armies.",
            "ti":"ኣነ ብስም እግዚኣብሄር ጐይታ ሰራዊት ናባኻ እመጽእ ኣለኹ።",
            "ref_en":"1 Samuel 17:45","ref_ti":"1 ሳሙኤል 17፡45"},
  "easy_q": [
    {"q_en":"What was David's job?","q_ti":"ስራሕ ዳዊት እንታይ ነበረ?","opts":"a) A cook &nbsp;&nbsp; b) <strong>A shepherd</strong> &nbsp;&nbsp; c) A sailor"},
    {"q_en":"Who was the giant?","q_ti":"እቲ ግዙፍ መን ነበረ?","opts":"a) Saul &nbsp;&nbsp; b) <strong>Goliath</strong> &nbsp;&nbsp; c) David"},
    {"q_en":"How many stones did David take?","q_ti":"ዳዊት ክንደይ ኣእማን ወሰደ?","opts":"a) One &nbsp;&nbsp; b) <strong>Five</strong> &nbsp;&nbsp; c) Ten"},
    {"q_en":"David trusted in ___.","q_ti":"ዳዊት ኣብ ___ ተኣመነ።","opts":"a) his sword &nbsp;&nbsp; b) <strong>God</strong> &nbsp;&nbsp; c) armour"},
  ],
  "hard_q": [
    ("Why was David not afraid of the giant?","ዳዊት ስለምንታይ ነቲ ግዙፍ ኣይፈርሆን?"),
    ("What had God helped David do before, as a shepherd?","ኣምላኽ ቀደም፡ ከም ጓሳ፡ ንዳዊት እንታይ ክገብር ሓገዞ?"),
    ("What 'giant' problems feel too big for you? How can God help?","እንታይ ዓበይቲ ጸገማት ይስመዑኻ? ኣምላኽ ብኸመይ ይሕግዝ?"),
    ("Write about a time you needed courage.","ትብዓት ዘድለየካ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("David looks after his father's sheep.","ዳዊት ኣባጊዕ ኣቦኡ ይሕሉ።"),
    ("Goliath dares Israel to fight him.","ጎልያድ ንእስራኤል ኪዋግእዎ ይብድህ።"),
    ("David offers to fight the giant.","ዳዊት ነቲ ግዙፍ ኪዋግኦ ይቐርብ።"),
    ("David picks five smooth stones.","ዳዊት ሓሙሽተ ልሙጻት ኣእማን ይወስድ።"),
    ("David's stone strikes Goliath.","እምኒ ዳዊት ንጎልያድ ይወቅዕ።"),
    ("God gives Israel the victory!","ኣምላኽ ንእስራኤል ዓወት ይህብ!"),
  ],
  "ws_words": ["DAVID","GIANT","SLING","STONE","SHEEP","BRAVE","SAUL","LORD"],
  "crossword": {
    "spine": "DAVID",
    "crossers": ["GIANT","SLING","BRAVE"],
    "grid": 13,
    "down_clues": [(1,"The brave shepherd boy.","DAVID — ዳዊት")],
    "across_clues": [(2,"Goliath was a huge one.","GIANT — ግዙፍ"),
                     (3,"David used it to throw a stone.","SLING — ወንጭፍ"),
                     (4,"Not afraid; full of courage.","BRAVE — ትብዕ")],
    "answer_line": "1 DAVID · 2 GIANT · 3 SLING · 4 BRAVE",
  },
  "match": [("Shepherd","ጓሳ"),("Giant","ግዙፍ"),("Stone","እምኒ"),("Sling","ወንጭፍ"),("Brave","ትብዕ"),("Sheep","በጊዕ")],
  "colouring": [
    {"title_en":"Colour David the Shepherd","sub_en":"With his sling","sub_ti":"ምስ ወንጭፉ","note_en":"Give David a colourful robe!","note_ti":"ንዳዊት ሕብራዊ ክዳን ሃቦ!"},
    {"title_en":"Colour the Crown","sub_en":"David became king one day","sub_ti":"ዳዊት ንጉስ ኮነ","note_en":"Add shiny jewels.","note_ti":"ብሩህ ኣእባን ወስኽ።"},
    {"title_en":"Colour the Sling & Stones","sub_en":"Five smooth stones","sub_ti":"ሓሙሽተ ኣእማን","note_en":"Colour each stone differently.","note_ti":"ንነፍሲ ወከፍ እምኒ ብዝተፈላለየ ሕብሪ ሕብሮ።"},
    {"title_en":"Colour the Sheep","sub_en":"David's flock","sub_ti":"መጓሰ ዳዊት","note_en":"How many sheep can you count?","note_ti":"ክንደይ ኣባጊዕ ትቖጽር?"},
  ],
  "count_word_en":"stones","count_word_ti":"ኣእማን","count_sets":[5,3,2,4],
  "count_fact_en":"David took 5 smooth stones.","count_fact_ti":"ዳዊት ሓሙሽተ ኣእማን ወሰደ።",
  "lesson_en":"Being brave like David","lesson_ti":"ከም ዳዊት ትብዕ ምዃን",
  "scenarios": [
    {"q_en":"A big problem feels too hard to face.","q_ti":"ዓቢ ጸገም ኣዝዩ ኸቢድ ይመስል።","opts":"a) <strong>Ask God for help and try.</strong> &nbsp;&nbsp; b) Give up."},
    {"q_en":"Others laugh because you are small or young.","q_ti":"ንእሽቶ ስለ ዝኾንካ ይስሕቁልካ።","opts":"a) Feel worthless. &nbsp;&nbsp; b) <strong>Remember God made you special.</strong>"},
    {"q_en":"You must stand up for what is right, alone.","q_ti":"በይንኻ ንቕኑዕ ክትከላኸል ኣለካ።","opts":"a) <strong>Be brave with God's help.</strong> &nbsp;&nbsp; b) Run away."},
  ],
  "reflect_write": [
    ("David remembered how God helped him before. Write one way God has helped you.","ኣምላኽ ብኸመይ ከም ዝሓገዘካ ሓንቲ ጽሓፍ።"),
    ("Being brave does not mean you are never scared. What can you do when scared?","ክትፈርህ ከለኻ እንታይ ክትገብር ትኽእል?"),
    ("Write a short prayer asking God for courage.","ንኣምላኽ ትብዓት ዝልምን ሓጺር ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help David Reach the Giant","maze_instr_en":"Guide David across the valley to face Goliath.",
  "maze_instr_ti":"ንዳዊት ብለሸቑ ኣቢሉ ናብ ጎልያድ ምርሓዮ።",
  "draw_title_en":"Draw Your Own Brave Hero","draw_sub_en":"Design a hero","draw_sub_ti":"ጅግና ስኣል",
  "draw_instr_en":"Draw yourself being brave and helping someone, just like David.",
  "draw_instr_ti":"ከም ዳዊት ትብዓት እናገበርካ ንሰብ ክትሕግዝ ከለኻ ስኣል።",
  "craft_title_en":"Craft: Paper Sling & Stones","craft_sub_en":"Make five soft stones!","craft_sub_ti":"ሓሙሽተ ልስሉስ ኣእማን ስራሕ!",
  "craft_need_en":"You will need: paper, crayons, cotton balls or crumpled paper for stones, scissors.",
  "craft_need_ti":"እትደሊ፦ ወረቐት፡ ሕብሪ፡ ጡጥ ወይ ዝተጠቕለለ ወረቐት ንኣእማን፡ መቐስ።",
  "craft_steps": [
    ("Draw and colour a sling on paper, then cut it out.","ወንጭፍ ኣብ ወረቐት ስኣል፡ ሕብሮ፡ ደሓር ቆርጾ።"),
    ("Make five soft 'stones' from cotton or crumpled paper.","ሓሙሽተ ልስሉስ 'ኣእማን' ካብ ጡጥ ስራሕ።"),
    ("Write a word of courage on each stone (Brave, Trust, Faith...).","ኣብ ነፍሲ ወከፍ እምኒ ናይ ትብዓት ቃል ጽሓፍ።"),
    ("Remember: with God, you can face any giant!","ዘክር፦ ምስ ኣምላኽ ንዝኾነ ግዙፍ ክትገጥም ትኽእል!"),
  ],
  "template_title_en":"Sling Template",
  "bookmarks": [("Be Brave","ትብዕ ኹን"),("God Is My Strength","ኣምላኽ ሓይለይ እዩ")],
  "secret_code": code("BRAVE","GOD IS GOOD","መልሲ፦ BRAVE (ትብዕ) · GOD IS GOOD (ኣምላኽ ሰናይ እዩ)"),
  "true_false": [
    ("David was a shepherd.","ዳዊት ጓሳ ነበረ።",True),
    ("David wore heavy armour to fight.","ዳዊት ከቢድ ኣጽዋር ተኸዲኑ ተዋግአ።",False),
    ("David took five smooth stones.","ዳዊት ሓሙሽተ ኣእማን ወሰደ።",True),
    ("David trusted in God.","ዳዊት ኣብ ኣምላኽ ተኣመነ።",True),
    ("Goliath won the fight.","ጎልያድ ኣብቲ ውግእ ሰዓረ።",False),
  ],
  "fill_blanks": {
    "bank": ["shepherd","giant","stones","sling","God"],
    "sentences": ["David was a young __________.",
                  "Goliath was a huge __________.",
                  "David took five smooth __________.",
                  "He used his __________ to throw one.",
                  "David trusted in __________, and won."],
    "answers": "shepherd · giant · stones · sling · God",
  },
  "acrostic": "BRAVE",
  "prayer": {"en":"Dear God, when problems feel like giants, help me to be brave. Thank you that you are stronger than anything I fear. I will trust in you. Amen.",
             "ti":"ኦ ኣምላኽ፡ ጸገማት ከም ግዙፋት ኪመስሉ ኸለዉ፡ ትብዕ ክኸውን ሓግዘኒ። ካብ ዝፈርሆ ኹሉ ሓያል ስለ ዝኾንካ የቐንየለይ። ኣብኻ ክኣምን እየ። ኣሜን።"},
  "reflect1_en":"What big thing would you like God's help with?","reflect1_ti":"ብዛዕባ እንታይ ዓቢ ነገር ሓገዝ ኣምላኽ ትደሊ?",
  "reflect2_en":"How does it feel to know God is on your side?","reflect2_ti":"ኣምላኽ ኣብ ጎንኻ ከም ዘሎ ምፍላጥ ከመይ ይስመዓካ?",
  "three_lessons": [("Be Brave","ትብዕ ኹን"),("Trust God","ኣብ ኣምላኽ ተኣመን"),("God Is Strong","ኣምላኽ ሓያል እዩ")],
  "review_en":"You have learned about David's courage. Remember these three things:",
  "review_ti":"ብዛዕባ ትብዓት ዳዊት ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for being brave and trusting God, just like David!",
  "cert_line_ti":"ከም ዳዊት ትብዕ ስለ ዝኾነን ኣብ ኣምላኽ ስለ ዝተኣመነን!",
})

# ===========================================================================
# BOOK 4 — Noah's Ark
# ===========================================================================
BOOKS.append({
  "slug": "04-noah",
  "icon": "ark", "icon2": "waves",
  "title_en": "Noah's Ark",
  "title_ti": "መርከብ ኖህ",
  "cover_line_en": "A colour-and-learn activity book about obedience, faith and God's promises.",
  "cover_line_ti": "ብዛዕባ ተኣዛዝነት፡ እምነትን ተስፋታት ኣምላኽን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("Noah", "a good man who obeyed God.", "ኖህ — ንኣምላኽ ዝተኣዘዘ ሰናይ ሰብኣይ።"),
    ("Noah's Family", "his wife, sons and their wives.", "ስድራ ኖህ — ሰበይቱ፡ ደቁን ኣንስቶምን።"),
    ("The Animals", "two of every kind, and more.", "እንስሳታት — ካብ ነፍሲ ወከፍ ዓሌት ክልተ።"),
    ("God", "who kept his promise with a rainbow.", "ኣምላኽ — ብቐስተ ደመና ተስፋኡ ዝሓለወ።"),
  ],
  "story": [
    {"sub_en":"God Speaks to Noah","sub_ti":"ኣምላኽ ንኖህ ተዛረቦ",
     "paras":[
       ("Noah was a good man who loved and obeyed God. But the world had become full of wrongdoing.",
        "ኖህ ንኣምላኽ ዘፍቅርን ዝእዘዝን ሰናይ ሰብኣይ ነበረ። እታ ዓለም ግና ብእከይ መሊኣ ነበረት።"),
       ("God told Noah, 'I will send a great flood. Build a big boat, an ark, to keep your family and the animals safe.'",
        "ኣምላኽ ንኖህ፡ 'ዓቢ ማይ ኣይሂ ኸምጽእ እየ። ንስድራኻን ንእንስሳታትን ንምድሓን ዓባይ መርከብ ስራሕ' በሎ።"),
     ]},
    {"sub_en":"Building the Ark","sub_ti":"መርከብ ምስራሕ",
     "paras":[
       ("Noah obeyed God. He and his sons worked for many years to build the huge wooden ark, exactly as God said.",
        "ኖህ ንኣምላኽ ተኣዘዘ። ንሱን ደቁን ከምቲ ኣምላኽ ዝበሎ ነታ ግዝፍቲ ዕንጨይቲ መርከብ ንብዙሕ ዓመታት ሰርሑ።"),
       ("People laughed at Noah for building a boat on dry land. But Noah kept trusting and obeying God.",
        "ሰባት ኣብ ንቑጽ ምድሪ መርከብ ስለ ዝሰርሐ ንኖህ ሰሓቕዎ። ኖህ ግና ንኣምላኽ ምእማንን ምእዛዝን ቀጸለ።"),
     ]},
    {"sub_en":"Two by Two","sub_ti":"ክልተ ክልተ",
     "paras":[
       ("When the ark was ready, God sent the animals — two of every kind, male and female. They came walking, hopping and flying into the ark.",
        "እታ መርከብ ምስ ተዳለወት፡ ኣምላኽ ነቶም እንስሳታት ለኣኾም — ካብ ነፍሲ ወከፍ ዓሌት ክልተ። እናኸዱ፡ እናዘለሉን እናነፈሩን ናብ መርከብ ኣተዉ።"),
       ("Noah, his wife, his three sons and their wives went in too. Then God shut the door, and the rain began.",
        "ኖህ፡ ሰበይቱ፡ ሰለስተ ደቁን ኣንስቶምን ኣተዉ። ሽዑ ኣምላኽ ነቲ ማዕጾ ዓጸዎ፡ ዝናብ ከኣ ጀመረ።"),
     ]},
    {"sub_en":"The Great Flood","sub_ti":"እቲ ዓቢ ኣይሂ",
     "paras":[
       ("It rained for forty days and forty nights. Water covered everything, but the ark floated safely on top.",
        "ኣርብዓ መዓልትን ኣርብዓ ለይትን ዘነበ። ማይ ንኹሉ ኸደኖ፡ እታ መርከብ ግና ብደሓን ኣብ ልዕሊ ማይ ተንሳፈፈት።"),
       ("Inside, Noah cared for all the animals. God kept every one of them safe through the storm.",
        "ኣብ ውሽጢ፡ ኖህ ንኹሎም እንስሳታት ተኸናኸኖም። ኣምላኽ ብማእከል እቲ ህቦብላ ንነፍሲ ወከፍ ሓለዎም።"),
     ]},
    {"sub_en":"The Rainbow Promise","sub_ti":"ተስፋ ቐስተ ደመና",
     "paras":[
       ("At last the water went down. Noah sent out a dove, and it returned with a fresh olive leaf — dry land was near!",
        "ኣብ መወዳእታ እቲ ማይ ጐደለ። ኖህ ርግቢት ለኣኸ፡ ንሳ ኸኣ ብጨንፈር ኣውልዕ ተመልሰት — ንቑጽ ምድሪ ቀሪባ ነበረት!"),
       ("Everyone came out of the ark. Noah thanked God, and God placed a beautiful rainbow in the sky.",
        "ኩሎም ካብ መርከብ ወጹ። ኖህ ንኣምላኽ ኣመስገነ፡ ኣምላኽ ከኣ ጽብቕቲ ቐስተ ደመና ኣብ ሰማይ ገበረ።"),
       ("God promised, 'Never again will a flood destroy the whole earth.' The rainbow reminds us that God keeps his promises.",
        "ኣምላኽ፡ 'ደጊም ንብዘላ ምድሪ ዜጥፍእ ኣይሂ ኣይኪኸውንን እዩ' ኢሉ ተመባጽዐ። እታ ቐስተ ደመና ኣምላኽ ተስፋኡ ኸም ዝሕሉ ተዘኻኽረና።"),
     ]},
  ],
  "verse": {"en":"I have put my rainbow in the clouds as a sign of my promise.",
            "ti":"ንቕሉኤይ ምልክት ቐስተይ ኣብ ደበና ገበርኩ።",
            "ref_en":"Genesis 9:13","ref_ti":"ዘፍጥረት 9፡13"},
  "easy_q": [
    {"q_en":"What did God tell Noah to build?","q_ti":"ኣምላኽ ንኖህ እንታይ ኪሰርሕ በሎ?","opts":"a) A house &nbsp;&nbsp; b) <strong>An ark</strong> &nbsp;&nbsp; c) A wall"},
    {"q_en":"How many of each animal came?","q_ti":"ካብ ነፍሲ ወከፍ እንስሳ ክንደይ መጹ?","opts":"a) <strong>Two</strong> &nbsp;&nbsp; b) Five &nbsp;&nbsp; c) Ten"},
    {"q_en":"How many days did it rain?","q_ti":"ክንደይ መዓልቲ ዘነበ?","opts":"a) Four &nbsp;&nbsp; b) <strong>Forty</strong> &nbsp;&nbsp; c) Four hundred"},
    {"q_en":"God's promise sign was a ___.","q_ti":"ምልክት ተስፋ ኣምላኽ ___ ነበረ።","opts":"a) star &nbsp;&nbsp; b) <strong>rainbow</strong> &nbsp;&nbsp; c) cloud"},
  ],
  "hard_q": [
    ("Why did Noah keep building even when people laughed?","ሰባት እኳ እንተሰሓቑ ኖህ ስለምንታይ ምስራሕ ቀጸለ?"),
    ("How do you think Noah cared for the animals on the ark?","ኖህ ኣብ መርከብ ነቶም እንስሳታት ብኸመይ ተኸናኸኖም ትብል?"),
    ("What does the rainbow teach us about God?","እታ ቐስተ ደመና ብዛዕባ ኣምላኽ እንታይ ትምህረና?"),
    ("Write about a time you obeyed even when it was hard.","ከቢድ እኳ እንተኾነ ዝተኣዘዝካሉ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("God tells Noah to build an ark.","ኣምላኽ ንኖህ መርከብ ኪሰርሕ ይነግሮ።"),
    ("Noah builds the ark from wood.","ኖህ ካብ ዕንጨይቲ መርከብ ይሰርሕ።"),
    ("The animals come two by two.","እንስሳታት ክልተ ክልተ ይመጹ።"),
    ("The rain falls for forty days.","ዝናብ ኣርብዓ መዓልቲ ይዘንብ።"),
    ("A dove brings an olive leaf.","ርግቢት ጨንፈር ኣውልዕ ተምጽእ።"),
    ("God sends a rainbow promise.","ኣምላኽ ተስፋ ቐስተ ደመና ይሰድድ።"),
  ],
  "ws_words": ["NOAH","ARK","FLOOD","DOVE","RAIN","RAINBOW","ANIMALS","PROMISE"],
  "crossword": {
    "spine": "NOAH",
    "crossers": ["ARK","DOVE","RAIN"],
    "grid": 13,
    "down_clues": [(1,"He obeyed God and built the ark.","NOAH — ኖህ")],
    "across_clues": [(2,"The big boat.","ARK — መርከብ"),
                     (3,"The bird with the olive leaf.","DOVE — ርግቢት"),
                     (4,"It fell for forty days.","RAIN — ዝናብ")],
    "answer_line": "1 NOAH · 2 ARK · 3 DOVE · 4 RAIN",
  },
  "match": [("Ark","መርከብ"),("Dove","ርግቢት"),("Rain","ዝናብ"),("Rainbow","ቐስተ ደመና"),("Animals","እንስሳታት"),("Promise","ተስፋ")],
  "colouring": [
    {"title_en":"Colour Noah's Ark","sub_en":"The big boat","sub_ti":"እታ ዓባይ መርከብ","note_en":"Add animals looking out of the windows!","note_ti":"ብመሳኹቲ ዝጥምቱ እንስሳታት ወስኽ!"},
    {"title_en":"Colour the Waves","sub_en":"The great flood","sub_ti":"እቲ ዓቢ ኣይሂ","note_en":"Use lots of blues.","note_ti":"ብዙሕ ሰማያዊ ተጠቐም።"},
    {"title_en":"Colour the Animals","sub_en":"Two by two","sub_ti":"ክልተ ክልተ","note_en":"Colour each pair the same.","note_ti":"ንነፍሲ ወከፍ ጽምዲ ሓደ ዓይነት ሕብሮ።"},
    {"title_en":"Colour the Rainbow","sub_en":"God's promise","sub_ti":"ተስፋ ኣምላኽ","note_en":"Use all seven colours!","note_ti":"ኩሎም ሸውዓተ ሕብርታት ተጠቐም!"},
  ],
  "count_word_en":"animals","count_word_ti":"እንስሳታት","count_sets":[2,2,4,2],
  "count_fact_en":"The animals came 2 by 2.","count_fact_ti":"እንስሳታት ክልተ ክልተ መጹ።",
  "lesson_en":"Obeying God like Noah","lesson_ti":"ከም ኖህ ንኣምላኽ ምእዛዝ",
  "scenarios": [
    {"q_en":"A parent asks you to do a chore you don't enjoy.","q_ti":"ወላዲ ዘይትፈትዎ ስራሕ ክትገብር ይሓተካ።","opts":"a) <strong>Obey with a good attitude.</strong> &nbsp;&nbsp; b) Complain and refuse."},
    {"q_en":"Others tease you for doing the right thing.","q_ti":"ቅኑዕ ስለ ዝገበርካ የላግጹልካ።","opts":"a) Stop to fit in. &nbsp;&nbsp; b) <strong>Keep doing right, like Noah.</strong>"},
    {"q_en":"A friend is left out and feels sad.","q_ti":"ሓደ ፈታዊ ተገሊሉ የጕሂ ኣሎ።","opts":"a) <strong>Care for them and include them.</strong> &nbsp;&nbsp; b) Ignore them."},
  ],
  "reflect_write": [
    ("Noah obeyed even when it was hard. Who can help you do the right thing?","ንመን ሓገዝ ክትሓትት ትኽእል?"),
    ("God kept everyone safe in the ark. When has God taken care of you?","ኣምላኽ መዓስ ተኸናኸነካ?"),
    ("Write a short prayer thanking God for his promises.","ኣምላኽ ስለ ተስፋታቱ እተመስግን ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help the Animals Reach the Ark","maze_instr_en":"Guide the animals safely into the ark before the rain.",
  "maze_instr_ti":"ንእንስሳታት ቅድሚ ዝናብ ናብ መርከብ ምርሓዮም።",
  "draw_title_en":"Draw Your Own Ark","draw_sub_en":"Design an ark","draw_sub_ti":"መርከብ ስኣል",
  "draw_instr_en":"Draw your own ark and the animals you would take on board.",
  "draw_instr_ti":"ናትካ መርከብን እትወስዶም እንስሳታትን ስኣል።",
  "craft_title_en":"Craft: Paper-Plate Rainbow","craft_sub_en":"Make a rainbow!","craft_sub_ti":"ቐስተ ደመና ስራሕ!",
  "craft_need_en":"You will need: paper or half a paper plate, crayons, cotton wool, glue.",
  "craft_need_ti":"እትደሊ፦ ወረቐት ወይ ፍርቂ ሸሓኒ፡ ሕብሪ፡ ጡጥ፡ ልቖ።",
  "craft_steps": [
    ("Draw seven arches for the rainbow colours.","ሸውዓተ ቀስትታት ንሕብርታት ስኣል።"),
    ("Colour them red, orange, yellow, green, blue, indigo and violet.","ብቐይሕ፡ ብጫ፡ ቀጠልያ፡ ሰማያዊ... ሕብሮም።"),
    ("Glue cotton wool clouds at each end.","ኣብ ጫፋት ደበና ጡጥ ኣጣብቕ።"),
    ("Remember: the rainbow shows that God keeps his promises!","ዘክር፦ ቐስተ ደመና ኣምላኽ ተስፋኡ ኸም ዝሕሉ ተርኢ!"),
  ],
  "template_title_en":"Ark Template",
  "bookmarks": [("Obey God","ንኣምላኽ ተኣዘዝ"),("God Keeps Promises","ኣምላኽ ተስፋ ይሕሉ")],
  "secret_code": code("OBEYS","GOD IS GOOD","መልሲ፦ OBEYS (ይእዘዝ) · GOD IS GOOD (ኣምላኽ ሰናይ እዩ)"),
  "true_false": [
    ("Noah obeyed God and built the ark.","ኖህ ተኣዚዙ መርከብ ሰርሐ።",True),
    ("Only one of each animal came.","ካብ ነፍሲ ወከፍ ሓደ ጥራይ መጸ።",False),
    ("It rained for forty days.","ኣርብዓ መዓልቲ ዘነበ።",True),
    ("A dove brought an olive leaf.","ርግቢት ጨንፈር ኣውልዕ ኣምጽአት።",True),
    ("God's promise sign was a star.","ምልክት ተስፋ ኣምላኽ ኮኸብ ነበረ።",False),
  ],
  "fill_blanks": {
    "bank": ["ark","animals","rain","dove","rainbow"],
    "sentences": ["God told Noah to build an __________.",
                  "The __________ came two by two.",
                  "The __________ fell for forty days.",
                  "A __________ brought back an olive leaf.",
                  "God set a __________ in the sky as a promise."],
    "answers": "ark · animals · rain · dove · rainbow",
  },
  "acrostic": "NOAH",
  "prayer": {"en":"Dear God, thank you that you always keep your promises. Help me to obey you and trust you, like Noah. Thank you for taking care of me. Amen.",
             "ti":"ኦ ኣምላኽ፡ ኩሉ ግዜ ተስፋኻ ስለ እትሕሉ የቐንየለይ። ከም ኖህ ክእዘዘካን ክኣምነካን ሓግዘኒ። ስለ እትከናኸነኒ የቐንየለይ። ኣሜን።"},
  "reflect1_en":"When is it hard to obey? What helps you?","reflect1_ti":"ምእዛዝ መዓስ ይኸብድ? እንታይ ይሕግዘካ?",
  "reflect2_en":"How does the rainbow make you feel about God?","reflect2_ti":"እታ ቐስተ ደመና ብዛዕባ ኣምላኽ ከመይ ይስመዓካ?",
  "three_lessons": [("Obey God","ንኣምላኽ ተኣዘዝ"),("Keep Trusting","ምእማን ቀጽል"),("God Is Faithful","ኣምላኽ እሙን እዩ")],
  "review_en":"You have learned about Noah's obedience. Remember these three things:",
  "review_ti":"ብዛዕባ ተኣዛዝነት ኖህ ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for obeying and trusting God, just like Noah!",
  "cert_line_ti":"ከም ኖህ ንኣምላኽ ስለ ዝተኣዘዘን ስለ ዝኣመነን!",
})


# ===========================================================================
# BOOK 5 — Jonah and the Big Fish
# ===========================================================================
BOOKS.append({
  "slug": "05-jonah",
  "icon": "fish", "icon2": "waves",
  "title_en": "Jonah and the Big Fish",
  "title_ti": "ዮናስን እታ ዓባይ ዓሳን",
  "cover_line_en": "A colour-and-learn activity book about obeying God and second chances.",
  "cover_line_ti": "ብዛዕባ ንኣምላኽ ምእዛዝን ካልኣይ ዕድልን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("Jonah", "a prophet who tried to run from God.", "ዮናስ — ካብ ኣምላኽ ኪሃድም ዝፈተነ ነብዪ።"),
    ("The Sailors", "the men on the ship.", "እቶም ማሮ — ኣብ መርከብ ዝነበሩ ሰባት።"),
    ("The Big Fish", "sent by God to rescue Jonah.", "እታ ዓባይ ዓሳ — ንዮናስ ንምድሓን ብኣምላኽ እተላእከት።"),
    ("The People of Nineveh", "a city that needed to hear God.", "ህዝቢ ነነዌ — ንቓል ኣምላኽ ዜድሊዮም።"),
  ],
  "story": [
    {"sub_en":"Jonah Runs Away","sub_ti":"ዮናስ ሃደመ",
     "paras":[
       ("God said to Jonah, 'Go to the big city of Nineveh and tell the people to stop doing wrong.' But Jonah did not want to go.",
        "ኣምላኽ ንዮናስ፡ 'ናብታ ዓባይ ኸተማ ነነዌ ኺድ፡ ንህዝቢ ኸኣ ኻብ ክፉእ ኪግደፉ ንገሮም' በሎ። ዮናስ ግና ኪኸይድ ኣይደለየን።"),
       ("Instead, Jonah got on a ship going the opposite way, trying to run away from God.",
        "ኣብ ክንዳኡ፡ ዮናስ ካብ ኣምላኽ ንምህዳም ናብ ተጻራሪ ኣንፈት እትኸይድ መርከብ ተሳፈረ።"),
     ]},
    {"sub_en":"The Big Storm","sub_ti":"እቲ ዓቢ ህቦብላ",
     "paras":[
       ("God sent a huge storm. The wind roared and the waves crashed. The sailors were terrified the ship would break apart.",
        "ኣምላኽ ዓቢ ህቦብላ ሰደደ። ንፋስ ጓየየ፡ ማዕበል ከኣ ተሓምሰ። እቶም ማሮ እታ መርከብ ከይትሰባበር ኣዝዮም ፈርሁ።"),
       ("Jonah knew it was because he had run from God. He said, 'Throw me into the sea, and it will grow calm.'",
        "ዮናስ ካብ ኣምላኽ ስለ ዝሃደመ ምዃኑ ፈለጠ። 'ናብ ባሕሪ ደርብዩኒ፡ ከኣ ኪህድእ እዩ' በለ።"),
     ]},
    {"sub_en":"Inside the Big Fish","sub_ti":"ኣብ ውሽጢ እታ ዓባይ ዓሳ",
     "paras":[
       ("When the sailors threw Jonah into the water, the storm stopped at once. Then God sent a great big fish that swallowed Jonah whole.",
        "እቶም ማሮ ንዮናስ ናብ ማይ ምስ ደርበይዎ፡ እቲ ህቦብላ ብኡብኡ ሃደአ። ሽዑ ኣምላኽ ንዮናስ ምሉእ እትውሕጦ ዓባይ ዓሳ ሰደደ።"),
       ("Jonah was safe inside the fish for three days and three nights. There, he prayed and told God he was sorry.",
        "ዮናስ ኣብ ውሽጢ እታ ዓሳ ሰለስተ መዓልትን ሰለስተ ለይትን ብደሓን ጸንሐ። ኣብኡ ጸለየ፡ ንኣምላኽ ከኣ ይቕረታ ሓተተ።"),
     ]},
    {"sub_en":"A Second Chance","sub_ti":"ካልኣይ ዕድል",
     "paras":[
       ("God heard Jonah's prayer. He told the fish to bring Jonah safely to dry land, and the fish set him on the shore.",
        "ኣምላኽ ጸሎት ዮናስ ሰምዐ። ነታ ዓሳ ንዮናስ ብደሓን ናብ ንቑጽ ምድሪ ኸተብጽሖ ኣዘዛ፡ ንሳ ኸኣ ኣብ ገምገም ኣውረደቶ።"),
       ("God gave Jonah a second chance. 'Go to Nineveh,' he said again. This time, Jonah obeyed.",
        "ኣምላኽ ንዮናስ ካልኣይ ዕድል ሃቦ። 'ናብ ነነዌ ኺድ' ኢሉ ደጊሙ በሎ። እዚ ግዜ ዮናስ ተኣዘዘ።"),
     ]},
    {"sub_en":"Nineveh Turns to God","sub_ti":"ነነዌ ናብ ኣምላኽ ተመልሰት",
     "paras":[
       ("Jonah went to Nineveh and told the people God's message. To his surprise, everyone listened and turned away from doing wrong!",
        "ዮናስ ናብ ነነዌ ኸይዱ ንህዝቢ መልእኽቲ ኣምላኽ ነገሮም። ዜደንቕ ኮይኑ፡ ኩሎም ሰሚዖም ካብ ክፉእ ተመልሱ!"),
       ("God was kind and forgave the whole city. Jonah learned that God loves everyone and gives second chances.",
        "ኣምላኽ ሕያዋይ ኮይኑ ንብዘላ ኸተማ ይቕረ በለላ። ዮናስ ኣምላኽ ንኹሉ ኸም ዜፍቅርን ካልኣይ ዕድል ከም ዝህብን ተማህረ።"),
       ("Even when we make mistakes, God still loves us and helps us start again.",
        "ጌጋ ኽንገብር ከለና እኳ፡ ኣምላኽ ገና የፍቅረናን ከም ብሓድሽ ክንጅምር ይሕግዘናን።"),
     ]},
  ],
  "verse": {"en":"I called to the Lord in my trouble, and he answered me.",
            "ti":"ኣብ ጸበባይ ናብ እግዚኣብሄር ጸዋዕኩ፡ ንሱ ኸኣ መለሰለይ።",
            "ref_en":"Jonah 2:2","ref_ti":"ዮናስ 2፡2"},
  "easy_q": [
    {"q_en":"Where did God tell Jonah to go?","q_ti":"ኣምላኽ ንዮናስ ናበይ ኪኸይድ በሎ?","opts":"a) Egypt &nbsp;&nbsp; b) <strong>Nineveh</strong> &nbsp;&nbsp; c) Rome"},
    {"q_en":"What swallowed Jonah?","q_ti":"ንዮናስ እንታይ ወሓጦ?","opts":"a) A whale-shark &nbsp;&nbsp; b) <strong>A big fish</strong> &nbsp;&nbsp; c) A wave"},
    {"q_en":"How many days was Jonah inside?","q_ti":"ዮናስ ክንደይ መዓልቲ ኣብ ውሽጢ ጸንሐ?","opts":"a) One &nbsp;&nbsp; b) <strong>Three</strong> &nbsp;&nbsp; c) Seven"},
    {"q_en":"God gave Jonah a second ___.","q_ti":"ኣምላኽ ንዮናስ ካልኣይ ___ ሃቦ።","opts":"a) fish &nbsp;&nbsp; b) <strong>chance</strong> &nbsp;&nbsp; c) storm"},
  ],
  "hard_q": [
    ("Why did Jonah try to run away from God?","ዮናስ ስለምንታይ ካብ ኣምላኽ ኪሃድም ፈተነ?"),
    ("What did Jonah do inside the fish?","ዮናስ ኣብ ውሽጢ እታ ዓሳ እንታይ ገበረ?"),
    ("What does a 'second chance' mean? Why is it kind?","'ካልኣይ ዕድል' ማለት እንታይ ማለት እዩ?"),
    ("Write about a time you were given a second chance.","ካልኣይ ዕድል እተዋህበካ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("God tells Jonah to go to Nineveh.","ኣምላኽ ንዮናስ ናብ ነነዌ ኪኸይድ ይነግሮ።"),
    ("Jonah runs away on a ship.","ዮናስ ብመርከብ ይሃድም።"),
    ("A big storm shakes the ship.","ዓቢ ህቦብላ ነታ መርከብ የናውጻ።"),
    ("A big fish swallows Jonah.","ዓባይ ዓሳ ንዮናስ ትውሕጦ።"),
    ("Jonah prays and God rescues him.","ዮናስ ይጽሊ፡ ኣምላኽ የናግፎ።"),
    ("Jonah obeys and Nineveh turns to God.","ዮናስ ይእዘዝ፡ ነነዌ ትምለስ።"),
  ],
  "ws_words": ["JONAH","FISH","STORM","SHIP","PRAY","NINEVEH","SEA","OBEY"],
  "crossword": {
    "spine": "JONAH",
    "crossers": ["FISH","STORM","PRAY"],
    "grid": 13,
    "down_clues": [(1,"He ran from God, then obeyed.","JONAH — ዮናስ")],
    "across_clues": [(2,"It swallowed Jonah.","FISH — ዓሳ"),
                     (3,"Wild wind and waves at sea.","STORM — ህቦብላ"),
                     (4,"Jonah did this inside the fish.","PRAY — ጸሎት")],
    "answer_line": "1 JONAH · 2 FISH · 3 STORM · 4 PRAY",
  },
  "match": [("Fish","ዓሳ"),("Ship","መርከብ"),("Storm","ህቦብላ"),("Pray","ጸሊ"),("Sea","ባሕሪ"),("Obey","ተኣዘዝ")],
  "colouring": [
    {"title_en":"Colour the Big Fish","sub_en":"Sent by God","sub_ti":"ብኣምላኽ እተላእከት","note_en":"Give the fish big friendly eyes!","note_ti":"ነታ ዓሳ ዓበይቲ ኣዒንቲ ሃባ!"},
    {"title_en":"Colour the Stormy Sea","sub_en":"Big waves","sub_ti":"ዓበይቲ ማዕበል","note_en":"Use dark blues and greys.","note_ti":"ድሙቕ ሰማያውን ሓሙኹሽትን ተጠቐም።"},
    {"title_en":"Colour Jonah Praying","sub_en":"Inside the fish","sub_ti":"ኣብ ውሽጢ ዓሳ","note_en":"Draw Jonah with folded hands.","note_ti":"ንዮናስ ኢዱ ኣጣሚሩ ስኣሎ።"},
    {"title_en":"Colour the City of Nineveh","sub_en":"They listened to God","sub_ti":"ንኣምላኽ ሰምዑ","note_en":"Add happy people.","note_ti":"ሕጉሳት ሰባት ወስኽ።"},
  ],
  "count_word_en":"fish","count_word_ti":"ዓሳታት","count_sets":[3,1,4,2],
  "count_fact_en":"Jonah was in the fish 3 days.","count_fact_ti":"ዮናስ ሰለስተ መዓልቲ ኣብ ዓሳ ጸንሐ።",
  "lesson_en":"Obeying God like Jonah learned to","lesson_ti":"ከም ዮናስ ንኣምላኽ ምእዛዝ",
  "scenarios": [
    {"q_en":"You are asked to do something good but you don't feel like it.","q_ti":"ጽቡቕ ነገር ክትገብር ተሓቲትካ፡ ኣይተሓጐስካን።","opts":"a) <strong>Choose to obey anyway.</strong> &nbsp;&nbsp; b) Run away from it."},
    {"q_en":"You made a mistake and feel bad.","q_ti":"ጌጋ ገይርካ ሕማቕ ይስመዓካ ኣሎ።","opts":"a) Hide and stay sad. &nbsp;&nbsp; b) <strong>Say sorry and try again.</strong>"},
    {"q_en":"Someone who was unkind says sorry to you.","q_ti":"ሕማቕ ዝገበረ ሰብ ይቕረታ ይሓተካ።","opts":"a) <strong>Forgive them kindly.</strong> &nbsp;&nbsp; b) Stay angry."},
  ],
  "reflect_write": [
    ("Jonah prayed inside the fish. Where can you pray?","ኣበይ ክትጽሊ ትኽእል?"),
    ("God gives second chances. Who can you forgive today?","ንመን ሎሚ ይቕረ ክትብል ትኽእል?"),
    ("Write a short prayer saying sorry and thank you to God.","ንኣምላኽ ይቕረታን ምስጋናን ዝሓዘ ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help Jonah Reach Nineveh","maze_instr_en":"Guide Jonah from the shore to the city of Nineveh.",
  "maze_instr_ti":"ንዮናስ ካብ ገምገም ናብ ነነዌ ምርሓዮ።",
  "draw_title_en":"Draw Your Own Big Fish","draw_sub_en":"Design a friendly fish","draw_sub_ti":"ዓሳ ስኣል",
  "draw_instr_en":"Draw a big, friendly fish and decorate its scales with patterns.",
  "draw_instr_ti":"ዓባይ ምቕልልቲ ዓሳ ስኣል፡ ቅርፍታ ኸኣ ኣመልክዕ።",
  "craft_title_en":"Craft: Paper-Plate Fish","craft_sub_en":"Make a big fish!","craft_sub_ti":"ዓባይ ዓሳ ስራሕ!",
  "craft_need_en":"You will need: a paper plate or circle, crayons, scissors, glue, paper scraps.",
  "craft_need_ti":"እትደሊ፦ ወረቐት ሸሓኒ፡ ሕብሪ፡ መቐስ፡ ልቖ፡ ወረቐት።",
  "craft_steps": [
    ("Cut a small triangle from the plate for the mouth; glue it on the back as a tail.","ንኣፍ ንእሽቶ ስሉስ ቆሪጽካ ኣብ ድሕሪት ከም ጭራ ኣጣብቖ።"),
    ("Colour the fish and add scales with patterns.","ነታ ዓሳ ሕብራ፡ ቅርፍቲ ወስኽ።"),
    ("Add a big eye and a happy smile.","ዓባይ ዓይንን ፍሽኽታን ወስኽ።"),
    ("Remember: God can rescue us, just like he rescued Jonah!","ዘክር፦ ኣምላኽ ከምቲ ንዮናስ ዘናገፎ የናግፈና!"),
  ],
  "template_title_en":"Fish Template",
  "bookmarks": [("Obey God","ንኣምላኽ ተኣዘዝ"),("God Gives New Starts","ኣምላኽ ሓድሽ ጅማሮ ይህብ")],
  "secret_code": code("OBEYS","GOD IS GOOD","መልሲ፦ OBEYS · GOD IS GOOD (ኣምላኽ ሰናይ እዩ)"),
  "true_false": [
    ("God told Jonah to go to Nineveh.","ኣምላኽ ንዮናስ ናብ ነነዌ በሎ።",True),
    ("Jonah obeyed right away.","ዮናስ ብኡብኡ ተኣዘዘ።",False),
    ("A big fish swallowed Jonah.","ዓባይ ዓሳ ንዮናስ ወሓጠቶ።",True),
    ("Jonah prayed inside the fish.","ዮናስ ኣብ ውሽጢ ዓሳ ጸለየ።",True),
    ("Nineveh ignored God's message.","ነነዌ ንመልእኽቲ ኣምላኽ ነጸገቶ።",False),
  ],
  "fill_blanks": {
    "bank": ["Nineveh","ship","fish","prayed","chance"],
    "sentences": ["God told Jonah to go to __________.",
                  "Jonah ran away on a __________.",
                  "A big __________ swallowed Jonah.",
                  "Inside, Jonah __________ to God.",
                  "God gave Jonah a second __________."],
    "answers": "Nineveh · ship · fish · prayed · chance",
  },
  "acrostic": "JONAH",
  "prayer": {"en":"Dear God, thank you for always hearing me when I pray, even when I have done wrong. Help me to obey you and to forgive others. Thank you for second chances. Amen.",
             "ti":"ኦ ኣምላኽ፡ ጌጋ እኳ እንተገበርኩ፡ ክጽሊ ኸለኹ ኩሉ ግዜ ስለ እትሰምዓኒ የቐንየለይ። ክእዘዘካን ንኻልኦት ይቕረ ክብልን ሓግዘኒ። ኣሜን።"},
  "reflect1_en":"When is it hard to obey? What helps you choose right?","reflect1_ti":"ምእዛዝ መዓስ ይኸብድ?",
  "reflect2_en":"How does it feel to be forgiven?","reflect2_ti":"ይቕረ ኪበሃለልካ ኸመይ ይስመዓካ?",
  "three_lessons": [("Obey God","ንኣምላኽ ተኣዘዝ"),("Say Sorry","ይቕረታ ሕተት"),("God Forgives","ኣምላኽ ይቕረ ይብል")],
  "review_en":"You have learned about Jonah and second chances. Remember these three things:",
  "review_ti":"ብዛዕባ ዮናስን ካልኣይ ዕድልን ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for learning to obey God and forgive, just like Jonah!",
  "cert_line_ti":"ከም ዮናስ ንኣምላኽ ምእዛዝን ይቕረ ምባልን ስለ እተማህረ!",
})

# ===========================================================================
# BOOK 6 — Joseph's Amazing Journey
# ===========================================================================
BOOKS.append({
  "slug": "06-joseph",
  "icon": "scroll", "icon2": "crown",
  "title_en": "Joseph's Amazing Journey",
  "title_ti": "ዜደንቕ ጕዕዞ ዮሴፍ",
  "cover_line_en": "A colour-and-learn activity book about forgiveness, patience and God's plan.",
  "cover_line_ti": "ብዛዕባ ይቕረ ምባል፡ ትዕግስትን መደብ ኣምላኽን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("Joseph", "a boy with a colourful coat and big dreams.", "ዮሴፍ — ሕብራዊ ቀሚሽን ዓበይቲ ሕልምታትን ዝነበሮ ቆልዓ።"),
    ("Jacob", "Joseph's father who loved him.", "ያእቆብ — ኣቦ ዮሴፍ፡ ዘፍቅሮ።"),
    ("The Brothers", "who were jealous of Joseph.", "እቶም ኣሕዋት — ንዮሴፍ ዝቐንኡ።"),
    ("Pharaoh", "the king of Egypt.", "ፈርኦን — ንጉስ ግብጺ።"),
  ],
  "story": [
    {"sub_en":"The Colourful Coat","sub_ti":"እቲ ሕብራዊ ቀሚሽ",
     "paras":[
       ("Joseph was one of twelve brothers. His father Jacob loved him dearly and gave him a beautiful coat of many colours.",
        "ዮሴፍ ካብ ዓሰርተው ክልተ ኣሕዋት ሓደ ነበረ። ኣቦኡ ያእቆብ ኣዝዩ የፍቅሮ ስለ ዝነበረ፡ ብዙሕ ሕብሪ ዘለዎ ጽቡቕ ቀሚሽ ሃቦ።"),
       ("Joseph also had special dreams from God. But his brothers became very jealous of him.",
        "ዮሴፍ ካብ ኣምላኽ ፍሉይ ሕልምታት እውን ነበሮ። ኣሕዋቱ ግና ኣዝዮም ቀንኡሉ።"),
     ]},
    {"sub_en":"Sold by His Brothers","sub_ti":"በ ኣሕዋቱ ተሸጠ",
     "paras":[
       ("One day the jealous brothers took Joseph's coat and sold him to traders going to Egypt. They told their father he was gone.",
        "ሓደ መዓልቲ እቶም ቀናእቲ ኣሕዋት ቀሚሽ ዮሴፍ ወሲዶም ናብ ግብጺ ንዝኸዱ ነጋዶ ሸጥዎ። ንኣቦኦም ከኣ ጠፊኡ በልዎ።"),
       ("In Egypt, Joseph worked hard and stayed honest. Even when he was treated unfairly and put in prison, he trusted God.",
        "ኣብ ግብጺ ዮሴፍ ተጋደለን ቅኑዕ ኮይኑ ጸንሐን። ብዘይ ፍትሒ ተታሒዙ ኣብ ቤት ማእሰርቲ እኳ እንተኣተወ፡ ኣብ ኣምላኽ ተኣመነ።"),
     ]},
    {"sub_en":"Dreams and Wisdom","sub_ti":"ሕልምታትን ጥበብን",
     "paras":[
       ("God gave Joseph the ability to understand dreams. When Pharaoh had a puzzling dream, Joseph explained it.",
        "ኣምላኽ ንዮሴፍ ሕልምታት ናይ ምርዳእ ክእለት ሃቦ። ፈርኦን ዜሕንኽ ሕልሚ ምስ ሓለመ፡ ዮሴፍ ተርጐመሉ።"),
       ("'Seven good years are coming, then seven years of hunger,' said Joseph. 'Store up food now to be ready.'",
        "'ሸውዓተ ጽቡቓት ዓመታት ይመጻ ኣለዋ፡ ደሓር ከኣ ሸውዓተ ዓመታት ጥሜት፡' በለ ዮሴፍ። 'ሕጂ ምግቢ ኣኻዕብቱ።'"),
     ]},
    {"sub_en":"From Prison to Palace","sub_ti":"ካብ ቤት ማእሰርቲ ናብ ቤተ መንግስቲ",
     "paras":[
       ("Pharaoh was amazed at Joseph's wisdom. He put Joseph in charge of all Egypt to save food for the hungry years.",
        "ፈርኦን ብጥበብ ዮሴፍ ተገረመ። ንዓመታት ጥሜት ምግቢ ንምዕቋር፡ ኣብ ልዕሊ ብዘላ ግብጺ ሸሞ።"),
       ("When the famine came, people from many lands came to Egypt to buy food — including Joseph's own brothers!",
        "እቲ ጥሜት ምስ መጸ፡ ካብ ብዙሕ ሃገራት ሰባት ምግቢ ኺዕድጉ ናብ ግብጺ መጹ — ኣሕዋት ዮሴፍ እውን ኣብ ውሽጦም!"),
     ]},
    {"sub_en":"Joseph Forgives","sub_ti":"ዮሴፍ ይቕረ በለ",
     "paras":[
       ("The brothers did not recognise Joseph, but he knew them. Instead of being angry, Joseph forgave them and wept for joy.",
        "እቶም ኣሕዋት ንዮሴፍ ኣየለለይዎን፡ ንሱ ግና ፈለጦም። ኣብ ክንዲ ምቝጣዕ፡ ዮሴፍ ይቕረ በለሎም ብሓጐስ ከኣ ነብዐ።"),
       ("'You meant to harm me, but God used it for good, to save many lives,' Joseph said. The whole family was joyfully reunited.",
        "'ንስኻትኩም ክፉእ ኣሰብኩምለይ፡ ኣምላኽ ግና ንብዙሓት ንምድሓን ንሰናይ ተጠቕመሉ፡' በለ ዮሴፍ። ኩላ ስድራ ብሓጐስ ተጠርነፈት።"),
       ("Joseph teaches us to forgive, to be patient, and to trust that God can bring good even from hard times.",
        "ዮሴፍ ይቕረ ኽንብል፡ ክንዕገስ፡ ኣምላኽ ካብ ጽንኩር እዋን እኳ ሰናይ ከም ዘምጽእ ክንኣምን ይምህረና።"),
     ]},
  ],
  "verse": {"en":"You planned to harm me, but God planned it for good.",
            "ti":"ንስኻትኩም ክፉእ ሓሰብኩምለይ፡ ኣምላኽ ግና ንሰናይ ሓሰቦ።",
            "ref_en":"Genesis 50:20","ref_ti":"ዘፍጥረት 50፡20"},
  "easy_q": [
    {"q_en":"What did Jacob give Joseph?","q_ti":"ያእቆብ ንዮሴፍ እንታይ ሃቦ?","opts":"a) A crown &nbsp;&nbsp; b) <strong>A colourful coat</strong> &nbsp;&nbsp; c) A sword"},
    {"q_en":"Where was Joseph taken?","q_ti":"ዮሴፍ ናበይ ተወስደ?","opts":"a) <strong>Egypt</strong> &nbsp;&nbsp; b) Rome &nbsp;&nbsp; c) Persia"},
    {"q_en":"What could Joseph understand?","q_ti":"ዮሴፍ እንታይ ኪርዳእ ይኽእል ነበረ?","opts":"a) Songs &nbsp;&nbsp; b) <strong>Dreams</strong> &nbsp;&nbsp; c) Maps"},
    {"q_en":"Joseph chose to ___ his brothers.","q_ti":"ዮሴፍ ንኣሕዋቱ ___ መረጸ።","opts":"a) punish &nbsp;&nbsp; b) <strong>forgive</strong> &nbsp;&nbsp; c) ignore"},
  ],
  "hard_q": [
    ("Why were Joseph's brothers jealous of him?","ኣሕዋት ዮሴፍ ስለምንታይ ቀንኡሉ?"),
    ("How did Joseph stay faithful during hard times?","ዮሴፍ ብጽንኩር እዋን ብኸመይ እሙን ኮይኑ ጸንሐ?"),
    ("Why is forgiving others hard? Why is it good?","ንኻልኦት ይቕረ ምባል ስለምንታይ ይኸብድ? ስለምንታይ ጽቡቕ እዩ?"),
    ("Write about a time you forgave someone.","ንሓደ ሰብ ይቕረ ዝበልካሉ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("Jacob gives Joseph a colourful coat.","ያእቆብ ንዮሴፍ ሕብራዊ ቀሚሽ ይህቦ።"),
    ("The jealous brothers sell Joseph.","እቶም ቀናእቲ ኣሕዋት ንዮሴፍ ይሸጥዎ።"),
    ("Joseph works hard and trusts God in Egypt.","ዮሴፍ ኣብ ግብጺ ይጋደልን ይኣምንን።"),
    ("Joseph explains Pharaoh's dream.","ዮሴፍ ንሕልሚ ፈርኦን ይትርጕም።"),
    ("Joseph is put in charge of Egypt.","ዮሴፍ ኣብ ልዕሊ ግብጺ ይሽየም።"),
    ("Joseph forgives his brothers.","ዮሴፍ ንኣሕዋቱ ይቕረ ይብለሎም።"),
  ],
  "ws_words": ["JOSEPH","COAT","DREAM","EGYPT","FORGIVE","BROTHERS","GRAIN","PLAN"],
  "crossword": {
    "spine": "JOSEPH",
    "crossers": ["COAT","DREAM","PLAN"],
    "grid": 13,
    "down_clues": [(1,"He forgave his brothers.","JOSEPH — ዮሴፍ")],
    "across_clues": [(2,"Jacob gave a colourful one.","COAT — ቀሚሽ"),
                     (3,"Joseph could understand these.","DREAM — ሕልሚ"),
                     (4,"God had a good one for Joseph.","PLAN — መደብ")],
    "answer_line": "1 JOSEPH · 2 COAT · 3 DREAM · 4 PLAN",
  },
  "match": [("Coat","ቀሚሽ"),("Dream","ሕልሚ"),("Forgive","ይቕረ በል"),("Brother","ሓው"),("Grain","እኽሊ"),("Plan","መደብ")],
  "colouring": [
    {"title_en":"Colour Joseph's Coat","sub_en":"Many colours","sub_ti":"ብዙሕ ሕብሪ","note_en":"Use as many colours as you can!","note_ti":"ብዙሕ ሕብሪ ተጠቐም!"},
    {"title_en":"Colour the Royal Palace","sub_en":"In Egypt","sub_ti":"ኣብ ግብጺ","note_en":"Add tall palm trees.","note_ti":"ነዋሕቲ ዳዅ ወስኽ።"},
    {"title_en":"Colour the Grain Store","sub_en":"Food for hungry years","sub_ti":"ምግቢ ንዓመታት ጥሜት","note_en":"Draw baskets full of grain.","note_ti":"ብእኽሊ ዝመልኡ ዘንቢላት ስኣል።"},
    {"title_en":"Colour the Happy Family","sub_en":"Together again","sub_ti":"እንደገና ብሓባር","note_en":"Give everyone a big smile.","note_ti":"ንኹሉ ፍሽኽታ ሃቦ።"},
  ],
  "count_word_en":"coats","count_word_ti":"ቀሚሽ","count_sets":[2,4,1,3],
  "count_fact_en":"Joseph was 1 of 12 brothers.","count_fact_ti":"ዮሴፍ ካብ 12 ኣሕዋት ሓደ ነበረ።",
  "lesson_en":"Forgiving like Joseph","lesson_ti":"ከም ዮሴፍ ይቕረ ምባል",
  "scenarios": [
    {"q_en":"A brother or sister breaks your favourite toy by accident.","q_ti":"ሓውኻ ወይ ሓብትኻ ብዘይ ፍቓድ ናውትኻ ሰበሮ።","opts":"a) <strong>Forgive them.</strong> &nbsp;&nbsp; b) Stay angry all day."},
    {"q_en":"Someone treats you unfairly.","q_ti":"ሓደ ሰብ ብዘይ ፍትሒ ይሕዘካ።","opts":"a) Plan revenge. &nbsp;&nbsp; b) <strong>Do good and trust God.</strong>"},
    {"q_en":"You are having a hard time and feel like giving up.","q_ti":"ጽንኩር እዋን ኣሎካ፡ ክትሓድግ ትደሊ።","opts":"a) <strong>Be patient and keep trusting God.</strong> &nbsp;&nbsp; b) Give up."},
  ],
  "reflect_write": [
    ("Joseph forgave his brothers. Who can you forgive?","ንመን ይቕረ ክትብል ትኽእል?"),
    ("Even in prison Joseph trusted God. What helps you stay hopeful?","ተስፋ ንኽትገብር እንታይ ይሕግዘካ?"),
    ("Write a short prayer asking God to help you forgive.","ይቕረ ንኽትብል ሓገዝ ኣምላኽ ዝልምን ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help Joseph's Family Reach Egypt","maze_instr_en":"Guide the brothers through the desert to Egypt to find food.",
  "maze_instr_ti":"ንኣሕዋት ብበረኻ ኣቢሎም ናብ ግብጺ ምርሓዮም።",
  "draw_title_en":"Design Your Own Colourful Coat","draw_sub_en":"Make a coat","draw_sub_ti":"ቀሚሽ ስኣል",
  "draw_instr_en":"Draw a coat and fill it with your favourite colours and patterns.",
  "draw_instr_ti":"ቀሚሽ ስኣል፡ ብዝፈተኻዮ ሕብርታት ምላእ።",
  "craft_title_en":"Craft: Paper Coat of Colours","craft_sub_en":"Make a colourful coat!","craft_sub_ti":"ሕብራዊ ቀሚሽ ስራሕ!",
  "craft_need_en":"You will need: paper, crayons or coloured paper scraps, scissors, glue.",
  "craft_need_ti":"እትደሊ፦ ወረቐት፡ ሕብሪ ወይ ሕብራዊ ወረቐት፡ መቐስ፡ ልቖ።",
  "craft_steps": [
    ("Cut out a coat shape from paper.","ካብ ወረቐት ቅርጺ ቀሚሽ ቆርጽ።"),
    ("Glue on strips of colour or colour in stripes.","ሕብራዊ ወረቐት ኣጣብቕ ወይ ብጋድም ሕብሮ።"),
    ("Add buttons and patterns.","መልጐምን ስእልታትን ወስኽ።"),
    ("Remember: God had a good plan for Joseph, and for you too!","ዘክር፦ ኣምላኽ ንዮሴፍ ጽቡቕ መደብ ነበሮ፡ ንዓኻ'ውን!"),
  ],
  "template_title_en":"Coat Template",
  "bookmarks": [("Forgive Others","ንኻልኦት ይቕረ በል"),("God Has a Plan","ኣምላኽ መደብ ኣለዎ")],
  "secret_code": code("FORGIVES","GOD IS GOOD","መልሲ፦ FORGIVES · GOD IS GOOD (ኣምላኽ ሰናይ እዩ)"),
  "true_false": [
    ("Jacob gave Joseph a colourful coat.","ያእቆብ ንዮሴፍ ሕብራዊ ቀሚሽ ሃቦ።",True),
    ("Joseph's brothers were kind to him.","ኣሕዋት ዮሴፍ ሕያዎት ነበሩ።",False),
    ("Joseph could understand dreams.","ዮሴፍ ሕልሚ ኪርዳእ ይኽእል ነበረ።",True),
    ("Joseph forgave his brothers.","ዮሴፍ ንኣሕዋቱ ይቕረ በለ።",True),
    ("Joseph stayed angry forever.","ዮሴፍ ንሓዋሩ ተቖጢዑ ጸንሐ።",False),
  ],
  "fill_blanks": {
    "bank": ["coat","Egypt","dreams","forgave","plan"],
    "sentences": ["Jacob gave Joseph a colourful __________.",
                  "Joseph was taken to __________.",
                  "God helped Joseph understand __________.",
                  "God had a good __________ all along.",
                  "Joseph __________ his brothers with love."],
    "answers": "coat · Egypt · dreams · plan · forgave",
  },
  "acrostic": "JOSEPH",
  "prayer": {"en":"Dear God, thank you that you have a good plan for me. Help me to be patient and to forgive others, like Joseph. I trust you in every season. Amen.",
             "ti":"ኦ ኣምላኽ፡ ንዓይ ጽቡቕ መደብ ስለ ዘሎካ የቐንየለይ። ከም ዮሴፍ ክዕገስን ንኻልኦት ይቕረ ክብልን ሓግዘኒ። ኣብ ኩሉ እዋን ክኣምነካ እየ። ኣሜን።"},
  "reflect1_en":"Who is someone you want to forgive?","reflect1_ti":"ንመን ይቕረ ክትብል ትደሊ?",
  "reflect2_en":"How does it feel to know God has a plan for you?","reflect2_ti":"ኣምላኽ መደብ ከም ዘለዎ ምፍላጥ ከመይ ይስመዓካ?",
  "three_lessons": [("Forgive","ይቕረ በል"),("Be Patient","ተዓገስ"),("Trust God's Plan","ኣብ መደብ ኣምላኽ ተኣመን")],
  "review_en":"You have learned about Joseph's forgiveness. Remember these three things:",
  "review_ti":"ብዛዕባ ይቕረ ምባል ዮሴፍ ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for forgiving and trusting God's plan, just like Joseph!",
  "cert_line_ti":"ከም ዮሴፍ ይቕረ ስለ ዝበለን ኣብ መደብ ኣምላኽ ስለ ዝተኣመነን!",
})


# ===========================================================================
# BOOK 7 — Moses and the Red Sea
# ===========================================================================
BOOKS.append({
  "slug": "07-moses",
  "icon": "waves", "icon2": "scroll",
  "title_en": "Moses and the Red Sea",
  "title_ti": "ሙሴን ቀይሕ ባሕርን",
  "cover_line_en": "A colour-and-learn activity book about rescue, faith and God's power.",
  "cover_line_ti": "ብዛዕባ ምድሓን፡ እምነትን ሓይሊ ኣምላኽን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("Moses", "the leader God chose to free his people.", "ሙሴ — ንህዝቡ ንምንጋፍ ኣምላኽ ዝሓረዮ መራሒ።"),
    ("The Israelites", "God's people, once slaves in Egypt.", "እስራኤላውያን — ህዝቢ ኣምላኽ፡ ኣብ ግብጺ ባሮት ዝነበሩ።"),
    ("Pharaoh", "the king who held them captive.", "ፈርኦን — ዝሓዞም ንጉስ።"),
    ("God", "who made a path through the sea.", "ኣምላኽ — ብማእከል ባሕሪ መገዲ ዝገበረ።"),
  ],
  "story": [
    {"sub_en":"Let My People Go","sub_ti":"ንህዝበይ ሕደጎም",
     "paras":[
       ("God's people, the Israelites, were slaves in Egypt. They worked hard and cried out to God for help.",
        "ህዝቢ ኣምላኽ እስራኤላውያን ኣብ ግብጺ ባሮት ነበሩ። ተጋደሉ፡ ናብ ኣምላኽ ከኣ ንሓገዝ ጠርዑ።"),
       ("God chose Moses to lead them to freedom. Moses told Pharaoh, 'God says: Let my people go!'",
        "ኣምላኽ ንሙሴ ናብ ናጽነት ኪመርሖም ሓረዮ። ሙሴ ንፈርኦን፡ 'ኣምላኽ፦ ንህዝበይ ሕደጎም ይብል!' በሎ።"),
     ]},
    {"sub_en":"Set Free at Last","sub_ti":"ኣብ መወዳእታ ናጻ ወጹ",
     "paras":[
       ("Pharaoh said no again and again. But after God showed his mighty power, Pharaoh finally let the Israelites leave Egypt.",
        "ፈርኦን ደጋጊሙ ኣበየ። ኣምላኽ ስልጣኑ ምስ ኣርኣየ ግና፡ ፈርኦን ኣብ መወዳእታ ንእስራኤላውያን ካብ ግብጺ ኪወጹ ሓደጎም።"),
       ("The people packed quickly and followed Moses out of Egypt, happy to be free at last.",
        "እቶም ህዝቢ ቀልጢፎም ኣኸቢቦም ንሙሴ ሰዓብዎ፡ ኣብ መወዳእታ ናጻ ብምዃኖም ተሓጐሱ።"),
     ]},
    {"sub_en":"Trapped at the Sea","sub_ti":"ኣብ ባሕሪ ተዓንቀፉ",
     "paras":[
       ("But Pharaoh changed his mind and chased them with his army. The Israelites reached the Red Sea and could go no further.",
        "ፈርኦን ግና ሓሳቡ ቐይሩ ምስ ሰራዊቱ ሰዓቦም። እስራኤላውያን ናብ ቀይሕ ባሕሪ በጺሖም ንቕድሚት ኪኸዱ ኣይከኣሉን።"),
       ("The people were afraid. Moses said, 'Do not be afraid. Stand still and watch how God will rescue you today!'",
        "እቶም ህዝቢ ፈርሁ። ሙሴ፡ 'ኣይትፍርሁ። ደው ኢልኩም ኣምላኽ ሎሚ ብኸመይ ከም ዜናግፈኩም ርኣዩ!' በለ።"),
     ]},
    {"sub_en":"God Parts the Sea","sub_ti":"ኣምላኽ ባሕሪ መቐለ",
     "paras":[
       ("Moses stretched out his hand over the sea. All night God sent a strong wind, and the water divided, making a dry path with walls of water on each side!",
        "ሙሴ ኢዱ ናብ ባሕሪ ዘርግሐ። ኣምላኽ ምሉእ ለይቲ ብርቱዕ ንፋስ ሰደደ፡ እቲ ማይ ተመቕለ፡ ብክልቲኡ ወገን መንደቕ ማይ ዘለዎ ንቑጽ መገዲ ገበረ!"),
       ("The Israelites walked through the sea on dry ground. God had made a way where there seemed to be no way.",
        "እስራኤላውያን ብማእከል ባሕሪ ኣብ ንቑጽ ምድሪ ተጓዕዙ። ኣምላኽ መገዲ ዜብሉ ኣብ ዝመሰለ ስፍራ መገዲ ገበረ።"),
     ]},
    {"sub_en":"Safe on the Other Side","sub_ti":"ኣብ ስግር ብደሓን",
     "paras":[
       ("When the last Israelite was safely across, the walls of water came back together. God's people were saved!",
        "እቲ ዳሕረዋይ እስራኤላዊ ብደሓን ምስ ሰገረ፡ እቲ መንደቕ ማይ ተመልሰ። ህዝቢ ኣምላኽ ድሓኑ!"),
       ("The people sang and danced with joy, thanking God for rescuing them in such a wonderful way.",
        "እቶም ህዝቢ ብሓጐስ ዘመሩን ሰዓሱዑን፡ በዚ ዜደንቕ መገዲ ስለ ዘናገፎም ንኣምላኽ ኣመስገኑ።"),
       ("Moses teaches us that God is powerful and can rescue us, even when things look impossible.",
        "ሙሴ ኣምላኽ ሓያል ምዃኑን ዘይከኣል ኣብ ዝመስለሉ እዋን እኳ ኬናግፈና ኸም ዝኽእልን ይምህረና።"),
     ]},
  ],
  "verse": {"en":"The Lord will fight for you. You only need to remain calm.",
            "ti":"እግዚኣብሄር ኪዋግኣልኩም እዩ፡ ንስኻትኩም ስቕ በሉ።",
            "ref_en":"Exodus 14:14","ref_ti":"ዘጸኣት 14፡14"},
  "easy_q": [
    {"q_en":"Who did God choose to lead his people?","q_ti":"ንህዝቡ ኪመርሕ ኣምላኽ ንመን ሓረየ?","opts":"a) Pharaoh &nbsp;&nbsp; b) <strong>Moses</strong> &nbsp;&nbsp; c) David"},
    {"q_en":"Where were the Israelites slaves?","q_ti":"እስራኤላውያን ኣበይ ባሮት ነበሩ?","opts":"a) <strong>Egypt</strong> &nbsp;&nbsp; b) Persia &nbsp;&nbsp; c) Babylon"},
    {"q_en":"What did God do to the sea?","q_ti":"ኣምላኽ ነታ ባሕሪ እንታይ ገበራ?","opts":"a) Froze it &nbsp;&nbsp; b) <strong>Parted it</strong> &nbsp;&nbsp; c) Dried it forever"},
    {"q_en":"The people walked across on ___ ground.","q_ti":"እቶም ህዝቢ ኣብ ___ ምድሪ ሰገሩ።","opts":"a) wet &nbsp;&nbsp; b) <strong>dry</strong> &nbsp;&nbsp; c) muddy"},
  ],
  "hard_q": [
    ("Why were the Israelites afraid at the sea?","እስራኤላውያን ኣብ ባሕሪ ስለምንታይ ፈርሁ?"),
    ("What did Moses tell the people to do?","ሙሴ ንህዝቢ እንታይ ኪገብሩ በሎም?"),
    ("What does this story teach about trusting God in scary times?","ኣብ ኣፍራሒ እዋን ብዛዕባ ምእማን እንታይ ይምህር?"),
    ("Write about a time God made a way for you.","ኣምላኽ መገዲ ዝገበረልካ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("The Israelites are slaves in Egypt.","እስራኤላውያን ኣብ ግብጺ ባሮት እዮም።"),
    ("Moses says, 'Let my people go!'","ሙሴ፡ 'ንህዝበይ ሕደጎም!' ይብል።"),
    ("The people leave Egypt with Moses.","እቶም ህዝቢ ምስ ሙሴ ካብ ግብጺ ይወጹ።"),
    ("Pharaoh's army traps them at the sea.","ሰራዊት ፈርኦን ኣብ ባሕሪ የዓንቅፎም።"),
    ("God parts the sea into a dry path.","ኣምላኽ ባሕሪ መቒሉ ንቑጽ መገዲ ይገብር።"),
    ("The people cross safely and sing!","እቶም ህዝቢ ብደሓን ሰጊሮም ይዝምሩ!"),
  ],
  "ws_words": ["MOSES","SEA","EGYPT","PATH","FREE","RESCUE","WATER","TRUST"],
  "crossword": {
    "spine": "MOSES",
    "crossers": ["SEA","FREE","SAVE"],
    "grid": 13,
    "down_clues": [(1,"He led God's people out of Egypt.","MOSES — ሙሴ")],
    "across_clues": [(2,"God parted the Red one.","SEA — ባሕሪ"),
                     (3,"No longer a slave.","FREE — ናጻ"),
                     (4,"What God did for his people.","SAVE — ምድሓን")],
    "answer_line": "1 MOSES · 2 SEA · 3 FREE · 4 SAVE",
  },
  "match": [("Sea","ባሕሪ"),("Free","ናጻ"),("Water","ማይ"),("Path","መገዲ"),("Rescue","ምድሓን"),("Leader","መራሒ")],
  "colouring": [
    {"title_en":"Colour the Parted Sea","sub_en":"Walls of water","sub_ti":"መንደቕ ማይ","note_en":"Add fish inside the water walls!","note_ti":"ኣብ ውሽጢ መንደቕ ማይ ዓሳ ወስኽ!"},
    {"title_en":"Colour Moses","sub_en":"With his staff","sub_ti":"ምስ በትሩ","note_en":"Draw his hand stretched out.","note_ti":"ኢዱ ዘርጊሑ ስኣሎ።"},
    {"title_en":"Colour the Waves","sub_en":"God's mighty power","sub_ti":"ሓይሊ ኣምላኽ","note_en":"Use blues and whites.","note_ti":"ሰማያውን ጻዕዳን ተጠቐም።"},
    {"title_en":"Colour the People Celebrating","sub_en":"Safe and free","sub_ti":"ብደሓንን ናጻን","note_en":"Draw people singing and dancing.","note_ti":"ዝዝምሩ ሰባት ስኣል።"},
  ],
  "count_word_en":"waves","count_word_ti":"ማዕበል","count_sets":[2,3,4,1],
  "count_fact_en":"God's wind blew all 1 night.","count_fact_ti":"ንፋስ ኣምላኽ ምሉእ ሓደ ለይቲ ነፈሰ።",
  "lesson_en":"Staying calm and trusting God","lesson_ti":"ህዱእ ኮይንካ ኣብ ኣምላኽ ምእማን",
  "scenarios": [
    {"q_en":"You feel trapped by a problem with no way out.","q_ti":"መውጽኢ ዜብሉ ጸገም ይስመዓካ ኣሎ።","opts":"a) <strong>Stay calm and ask God to help.</strong> &nbsp;&nbsp; b) Panic and give up."},
    {"q_en":"Everyone around you is afraid.","q_ti":"ኩሎም ኣብ ከባቢኻ ዘለዉ ይፈርሁ ኣለዉ።","opts":"a) <strong>Speak calm, kind words.</strong> &nbsp;&nbsp; b) Make it worse."},
    {"q_en":"Something good happens and you are thankful.","q_ti":"ጽቡቕ ነገር ኮይኑ ተመስጊንካ ኣለኻ።","opts":"a) Forget it quickly. &nbsp;&nbsp; b) <strong>Thank God with joy.</strong>"},
  ],
  "reflect_write": [
    ("Moses said, 'Stand still and watch.' When is it good to be calm?","ህዱእ ምዃን መዓስ ጽቡቕ እዩ?"),
    ("God made a way through the sea. What 'sea' do you need help with?","ሓገዝ ብዛዕባ እንታይ ተድሊ?"),
    ("Write a short prayer thanking God for his power.","ኣምላኽ ስለ ሓይሉ እተመስግን ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help the People Cross the Sea","maze_instr_en":"Guide the Israelites along the dry path to the other side.",
  "maze_instr_ti":"ንእስራኤላውያን ብንቑጽ መገዲ ናብ ስግር ምርሓዮም።",
  "draw_title_en":"Draw the Parted Sea","draw_sub_en":"Make your own scene","draw_sub_ti":"ናትካ ትርኢት ስኣል",
  "draw_instr_en":"Draw the two walls of water and the people walking safely between them.",
  "draw_instr_ti":"ክልቲኡ መንደቕ ማይን ኣብ ማእከሎም ብደሓን ዝኸዱ ሰባትን ስኣል።",
  "craft_title_en":"Craft: Parting Sea Card","craft_sub_en":"Make a moving sea!","craft_sub_ti":"ዝንቀሳቐስ ባሕሪ ስራሕ!",
  "craft_need_en":"You will need: blue paper, a sheet for the base, scissors, glue, crayons.",
  "craft_need_ti":"እትደሊ፦ ሰማያዊ ወረቐት፡ መሰረት ወረቐት፡ መቐስ፡ ልቖ፡ ሕብሪ።",
  "craft_steps": [
    ("Draw a dry path down the middle of your base sheet.","ኣብ ማእከል እቲ ወረቐት ንቑጽ መገዲ ስኣል።"),
    ("Cut two blue 'water walls' and glue one on each side.","ክልተ ሰማያዊ መንደቕ ማይ ቆሪጽካ ኣብ ክልቲኡ ወገን ኣጣብቕ።"),
    ("Draw little people walking through the middle.","ኣብ ማእከል ዝኸዱ ናእሽቱ ሰባት ስኣል።"),
    ("Remember: God can make a way where there seems to be none!","ዘክር፦ ኣምላኽ መገዲ ዜብሉ ኣብ ዝመስል መገዲ ኪገብር ይኽእል!"),
  ],
  "template_title_en":"Wave Template",
  "bookmarks": [("Stay Calm","ህዱእ ኹን"),("God Makes a Way","ኣምላኽ መገዲ ይገብር")],
  "secret_code": code("SAVES","GOD IS GOOD","መልሲ፦ SAVES · GOD IS GOOD (ኣምላኽ ሰናይ እዩ)"),
  "true_false": [
    ("Moses led God's people.","ሙሴ ንህዝቢ ኣምላኽ መርሐ።",True),
    ("The people were free from the start.","እቶም ህዝቢ ካብ መጀመርታ ናጻ ነበሩ።",False),
    ("God parted the Red Sea.","ኣምላኽ ቀይሕ ባሕሪ መቐለ።",True),
    ("The people crossed on dry ground.","እቶም ህዝቢ ኣብ ንቑጽ ምድሪ ሰገሩ።",True),
    ("Moses told the people to panic.","ሙሴ ንህዝቢ ኪሽበሩ በሎም።",False),
  ],
  "fill_blanks": {
    "bank": ["Moses","Egypt","sea","dry","free"],
    "sentences": ["God chose __________ to lead the people.",
                  "The Israelites were slaves in __________.",
                  "God parted the Red __________.",
                  "The people walked across on __________ ground.",
                  "At last God's people were __________."],
    "answers": "Moses · Egypt · sea · dry · free",
  },
  "acrostic": "MOSES",
  "prayer": {"en":"Dear God, thank you that you are powerful and can rescue me. When I feel trapped or scared, help me to stay calm and trust you. You always make a way. Amen.",
             "ti":"ኦ ኣምላኽ፡ ሓያል ስለ ዝኾንካን ከተናግፈኒ ስለ እትኽእልን የቐንየለይ። ተዓንቂፈ ወይ ፈሪሐ ኸለኹ፡ ህዱእ ኮይነ ክኣምነካ ሓግዘኒ። ኣሜን።"},
  "reflect1_en":"What helps you stay calm when you are afraid?","reflect1_ti":"ክትፈርህ ከለኻ ህዱእ ንኽትከውን እንታይ ይሕግዘካ?",
  "reflect2_en":"How does it feel to know God is powerful?","reflect2_ti":"ኣምላኽ ሓያል ምዃኑ ምፍላጥ ከመይ ይስመዓካ?",
  "three_lessons": [("Stay Calm","ህዱእ ኹን"),("Trust God","ኣብ ኣምላኽ ተኣመን"),("God Is Mighty","ኣምላኽ ሓያል እዩ")],
  "review_en":"You have learned about Moses and the Red Sea. Remember these three things:",
  "review_ti":"ብዛዕባ ሙሴን ቀይሕ ባሕርን ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for trusting God's mighty power, just like Moses!",
  "cert_line_ti":"ከም ሙሴ ኣብ ሓይሊ ኣምላኽ ስለ ዝተኣመነን!",
})

# ===========================================================================
# BOOK 8 — The Good Samaritan
# ===========================================================================
BOOKS.append({
  "slug": "08-good-samaritan",
  "icon": "heart", "icon2": "scroll",
  "title_en": "The Good Samaritan",
  "title_ti": "እቲ ሕያዋይ ሳምራዊ",
  "cover_line_en": "A colour-and-learn activity book about kindness, mercy and loving your neighbour.",
  "cover_line_ti": "ብዛዕባ ሕያውነት፡ ምሕረትን ንብጻይካ ምፍቃርን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("The Hurt Traveller", "a man who was robbed and helped.", "እቲ እተጐድአ ገያሻይ — እተዘምተ ሰብኣይ።"),
    ("The Priest", "who passed by on the other side.", "እቲ ኻህን — በቲ ኻልእ ወገን ሓለፈ።"),
    ("The Levite", "who also passed by.", "እቲ ሌዋዊ — ንሱ እውን ሓለፈ።"),
    ("The Good Samaritan", "who stopped to help.", "እቲ ሕያዋይ ሳምራዊ — ደው ኢሉ ዝሓገዘ።"),
  ],
  "story": [
    {"sub_en":"A Question for Jesus","sub_ti":"ንየሱስ ሕቶ",
     "paras":[
       ("One day a man asked Jesus, 'Who is my neighbour?' Jesus answered by telling a wonderful story.",
        "ሓደ መዓልቲ ሓደ ሰብ ንየሱስ፡ 'ብጻየይ መን እዩ?' ኢሉ ሓተቶ። የሱስ ብጹብቕ ታሪኽ መለሰሉ።"),
       ("'A man was travelling on a lonely road,' Jesus began.",
        "'ሓደ ሰብኣይ በ በይናዊ መገዲ ይጓዓዝ ነበረ፡' ኢሉ የሱስ ጀመረ።"),
     ]},
    {"sub_en":"Robbers on the Road","sub_ti":"ኸተርቲ ኣብ መገዲ",
     "paras":[
       ("Suddenly, robbers attacked the traveller. They took everything he had and hurt him, leaving him on the ground.",
        "ብድንገት ኸተርቲ ነቲ ገያሻይ ወቕዕዎ። ዘለዎ ኹሉ ወሲዶም ጐዲኦም ኣብ ምድሪ ሓደግዎ።"),
       ("The poor man could not get up. He needed someone to help him.",
        "እቲ ውጹዕ ሰብኣይ ኪትንስእ ኣይከኣለን። ዝሕግዞ ሰብ የድልዮ ነበረ።"),
     ]},
    {"sub_en":"Two Men Pass By","sub_ti":"ክልተ ሰባት ሓለፉ",
     "paras":[
       ("A priest came down the road. He saw the hurt man — but he crossed to the other side and walked past.",
        "ሓደ ኻህን በቲ መገዲ መጸ። ነቲ እተጐድአ ሰብኣይ ረኣዮ — ግና ናብቲ ኻልእ ወገን ሰጊሩ ሓለፎ።"),
       ("Then a Levite came. He also saw the man, but he too passed by without helping.",
        "ደሓር ሓደ ሌዋዊ መጸ። ንሱ እውን ነቲ ሰብኣይ ረኣዮ፡ ግና ብዘይ ምሕጋዝ ሓለፎ።"),
     ]},
    {"sub_en":"The Kind Samaritan","sub_ti":"እቲ ሕያዋይ ሳምራዊ",
     "paras":[
       ("Next, a Samaritan came along. Many people thought Samaritans were strangers, but this man had a kind heart.",
        "ቀጺሉ ሓደ ሳምራዊ መጸ። ብዙሓት ሰባት ንሳምራውያን ጓኖት ገይሮም ይሓስቡ ነበሩ፡ እዚ ሰብኣይ ግና ሕያዋይ ልቢ ነበሮ።"),
       ("He felt sorry for the hurt man. He cleaned and bandaged his wounds, lifted him onto his own donkey, and took him to an inn.",
        "ነቲ እተጐድአ ሰብኣይ ደንገጸሉ። ቍስሉ ኣጽርዩ ጠቕለለ፡ ናብ ኣድጉ ኣደየቦ፡ ናብ ማዕረፎ ኸኣ ወሰዶ።"),
     ]},
    {"sub_en":"Go and Do the Same","sub_ti":"ኪድ ከምኡ ግበር",
     "paras":[
       ("The Samaritan paid the innkeeper to care for the man until he was well. He was a true neighbour.",
        "እቲ ሳምራዊ ክሳብ ዝሓዊ ኺከናኸኖ ንዋና እቲ ማዕረፎ ኸፈሎ። ናይ ሓቂ ብጻይ ነበረ።"),
       ("Jesus asked, 'Which one was a good neighbour?' The answer was clear: the one who showed kindness and mercy.",
        "የሱስ፡ 'ካብዞም ሰለስተ ጽቡቕ ብጻይ መን ነበረ?' ኢሉ ሓተተ። መልሱ ንጹር ነበረ፦ እቲ ሕያውነትን ምሕረትን ዘርኣየ።"),
       ("Then Jesus said, 'Go and do the same.' We are neighbours to anyone who needs our help and kindness.",
        "ሽዑ የሱስ፡ 'ኪድ ከምኡ ግበር' በለ። ንዝኾነ ሓገዝና ዜድልዮ ሰብ ብጻዩ ኢና።"),
     ]},
  ],
  "verse": {"en":"Love your neighbour as you love yourself.",
            "ti":"ንብጻይካ ኸም ነፍስኻ ኣፍቅሮ።",
            "ref_en":"Luke 10:27","ref_ti":"ሉቃስ 10፡27"},
  "easy_q": [
    {"q_en":"What happened to the traveller?","q_ti":"ነቲ ገያሻይ እንታይ ኮነ?","opts":"a) He got lost &nbsp;&nbsp; b) <strong>Robbers hurt him</strong> &nbsp;&nbsp; c) He slept"},
    {"q_en":"Who stopped to help?","q_ti":"ደው ኢሉ ዝሓገዘ መን ነበረ?","opts":"a) The priest &nbsp;&nbsp; b) The Levite &nbsp;&nbsp; c) <strong>The Samaritan</strong>"},
    {"q_en":"What did the Samaritan use to carry the man?","q_ti":"እቲ ሳምራዊ ብምንታይ ኣመላለሶ?","opts":"a) A cart &nbsp;&nbsp; b) <strong>A donkey</strong> &nbsp;&nbsp; c) A boat"},
    {"q_en":"Jesus said, 'Go and do the ___.'","q_ti":"የሱስ፡ 'ኪድ ___ ግበር' በለ።","opts":"a) <strong>same</strong> &nbsp;&nbsp; b) opposite &nbsp;&nbsp; c) nothing"},
  ],
  "hard_q": [
    ("Why do you think the priest and Levite did not stop?","እቲ ኻህንን ሌዋውን ስለምንታይ ደው ኣይበሉን ትብል?"),
    ("What made the Samaritan a good neighbour?","ነቲ ሳምራዊ ጽቡቕ ብጻይ ዝገበሮ እንታይ እዩ?"),
    ("Who are the 'neighbours' around you that need kindness?","ሕያውነት ዜድልዮም ኣብ ከባቢኻ ዘለዉ ብጾት መን እዮም?"),
    ("Write about a time you helped someone.","ንሓደ ሰብ ዝሓገዝካሉ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("A man asks Jesus, 'Who is my neighbour?'","ሓደ ሰብ ንየሱስ ብጻየይ መን እዩ ይብሎ።"),
    ("Robbers hurt a traveller on the road.","ኸተርቲ ንገያሻይ ኣብ መገዲ ይጐድእዎ።"),
    ("A priest passes by without helping.","ሓደ ኻህን ብዘይ ምሕጋዝ ይሓልፍ።"),
    ("A Levite passes by too.","ሓደ ሌዋዊ እውን ይሓልፍ።"),
    ("The Samaritan stops and helps.","እቲ ሳምራዊ ደው ኢሉ ይሕግዝ።"),
    ("Jesus says, 'Go and do the same.'","የሱስ ኪድ ከምኡ ግበር ይብል።"),
  ],
  "ws_words": ["KIND","HELP","MERCY","LOVE","DONKEY","NEIGHBOUR","CARE","GOOD"],
  "crossword": {
    "spine": "MERCY",
    "crossers": ["HELP","ROAD","CARE"],
    "grid": 13,
    "down_clues": [(1,"Showing pity and help.","MERCY — ምሕረት")],
    "across_clues": [(2,"What the Samaritan gave.","HELP — ሓገዝ"),
                     (3,"Where the man was hurt.","ROAD — መገዲ"),
                     (4,"To look after someone.","CARE — ምክንኻን")],
    "answer_line": "1 MERCY · 2 HELP · 3 ROAD · 4 CARE",
  },
  "match": [("Kind","ሕያዋይ"),("Help","ሓገዝ"),("Love","ፍቕሪ"),("Mercy","ምሕረት"),("Donkey","ኣድጊ"),("Neighbour","ብጻይ")],
  "colouring": [
    {"title_en":"Colour the Good Samaritan","sub_en":"He helped a stranger","sub_ti":"ንጓና ሓገዘ","note_en":"Give him a kind, gentle face.","note_ti":"ሕያዋይ ገጽ ሃቦ።"},
    {"title_en":"Colour the Donkey","sub_en":"Carrying the hurt man","sub_ti":"ነቲ ሕሙም ተሰኪሙ","note_en":"Add a soft blanket.","note_ti":"ልስሉስ ኮቦርታ ወስኽ።"},
    {"title_en":"Colour the Road","sub_en":"The lonely road","sub_ti":"እቲ በይናዊ መገዲ","note_en":"Draw hills and rocks.","note_ti":"ኣኽራንን ኣእማንን ስኣል።"},
    {"title_en":"Colour a Heart of Kindness","sub_en":"Love your neighbour","sub_ti":"ንብጻይካ ኣፍቅር","note_en":"Fill the heart with kind words.","note_ti":"ነቲ ልቢ ብሕያዋይ ቃላት ምላእ።"},
  ],
  "count_word_en":"hearts","count_word_ti":"ልብታት","count_sets":[3,2,4,1],
  "count_fact_en":"3 people passed; 1 helped.","count_fact_ti":"3 ሓለፉ፡ 1 ሓገዘ።",
  "lesson_en":"Being kind like the Samaritan","lesson_ti":"ከም ሳምራዊ ሕያዋይ ምዃን",
  "scenarios": [
    {"q_en":"You see someone fall down and drop their things.","q_ti":"ሓደ ሰብ ወዲቑ ንብረቱ በቲኑ ትርኢ።","opts":"a) <strong>Stop and help them up.</strong> &nbsp;&nbsp; b) Walk past."},
    {"q_en":"A child no one likes needs a partner for a game.","q_ti":"ሓደ ቆልዓ መጻወቲ የብሉን።","opts":"a) Leave them out. &nbsp;&nbsp; b) <strong>Be their kind partner.</strong>"},
    {"q_en":"Someone is sad and sitting alone.","q_ti":"ሓደ ሰብ ጐሂዩ በይኑ ተቐሚጡ ኣሎ።","opts":"a) <strong>Sit with them and be kind.</strong> &nbsp;&nbsp; b) Ignore them."},
  ],
  "reflect_write": [
    ("The Samaritan helped even a stranger. Who can you be kind to?","ንመን ሕያዋይ ክትከውን ትኽእል?"),
    ("Sometimes helping costs us time or money. Why is it still good?","ምሕጋዝ ስለምንታይ ጽቡቕ እዩ?"),
    ("Write a short prayer asking God for a kind heart.","ንኣምላኽ ሕያዋይ ልቢ ዝልምን ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help the Samaritan Reach the Inn","maze_instr_en":"Guide the Samaritan and the donkey along the road to the inn.",
  "maze_instr_ti":"ንሳምራውን ኣድግን ናብ ማዕረፎ ምርሓዮም።",
  "draw_title_en":"Draw an Act of Kindness","draw_sub_en":"Show you helping","draw_sub_ti":"ክትሕግዝ ከለኻ ስኣል",
  "draw_instr_en":"Draw a picture of yourself doing something kind for someone.",
  "draw_instr_ti":"ንሓደ ሰብ ሕያውነት እናገበርካ ስኣል።",
  "craft_title_en":"Craft: Kindness Heart Chain","craft_sub_en":"Make a chain of good deeds!","craft_sub_ti":"ሰንሰለት ሰናይ ግብሪ ስራሕ!",
  "craft_need_en":"You will need: coloured paper, scissors, glue, a pen.",
  "craft_need_ti":"እትደሊ፦ ሕብራዊ ወረቐት፡ መቐስ፡ ልቖ፡ ብርዒ።",
  "craft_steps": [
    ("Cut several paper hearts.","ብዙሓት ልብታት ወረቐት ቆርጽ።"),
    ("On each heart, write one kind thing you can do.","ኣብ ነፍሲ ወከፍ ልቢ ሓደ ሕያዋይ ግብሪ ጽሓፍ።"),
    ("Glue the hearts into a chain or hang them up.","ነቶም ልብታት ከም ሰንሰለት ኣጣብቕ።"),
    ("Do one kind act each day. Love your neighbour!","መዓልታዊ ሓደ ሕያዋይ ግብሪ ግበር። ንብጻይካ ኣፍቅር!"),
  ],
  "template_title_en":"Heart Template",
  "bookmarks": [("Be Kind","ሕያዋይ ኹን"),("Love Your Neighbour","ንብጻይካ ኣፍቅር")],
  "secret_code": code("KINDNESS","GOD IS LOVE","መልሲ፦ KINDNESS · GOD IS LOVE (ኣምላኽ ፍቕሪ እዩ)"),
  "true_false": [
    ("Robbers hurt the traveller.","ኸተርቲ ንገያሻይ ጐድእዎ።",True),
    ("The priest stopped to help.","እቲ ኻህን ደው ኢሉ ሓገዘ።",False),
    ("The Samaritan helped the man.","እቲ ሳምራዊ ነቲ ሰብኣይ ሓገዞ።",True),
    ("Jesus said to love our neighbour.","የሱስ ንብጻይና ኸነፍቅር በለ።",True),
    ("Jesus said to ignore hurt people.","የሱስ ንእተጐድኡ ኽንርስዖም በለ።",False),
  ],
  "fill_blanks": {
    "bank": ["neighbour","robbers","Samaritan","donkey","kind"],
    "sentences": ["A man asked, 'Who is my __________?'",
                  "The traveller was hurt by __________.",
                  "A good __________ stopped to help.",
                  "He carried the man on his __________.",
                  "Jesus wants us to be __________ to everyone."],
    "answers": "neighbour · robbers · Samaritan · donkey · kind",
  },
  "acrostic": "KIND",
  "prayer": {"en":"Dear God, thank you for loving me. Help me to have a kind heart and to help people in need, like the Good Samaritan. Teach me to love my neighbour. Amen.",
             "ti":"ኦ ኣምላኽ፡ ስለ እተፍቅረኒ የቐንየለይ። ከም እቲ ሕያዋይ ሳምራዊ ሕያዋይ ልቢ ሃበኒ፡ ንዜድልዮም ክሕግዝ ሓግዘኒ። ንብጻየይ ከፍቅር ምሃረኒ። ኣሜን።"},
  "reflect1_en":"Who around you needs kindness today?","reflect1_ti":"ሎሚ ኣብ ከባቢኻ ሕያውነት ዜድልዮ መን ኣሎ?",
  "reflect2_en":"How does it feel when someone is kind to you?","reflect2_ti":"ሓደ ሰብ ሕያዋይ ኪኾነልካ ኸሎ ኸመይ ይስመዓካ?",
  "three_lessons": [("Be Kind","ሕያዋይ ኹን"),("Show Mercy","ምሕረት ኣርኢ"),("Love Others","ንኻልኦት ኣፍቅር")],
  "review_en":"You have learned about the Good Samaritan. Remember these three things:",
  "review_ti":"ብዛዕባ እቲ ሕያዋይ ሳምራዊ ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for being kind and loving your neighbour, like the Good Samaritan!",
  "cert_line_ti":"ከም እቲ ሕያዋይ ሳምራዊ ሕያዋይ ስለ ዝኾነን ንብጻዩ ስለ ዘፍቀረን!",
})


# ===========================================================================
# BOOK 9 — Jesus Feeds the Five Thousand
# ===========================================================================
BOOKS.append({
  "slug": "09-feeding-5000",
  "icon": "basket", "icon2": "fish",
  "title_en": "Jesus Feeds the Five Thousand",
  "title_ti": "የሱስ ንሓሙሽተ ሽሕ መገበ",
  "cover_line_en": "A colour-and-learn activity book about sharing, thankfulness and God's provision.",
  "cover_line_ti": "ብዛዕባ ምክፍፋል፡ ምስጋናን ቀረብ ኣምላኽን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("Jesus", "who cared for the crowd.", "የሱስ — ነቲ ህዝቢ ዝተኸናኸነ።"),
    ("The Boy", "who shared his lunch.", "እቲ ቆልዓ — ምሳሑ ዝኸፈለ።"),
    ("The Disciples", "Jesus' helpers.", "እቶም ደቀ መዛሙርቲ — ሓገዝቲ የሱስ።"),
    ("The Crowd", "over five thousand hungry people.", "እቲ ህዝቢ — ካብ ሓሙሽተ ሽሕ ንላዕሊ ጥሙያት።"),
  ],
  "story": [
    {"sub_en":"A Huge Crowd","sub_ti":"ብዙሕ ህዝቢ",
     "paras":[
       ("One day a huge crowd followed Jesus to a quiet place. There were more than five thousand people who came to hear him teach.",
        "ሓደ መዓልቲ ብዙሕ ህዝቢ ንየሱስ ናብ ጭምት ስፍራ ሰዓብዎ። ካብ ሓሙሽተ ሽሕ ንላዕሊ ሰባት ትምህርቱ ኪሰምዑ መጹ።"),
       ("Jesus taught them all day. As evening came, the people were tired and very hungry.",
        "የሱስ ምሉእ መዓልቲ መሃሮም። ምሸት ምስ ኮነ፡ እቶም ህዝቢ ደኸሙን ኣዝዮም ጠመዩን።"),
     ]},
    {"sub_en":"So Many to Feed","sub_ti":"ብዙሓት ዚምገቡ",
     "paras":[
       ("The disciples said, 'Send the people away to buy food.' But Jesus said, 'You give them something to eat.'",
        "እቶም ደቀ መዛሙርቲ፡ 'ነቶም ሰባት ምግቢ ኺዕድጉ ስደዶም' በሉ። የሱስ ግና፡ 'ንስኻትኩም ዚብልዑ ሃብዎም' በለ።"),
       ("They were worried. 'We do not have enough money to feed all these people!' they said.",
        "ተጨነቑ። 'ንኹሎም እዞም ሰባት ንምምጋብ እኹል ገንዘብ የብልናን!' በሉ።"),
     ]},
    {"sub_en":"A Boy's Small Lunch","sub_ti":"ንእሽቶ ምሳሕ ቆልዓ",
     "paras":[
       ("Then a boy came forward. He had five small loaves of bread and two little fish. It was not much, but he gladly shared it.",
        "ሽዑ ሓደ ቆልዓ ቀረበ። ሓሙሽተ ንኣሽቱ እንጌራን ክልተ ንኣሽቱ ዓሳን ነበሮ። ብዙሕ ኣይነበረን፡ ግና ብሓጐስ ከፈሎ።"),
       ("The disciples wondered, 'What good is so little food for so many people?'",
        "እቶም ደቀ መዛሙርቲ፡ 'እዚ ዅሉ ንእሽቶ ምግቢ ንኸምዚ ብዙሕ ህዝቢ እንታይ ይጠቅም?' ኢሎም ተገረሙ።"),
     ]},
    {"sub_en":"Jesus Gives Thanks","sub_ti":"የሱስ ኣመስገነ",
     "paras":[
       ("Jesus took the five loaves and two fish. He looked up to heaven, gave thanks to God, and began to break the bread.",
        "የሱስ ነቲ ሓሙሽተ እንጌራን ክልተ ዓሳን ወሰደ። ናብ ሰማይ ጠሚቱ ንኣምላኽ ኣመስገነ፡ ነቲ እንጌራ ኪቘርስ ጀመረ።"),
       ("The disciples passed the food around. Amazingly, it kept multiplying — there was more than enough for everyone!",
        "እቶም ደቀ መዛሙርቲ ነቲ ምግቢ ኣመላለስዎ። ዜደንቕ ኮይኑ፡ እናበዝሐ ኸደ — ንኹሉ እኹልን ተረፍን ኮነ!"),
     ]},
    {"sub_en":"Twelve Baskets Left Over","sub_ti":"ዓሰርተው ክልተ መtroኹት ተረፈ",
     "paras":[
       ("Everyone ate until they were full. Then the disciples gathered the leftovers — twelve whole baskets full!",
        "ኩሉ ሰብ ክሳብ ዝጸግብ በልዐ። ደሓር እቶም ደቀ መዛሙርቲ ነቲ ተረፍ ኣከብዎ — ዓሰርተው ክልተ ምሉእ መtroኹት!"),
       ("From one boy's small lunch, Jesus fed thousands. When we share what we have, God can do amazing things.",
        "ካብ ንእሽቶ ምሳሕ ሓደ ቆልዓ፡ የሱስ ንኣሽሓት መገበ። ዘሎና ኽንካፈል ከለና፡ ኣምላኽ ዜደንቕ ነገራት ኪገብር ይኽእል።"),
       ("Jesus teaches us to share, to be thankful, and to trust that God will provide what we need.",
        "የሱስ ኽንካፈል፡ ከነመስግን፡ ኣምላኽ ዜድልየና ኸም ዜዳሉ ኽንኣምን ይምህረና።"),
     ]},
  ],
  "verse": {"en":"They all ate as much as they wanted.",
            "ti":"ኩሎም ከም ዝደለይዎ በልዑ ጸገቡ።",
            "ref_en":"John 6:11","ref_ti":"ዮሃንስ 6፡11"},
  "easy_q": [
    {"q_en":"How many people were there?","q_ti":"ክንደይ ሰባት ነበሩ?","opts":"a) Fifty &nbsp;&nbsp; b) Five hundred &nbsp;&nbsp; c) <strong>Five thousand</strong>"},
    {"q_en":"What did the boy share?","q_ti":"እቲ ቆልዓ እንታይ ከፈለ?","opts":"a) <strong>Loaves and fish</strong> &nbsp;&nbsp; b) Fruit &nbsp;&nbsp; c) Water"},
    {"q_en":"What did Jesus do before sharing?","q_ti":"የሱስ ቅድሚ ምክፍፋል እንታይ ገበረ?","opts":"a) Slept &nbsp;&nbsp; b) <strong>Gave thanks</strong> &nbsp;&nbsp; c) Left"},
    {"q_en":"How many baskets were left over?","q_ti":"ክንደይ መtroኹት ተረፈ?","opts":"a) Two &nbsp;&nbsp; b) <strong>Twelve</strong> &nbsp;&nbsp; c) None"},
  ],
  "hard_q": [
    ("How do you think the boy felt when he shared his lunch?","እቲ ቆልዓ ምሳሑ ኺካፈል ከሎ ኸመይ ተሰሚዕዎ ይኸውን?"),
    ("Why did Jesus give thanks before the meal?","የሱስ ቅድሚ ምግቢ ስለምንታይ ኣመስገነ?"),
    ("What do you have that you could share with others?","ምስ ካልኦት እትካፈሎ እንታይ ኣሎካ?"),
    ("Write about a time someone shared with you.","ሓደ ሰብ ምሳኻ ዝተኻፈለሉ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("A huge crowd follows Jesus.","ብዙሕ ህዝቢ ንየሱስ ይስዕቦ።"),
    ("Evening comes and the people are hungry.","ምሸት ኮይኑ እቶም ህዝቢ ይጠምዩ።"),
    ("A boy shares five loaves and two fish.","ሓደ ቆልዓ ሓሙሽተ እንጌራን ክልተ ዓሳን ይካፈል።"),
    ("Jesus gives thanks and breaks the bread.","የሱስ ኣመስጊኑ ነቲ እንጌራ ይቘርስ።"),
    ("Everyone eats until they are full.","ኩሉ ሰብ ክሳብ ዝጸግብ ይበልዕ።"),
    ("Twelve baskets of food are left over.","ዓሰርተው ክልተ መtroኹት ምግቢ ይተርፍ።"),
  ],
  "ws_words": ["JESUS","BREAD","FISH","SHARE","THANKS","BASKETS","LOAVES","CROWD"],
  "crossword": {
    "spine": "BREAD",
    "crossers": ["SHARE","THANK","FOOD"],
    "grid": 13,
    "down_clues": [(1,"Five loaves of this.","BREAD — እንጌራ")],
    "across_clues": [(2,"What the boy did with his lunch.","SHARE — ምክፋል"),
                     (3,"Jesus did this to God first.","THANK — ምስጋና"),
                     (4,"There was more than enough of it.","FOOD — ምግቢ")],
    "answer_line": "1 BREAD · 2 SHARE · 3 THANK · 4 FOOD",
  },
  "match": [("Bread","እንጌራ"),("Fish","ዓሳ"),("Share","ተኻፈል"),("Thanks","ምስጋና"),("Basket","ዘንቢል"),("Crowd","ህዝቢ")],
  "colouring": [
    {"title_en":"Colour the Basket of Bread","sub_en":"Loaves and fish","sub_ti":"እንጌራን ዓሳን","note_en":"Fill the basket right up!","note_ti":"ነቲ ዘንቢል ምላእ!"},
    {"title_en":"Colour the Two Fish","sub_en":"The boy's lunch","sub_ti":"ምሳሕ ቆልዓ","note_en":"Give them shiny scales.","note_ti":"ዘንጸባርቕ ቅርፍቲ ሃቦም።"},
    {"title_en":"Colour the Loaves","sub_en":"Five small loaves","sub_ti":"ሓሙሽተ እንጌራ","note_en":"How many can you count?","note_ti":"ክንደይ ትቖጽር?"},
    {"title_en":"Colour the Happy Crowd","sub_en":"Everyone was full","sub_ti":"ኩሉ ጸገበ","note_en":"Draw many smiling faces.","note_ti":"ብዙሕ ፍሽኽ ዝብል ገጻት ስኣል።"},
  ],
  "count_word_en":"loaves","count_word_ti":"እንጌራ","count_sets":[5,2,4,3],
  "count_fact_en":"5 loaves + 2 fish fed 5000!","count_fact_ti":"5 እንጌራን 2 ዓሳን ን 5000 መገበ!",
  "lesson_en":"Sharing like the boy","lesson_ti":"ከም እቲ ቆልዓ ምክፍፋል",
  "scenarios": [
    {"q_en":"You have a snack and a friend has none.","q_ti":"መቐረ ኣሎካ፡ ፈታዊኻ ግና የብሉን።","opts":"a) <strong>Share some with them.</strong> &nbsp;&nbsp; b) Eat it all yourself."},
    {"q_en":"There is one toy and two of you.","q_ti":"ሓደ መጻወቲ ኣሎ፡ ንስኻትኩም ክልተ ኢኹም።","opts":"a) Grab it first. &nbsp;&nbsp; b) <strong>Take turns and share.</strong>"},
    {"q_en":"You receive a nice gift.","q_ti":"ጽቡቕ ህያብ ተቐቢልካ።","opts":"a) <strong>Say thank you with a happy heart.</strong> &nbsp;&nbsp; b) Complain it's not enough."},
  ],
  "reflect_write": [
    ("The boy shared even though he had little. What can you share?","እንታይ ክትካፈል ትኽእል?"),
    ("Jesus gave thanks. Write three things you are thankful for.","እተመስግነሉ ሰለስተ ነገራት ጽሓፍ።"),
    ("Write a short prayer thanking God for what he provides.","ኣምላኽ ስለ ዜዳልወልካ እተመስግን ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help Pass the Baskets Around","maze_instr_en":"Guide the disciple with the basket to feed the hungry crowd.",
  "maze_instr_ti":"ንደቀ መዝሙር ምስ ዘንቢሉ ናብቲ ጥሙይ ህዝቢ ምርሓዮ።",
  "draw_title_en":"Draw Your Favourite Meal to Share","draw_sub_en":"Design a meal","draw_sub_ti":"ምግቢ ስኣል",
  "draw_instr_en":"Draw a meal you would love to share with your family or friends.",
  "draw_instr_ti":"ምስ ስድራኻ ኽትካፈሎ እትደሊ ምግቢ ስኣል።",
  "craft_title_en":"Craft: Paper Basket of Loaves & Fish","craft_sub_en":"Make a food basket!","craft_sub_ti":"ዘንቢል ምግቢ ስራሕ!",
  "craft_need_en":"You will need: paper, crayons, scissors, glue.",
  "craft_need_ti":"እትደሊ፦ ወረቐት፡ ሕብሪ፡ መቐስ፡ ልቖ።",
  "craft_steps": [
    ("Colour and cut out a basket shape.","ቅርጺ ዘንቢል ሕብሮ ቆርጾ።"),
    ("Draw and cut five loaves and two fish.","ሓሙሽተ እንጌራን ክልተ ዓሳን ስኣል ቆርጾ።"),
    ("Glue the food into the basket.","ነቲ ምግቢ ኣብ ዘንቢል ኣጣብቖ።"),
    ("Remember: when we share, God can bless it and make it more!","ዘክር፦ ክንካፈል ከለና፡ ኣምላኽ ኪባርኾ ይኽእል!"),
  ],
  "template_title_en":"Basket Template",
  "bookmarks": [("Share with Others","ምስ ካልኦት ተኻፈል"),("Give Thanks","ኣመስግን")],
  "secret_code": code("SHARES","GOD PROVIDES","መልሲ፦ SHARES · GOD PROVIDES (ኣምላኽ የዳሉ)"),
  "true_false": [
    ("There were over five thousand people.","ካብ 5000 ንላዕሊ ሰባት ነበሩ።",True),
    ("The boy kept his lunch for himself.","እቲ ቆልዓ ምሳሑ ንርእሱ ሓዘ።",False),
    ("Jesus gave thanks to God.","የሱስ ንኣምላኽ ኣመስገነ።",True),
    ("Everyone ate until they were full.","ኩሉ ክሳብ ዝጸግብ በልዐ።",True),
    ("There was no food left over.","ዝተረፈ ምግቢ ኣይነበረን።",False),
  ],
  "fill_blanks": {
    "bank": ["crowd","loaves","fish","thanks","baskets"],
    "sentences": ["A huge __________ followed Jesus.",
                  "A boy shared five __________ of bread.",
                  "He also shared two little __________.",
                  "Jesus gave __________ to God.",
                  "Twelve __________ of food were left over."],
    "answers": "crowd · loaves · fish · thanks · baskets",
  },
  "acrostic": "SHARE",
  "prayer": {"en":"Dear God, thank you for giving me all I need. Help me to share with others and to have a thankful heart, like the boy with his lunch. Amen.",
             "ti":"ኦ ኣምላኽ፡ ዜድልየኒ ዅሉ ስለ እትህበኒ የቐንየለይ። ከም እቲ ቆልዓ ምስ ካልኦት ክካፈልን ዝያዳ ኣመስጋኒ ልቢ ክህልወንን ሓግዘኒ። ኣሜን።"},
  "reflect1_en":"What is something you can share today?","reflect1_ti":"ሎሚ እንታይ ክትካፈል ትኽእል?",
  "reflect2_en":"What are you most thankful for?","reflect2_ti":"ብዝያዳ ብዛዕባ እንታይ ተመስግን?",
  "three_lessons": [("Share","ተኻፈል"),("Give Thanks","ኣመስግን"),("Trust God Provides","ኣምላኽ የዳሉ")],
  "review_en":"You have learned how Jesus fed the five thousand. Remember these three things:",
  "review_ti":"የሱስ ንሓሙሽተ ሽሕ ብኸመይ ከም ዝመገበ ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for sharing and giving thanks, like the boy with his loaves and fish!",
  "cert_line_ti":"ከም እቲ ቆልዓ ስለ ዝተኻፈለን ስለ ዘመስገነን!",
})

# ===========================================================================
# BOOK 10 — The Lost Sheep
# ===========================================================================
BOOKS.append({
  "slug": "10-lost-sheep",
  "icon": "sheep", "icon2": "heart",
  "title_en": "The Lost Sheep",
  "title_ti": "እታ ዝጠፍአት በጊዕ",
  "cover_line_en": "A colour-and-learn activity book about God's love and never being forgotten.",
  "cover_line_ti": "ብዛዕባ ፍቕሪ ኣምላኽን ከቶ ዘይምርሳዕን ዝገልጽ መጽሓፍ ንጥፈት።",
  "characters": [
    ("The Shepherd", "who loves every sheep.", "እቲ ጓሳ — ንነፍሲ ወከፍ በጊዕ ዘፍቅር።"),
    ("The Lost Sheep", "one sheep that wandered away.", "እታ ዝጠፍአት በጊዕ — ሓንቲ ዝተባዘሐት።"),
    ("The Flock", "the ninety-nine safe sheep.", "እቲ መጓሰ — እተን 99 ደሓን ኣባጊዕ።"),
    ("Jesus", "who told this loving story.", "የሱስ — እዚ ናይ ፍቕሪ ታሪኽ ዝነገረ።"),
  ],
  "story": [
    {"sub_en":"A Good Shepherd","sub_ti":"ሕያዋይ ጓሳ",
     "paras":[
       ("Jesus told a story about a shepherd who had one hundred sheep. He knew and loved every single one of them.",
        "የሱስ ብዛዕባ ሚእቲ ኣባጊዕ ዝነበሮ ጓሳ ታሪኽ ነገረ። ንነፍሲ ወከፈን ይፈልጠንን የፍቅረንን ነበረ።"),
       ("Each evening the shepherd counted his sheep to make sure they were all safe.",
        "ነፍሲ ወከፍ ምሸት እቲ ጓሳ ኩለን ደሓን ምዃነን ንምርግጋጽ ኣባጊዑ ይቖጽር ነበረ።"),
     ]},
    {"sub_en":"One Sheep Is Missing","sub_ti":"ሓንቲ በጊዕ ጠፍአት",
     "paras":[
       ("One night, as he counted, the shepherd found only ninety-nine sheep. One little sheep was lost!",
        "ሓደ ለይቲ፡ ኪቖጽር ከሎ፡ እቲ ጓሳ 99 ኣባጊዕ ጥራይ ረኸበ። ሓንቲ ንእሽቶ በጊዕ ጠፊኣ ነበረት!"),
       ("The little sheep had wandered off and could not find its way home. It was alone, cold and afraid in the dark.",
        "እታ ንእሽቶ በጊዕ ተባዚሓ መገዲ ገዛ ኺትረክብ ኣይከኣለትን። ኣብ ጸልማት በይናን ቆራሪትን ፈራሪትን ነበረት።"),
     ]},
    {"sub_en":"The Shepherd Searches","sub_ti":"እቲ ጓሳ ደለየ",
     "paras":[
       ("The shepherd left the ninety-nine safe sheep and went out into the night to search for the one that was lost.",
        "እቲ ጓሳ ነተን 99 ደሓን ኣባጊዕ ሓዲጉ፡ ነታ ዝጠፍአት ኪደሊ ናብ ለይቲ ወጸ።"),
       ("He climbed over rocks and through bushes, calling out, looking everywhere, and would not give up.",
        "ኣብ ኣኻውሕን ኣብ ጭፍራታትን እናሓኸ፡ እናጸውዐ፡ ኣብ ኩሉ እናደለየ፡ ተስፋ ኣይቖረጸን።"),
     ]},
    {"sub_en":"Found at Last","sub_ti":"ኣብ መወዳእታ ተረኽበት",
     "paras":[
       ("At last the shepherd heard a soft 'baa'. There was the lost sheep! He was so happy to have found it.",
        "ኣብ መወዳእታ እቲ ጓሳ ልዙብ 'ማዕ' ሰምዐ። እታ ዝጠፍአት በጊዕ ኣብኡ ነበረት! ብምርካቡ ኣዝዩ ተሓጐሰ።"),
       ("Gently, he lifted the sheep onto his shoulders and carried it safely all the way home.",
        "ብልኡም ነታ በጊዕ ኣብ መንኩቡ ኣውጺኡ፡ ብደሓን ናብ ገዛ ተሰኪሙ ወሰዳ።"),
     ]},
    {"sub_en":"A Great Celebration","sub_ti":"ዓቢ በዓል",
     "paras":[
       ("The shepherd called his friends and said, 'Be happy with me! I found my lost sheep!' There was great rejoicing.",
        "እቲ ጓሳ ንኣዕሩኹ ጸዊዑ፡ 'ምሳይ ተሓጐሱ! ዝጠፍአት በጐዐይ ረኺበያ!' በለ። ዓቢ ሓጐስ ኮነ።"),
       ("Jesus said, 'God is like this shepherd. He loves each one of us and never wants anyone to be lost.'",
        "የሱስ፡ 'ኣምላኽ ከምዚ ጓሳ እዩ። ንነፍሲ ወከፍና የፍቅረናን ሓደ እኳ ኪጠፍእ ኣይደልን።'"),
       ("You are so precious to God. If you ever feel lost, remember: God is always searching for you with love.",
        "ንስኻ ኣብ ቅድሚ ኣምላኽ ኣዝዩ ኽቡር ኢኻ። ጠፊእካ እንተ ተሰሚዑካ፡ ዘክር፦ ኣምላኽ ብፍቕሪ ይደልየካ ኣሎ።"),
     ]},
  ],
  "verse": {"en":"He will search for the lost and bring back the ones that wander away.",
            "ti":"ንዝጠፍአት ኪደሊ፡ ንዝተባዘሐት ከኣ ኪመልስ እዩ።",
            "ref_en":"Ezekiel 34:16","ref_ti":"ህዝቅኤል 34፡16"},
  "easy_q": [
    {"q_en":"How many sheep did the shepherd have?","q_ti":"እቲ ጓሳ ክንደይ ኣባጊዕ ነበሮ?","opts":"a) Ten &nbsp;&nbsp; b) <strong>One hundred</strong> &nbsp;&nbsp; c) Five"},
    {"q_en":"How many sheep got lost?","q_ti":"ክንደይ በጊዕ ጠፍአት?","opts":"a) <strong>One</strong> &nbsp;&nbsp; b) Ten &nbsp;&nbsp; c) Fifty"},
    {"q_en":"What did the shepherd do?","q_ti":"እቲ ጓሳ እንታይ ገበረ?","opts":"a) Gave up &nbsp;&nbsp; b) <strong>Searched for it</strong> &nbsp;&nbsp; c) Went to sleep"},
    {"q_en":"When he found it, he ___.","q_ti":"ምስ ረኸባ ___ ።","opts":"a) was sad &nbsp;&nbsp; b) <strong>was very happy</strong> &nbsp;&nbsp; c) was angry"},
  ],
  "hard_q": [
    ("Why did the shepherd leave the ninety-nine to find just one?","እቲ ጓሳ ንሓንቲ ኺደሊ ስለምንታይ ነተን 99 ሓደገ?"),
    ("How do you think the lost sheep felt when it was found?","እታ ዝጠፍአት ምስ ተረኽበት ከመይ ተሰሚዕዋ ይኸውን?"),
    ("The shepherd is like God. What does this teach about God's love?","እዚ ብዛዕባ ፍቕሪ ኣምላኽ እንታይ ይምህር?"),
    ("Write about a time you felt loved and cared for.","ፍቕርን ሓልዮትን እተሰምዓካ ግዜ ጽሓፍ።"),
  ],
  "sequence": [
    ("The shepherd has one hundred sheep.","እቲ ጓሳ ሚእቲ ኣባጊዕ ኣለዎ።"),
    ("He counts and finds one is missing.","ቆጺሩ ሓንቲ ጠፊኣ ይረክብ።"),
    ("He leaves the ninety-nine to search.","ነተን 99 ሓዲጉ ይደሊ።"),
    ("He looks everywhere in the dark.","ኣብ ጸልማት ኣብ ኩሉ ይደሊ።"),
    ("He finds the lost sheep and carries it home.","ረኺቡ ተሰኪሙ ናብ ገዛ ይወስዳ።"),
    ("Everyone celebrates with great joy!","ኩሉ ብዓቢ ሓጐስ ይሕጐስ!"),
  ],
  "ws_words": ["SHEEP","LOST","SHEPHERD","FOUND","LOVE","SEARCH","FLOCK","JOY"],
  "crossword": {
    "spine": "SHEEP",
    "crossers": ["LOST","HOPE","LOVE"],
    "grid": 13,
    "down_clues": [(1,"The shepherd had one hundred.","SHEEP — ኣባጊዕ")],
    "across_clues": [(2,"One sheep was this.","LOST — ጠፍአት"),
                     (3,"The shepherd never lost this.","HOPE — ተስፋ"),
                     (4,"Why the shepherd searched.","LOVE — ፍቕሪ")],
    "answer_line": "1 SHEEP · 2 LOST · 3 HOPE · 4 LOVE",
  },
  "match": [("Sheep","በጊዕ"),("Shepherd","ጓሳ"),("Lost","ጠፍአት"),("Found","ተረኽበት"),("Love","ፍቕሪ"),("Joy","ሓጐስ")],
  "colouring": [
    {"title_en":"Colour the Lost Sheep","sub_en":"Safe at last","sub_ti":"ኣብ መወዳእታ ደሓን","note_en":"Give the sheep fluffy wool!","note_ti":"ነታ በጊዕ ልስሉስ ጸጕሪ ሃባ!"},
    {"title_en":"Colour a Heart of Love","sub_en":"God loves you","sub_ti":"ኣምላኽ የፍቅረካ","note_en":"Fill it with warm colours.","note_ti":"ብዉዑይ ሕብሪ ምላእ።"},
    {"title_en":"Colour the Shepherd","sub_en":"Carrying the sheep","sub_ti":"ነታ በጊዕ ተሰኪሙ","note_en":"Draw the sheep on his shoulders.","note_ti":"ነታ በጊዕ ኣብ መንኩቡ ስኣል።"},
    {"title_en":"Colour the Whole Flock","sub_en":"All together again","sub_ti":"ኩለን ብሓባር","note_en":"How many sheep can you count?","note_ti":"ክንደይ ኣባጊዕ ትቖጽር?"},
  ],
  "count_word_en":"sheep","count_word_ti":"ኣባጊዕ","count_sets":[4,2,3,1],
  "count_fact_en":"99 were safe; the shepherd sought 1.","count_fact_ti":"99 ደሓን ነበራ፡ ንሓንቲ ደለየ።",
  "lesson_en":"Knowing you are loved by God","lesson_ti":"ብኣምላኽ ከም እትፍቀር ምፍላጥ",
  "scenarios": [
    {"q_en":"A friend feels left out and forgotten.","q_ti":"ሓደ ፈታዊ ተረሲዑ ይስመዖ ኣሎ።","opts":"a) <strong>Go and include them.</strong> &nbsp;&nbsp; b) Leave them out."},
    {"q_en":"Someone new feels lost and unsure.","q_ti":"ሓደ ሓድሽ ሰብ ጠፊኡ ይስመዖ ኣሎ።","opts":"a) Ignore them. &nbsp;&nbsp; b) <strong>Kindly help them feel welcome.</strong>"},
    {"q_en":"You feel sad and alone sometimes.","q_ti":"ሓድሓደ ግዜ ጐሂኻ በይንኻ ትኸውን።","opts":"a) <strong>Remember God loves you and is near.</strong> &nbsp;&nbsp; b) Believe no one cares."},
  ],
  "reflect_write": [
    ("The shepherd never gave up. How does it feel to know God looks for you?","ኣምላኽ ይደልየካ ምዃኑ ምፍላጥ ከመይ ይስመዓካ?"),
    ("Who can you help feel loved and not forgotten?","ንመን ከይተረስዐ ክትሕግዞ ትኽእል?"),
    ("Write a short prayer thanking God for his love.","ኣምላኽ ስለ ፍቕሩ እተመስግን ጸሎት ጽሓፍ።"),
  ],
  "maze_title_en":"Help the Shepherd Find the Sheep","maze_instr_en":"Guide the shepherd through the hills to find the lost sheep.",
  "maze_instr_ti":"ንጓሳ ብኣኽራን ኣቢሉ ነታ ዝጠፍአት በጊዕ ኪረክብ ምርሓዮ።",
  "draw_title_en":"Draw the Shepherd and Sheep","draw_sub_en":"Show the happy ending","draw_sub_ti":"ሕጉስ መወዳእታ ስኣል",
  "draw_instr_en":"Draw the shepherd carrying the found sheep home on his shoulders.",
  "draw_instr_ti":"እቲ ጓሳ ነታ በጊዕ ኣብ መንኩቡ ተሰኪሙ ናብ ገዛ ክወስዳ ከሎ ስኣል።",
  "craft_title_en":"Craft: Cotton-Wool Sheep","craft_sub_en":"Make a fluffy sheep!","craft_sub_ti":"ልስሉስ በጊዕ ስራሕ!",
  "craft_need_en":"You will need: paper, cotton wool, glue, a black crayon, scissors.",
  "craft_need_ti":"እትደሊ፦ ወረቐት፡ ጡጥ፡ ልቖ፡ ጸሊም ሕብሪ፡ መቐስ።",
  "craft_steps": [
    ("Draw a simple sheep body and face on paper.","ኣካልን ገጽን በጊዕ ኣብ ወረቐት ስኣል።"),
    ("Glue soft cotton wool all over the body for wool.","ኣብ ኩሉ ኣካል ጡጥ ኣጣብቕ።"),
    ("Add black legs, ears and a happy face.","ጸለምቲ ኣእጋር፡ እዝንን ሕጉስ ገጽን ወስኽ።"),
    ("Remember: God loves you and will always come looking for you!","ዘክር፦ ኣምላኽ የፍቅረካ፡ ኩሉ ግዜ ኸኣ ኪደልየካ እዩ!"),
  ],
  "template_title_en":"Sheep Template",
  "bookmarks": [("God Loves Me","ኣምላኽ የፍቅረኒ"),("I Am Never Lost to God","ኣብ ኣምላኽ ከቶ ኣይጠፍእን")],
  "secret_code": code("LOVED","GOD SEEKS ME","መልሲ፦ LOVED (ፍቁር) · GOD SEEKS ME (ኣምላኽ ይደልየኒ)"),
  "true_false": [
    ("The shepherd had one hundred sheep.","እቲ ጓሳ ሚእቲ ኣባጊዕ ነበሮ።",True),
    ("The shepherd did not care about one lost sheep.","እቲ ጓሳ ብሓንቲ ዝጠፍአት ኣይግደስን ነበረ።",False),
    ("The shepherd searched until he found it.","ክሳብ ዝረኽባ ደለየ።",True),
    ("God is like the loving shepherd.","ኣምላኽ ከምቲ ፈቃር ጓሳ እዩ።",True),
    ("God forgets people who wander away.","ኣምላኽ ንዝተባዘሑ ይርስዖም።",False),
  ],
  "fill_blanks": {
    "bank": ["hundred","lost","searched","found","loves"],
    "sentences": ["The shepherd had one __________ sheep.",
                  "One little sheep was __________.",
                  "The shepherd __________ everywhere for it.",
                  "At last he __________ the sheep.",
                  "God __________ each one of us."],
    "answers": "hundred · lost · searched · found · loves",
  },
  "acrostic": "SHEEP",
  "prayer": {"en":"Dear God, thank you that you love me and never forget me. When I feel lost or alone, help me to remember that you are always near and always searching for me. Amen.",
             "ti":"ኦ ኣምላኽ፡ ስለ እተፍቅረኒን ከቶ ስለ ዘይትርስዓንን የቐንየለይ። ጠፊአ ወይ በይነይ ኸለኹ፡ ኩሉ ግዜ ኣብ ጥቓይ ከም ዘለኻ ክዝክር ሓግዘኒ። ኣሜን።"},
  "reflect1_en":"How does it feel to know God will never forget you?","reflect1_ti":"ኣምላኽ ከቶ ኸም ዘይርስዓካ ምፍላጥ ከመይ ይስመዓካ?",
  "reflect2_en":"Who can you show that they are loved and wanted?","reflect2_ti":"ንመን ፍቁር ምዃኑ ከተርኢ ትኽእል?",
  "three_lessons": [("You Are Loved","ፍቁር ኢኻ"),("You Matter","ትግደስ ኢኻ"),("God Seeks You","ኣምላኽ ይደልየካ")],
  "review_en":"You have learned about the Lost Sheep. Remember these three things:",
  "review_ti":"ብዛዕባ እታ ዝጠፍአት በጊዕ ተማሂርካ። እዞም ሰለስተ ነገራት ዘክር፦",
  "cert_line_en":"for learning how much God loves and searches for you, like the shepherd!",
  "cert_line_ti":"ከምቲ ጓሳ ኣምላኽ ክንደይ ከም ዘፍቅረካ ስለ እተማህረ!",
})
