# -*- coding: utf-8 -*-
"""
Lesson data for the Christian Sunday-School Activity Books.
Series author: Daniel Tesfamariam.
"""
_ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
_L2N = {ch: str(i + 1) for i, ch in enumerate(_ALPHA)}


def code(line1, line2):
    used = sorted({ch for ch in (line1 + line2) if ch.isalpha()}, key=lambda c: int(_L2N[c]))
    return {"key": [(_L2N[c], c) for c in used], "l2n": _L2N, "line1": line1, "line2": line2}


BOOKS = []

# ===========================================================================
# 1 — Esther's Brave Choice Sunday School Lesson Pack
# ===========================================================================
BOOKS.append({
  "slug": "01-esther", "short": "Esther's Brave Choice",
  "icon": "crown", "icon2": "palace",
  "title": "Esther's Brave Choice",
  "theme": "A Sunday-School Lesson on Courage & Faith",
  "cover_line": "Learning to be brave and do what is right, trusting God.",
  "welcome": "Welcome to this lesson about Queen Esther, a brave young woman God used to save her people. This pack gives you everything for one Sunday-school session: the Bible story, a memory verse, discussion, games, a craft, and printable activities for children aged 4 to 12.",
  "welcome_tip": "Read the whole pack before class and pick the activities that fit your time and group size.",
  "how_to_use": [
    "Start with the Opening Prayer and Icebreaker (page 5).",
    "Read the Bible Story together (pages 6–9).",
    "Learn the Memory Verse (page 10) and discuss it (page 11).",
    "Choose activities, a game and the craft to match your class time.",
    "End with the Closing Prayer and hand out the certificate.",
  ],
  "aim": "Children will learn that God can use anyone who is brave and trusts him to do what is right.",
  "objectives": [
    "Retell the main events of Esther's story.",
    "Explain what it means to be brave for God.",
    "Recite the memory verse (Esther 4:14).",
    "Name one way to be brave and kind this week.",
  ],
  "prep": ["Bibles or the story pages printed", "Crayons, pencils, scissors, glue",
           "Card or paper for the crown craft", "Optional: a toy crown or sticker jewels"],
  "prep_tip": "Set out crayons and craft supplies before class so transitions are smooth.",
  "gathering": "As children arrive, greet each one by name. Gather in a circle and welcome everyone. Remind them that today's story is about being brave, even when it is hard.",
  "opening_prayer": "Dear God, thank you for bringing us together today. Open our hearts to learn about being brave for you, just like Queen Esther. Amen.",
  "icebreaker": "When was a time you had to be brave? Share with the group.",
  "story": [
    {"sub": "A New Queen", "paras": [
      "Long ago in the land of Persia, there was a great king named Xerxes. A young Jewish woman named Esther was chosen to be his queen. She was kind and beautiful.",
      "Esther had been raised by her older cousin Mordecai, who loved her like his own daughter. He told her to keep it a secret that she was Jewish, for now."]},
    {"sub": "A Wicked Plan", "paras": [
      "The king had a proud helper named Haman. Haman was angry because Mordecai would only bow to God, not to him.",
      "So Haman made a terrible plan and tricked the king into signing a law that all the Jewish people would be destroyed on one day."]},
    {"sub": "A Brave Choice", "paras": [
      "Mordecai sent word to Esther: 'You must go to the king and beg him to save our people!' But going to the king uninvited could mean death.",
      "Mordecai said, 'Maybe you became queen for a time just like this.' Esther prayed and fasted, then made her brave choice: 'I will go to the king. If I die, I die.'"]},
    {"sub": "God Saves His People", "paras": [
      "Esther bravely told the king the truth about Haman's wicked plan. The king was angry — not at Esther, but at Haman!",
      "Because Esther was brave, the king stopped the plan and the Jewish people were saved. God used one brave person to do something great."]},
  ],
  "verse": {"text": "Maybe you have become queen for just such a time as this.", "ref": "Esther 4:14"},
  "verse_tip": "Break the verse into small phrases and add simple hand motions to help children remember it.",
  "discussion": [
    "Why was Esther afraid to go to the king?",
    "What did Mordecai say that helped Esther be brave?",
    "Why did Esther pray and fast before she acted?",
    "When is it hard for you to do the right thing?",
    "How can we ask God to help us be brave?",
  ],
  "easy_q": [
    {"q": "What did Esther become?", "opts": "a) A teacher &nbsp; b) <strong>A queen</strong> &nbsp; c) A farmer"},
    {"q": "Who raised Esther?", "opts": "a) <strong>Mordecai</strong> &nbsp; b) Haman &nbsp; c) The king"},
    {"q": "Who made the wicked plan?", "opts": "a) Esther &nbsp; b) <strong>Haman</strong> &nbsp; c) Mordecai"},
    {"q": "Esther was brave and did what was ___.", "opts": "a) wrong &nbsp; b) <strong>right</strong> &nbsp; c) silly"},
  ],
  "hard_q": [
    "Why do you think God placed Esther in the palace 'for such a time as this'?",
    "How does praying help us before we make a hard choice?",
    "Describe a time you were brave and did the right thing.",
    "How can you encourage a friend to be brave for God?",
  ],
  "true_false": [
    ("Esther was a queen.", True), ("Haman was kind and good.", False),
    ("Mordecai raised Esther.", True), ("Esther prayed before she was brave.", True),
    ("God did not save the people.", False),
  ],
  "sequence": [
    "Esther is chosen to be queen.", "Haman makes a wicked plan.",
    "Esther prays, then bravely speaks to the king.", "God saves the Jewish people.",
  ],
  "ws_words": ["ESTHER", "QUEEN", "BRAVE", "KING", "PRAY", "CROWN", "HAMAN", "FAITH"],
  "crossword": {"spine": "ESTHER", "crossers": ["QUEEN", "TRUST", "HERO"], "grid": 13,
    "down_clues": [(1, "The brave young queen.")],
    "across_clues": [(2, "Esther became this."), (3, "To lean on God completely."),
                     (4, "A brave person who helps others.")],
    "answer_line": "1 ESTHER · 2 QUEEN · 3 TRUST · 4 HERO"},
  "match": [("Queen", "a royal woman"), ("Brave", "not afraid"), ("Pray", "talk to God"),
            ("Crown", "worn by royalty"), ("Faith", "trusting God"), ("Rescue", "to save")],
  "fill_blanks": {"bank": ["queen", "brave", "prayed", "king", "saved"],
    "sentences": ["Esther became the __________ of Persia.", "She __________ before she acted.",
                  "Esther went to the __________.", "Esther was very __________.",
                  "God __________ his people."],
    "answers": "queen · prayed · king · brave · saved"},
  "acrostic": "BRAVE",
  "secret_code": code("BRAVE", "TRUST GOD"),
  "colouring": [
    {"title": "Colour the Royal Crown", "sub": "Esther the Queen", "note": "Colour the jewels with your brightest colours!"},
    {"title": "Colour Queen Esther", "sub": "Brave and kind", "note": "What colour is her royal robe?"},
    {"title": "Colour the Palace", "sub": "In the land of Persia", "note": "Add a sun and some flowers."},
    {"title": "Colour a Crown of Courage", "sub": "You can be brave too", "note": "Write your name on the crown!"},
  ],
  "count_word": "crowns", "count_sets": [2, 3, 1, 4],
  "maze_title": "Help Esther Reach the King", "maze_instr": "Guide Esther through the palace to the king's throne.",
  "scenarios": [
    {"q": "A new child is sitting alone at church.", "opts": "a) Ignore them. &nbsp; b) <strong>Sit with them and be a friend.</strong>"},
    {"q": "Friends are teasing someone smaller.", "opts": "a) <strong>Kindly ask them to stop.</strong> &nbsp; b) Join in."},
    {"q": "You broke something and no one saw.", "opts": "a) Hide it. &nbsp; b) <strong>Tell the truth, even though it's hard.</strong>"},
  ],
  "apply_sub": "Being brave and kind like Esther",
  "drama": [
    "Choose children to play Esther, Mordecai, the King and Haman.",
    "Narrator reads the story slowly while actors mime the actions.",
    "Esther bravely 'speaks' to the King to save her people.",
    "End with everyone cheering because God saved the day!",
  ],
  "game_title": "Game: Brave Crown Relay", "game_need": "two paper crowns, two chairs",
  "game_steps": ["Split into two teams.", "Each child wears the crown, walks to the chair and back.",
                 "They pass the crown to the next player.", "The first team to finish shouts 'Be brave!'"],
  "game_tip": "Cheer for every child so being 'brave' up front feels safe and fun.",
  "craft_title": "Craft: Make a Paper Crown", "craft_sub": "You can be brave, too!",
  "craft_need": "card or paper, scissors, crayons, glue, sticker jewels",
  "craft_steps": ["Cut out a crown band (use the template on the next page).",
                  "Colour it and decorate with jewels or stickers.",
                  "Wrap it around the child's head and tape the ends.",
                  "Remember: God can use YOU to do brave, good things!"],
  "template_title": "Crown Template",
  "snack": "Serve 'crown' cookies or star-shaped crackers while you talk about Esther's courage.",
  "takehome": "Esther teaches us that God can use anyone who is brave and trusts him.",
  "home_activity": "Ask your child about a time they can be brave and kind this week, and pray together.",
  "family_prayer": "Dear God, help our family be brave and kind, and to always do what is right. Amen.",
  "three_lessons": ["Be Brave", "Do Right", "Trust God"],
  "review": "Today we learned that Esther bravely trusted God to save her people. God can use us to do brave things too!",
  "closing_prayer": "Dear God, thank you for the brave example of Esther. Help us to trust you and do what is right this week. In Jesus' name, Amen.",
  "welldone": "You have finished the Esther lesson! Remember to be brave, do right, and trust God every day.",
  "cert_line": "for learning to be brave and trust God, just like Queen Esther!",
})


# ===========================================================================
# 2 — Daniel and the Lions' Den Sunday School Activity Pack
# ===========================================================================
BOOKS.append({
  "slug": "02-daniel", "short": "Daniel and the Lions' Den",
  "icon": "lion", "icon2": "scroll",
  "title": "Daniel and the Lions' Den",
  "theme": "A Sunday-School Lesson on Prayer & Faith",
  "cover_line": "Learning to pray faithfully and trust God to protect us.",
  "welcome": "Welcome to this lesson about Daniel, a man who prayed to God every day and trusted him even in danger. This pack has everything for one session: the story, memory verse, discussion, games, a craft and printable activities for ages 4 to 12.",
  "welcome_tip": "Practise the lion 'roar' with the children early so they enjoy the story time.",
  "how_to_use": [
    "Open with prayer and the icebreaker (page 5).",
    "Read the Bible Story together (pages 6–9).",
    "Learn the memory verse and discuss it.",
    "Pick activities, a game and the craft for your class time.",
    "Close in prayer and give out the certificate.",
  ],
  "aim": "Children will learn to pray faithfully and trust that God protects those who love him.",
  "objectives": ["Retell how Daniel was saved in the lions' den.",
    "Explain why Daniel kept praying.", "Recite the memory verse (Daniel 6:22).",
    "Name a time and place they can pray this week."],
  "prep": ["Bibles or printed story pages", "Crayons, scissors, glue",
           "Paper plates for the lion craft", "Yellow/orange paper for the mane"],
  "prep_tip": "Cut a few mane strips in advance for younger children.",
  "gathering": "Greet each child and gather in a circle. Ask who prayed this week and celebrate their answers.",
  "opening_prayer": "Dear God, thank you that we can talk to you any time. Help us learn to pray like Daniel and to trust you. Amen.",
  "icebreaker": "When and where do you like to pray? Share with the group.",
  "story": [
    {"sub": "Daniel Loves God", "paras": [
      "Daniel lived far from home in Babylon and served King Darius. He was wise, honest and kind.",
      "Three times every day, Daniel knelt by his window and prayed to God. He was never ashamed to pray."]},
    {"sub": "A Jealous Trap", "paras": [
      "Some jealous officials could find nothing wrong with Daniel, so they made a sneaky plan.",
      "They tricked the king into a law: for thirty days, no one could pray to anyone but the king. Anyone who disobeyed would be thrown to the lions!"]},
    {"sub": "Daniel Keeps Praying", "paras": [
      "When Daniel heard about the law, he still went home, opened his window, and prayed to God as he always did.",
      "The jealous men saw him and ran to the king. Sadly, the king had to send Daniel to the den of hungry lions."]},
    {"sub": "God Shuts the Lions' Mouths", "paras": [
      "The king could not sleep all night. Early in the morning he ran to the den and called out.",
      "Daniel answered, 'My God sent his angel and shut the lions' mouths!' He was completely safe. The king honoured Daniel's God."]},
  ],
  "verse": {"text": "My God sent his angel to shut the lions' mouths.", "ref": "Daniel 6:22"},
  "verse_tip": "Let children make a gentle 'roar' then 'zip' their mouths shut to remember the verse.",
  "discussion": ["Why did Daniel keep praying even when it was against the law?",
    "How do you think the king felt during the night?",
    "How does God help us when we are afraid?",
    "When is it hard to keep a good habit like praying?",
    "Who can you ask to pray with you?"],
  "easy_q": [
    {"q": "How many times a day did Daniel pray?", "opts": "a) One &nbsp; b) <strong>Three</strong> &nbsp; c) Ten"},
    {"q": "Where was Daniel thrown?", "opts": "a) A river &nbsp; b) <strong>The lions' den</strong> &nbsp; c) A tower"},
    {"q": "Who shut the lions' mouths?", "opts": "a) Daniel &nbsp; b) The king &nbsp; c) <strong>God's angel</strong>"},
    {"q": "Daniel was ___ by the lions.", "opts": "a) hurt &nbsp; b) <strong>not hurt</strong> &nbsp; c) eaten"},
  ],
  "hard_q": ["Why did Daniel keep praying even when it was dangerous?",
    "What does this story teach about trusting God when we are afraid?",
    "Describe a time you prayed about something hard.",
    "How can you make prayer a daily habit?"],
  "true_false": [("Daniel prayed to God.", True), ("The lions ate Daniel.", False),
    ("A jealous group made a trap.", True), ("God sent an angel to help.", True),
    ("The king was happy about the trap.", False)],
  "sequence": ["Daniel prays three times a day.", "Jealous men make a trap.",
    "Daniel is thrown into the lions' den.", "God's angel keeps Daniel safe."],
  "ws_words": ["DANIEL", "LIONS", "PRAY", "KING", "ANGEL", "FAITH", "DEN", "TRUST"],
  "crossword": {"spine": "DANIEL", "crossers": ["LIONS", "KING", "ANGEL", "PRAY"], "grid": 13,
    "down_clues": [(1, "He prayed three times a day.")],
    "across_clues": [(2, "Big cats in the den."), (3, "Darius was one."),
                     (4, "God sent one to shut the mouths."), (5, "Daniel did this to God.")],
    "answer_line": "1 DANIEL · 2 LIONS · 3 KING · 4 ANGEL · 5 PRAY"},
  "match": [("Lion", "a big wild cat"), ("Pray", "talk to God"), ("Angel", "God's messenger"),
            ("Faith", "trusting God"), ("Den", "the lions' cave"), ("King", "the ruler")],
  "fill_blanks": {"bank": ["prayed", "lions", "angel", "king", "safe"],
    "sentences": ["Daniel __________ to God three times a day.", "Daniel was thrown into the den of __________.",
                  "God sent an __________ to shut their mouths.", "In the morning Daniel was __________.",
                  "The __________ honoured Daniel's God."],
    "answers": "prayed · lions · angel · safe · king"},
  "acrostic": "DANIEL",
  "secret_code": code("PRAY", "GOD IS NEAR"),
  "colouring": [
    {"title": "Colour the Brave Lion", "sub": "In the den", "note": "Give the lion a big furry mane!"},
    {"title": "Colour Daniel Praying", "sub": "By his window", "note": "Draw a sunny sky behind him."},
    {"title": "Colour the King's Scroll", "sub": "The new law", "note": "What colour is the royal seal?"},
    {"title": "Colour the Lions' Den", "sub": "God kept Daniel safe", "note": "How many lions can you count?"},
  ],
  "count_word": "lions", "count_sets": [2, 3, 1, 4],
  "maze_title": "Help Daniel Out of the Den", "maze_instr": "Guide Daniel safely out of the den to the king.",
  "scenarios": [
    {"q": "Friends want you to skip praying to play.", "opts": "a) <strong>Kindly keep your good habit.</strong> &nbsp; b) Give up right away."},
    {"q": "You feel scared about something big.", "opts": "a) <strong>Pray and ask God for help.</strong> &nbsp; b) Worry all alone."},
    {"q": "Someone dares you to do wrong.", "opts": "a) Do it to look cool. &nbsp; b) <strong>Say no and do what is right.</strong>"},
  ],
  "apply_sub": "Praying and trusting like Daniel",
  "drama": ["Choose children to be Daniel, the King, jealous officials and gentle lions.",
    "Narrator reads while Daniel kneels to 'pray' by a window.",
    "Daniel is placed among the 'lions', who lie down quietly.",
    "The King rejoices to find Daniel safe — everyone cheers!"],
  "game_title": "Game: Sleeping Lions", "game_need": "just space to lie down",
  "game_steps": ["Children lie still like the calm lions.", "One leader gently tries to make them giggle (no touching).",
                 "Anyone who moves joins the leader.", "The last still 'lion' wins and picks the next round."],
  "game_tip": "This calm game is great for settling the group after active time.",
  "craft_title": "Craft: Paper-Plate Lion", "craft_sub": "Make a friendly lion mane!",
  "craft_need": "a paper plate, yellow/orange paper, scissors, glue, crayons",
  "craft_steps": ["Colour a lion face in the middle of the plate.",
                  "Cut paper strips for the mane and glue them around the edge.",
                  "Add ears, eyes, a nose and whiskers.",
                  "Remember: God can protect you, just as he protected Daniel!"],
  "template_title": "Lion Mask Template",
  "snack": "Serve animal crackers and talk about how God kept the lions calm.",
  "takehome": "Daniel teaches us to pray faithfully and trust God, even when things are scary.",
  "home_activity": "Choose a daily prayer time as a family this week — maybe at breakfast or bedtime.",
  "family_prayer": "Dear God, thank you for hearing us when we pray. Help our family to trust you every day. Amen.",
  "three_lessons": ["Pray Always", "Stay Faithful", "Trust God"],
  "review": "Today we learned that Daniel prayed every day and trusted God, who kept him safe in the lions' den.",
  "closing_prayer": "Dear God, thank you for protecting Daniel. Help us to pray to you every day and to trust you when we are afraid. Amen.",
  "welldone": "You have finished the Daniel lesson! Keep praying, stay faithful, and trust God every day.",
  "cert_line": "for learning to pray faithfully and trust God, just like Daniel!",
})

# ===========================================================================
# 3 — David and Goliath Sunday School Lesson & Activities
# ===========================================================================
BOOKS.append({
  "slug": "03-david", "short": "David and Goliath",
  "icon": "sling", "icon2": "crown",
  "title": "David and Goliath",
  "theme": "A Sunday-School Lesson on Courage & God's Strength",
  "cover_line": "Learning that with God, no problem is too big to face.",
  "welcome": "Welcome to this lesson about David, a young shepherd who trusted God to defeat a giant. This pack contains a full session: story, memory verse, discussion, games, a craft and printable activities for ages 4 to 12.",
  "welcome_tip": "Use a tall marker on the wall to show how big Goliath was — children love this!",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and hand out the certificate."],
  "aim": "Children will learn that God gives us courage and strength to face big problems.",
  "objectives": ["Retell the story of David and Goliath.", "Explain why David was not afraid.",
    "Recite the memory verse (1 Samuel 17:45).", "Name a 'giant' problem God can help them face."],
  "prep": ["Bibles or printed story pages", "Crayons, scissors, glue",
           "Paper and soft materials (cotton) for the craft", "Optional: a measuring tape"],
  "prep_tip": "Have children measure themselves and compare to Goliath's height for a fun start.",
  "gathering": "Gather in a circle. Ask children what makes them feel small or scared, and reassure them God is bigger.",
  "opening_prayer": "Dear God, you are stronger than anything we fear. Help us be brave like David and trust in you. Amen.",
  "icebreaker": "What is something that feels really big or scary to you?",
  "story": [
    {"sub": "The Shepherd Boy", "paras": [
      "David was the youngest of eight brothers. He looked after his father's sheep and played the harp.",
      "When lions or bears attacked the flock, David protected them. God gave him courage and strength."]},
    {"sub": "The Giant's Challenge", "paras": [
      "The Philistine army had a giant named Goliath, over nine feet tall. Every day he dared Israel to fight him.",
      "All the soldiers, even the king, were terrified. No one was brave enough to face the giant."]},
    {"sub": "David Is Not Afraid", "paras": [
      "David said, 'Who is this giant to defy the army of the living God?' He offered to fight Goliath.",
      "'The Lord who saved me from the lion and the bear will save me,' David said. He took his sling and five smooth stones."]},
    {"sub": "God Gives the Victory", "paras": [
      "Goliath laughed, but David said, 'You come with a sword, but I come in the name of the Lord!'",
      "David swung his sling and the stone struck the giant. Goliath fell! God gave the victory to the boy who trusted him."]},
  ],
  "verse": {"text": "I come to you in the name of the Lord of heaven's armies.", "ref": "1 Samuel 17:45"},
  "verse_tip": "Have children 'swing' an imaginary sling as they say the last words of the verse.",
  "discussion": ["Why was David not afraid of the giant?", "How had God helped David before?",
    "What 'giant' problems feel too big for you?", "How can God help us face hard things?",
    "Why is it better to trust God than to trust our own strength?"],
  "easy_q": [
    {"q": "What was David's job?", "opts": "a) A cook &nbsp; b) <strong>A shepherd</strong> &nbsp; c) A sailor"},
    {"q": "Who was the giant?", "opts": "a) Saul &nbsp; b) <strong>Goliath</strong> &nbsp; c) David"},
    {"q": "How many stones did David take?", "opts": "a) One &nbsp; b) <strong>Five</strong> &nbsp; c) Ten"},
    {"q": "David trusted in ___.", "opts": "a) his sword &nbsp; b) <strong>God</strong> &nbsp; c) armour"},
  ],
  "hard_q": ["Why was David able to be brave when everyone else was afraid?",
    "How does remembering God's past help give us courage?",
    "Describe a 'giant' you need God's help with.", "How can you encourage someone who feels afraid?"],
  "true_false": [("David was a shepherd.", True), ("David wore heavy armour.", False),
    ("David took five smooth stones.", True), ("David trusted in God.", True), ("Goliath won the fight.", False)],
  "sequence": ["David looks after the sheep.", "Goliath dares Israel to fight.",
    "David trusts God and uses his sling.", "God gives Israel the victory."],
  "ws_words": ["DAVID", "GIANT", "SLING", "STONE", "SHEEP", "BRAVE", "SAUL", "LORD"],
  "crossword": {"spine": "DAVID", "crossers": ["GIANT", "SLING", "BRAVE"], "grid": 13,
    "down_clues": [(1, "The brave shepherd boy.")],
    "across_clues": [(2, "Goliath was a huge one."), (3, "David used it to throw a stone."),
                     (4, "Not afraid; full of courage.")],
    "answer_line": "1 DAVID · 2 GIANT · 3 SLING · 4 BRAVE"},
  "match": [("Shepherd", "cares for sheep"), ("Giant", "a very big man"), ("Sling", "throws a stone"),
            ("Brave", "not afraid"), ("Sheep", "David's flock"), ("Victory", "a win from God")],
  "fill_blanks": {"bank": ["shepherd", "giant", "stones", "sling", "God"],
    "sentences": ["David was a young __________.", "Goliath was a huge __________.",
                  "David took five smooth __________.", "He used his __________ to throw one.",
                  "David trusted in __________, and won."],
    "answers": "shepherd · giant · stones · sling · God"},
  "acrostic": "BRAVE",
  "secret_code": code("BRAVE", "GOD IS STRONG"),
  "colouring": [
    {"title": "Colour David the Shepherd", "sub": "With his sling", "note": "Give David a colourful robe!"},
    {"title": "Colour the Sling & Stones", "sub": "Five smooth stones", "note": "Colour each stone differently."},
    {"title": "Colour the Sheep", "sub": "David's flock", "note": "How many sheep can you count?"},
    {"title": "Colour a Crown", "sub": "David became king one day", "note": "Add shiny jewels."},
  ],
  "count_word": "stones", "count_sets": [5, 3, 2, 4],
  "maze_title": "Help David Reach the Giant", "maze_instr": "Guide David across the valley to face Goliath.",
  "scenarios": [
    {"q": "A big problem feels too hard.", "opts": "a) <strong>Ask God for help and try.</strong> &nbsp; b) Give up."},
    {"q": "Others laugh because you are small or young.", "opts": "a) Feel worthless. &nbsp; b) <strong>Remember God made you special.</strong>"},
    {"q": "You must stand up for what is right, alone.", "opts": "a) <strong>Be brave with God's help.</strong> &nbsp; b) Run away."},
  ],
  "apply_sub": "Facing giants with God like David",
  "drama": ["Choose David, Goliath (make him 'tall' on tiptoe or a chair), King Saul and soldiers.",
    "The soldiers cower while Goliath 'shouts'.", "David steps forward and 'swings' his sling.",
    "Goliath falls and everyone celebrates God's victory!"],
  "game_title": "Game: Beanbag Sling Toss", "game_need": "soft beanbags or rolled socks, a target or bucket",
  "game_steps": ["Set a bucket or target a few steps away.", "Each child gets five soft 'stones' to toss.",
                 "Count how many land in the target.", "Cheer that David trusted God, not just his aim!"],
  "game_tip": "Use only soft items and keep the throwing line clear for safety.",
  "craft_title": "Craft: Paper Sling & Courage Stones", "craft_sub": "Make five courage stones!",
  "craft_need": "paper, crayons, cotton balls or crumpled paper, scissors",
  "craft_steps": ["Draw and cut out a sling shape.", "Make five soft 'stones' from cotton or paper.",
                  "Write a courage word on each stone (Brave, Trust, Faith...).",
                  "Remember: with God, you can face any giant!"],
  "template_title": "Sling Template",
  "snack": "Serve five small round crackers as 'smooth stones' for each child.",
  "takehome": "David teaches us that with God, no problem is too big to face.",
  "home_activity": "Talk about a 'giant' your family faces this week and pray about it together.",
  "family_prayer": "Dear God, you are stronger than anything we fear. Help our family be brave and trust you. Amen.",
  "three_lessons": ["Be Brave", "Trust God", "God Is Strong"],
  "review": "Today we learned that David trusted God to defeat a giant. With God, we can be brave too!",
  "closing_prayer": "Dear God, thank you for being stronger than any giant. Help us to trust you when things feel too big. Amen.",
  "welldone": "You have finished the David lesson! Be brave, trust God, and remember he is strong.",
  "cert_line": "for learning to be brave and trust God's strength, just like David!",
})


# ===========================================================================
# 4 — Noah's Ark Sunday School Activity Pack
# ===========================================================================
BOOKS.append({
  "slug": "04-noah", "short": "Noah's Ark",
  "icon": "ark", "icon2": "waves",
  "title": "Noah's Ark",
  "theme": "A Sunday-School Lesson on Obedience & God's Promises",
  "cover_line": "Learning to obey God and trust that he keeps his promises.",
  "welcome": "Welcome to this lesson about Noah, who obeyed God and built the ark. This pack has a full session: story, memory verse, discussion, games, a craft and activities for ages 4 to 12.",
  "welcome_tip": "Bring toy animals or animal pictures to make the 'two by two' part come alive.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn to obey God and trust that he always keeps his promises.",
  "objectives": ["Retell the story of Noah's ark.", "Explain why Noah obeyed God.",
    "Recite the memory verse (Genesis 9:13).", "Name one way to obey God this week."],
  "prep": ["Bibles or printed story pages", "Crayons, scissors, glue",
           "Cotton wool and paper for the rainbow craft", "Optional: toy animals"],
  "prep_tip": "Sort craft materials by colour beforehand to speed up the rainbow craft.",
  "gathering": "Gather in a circle. Ask children about a promise someone kept for them, and how it felt.",
  "opening_prayer": "Dear God, thank you that you always keep your promises. Help us to obey you like Noah did. Amen.",
  "icebreaker": "What is your favourite animal? If you were on the ark, which would you want next to you?",
  "story": [
    {"sub": "God Speaks to Noah", "paras": [
      "Noah was a good man who loved and obeyed God. But the world had become full of wrongdoing.",
      "God told Noah, 'I will send a great flood. Build a big boat, an ark, to keep your family and the animals safe.'"]},
    {"sub": "Building the Ark", "paras": [
      "Noah obeyed. He and his sons worked for years to build the huge wooden ark, exactly as God said.",
      "People laughed at Noah for building a boat on dry land, but Noah kept trusting and obeying God."]},
    {"sub": "Two by Two", "paras": [
      "When the ark was ready, God sent the animals — two of every kind. They walked, hopped and flew inside.",
      "Noah's family went in too. Then God shut the door, and the rain began to fall."]},
    {"sub": "The Rainbow Promise", "paras": [
      "It rained forty days and nights, but the ark floated safely. At last the water went down and everyone came out.",
      "God placed a beautiful rainbow in the sky and promised never again to flood the whole earth. God keeps his promises!"]},
  ],
  "verse": {"text": "I have put my rainbow in the clouds as a sign of my promise.", "ref": "Genesis 9:13"},
  "verse_tip": "Draw a rainbow on the board and add one word of the verse to each colour band.",
  "discussion": ["Why did Noah keep building even when people laughed?",
    "How do you think Noah cared for all the animals?", "What does the rainbow remind us about God?",
    "When is it hard to obey?", "How can we trust God's promises?"],
  "easy_q": [
    {"q": "What did God tell Noah to build?", "opts": "a) A house &nbsp; b) <strong>An ark</strong> &nbsp; c) A wall"},
    {"q": "How many of each animal came?", "opts": "a) <strong>Two</strong> &nbsp; b) Five &nbsp; c) Ten"},
    {"q": "How many days did it rain?", "opts": "a) Four &nbsp; b) <strong>Forty</strong> &nbsp; c) Four hundred"},
    {"q": "God's promise sign was a ___.", "opts": "a) star &nbsp; b) <strong>rainbow</strong> &nbsp; c) cloud"},
  ],
  "hard_q": ["Why did Noah keep obeying even when it was hard?",
    "What does the rainbow teach us about God's character?",
    "Describe a time you obeyed even when it was difficult.", "How can your family trust God this week?"],
  "true_false": [("Noah obeyed God and built the ark.", True), ("Only one of each animal came.", False),
    ("It rained for forty days.", True), ("A dove brought back an olive leaf.", True),
    ("God's promise sign was a star.", False)],
  "sequence": ["God tells Noah to build an ark.", "Noah builds the ark and the animals come.",
    "The rain falls for forty days.", "God sends a rainbow promise."],
  "ws_words": ["NOAH", "ARK", "FLOOD", "DOVE", "RAIN", "RAINBOW", "ANIMALS", "PROMISE"],
  "crossword": {"spine": "NOAH", "crossers": ["ARK", "DOVE", "RAIN"], "grid": 13,
    "down_clues": [(1, "He obeyed God and built the ark.")],
    "across_clues": [(2, "The big boat."), (3, "The bird with the olive leaf."), (4, "It fell for forty days.")],
    "answer_line": "1 NOAH · 2 ARK · 3 DOVE · 4 RAIN"},
  "match": [("Ark", "the big boat"), ("Dove", "a gentle bird"), ("Rain", "water from the sky"),
            ("Rainbow", "God's promise"), ("Obey", "do what God says"), ("Promise", "a kept word")],
  "fill_blanks": {"bank": ["ark", "animals", "rain", "dove", "rainbow"],
    "sentences": ["God told Noah to build an __________.", "The __________ came two by two.",
                  "The __________ fell for forty days.", "A __________ brought back an olive leaf.",
                  "God set a __________ in the sky."],
    "answers": "ark · animals · rain · dove · rainbow"},
  "acrostic": "NOAH",
  "secret_code": code("OBEY", "GOD IS TRUE"),
  "colouring": [
    {"title": "Colour Noah's Ark", "sub": "The big boat", "note": "Add animals looking out of the windows!"},
    {"title": "Colour the Animals", "sub": "Two by two", "note": "Colour each pair the same."},
    {"title": "Colour the Rainbow", "sub": "God's promise", "note": "Use all seven colours!"},
    {"title": "Colour the Dove", "sub": "With the olive leaf", "note": "Make the dove pure white."},
  ],
  "count_word": "animals", "count_sets": [2, 2, 4, 2],
  "maze_title": "Help the Animals Reach the Ark", "maze_instr": "Guide the animals safely into the ark before the rain.",
  "scenarios": [
    {"q": "A parent asks you to do a chore you dislike.", "opts": "a) <strong>Obey with a good attitude.</strong> &nbsp; b) Complain and refuse."},
    {"q": "Others tease you for doing right.", "opts": "a) Stop to fit in. &nbsp; b) <strong>Keep doing right, like Noah.</strong>"},
    {"q": "A friend feels left out.", "opts": "a) <strong>Care for them and include them.</strong> &nbsp; b) Ignore them."},
  ],
  "apply_sub": "Obeying God like Noah",
  "drama": ["Choose Noah, his family, and children to be animals in pairs.",
    "Noah 'builds' the ark while others 'laugh', then wonder.", "Animals march in two by two.",
    "Everyone cheers under a paper rainbow at the end!"],
  "game_title": "Game: Animals Two by Two", "game_need": "pairs of animal cards or just imagination",
  "game_steps": ["Whisper an animal name to pairs of children.", "On 'go', everyone makes their animal sound.",
                 "Children must find their matching partner by sound.", "Once paired, they 'board the ark' (a taped square)."],
  "game_tip": "Keep the noise fun but brief, then settle straight into the next activity.",
  "craft_title": "Craft: Paper-Plate Rainbow", "craft_sub": "Make God's promise sign!",
  "craft_need": "paper or half a paper plate, crayons, cotton wool, glue",
  "craft_steps": ["Draw seven arches for the rainbow.", "Colour them red, orange, yellow, green, blue, indigo, violet.",
                  "Glue cotton-wool clouds at each end.", "Remember: the rainbow shows God keeps his promises!"],
  "template_title": "Ark Template",
  "snack": "Serve animal crackers 'two by two' and rainbow fruit slices.",
  "takehome": "Noah teaches us to obey God and trust that he always keeps his promises.",
  "home_activity": "Look for a rainbow (or draw one) and talk about a promise God keeps.",
  "family_prayer": "Dear God, thank you that you keep your promises. Help our family to obey and trust you. Amen.",
  "three_lessons": ["Obey God", "Keep Trusting", "God Is Faithful"],
  "review": "Today we learned that Noah obeyed God, and God kept everyone safe and gave the rainbow promise.",
  "closing_prayer": "Dear God, thank you for keeping your promises like the rainbow. Help us obey you this week. Amen.",
  "welldone": "You have finished the Noah lesson! Obey God, keep trusting, and remember he is faithful.",
  "cert_line": "for learning to obey and trust God, just like Noah!",
})

# ===========================================================================
# 5 — Jonah's Big Adventure Sunday School Lesson Pack
# ===========================================================================
BOOKS.append({
  "slug": "05-jonah", "short": "Jonah's Big Adventure",
  "icon": "fish", "icon2": "waves",
  "title": "Jonah's Big Adventure",
  "theme": "A Sunday-School Lesson on Obedience & Second Chances",
  "cover_line": "Learning to obey God and that God gives second chances.",
  "welcome": "Welcome to this lesson about Jonah and the big fish. This pack has a full session: story, memory verse, discussion, games, a craft and printable activities for ages 4 to 12.",
  "welcome_tip": "A blue sheet or fabric makes a great 'sea' for the story and games.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn to obey God and that God lovingly gives second chances.",
  "objectives": ["Retell Jonah's adventure.", "Explain why obeying God is best.",
    "Recite the memory verse (Jonah 2:2).", "Name someone they can forgive or a fresh start they can make."],
  "prep": ["Bibles or printed story pages", "Crayons, scissors, glue",
           "Paper plate for the fish craft", "Optional: a blue sheet for the 'sea'"],
  "prep_tip": "Practise the 'storm' sounds (clapping, stamping) so children can join in the story.",
  "gathering": "Gather in a circle. Ask about a time someone gave them another chance and how it felt.",
  "opening_prayer": "Dear God, thank you that you always hear us and give us second chances. Help us to obey you. Amen.",
  "icebreaker": "Have you ever tried to run away from doing something? What happened?",
  "story": [
    {"sub": "Jonah Runs Away", "paras": [
      "God told Jonah, 'Go to the big city of Nineveh and tell the people to stop doing wrong.' But Jonah did not want to go.",
      "Instead, Jonah got on a ship going the opposite way, trying to run away from God."]},
    {"sub": "The Big Storm", "paras": [
      "God sent a huge storm. The wind roared and the waves crashed. The sailors were terrified.",
      "Jonah knew it was because he had run away. He said, 'Throw me into the sea, and it will grow calm.'"]},
    {"sub": "Inside the Big Fish", "paras": [
      "When they threw Jonah in, the storm stopped. Then God sent a great big fish that swallowed Jonah whole.",
      "Jonah was safe inside for three days. There, he prayed and told God he was sorry."]},
    {"sub": "A Second Chance", "paras": [
      "God heard Jonah and had the fish bring him safely to dry land. 'Go to Nineveh,' God said again.",
      "This time Jonah obeyed. The people of Nineveh listened and turned to God, who kindly forgave them."]},
  ],
  "verse": {"text": "I called to the Lord in my trouble, and he answered me.", "ref": "Jonah 2:2"},
  "verse_tip": "Have children cup hands like a fish while saying the verse to picture Jonah praying inside.",
  "discussion": ["Why did Jonah try to run from God?", "What did Jonah do inside the fish?",
    "What does a 'second chance' mean?", "Why is it good to obey God the first time?",
    "Who can you forgive or be kind to this week?"],
  "easy_q": [
    {"q": "Where did God tell Jonah to go?", "opts": "a) Egypt &nbsp; b) <strong>Nineveh</strong> &nbsp; c) Rome"},
    {"q": "What swallowed Jonah?", "opts": "a) A wave &nbsp; b) <strong>A big fish</strong> &nbsp; c) A boat"},
    {"q": "How many days was Jonah inside?", "opts": "a) One &nbsp; b) <strong>Three</strong> &nbsp; c) Seven"},
    {"q": "God gave Jonah a second ___.", "opts": "a) fish &nbsp; b) <strong>chance</strong> &nbsp; c) storm"},
  ],
  "hard_q": ["Why did Jonah try to run away from God?", "What did Jonah learn inside the fish?",
    "Describe a time you were given a second chance.", "How can you obey God even when it's hard?"],
  "true_false": [("God told Jonah to go to Nineveh.", True), ("Jonah obeyed right away.", False),
    ("A big fish swallowed Jonah.", True), ("Jonah prayed inside the fish.", True),
    ("Nineveh ignored God's message.", False)],
  "sequence": ["God tells Jonah to go to Nineveh.", "Jonah runs away and a storm comes.",
    "A big fish swallows Jonah, and he prays.", "Jonah obeys and Nineveh turns to God."],
  "ws_words": ["JONAH", "FISH", "STORM", "SHIP", "PRAY", "NINEVEH", "SEA", "OBEY"],
  "crossword": {"spine": "JONAH", "crossers": ["FISH", "STORM", "PRAY"], "grid": 13,
    "down_clues": [(1, "He ran from God, then obeyed.")],
    "across_clues": [(2, "It swallowed Jonah."), (3, "Wild wind and waves at sea."),
                     (4, "Jonah did this inside the fish.")],
    "answer_line": "1 JONAH · 2 FISH · 3 STORM · 4 PRAY"},
  "match": [("Fish", "swallowed Jonah"), ("Ship", "a boat on the sea"), ("Storm", "wild wind and waves"),
            ("Pray", "talk to God"), ("Obey", "do what God says"), ("Forgive", "give a fresh start")],
  "fill_blanks": {"bank": ["Nineveh", "ship", "fish", "prayed", "chance"],
    "sentences": ["God told Jonah to go to __________.", "Jonah ran away on a __________.",
                  "A big __________ swallowed Jonah.", "Inside, Jonah __________ to God.",
                  "God gave Jonah a second __________."],
    "answers": "Nineveh · ship · fish · prayed · chance"},
  "acrostic": "JONAH",
  "secret_code": code("OBEY", "GOD HEARS US"),
  "colouring": [
    {"title": "Colour the Big Fish", "sub": "Sent by God", "note": "Give the fish big friendly eyes!"},
    {"title": "Colour the Stormy Sea", "sub": "Big waves", "note": "Use dark blues and greys."},
    {"title": "Colour Jonah Praying", "sub": "Inside the fish", "note": "Draw Jonah with folded hands."},
    {"title": "Colour the City of Nineveh", "sub": "They listened to God", "note": "Add happy people."},
  ],
  "count_word": "fish", "count_sets": [3, 1, 4, 2],
  "maze_title": "Help Jonah Reach Nineveh", "maze_instr": "Guide Jonah from the shore to the city of Nineveh.",
  "scenarios": [
    {"q": "You are asked to do good but don't feel like it.", "opts": "a) <strong>Choose to obey anyway.</strong> &nbsp; b) Run away from it."},
    {"q": "You made a mistake and feel bad.", "opts": "a) Hide and stay sad. &nbsp; b) <strong>Say sorry and try again.</strong>"},
    {"q": "Someone who was unkind says sorry.", "opts": "a) <strong>Forgive them kindly.</strong> &nbsp; b) Stay angry."},
  ],
  "apply_sub": "Obeying God and forgiving like the lesson teaches",
  "drama": ["Choose Jonah, sailors, and children to be the 'sea' and the 'big fish'.",
    "Sailors 'rock' the boat during the storm.", "The 'fish' (children in a circle) surrounds Jonah, who prays.",
    "Jonah is set free and hurries off to Nineveh — the people cheer and turn to God!"],
  "game_title": "Game: Storm & Calm", "game_need": "space to move",
  "game_steps": ["When the leader says 'Storm!', children sway and make wind sounds.",
                 "When the leader says 'Calm!', everyone freezes still and quiet.",
                 "Anyone who moves during 'Calm' sits for a round.", "Talk about how God calmed the real storm."],
  "game_tip": "Alternate quickly between storm and calm to keep everyone laughing and listening.",
  "craft_title": "Craft: Paper-Plate Big Fish", "craft_sub": "Make Jonah's big fish!",
  "craft_need": "a paper plate, crayons, scissors, glue",
  "craft_steps": ["Cut a small triangle from the plate; glue it on the back as a tail.",
                  "Colour the fish and add scales.", "Add a big eye and a friendly smile.",
                  "Remember: God can rescue us, just like he rescued Jonah!"],
  "template_title": "Fish Template",
  "snack": "Serve fish-shaped crackers and blue jelly 'sea' cups.",
  "takehome": "Jonah teaches us to obey God and that God lovingly gives second chances.",
  "home_activity": "Talk about obeying quickly, and forgive someone in the family this week.",
  "family_prayer": "Dear God, thank you for second chances. Help our family to obey you and forgive one another. Amen.",
  "three_lessons": ["Obey God", "Say Sorry", "God Forgives"],
  "review": "Today we learned that Jonah ran away, but God rescued him and gave a second chance. God hears us when we pray.",
  "closing_prayer": "Dear God, thank you for always hearing us. Help us to obey you and to forgive others. Amen.",
  "welldone": "You have finished Jonah's adventure! Obey God, say sorry when needed, and remember God forgives.",
  "cert_line": "for learning to obey God and value second chances, just like Jonah!",
})


# ===========================================================================
# 6 — Joseph Forgives His Brothers Bible Lesson Pack
# ===========================================================================
BOOKS.append({
  "slug": "06-joseph", "short": "Joseph Forgives His Brothers",
  "icon": "scroll", "icon2": "crown",
  "title": "Joseph Forgives His Brothers",
  "theme": "A Sunday-School Lesson on Forgiveness & God's Plan",
  "cover_line": "Learning to forgive others and trust God's good plan.",
  "welcome": "Welcome to this lesson about Joseph, who forgave his brothers and trusted God's plan. This pack has a full session: story, memory verse, discussion, games, a craft and activities for ages 4 to 12.",
  "welcome_tip": "Bring strips of coloured paper so children can 'build' Joseph's colourful coat.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn to forgive others and trust that God works everything for good.",
  "objectives": ["Retell Joseph's story.", "Explain what forgiveness means.",
    "Recite the memory verse (Genesis 50:20).", "Name one person they can forgive."],
  "prep": ["Bibles or printed story pages", "Crayons, coloured paper, scissors, glue", "Optional: a plain coat or cloth"],
  "prep_tip": "Talk gently about forgiveness; some children may find this topic personal.",
  "gathering": "Gather in a circle. Ask children how it feels to be forgiven after doing something wrong.",
  "opening_prayer": "Dear God, thank you for forgiving us. Help us learn to forgive others, like Joseph did. Amen.",
  "icebreaker": "What is your favourite colour? If you had a coat of many colours, which would you choose?",
  "story": [
    {"sub": "The Colourful Coat", "paras": [
      "Joseph was one of twelve brothers. His father loved him and gave him a beautiful coat of many colours.",
      "Joseph also had special dreams from God. But his brothers became very jealous of him."]},
    {"sub": "Sold by His Brothers", "paras": [
      "The jealous brothers sold Joseph to traders going to Egypt and told their father he was gone.",
      "In Egypt, Joseph worked hard and stayed honest. Even when treated unfairly, he trusted God."]},
    {"sub": "From Prison to Palace", "paras": [
      "God helped Joseph understand dreams. He warned Pharaoh of coming hungry years and how to prepare.",
      "Pharaoh put Joseph in charge of all Egypt to store food. Joseph saved many people from starving."]},
    {"sub": "Joseph Forgives", "paras": [
      "When his brothers came to buy food, Joseph knew them. Instead of anger, he forgave them and wept for joy.",
      "'You meant to harm me, but God used it for good,' Joseph said. The whole family was joyfully together again."]},
  ],
  "verse": {"text": "You planned to harm me, but God planned it for good.", "ref": "Genesis 50:20"},
  "verse_tip": "Use a frown-to-smile motion to show how God turns bad things into good.",
  "discussion": ["Why were Joseph's brothers jealous?", "How did Joseph stay faithful in hard times?",
    "Why is forgiving others hard, and why is it good?", "How can God bring good from hard times?",
    "Who is someone you need to forgive?"],
  "easy_q": [
    {"q": "What did Joseph's father give him?", "opts": "a) A crown &nbsp; b) <strong>A colourful coat</strong> &nbsp; c) A sword"},
    {"q": "Where was Joseph taken?", "opts": "a) <strong>Egypt</strong> &nbsp; b) Rome &nbsp; c) Persia"},
    {"q": "What could Joseph understand?", "opts": "a) Songs &nbsp; b) <strong>Dreams</strong> &nbsp; c) Maps"},
    {"q": "Joseph chose to ___ his brothers.", "opts": "a) punish &nbsp; b) <strong>forgive</strong> &nbsp; c) ignore"},
  ],
  "hard_q": ["Why were Joseph's brothers jealous of him?", "How did Joseph keep trusting God in prison?",
    "Describe a time you forgave someone.", "How can forgiving others make you feel free?"],
  "true_false": [("Joseph got a colourful coat.", True), ("Joseph's brothers were kind to him.", False),
    ("Joseph could understand dreams.", True), ("Joseph forgave his brothers.", True),
    ("Joseph stayed angry forever.", False)],
  "sequence": ["Joseph gets a colourful coat.", "His brothers sell him to Egypt.",
    "Joseph is put in charge of Egypt.", "Joseph forgives his brothers."],
  "ws_words": ["JOSEPH", "COAT", "DREAM", "EGYPT", "FORGIVE", "BROTHERS", "GRAIN", "PLAN"],
  "crossword": {"spine": "JOSEPH", "crossers": ["COAT", "DREAM", "PLAN"], "grid": 13,
    "down_clues": [(1, "He forgave his brothers.")],
    "across_clues": [(2, "His father gave a colourful one."), (3, "Joseph could understand these."),
                     (4, "God had a good one for Joseph.")],
    "answer_line": "1 JOSEPH · 2 COAT · 3 DREAM · 4 PLAN"},
  "match": [("Coat", "colourful gift"), ("Dream", "Joseph understood these"), ("Forgive", "let go of a wrong"),
            ("Brother", "family member"), ("Grain", "stored food"), ("Plan", "God's good purpose")],
  "fill_blanks": {"bank": ["coat", "Egypt", "dreams", "forgave", "plan"],
    "sentences": ["Joseph's father gave him a colourful __________.", "Joseph was taken to __________.",
                  "God helped Joseph understand __________.", "God had a good __________ all along.",
                  "Joseph __________ his brothers with love."],
    "answers": "coat · Egypt · dreams · plan · forgave"},
  "acrostic": "FORGIVE",
  "secret_code": code("FORGIVE", "GOD IS GOOD"),
  "colouring": [
    {"title": "Colour Joseph's Coat", "sub": "Many colours", "note": "Use as many colours as you can!"},
    {"title": "Colour the Grain Store", "sub": "Food for hungry years", "note": "Draw baskets full of grain."},
    {"title": "Colour the Palace", "sub": "In Egypt", "note": "Add tall palm trees."},
    {"title": "Colour the Happy Family", "sub": "Together again", "note": "Give everyone a big smile."},
  ],
  "count_word": "coats", "count_sets": [2, 4, 1, 3],
  "maze_title": "Help the Family Reach Egypt", "maze_instr": "Guide the brothers through the desert to Egypt to find food.",
  "scenarios": [
    {"q": "Someone breaks your favourite thing by accident.", "opts": "a) <strong>Forgive them.</strong> &nbsp; b) Stay angry all day."},
    {"q": "Someone treats you unfairly.", "opts": "a) Plan revenge. &nbsp; b) <strong>Do good and trust God.</strong>"},
    {"q": "You feel like giving up in a hard time.", "opts": "a) <strong>Be patient and keep trusting God.</strong> &nbsp; b) Give up."},
  ],
  "apply_sub": "Forgiving others like Joseph",
  "drama": ["Choose Joseph, his father, the brothers and Pharaoh.",
    "The brothers 'sell' Joseph; Joseph works and rises in Egypt.",
    "The brothers come for food and don't recognise Joseph.",
    "Joseph reveals himself and forgives them — a joyful family hug!"],
  "game_title": "Game: Coat of Colours Relay", "game_need": "coloured paper strips, two baskets",
  "game_steps": ["Two teams line up with a basket of colour strips.", "Each child adds one strip to a 'coat' on the wall.",
                 "First team to build a full colourful coat wins.", "Talk about how God had a colourful plan for Joseph."],
  "game_tip": "Keep strips large and taped lightly so it's quick and mess-free.",
  "craft_title": "Craft: Coat of Many Colours", "craft_sub": "Make a colourful coat!",
  "craft_need": "paper, crayons or coloured paper scraps, scissors, glue",
  "craft_steps": ["Cut out a coat shape from paper.", "Glue on colour strips or colour in bright stripes.",
                  "Add buttons and patterns.", "Remember: God had a good plan for Joseph, and for you too!"],
  "template_title": "Coat Template",
  "snack": "Serve a rainbow of fruit pieces to match Joseph's colourful coat.",
  "takehome": "Joseph teaches us to forgive others and trust God's good plan.",
  "home_activity": "As a family, forgive one another for something small and pray together.",
  "family_prayer": "Dear God, thank you for your good plans. Help our family to forgive and to trust you. Amen.",
  "three_lessons": ["Forgive", "Be Patient", "Trust God's Plan"],
  "review": "Today we learned that Joseph forgave his brothers and trusted God's plan, even after hard times.",
  "closing_prayer": "Dear God, thank you for forgiving us. Help us to forgive others and trust your good plan. Amen.",
  "welldone": "You have finished the Joseph lesson! Forgive others, be patient, and trust God's plan.",
  "cert_line": "for learning to forgive and trust God's plan, just like Joseph!",
})

# ===========================================================================
# 7 — Moses and the Ten Commandments Activity Pack
# ===========================================================================
BOOKS.append({
  "slug": "07-moses-commandments", "short": "Moses and the Ten Commandments",
  "icon": "tablets", "icon2": "scroll",
  "title": "Moses and the Ten Commandments",
  "theme": "A Sunday-School Lesson on God's Good Rules",
  "cover_line": "Learning that God's rules help us love him and love others.",
  "welcome": "Welcome to this lesson about Moses receiving God's Ten Commandments. This pack has a full session: story, memory verse, discussion, games, a craft and activities for ages 4 to 12.",
  "welcome_tip": "Cut two 'tablet' shapes from card ahead of time to show the Ten Commandments.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn that God gave good rules to help us love him and love others.",
  "objectives": ["Retell how Moses received the commandments.", "Explain why God's rules are good.",
    "Recite the memory verse (Exodus 20:6).", "Name a rule that shows love to God or others."],
  "prep": ["Bibles or printed story pages", "Crayons, card, scissors, glue", "Grey/brown paper for stone tablets"],
  "prep_tip": "Explain the commandments simply: love God, and love people.",
  "gathering": "Gather in a circle. Ask why we have rules at home and school, and how they help us.",
  "opening_prayer": "Dear God, thank you for giving us good rules to keep us safe and loving. Help us to obey them. Amen.",
  "icebreaker": "What is one good rule at your home? Why does it help?",
  "story": [
    {"sub": "God's People at the Mountain", "paras": [
      "After God rescued his people from Egypt, Moses led them to a great mountain called Sinai.",
      "God wanted to give his people good rules to help them love him and live well together."]},
    {"sub": "Moses Meets God", "paras": [
      "Moses climbed up the mountain to meet with God. There was thunder, smoke and a loud trumpet sound.",
      "God spoke to Moses and gave him the rules to share with all the people."]},
    {"sub": "The Ten Commandments", "paras": [
      "God gave ten commandments written on two stone tablets. The first ones teach us to love God: worship only him, and keep his day holy.",
      "The others teach us to love people: honour your parents, do not steal, do not lie, and be kind and truthful."]},
    {"sub": "Rules That Show Love", "paras": [
      "God's rules were not to make life hard — they were a gift to help his people live in love and peace.",
      "When we obey God's good rules, we show that we love him and we care for the people around us."]},
  ],
  "verse": {"text": "I show my love to those who love me and obey my commands.", "ref": "Exodus 20:6"},
  "verse_tip": "Split the verse: 'love me' (hands on heart) and 'obey' (hands together) to help memory.",
  "discussion": ["Why did God give his people rules?", "Which commandments teach us to love God?",
    "Which teach us to love people?", "How do good rules keep us safe?",
    "What is one rule you can obey to show love this week?"],
  "easy_q": [
    {"q": "Who led God's people to the mountain?", "opts": "a) David &nbsp; b) <strong>Moses</strong> &nbsp; c) Noah"},
    {"q": "How many commandments did God give?", "opts": "a) Three &nbsp; b) <strong>Ten</strong> &nbsp; c) Fifty"},
    {"q": "The commandments were written on ___.", "opts": "a) paper &nbsp; b) <strong>stone tablets</strong> &nbsp; c) sand"},
    {"q": "God's rules help us to ___.", "opts": "a) argue &nbsp; b) <strong>love God and others</strong> &nbsp; c) hide"},
  ],
  "hard_q": ["Why are God's rules a gift, not a burden?", "How do the commandments help people live together?",
    "Describe a rule that shows love to others.", "How can you honour your parents this week?"],
  "true_false": [("Moses met God on the mountain.", True), ("God gave three commandments.", False),
    ("The commandments were on stone tablets.", True), ("The rules help us love God and others.", True),
    ("God's rules are meant to be unkind.", False)],
  "sequence": ["God rescues his people from Egypt.", "Moses climbs the mountain to meet God.",
    "God gives the Ten Commandments on stone.", "The people learn to love God and others."],
  "ws_words": ["MOSES", "TEN", "RULES", "STONE", "LOVE", "OBEY", "SINAI", "HONOUR"],
  "crossword": {"spine": "MOSES", "crossers": ["STONE", "TEN", "OBEY"], "grid": 13,
    "down_clues": [(1, "He received the commandments.")],
    "across_clues": [(2, "The tablets were made of this."), (3, "The number of commandments."),
                     (4, "To do what God says.")],
    "answer_line": "1 MOSES · 2 STONE · 3 TEN · 4 OBEY"},
  "match": [("Moses", "led God's people"), ("Ten", "the number of rules"), ("Tablets", "the stone slabs"),
            ("Obey", "do what God says"), ("Honour", "show respect"), ("Love", "care for God and others")],
  "fill_blanks": {"bank": ["Moses", "mountain", "ten", "stone", "love"],
    "sentences": ["__________ led God's people from Egypt.", "He met God on the __________.",
                  "God gave __________ commandments.", "They were written on __________ tablets.",
                  "The rules teach us to __________ God and others."],
    "answers": "Moses · mountain · ten · stone · love"},
  "acrostic": "OBEY",
  "secret_code": code("OBEY", "GOD IS LOVE"),
  "colouring": [
    {"title": "Colour the Stone Tablets", "sub": "The Ten Commandments", "note": "Write the numbers I to X!"},
    {"title": "Colour Mount Sinai", "sub": "Where Moses met God", "note": "Add smoke and clouds at the top."},
    {"title": "Colour Moses", "sub": "Holding the tablets", "note": "Give Moses a long robe."},
    {"title": "Colour a Heart of Love", "sub": "Rules that show love", "note": "Fill it with kind words."},
  ],
  "count_word": "tablets", "count_sets": [2, 4, 2, 3],
  "maze_title": "Help Moses Climb the Mountain", "maze_instr": "Guide Moses up the mountain path to meet God.",
  "scenarios": [
    {"q": "You feel like ignoring a good family rule.", "opts": "a) <strong>Obey it with a good heart.</strong> &nbsp; b) Break it secretly."},
    {"q": "You could tell a small lie to avoid trouble.", "opts": "a) Lie to be safe. &nbsp; b) <strong>Tell the truth.</strong>"},
    {"q": "Your parents ask for your help.", "opts": "a) <strong>Honour them and help gladly.</strong> &nbsp; b) Refuse and complain."},
  ],
  "apply_sub": "Loving God and others through obedience",
  "drama": ["Choose Moses and children to be the people at the mountain.",
    "Make 'thunder' by stamping and 'trumpet' sounds with voices.",
    "Moses 'climbs' up and returns holding two paper tablets.",
    "The people cheer for God's good rules and promise to obey."],
  "game_title": "Game: Simon Says (God's Rules)", "game_need": "just the group",
  "game_steps": ["Play 'Simon Says' but say 'God says'.", "Give kind, loving actions: 'God says help a friend'.",
                 "If you act without 'God says', you sit for a round.", "Talk about obeying God's good words."],
  "game_tip": "Use the game to reinforce that obeying is about love, not just following orders.",
  "craft_title": "Craft: Stone Tablet Cards", "craft_sub": "Make your own commandment tablets!",
  "craft_need": "grey or brown card, crayons, scissors, glue",
  "craft_steps": ["Cut two rounded 'tablet' shapes from card.", "On one, write ways to love God; on the other, ways to love people.",
                  "Decorate the edges.", "Remember: God's rules help us love him and love others!"],
  "template_title": "Stone Tablet Template",
  "snack": "Serve rectangular crackers as 'tablets' and let kids 'write' with a raisin.",
  "takehome": "Moses teaches us that God's rules are a gift to help us love him and love others.",
  "home_activity": "Choose one commandment to focus on as a family this week and talk about it.",
  "family_prayer": "Dear God, thank you for your good rules. Help our family to love you and love others. Amen.",
  "three_lessons": ["Love God", "Love Others", "Obey Gladly"],
  "review": "Today we learned that God gave Moses ten good rules to help his people love God and love one another.",
  "closing_prayer": "Dear God, thank you for your commandments. Help us to obey you and show love this week. Amen.",
  "welldone": "You have finished the Ten Commandments lesson! Love God, love others, and obey gladly.",
  "cert_line": "for learning to love God and others through his good rules, just like Moses taught!",
})


# ===========================================================================
# 8 — The Good Samaritan Kindness Lesson Pack
# ===========================================================================
BOOKS.append({
  "slug": "08-good-samaritan", "short": "The Good Samaritan",
  "icon": "heart", "icon2": "scroll",
  "title": "The Good Samaritan",
  "theme": "A Sunday-School Lesson on Kindness & Loving Others",
  "cover_line": "Learning to be kind and to love our neighbour like Jesus taught.",
  "welcome": "Welcome to this lesson about the Good Samaritan, a story Jesus told about kindness. This pack has a full session: story, memory verse, discussion, games, a craft and activities for ages 4 to 12.",
  "welcome_tip": "Keep a 'kindness jar' in class where children add notes about kind acts.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn to show kindness and mercy, loving their neighbour as themselves.",
  "objectives": ["Retell the story of the Good Samaritan.", "Explain who our 'neighbour' is.",
    "Recite the memory verse (Luke 10:27).", "Name one kind act they can do this week."],
  "prep": ["Bibles or printed story pages", "Crayons, coloured paper, scissors, glue", "Optional: bandages as props"],
  "prep_tip": "Have children brainstorm kind acts before the craft to inspire their kindness chain.",
  "gathering": "Gather in a circle. Ask children about a time someone was kind to them.",
  "opening_prayer": "Dear God, thank you for loving us. Help us learn to be kind and to love others, like the Good Samaritan. Amen.",
  "icebreaker": "What is a kind thing someone did for you this week?",
  "story": [
    {"sub": "A Question for Jesus", "paras": [
      "One day a man asked Jesus, 'Who is my neighbour?' Jesus answered by telling a wonderful story.",
      "'A man was travelling on a lonely road,' Jesus began, 'when robbers attacked him and left him hurt.'"]},
    {"sub": "Two Men Pass By", "paras": [
      "A priest came down the road. He saw the hurt man, but he crossed to the other side and walked past.",
      "Then a Levite came. He also saw the man, but he too passed by without helping."]},
    {"sub": "The Kind Samaritan", "paras": [
      "Next, a Samaritan came along. He felt sorry for the hurt man and stopped to help.",
      "He cleaned and bandaged the wounds, lifted the man onto his own donkey, and took him to an inn to rest."]},
    {"sub": "Go and Do the Same", "paras": [
      "The Samaritan even paid the innkeeper to care for the man. He was a true neighbour.",
      "Jesus asked, 'Which one was a good neighbour?' Then he said, 'Go and do the same.' We are neighbours to anyone who needs kindness."]},
  ],
  "verse": {"text": "Love your neighbour as you love yourself.", "ref": "Luke 10:27"},
  "verse_tip": "Point to a neighbour, then to yourself, as you say the verse to make it stick.",
  "discussion": ["Why do you think the priest and Levite did not stop?", "What made the Samaritan a good neighbour?",
    "Who are the 'neighbours' around you?", "Why can helping others cost us something?",
    "How can you show kindness this week?"],
  "easy_q": [
    {"q": "What happened to the traveller?", "opts": "a) He got lost &nbsp; b) <strong>Robbers hurt him</strong> &nbsp; c) He slept"},
    {"q": "Who stopped to help?", "opts": "a) The priest &nbsp; b) The Levite &nbsp; c) <strong>The Samaritan</strong>"},
    {"q": "What carried the hurt man?", "opts": "a) A cart &nbsp; b) <strong>A donkey</strong> &nbsp; c) A boat"},
    {"q": "Jesus said, 'Go and do the ___.'", "opts": "a) <strong>same</strong> &nbsp; b) opposite &nbsp; c) nothing"},
  ],
  "hard_q": ["Why is it sometimes hard to stop and help others?", "What made the Samaritan different from the others?",
    "Describe a time you helped someone in need.", "Who is someone you can be a 'neighbour' to this week?"],
  "true_false": [("Robbers hurt the traveller.", True), ("The priest stopped to help.", False),
    ("The Samaritan helped the man.", True), ("Jesus said to love our neighbour.", True),
    ("Jesus said to ignore hurt people.", False)],
  "sequence": ["A man is hurt by robbers.", "A priest and a Levite pass by.",
    "The Samaritan stops and helps.", "Jesus says, 'Go and do the same.'"],
  "ws_words": ["KIND", "HELP", "MERCY", "LOVE", "DONKEY", "NEIGHBOUR", "CARE", "GOOD"],
  "crossword": {"spine": "MERCY", "crossers": ["HELP", "ROAD", "CARE"], "grid": 13,
    "down_clues": [(1, "Showing pity and help.")],
    "across_clues": [(2, "What the Samaritan gave."), (3, "Where the man was hurt."), (4, "To look after someone.")],
    "answer_line": "1 MERCY · 2 HELP · 3 ROAD · 4 CARE"},
  "match": [("Kind", "gentle and caring"), ("Help", "to give aid"), ("Love", "care deeply"),
            ("Mercy", "pity and help"), ("Donkey", "carried the man"), ("Neighbour", "anyone in need")],
  "fill_blanks": {"bank": ["neighbour", "robbers", "Samaritan", "donkey", "kind"],
    "sentences": ["A man asked, 'Who is my __________?'", "The traveller was hurt by __________.",
                  "A good __________ stopped to help.", "He carried the man on his __________.",
                  "Jesus wants us to be __________ to everyone."],
    "answers": "neighbour · robbers · Samaritan · donkey · kind"},
  "acrostic": "KIND",
  "secret_code": code("KIND", "LOVE OTHERS"),
  "colouring": [
    {"title": "Colour the Good Samaritan", "sub": "He helped a stranger", "note": "Give him a kind, gentle face."},
    {"title": "Colour the Donkey", "sub": "Carrying the hurt man", "note": "Add a soft blanket."},
    {"title": "Colour the Road", "sub": "The lonely road", "note": "Draw hills and rocks."},
    {"title": "Colour a Heart of Kindness", "sub": "Love your neighbour", "note": "Fill the heart with kind words."},
  ],
  "count_word": "hearts", "count_sets": [3, 2, 4, 1],
  "maze_title": "Help the Samaritan Reach the Inn", "maze_instr": "Guide the Samaritan and the donkey along the road to the inn.",
  "scenarios": [
    {"q": "You see someone fall and drop their things.", "opts": "a) <strong>Stop and help them up.</strong> &nbsp; b) Walk past."},
    {"q": "A child no one likes needs a game partner.", "opts": "a) Leave them out. &nbsp; b) <strong>Be their kind partner.</strong>"},
    {"q": "Someone is sad and sitting alone.", "opts": "a) <strong>Sit with them and be kind.</strong> &nbsp; b) Ignore them."},
  ],
  "apply_sub": "Being a kind neighbour like the Samaritan",
  "drama": ["Choose the traveller, robbers (gentle miming!), a priest, a Levite and the Samaritan.",
    "The traveller is 'hurt'; the priest and Levite pass by.",
    "The Samaritan stops, 'bandages' the man and helps him onto a 'donkey'.",
    "End by asking, 'Who was the good neighbour?'"],
  "game_title": "Game: Kindness Pass-It-On", "game_need": "a soft ball or beanbag",
  "game_steps": ["Sit in a circle and pass the ball.", "Whoever holds it names one kind act.",
                 "No repeating ideas!", "See how many kind acts the group can name together."],
  "game_tip": "Write the ideas on the board and encourage children to try one this week.",
  "craft_title": "Craft: Kindness Heart Chain", "craft_sub": "Make a chain of good deeds!",
  "craft_need": "coloured paper, scissors, glue, a pen",
  "craft_steps": ["Cut several paper hearts.", "On each heart, write one kind thing you can do.",
                  "Glue the hearts into a chain.", "Do one kind act each day. Love your neighbour!"],
  "template_title": "Heart Template",
  "snack": "Serve heart-shaped biscuits or fruit while talking about showing kindness.",
  "takehome": "The Good Samaritan teaches us to be kind and to love our neighbour as ourselves.",
  "home_activity": "As a family, do one kind act for a neighbour or friend this week.",
  "family_prayer": "Dear God, thank you for loving us. Help our family to be kind and to love our neighbours. Amen.",
  "three_lessons": ["Be Kind", "Show Mercy", "Love Others"],
  "review": "Today we learned that the Good Samaritan showed kindness. Jesus wants us to love our neighbour.",
  "closing_prayer": "Dear God, help us to have kind hearts and to help people in need, like the Good Samaritan. Amen.",
  "welldone": "You have finished the Good Samaritan lesson! Be kind, show mercy, and love others.",
  "cert_line": "for learning to be kind and love your neighbour, like the Good Samaritan!",
})

# ===========================================================================
# 9 — Jesus Loves Children Bible Activity Pack
# ===========================================================================
BOOKS.append({
  "slug": "09-jesus-loves-children", "short": "Jesus Loves Children",
  "icon": "children", "icon2": "heart",
  "title": "Jesus Loves Children",
  "theme": "A Sunday-School Lesson on Jesus' Love for You",
  "cover_line": "Learning that Jesus loves and welcomes every child — including you!",
  "welcome": "Welcome to this lesson about how Jesus welcomed and blessed the children. This pack has a full session: story, memory verse, discussion, games, a craft and activities for ages 4 to 12.",
  "welcome_tip": "This is a wonderful lesson to remind every child they are loved and valued by Jesus.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible Story (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn that Jesus loves and welcomes every child, including them.",
  "objectives": ["Retell how Jesus welcomed the children.", "Explain that Jesus loves each child.",
    "Recite the memory verse (Mark 10:14).", "Say one way they know Jesus loves them."],
  "prep": ["Bibles or printed story pages", "Crayons, paper, scissors, glue", "A mirror or hand-mirror craft materials"],
  "prep_tip": "Affirm each child personally — this lesson is about belonging and being loved.",
  "gathering": "Gather in a circle. Tell each child, 'Jesus loves you!' and let them say it to a friend.",
  "opening_prayer": "Dear Jesus, thank you for loving each one of us. Help us to feel your love and to share it. Amen.",
  "icebreaker": "What makes you feel loved and special?",
  "story": [
    {"sub": "Crowds Follow Jesus", "paras": [
      "Everywhere Jesus went, crowds followed to hear him teach and to be healed.",
      "Parents wanted Jesus to bless their children, so they brought them close to him."]},
    {"sub": "The Disciples Say No", "paras": [
      "The disciples thought Jesus was too busy and important for little children.",
      "They tried to send the children away. 'Don't bother Jesus,' they said."]},
    {"sub": "Let the Children Come", "paras": [
      "But Jesus was not too busy. He said, 'Let the little children come to me. Do not stop them!'",
      "Jesus welcomed every child with open arms. Children were important and precious to him."]},
    {"sub": "Jesus Blesses the Children", "paras": [
      "Jesus took the children in his arms, placed his hands on them, and blessed them.",
      "Jesus said God's kingdom belongs to those who come to him like a child. Jesus loves you very much!"]},
  ],
  "verse": {"text": "Let the little children come to me.", "ref": "Mark 10:14"},
  "verse_tip": "Open your arms wide as you say the verse — just as Jesus welcomed the children.",
  "discussion": ["Why did the disciples try to send the children away?", "What did Jesus say instead?",
    "How do you think the children felt when Jesus welcomed them?", "How do we know Jesus loves us?",
    "How can we welcome others the way Jesus welcomed the children?"],
  "easy_q": [
    {"q": "Who wanted to bless the children?", "opts": "a) <strong>Jesus</strong> &nbsp; b) A king &nbsp; c) A teacher"},
    {"q": "Who tried to send the children away?", "opts": "a) Parents &nbsp; b) <strong>The disciples</strong> &nbsp; c) Angels"},
    {"q": "Jesus said, 'Let the children ___ to me.'", "opts": "a) <strong>come</strong> &nbsp; b) wait &nbsp; c) leave"},
    {"q": "Jesus ___ the children.", "opts": "a) ignored &nbsp; b) <strong>blessed</strong> &nbsp; c) scolded"},
  ],
  "hard_q": ["Why were children important to Jesus?", "What does it mean that Jesus welcomed everyone?",
    "How does it feel to know Jesus loves you?", "How can you help others feel welcome and loved?"],
  "true_false": [("Jesus welcomed the children.", True), ("The disciples wanted to send children away.", True),
    ("Jesus was too busy for children.", False), ("Jesus blessed the children.", True),
    ("Jesus said children are not important.", False)],
  "sequence": ["Crowds follow Jesus.", "Parents bring their children to Jesus.",
    "The disciples try to send them away.", "Jesus welcomes and blesses the children."],
  "ws_words": ["JESUS", "LOVE", "CHILDREN", "BLESS", "COME", "WELCOME", "KIND", "HUG"],
  "crossword": {"spine": "JESUS", "crossers": ["LOVE", "BLESS", "TRUST"], "grid": 13,
    "down_clues": [(1, "He welcomed the children.")],
    "across_clues": [(2, "What Jesus has for every child."), (3, "Jesus did this to the children."),
                     (4, "To lean on Jesus completely.")],
    "answer_line": "1 JESUS · 2 LOVE · 3 BLESS · 4 TRUST"},
  "match": [("Jesus", "God's Son"), ("Love", "deep care"), ("Bless", "to give God's favour"),
            ("Welcome", "make someone glad"), ("Kind", "gentle and caring"), ("Child", "loved by Jesus")],
  "fill_blanks": {"bank": ["Jesus", "children", "come", "blessed", "love"],
    "sentences": ["The parents brought their children to __________.", "The disciples tried to send the __________ away.",
                  "Jesus said, 'Let the children __________ to me.'", "Jesus __________ the children.",
                  "Jesus has great __________ for you."],
    "answers": "Jesus · children · come · blessed · love"},
  "acrostic": "LOVE",
  "secret_code": code("LOVE", "JESUS LOVES YOU"),
  "colouring": [
    {"title": "Colour Jesus and the Children", "sub": "Welcomed with love", "note": "Draw smiles on every face!"},
    {"title": "Colour a Big Heart", "sub": "Jesus loves you", "note": "Write your name inside the heart."},
    {"title": "Colour the Happy Children", "sub": "Coming to Jesus", "note": "Colour lots of children."},
    {"title": "Colour a Welcome Banner", "sub": "All are welcome", "note": "Add bright colours and stars."},
  ],
  "count_word": "children", "count_sets": [3, 2, 4, 1],
  "maze_title": "Help the Children Reach Jesus", "maze_instr": "Guide the children through the crowd to Jesus.",
  "scenarios": [
    {"q": "A new child feels shy and left out.", "opts": "a) <strong>Welcome them warmly.</strong> &nbsp; b) Leave them alone."},
    {"q": "Someone feels unloved and sad.", "opts": "a) Ignore them. &nbsp; b) <strong>Remind them Jesus loves them.</strong>"},
    {"q": "A younger child wants to join your game.", "opts": "a) <strong>Include them kindly.</strong> &nbsp; b) Send them away."},
  ],
  "apply_sub": "Welcoming and loving others like Jesus",
  "drama": ["Choose Jesus, parents, children and disciples.",
    "Parents bring children forward; disciples try to stop them.",
    "Jesus opens his arms and says, 'Let the children come to me!'",
    "Jesus 'blesses' each child with a gentle hand on the head."],
  "game_title": "Game: Come to Jesus Circle", "game_need": "just the group",
  "game_steps": ["One child stands as a friendly 'welcomer' in the middle.", "They call, 'Come to me!' and wave friends in.",
                 "Each child joins the circle with a happy wave.", "Talk about how Jesus welcomes everyone."],
  "game_tip": "Make sure every child is chosen and welcomed so no one feels left out.",
  "craft_title": "Craft: 'Jesus Loves Me' Mirror", "craft_sub": "See how loved you are!",
  "craft_need": "paper or card, foil or a small mirror, crayons, glue, scissors",
  "craft_steps": ["Cut a circle or heart frame from card.", "Glue foil (or a small mirror) in the middle.",
                  "Write 'Jesus loves me!' around the frame.", "Look in it and remember: Jesus loves YOU!"],
  "template_title": "Heart Frame Template",
  "snack": "Serve heart-shaped snacks and say 'Jesus loves you' as you hand each one out.",
  "takehome": "Jesus teaches us that he loves and welcomes every child — including yours.",
  "home_activity": "Tell your child 'Jesus loves you' each day this week, and pray together.",
  "family_prayer": "Dear Jesus, thank you for loving each person in our family. Help us to share your love. Amen.",
  "three_lessons": ["Jesus Loves You", "You Matter", "Welcome Others"],
  "review": "Today we learned that Jesus welcomed the children with love. Jesus loves and welcomes you too!",
  "closing_prayer": "Dear Jesus, thank you for loving us and welcoming us to you. Help us to love and welcome others. Amen.",
  "welldone": "You have finished this lesson! Remember every day: Jesus loves you, you matter, and you can welcome others.",
  "cert_line": "for learning how much Jesus loves and welcomes every child!",
})

# ===========================================================================
# 10 — The Armor of God Sunday School Activity Pack
# ===========================================================================
BOOKS.append({
  "slug": "10-armor-of-god", "short": "The Armor of God",
  "icon": "shield", "icon2": "helmet",
  "title": "The Armor of God",
  "theme": "A Sunday-School Lesson on Standing Strong in Faith",
  "cover_line": "Learning to put on God's armor and stand strong in faith.",
  "welcome": "Welcome to this lesson about the Armor of God from Ephesians 6. This pack has a full session: story, memory verse, discussion, games, a craft and activities for ages 4 to 12.",
  "welcome_tip": "Make simple cardboard armor pieces to show each part as you teach.",
  "how_to_use": ["Open with prayer and the icebreaker.", "Read the Bible lesson (pages 6–9).",
    "Learn and discuss the memory verse.", "Choose activities, a game and the craft.",
    "Close in prayer and give out the certificate."],
  "aim": "Children will learn that God gives us spiritual 'armor' to stand strong and do what is right.",
  "objectives": ["Name the pieces of the armor of God.", "Explain what each piece helps us do.",
    "Recite the memory verse (Ephesians 6:11).", "Choose one piece of armor to 'wear' this week."],
  "prep": ["Bibles or printed lesson pages", "Crayons, card, scissors, glue", "Optional: cardboard for a shield and sword"],
  "prep_tip": "Teach each armor piece with a simple action so children remember them.",
  "gathering": "Gather in a circle. Ask children what protects a knight or soldier, then explain God protects us too.",
  "opening_prayer": "Dear God, thank you for giving us your armor to stand strong. Help us to be brave and do right. Amen.",
  "icebreaker": "If you were a knight, which piece of armor would you want most, and why?",
  "story": [
    {"sub": "Standing Strong", "paras": [
      "The apostle Paul wrote a letter to teach Christians how to stand strong and do what is right.",
      "He said God gives us special 'armor' — not made of metal, but to help our hearts and minds be strong in faith."]},
    {"sub": "The Belt and the Breastplate", "paras": [
      "First is the belt of truth — always telling the truth and living honestly.",
      "Next is the breastplate of righteousness — doing what is right, which guards our hearts like a breastplate guards the chest."]},
    {"sub": "Shoes, Shield and Helmet", "paras": [
      "We wear shoes of peace, ready to share the good news of Jesus wherever we go.",
      "The shield of faith protects us when we are tempted, and the helmet of salvation guards our minds, reminding us we belong to God."]},
    {"sub": "The Sword of the Spirit", "paras": [
      "Last is the sword of the Spirit, which is God's Word, the Bible. We learn it and use it to know what is true.",
      "When we 'put on' all of God's armor and pray, we can stand strong and do what is right, with God's help."]},
  ],
  "verse": {"text": "Put on the full armor of God so you can stand strong.", "ref": "Ephesians 6:11"},
  "verse_tip": "Do a 'suit up' motion (belt, chest, feet, arm, head) as you review each armor piece.",
  "discussion": ["Why do soldiers wear armor?", "What does the belt of truth help us do?",
    "How does the shield of faith help us?", "Why is God's Word called a sword?",
    "Which piece of armor do you most want to 'wear' this week?"],
  "easy_q": [
    {"q": "Who wrote about the armor of God?", "opts": "a) David &nbsp; b) <strong>Paul</strong> &nbsp; c) Noah"},
    {"q": "The shield is the shield of ___.", "opts": "a) gold &nbsp; b) <strong>faith</strong> &nbsp; c) wood"},
    {"q": "The sword of the Spirit is God's ___.", "opts": "a) crown &nbsp; b) <strong>Word</strong> &nbsp; c) song"},
    {"q": "The armor helps us to ___.", "opts": "a) hide &nbsp; b) <strong>stand strong</strong> &nbsp; c) sleep"},
  ],
  "hard_q": ["Why do we need God's armor, not metal armor?", "How does the helmet of salvation guard our minds?",
    "Describe a time you needed to 'stand strong' and do right.", "How can reading the Bible help you each day?"],
  "true_false": [("God gives us spiritual armor.", True), ("The armor is made of real metal.", False),
    ("The shield is the shield of faith.", True), ("The sword of the Spirit is God's Word.", True),
    ("The armor helps us run away and hide.", False)],
  "sequence": ["Paul teaches us to stand strong.", "We put on the belt of truth and breastplate.",
    "We take up the shield of faith and helmet.", "We hold the sword of the Spirit — God's Word."],
  "ws_words": ["ARMOR", "SHIELD", "FAITH", "TRUTH", "HELMET", "SWORD", "STAND", "PEACE"],
  "crossword": {"spine": "ARMOR", "crossers": ["FAITH", "TRUTH", "SWORD"], "grid": 13,
    "down_clues": [(1, "God gives us this to stand strong.")],
    "across_clues": [(2, "The shield of ___."), (3, "The belt of ___."), (4, "The ___ of the Spirit is God's Word.")],
    "answer_line": "1 ARMOR · 2 FAITH · 3 TRUTH · 4 SWORD"},
  "match": [("Belt", "of truth"), ("Shield", "of faith"), ("Helmet", "of salvation"),
            ("Sword", "God's Word"), ("Shoes", "of peace"), ("Breastplate", "of righteousness")],
  "fill_blanks": {"bank": ["armor", "truth", "faith", "sword", "stand"],
    "sentences": ["God gives us his full __________.", "We wear the belt of __________.",
                  "We take up the shield of __________.", "The __________ of the Spirit is God's Word.",
                  "God's armor helps us to __________ strong."],
    "answers": "armor · truth · faith · sword · stand"},
  "acrostic": "FAITH",
  "secret_code": code("FAITH", "STAND STRONG"),
  "colouring": [
    {"title": "Colour the Shield of Faith", "sub": "It protects us", "note": "Add a bright cross in the centre!"},
    {"title": "Colour the Helmet of Salvation", "sub": "Guards our minds", "note": "Make it shiny and strong."},
    {"title": "Colour the Sword of the Spirit", "sub": "God's Word", "note": "Write 'BIBLE' on the blade."},
    {"title": "Colour a Cross", "sub": "Jesus is our strength", "note": "Decorate it beautifully."},
  ],
  "count_word": "shields", "count_sets": [2, 3, 1, 4],
  "maze_title": "Suit Up in God's Armor", "maze_instr": "Guide the child through the maze to collect all the armor pieces.",
  "scenarios": [
    {"q": "A friend wants you to lie for them.", "opts": "a) <strong>Wear the belt of truth and be honest.</strong> &nbsp; b) Lie to help."},
    {"q": "You feel tempted to do something wrong.", "opts": "a) Give in. &nbsp; b) <strong>Raise the shield of faith and say no.</strong>"},
    {"q": "You are unsure what is right.", "opts": "a) <strong>Read God's Word for help.</strong> &nbsp; b) Just guess."},
  ],
  "apply_sub": "Standing strong in God's armor",
  "drama": ["Give children cardboard armor pieces: belt, breastplate, shoes, shield, helmet, sword.",
    "As the narrator names each piece, a child 'puts it on' with an action.",
    "The group stands together, 'strong' and ready.",
    "End by 'praying' together, the most important part of standing strong."],
  "game_title": "Game: Armor Relay", "game_need": "paper armor pieces, two boxes",
  "game_steps": ["Two teams race to collect armor pieces from a box.", "Each runner 'puts on' one piece and returns.",
                 "The first team fully 'suited up' wins.", "Shout the memory verse together to finish."],
  "game_tip": "Name each piece as it's 'worn' so children link the game to the lesson.",
  "craft_title": "Craft: Shield of Faith", "craft_sub": "Make your own shield!",
  "craft_need": "card, crayons, scissors, a strip of paper for a handle, glue",
  "craft_steps": ["Cut a shield shape from card.", "Draw a big cross and colour it boldly.",
                  "Write 'Faith' across the top.", "Tape a paper handle on the back and hold it up strong!"],
  "template_title": "Shield Template",
  "snack": "Serve shield-shaped crackers or biscuits while reviewing the armor pieces.",
  "takehome": "The Armor of God teaches us to stand strong in faith and do what is right, with God's help.",
  "home_activity": "Each morning this week, 'put on' one piece of armor as a family and pray.",
  "family_prayer": "Dear God, thank you for your armor. Help our family to stand strong in faith and truth. Amen.",
  "three_lessons": ["Stand Strong", "Live in Truth", "Trust in Faith"],
  "review": "Today we learned that God gives us armor — truth, righteousness, peace, faith, salvation and his Word — to stand strong.",
  "closing_prayer": "Dear God, help us to put on your full armor every day, so we can stand strong and do what is right. Amen.",
  "welldone": "You have finished the Armor of God lesson! Stand strong, live in truth, and trust in faith.",
  "cert_line": "for learning to put on God's armor and stand strong in faith!",
})
